"""
The validation pack as a workbook.

A model validation team does not review a method in a web page. They review it
in a file they can annotate, circulate and attach to a sign-off, months after
the person who built it has moved on. So the pack downloads as one workbook
carrying everything the decision rests on: the methodology as written, the
questions that were asked and how they were answered, the plan, the SQL, the
fixture row by row, what was expected, what came back, and where the two were
reconciled.

Two rules run through it:

  * Nothing is summarised away. If a figure appears in the product it appears
    here with the rows behind it, because "trust the number" is exactly the
    posture this product exists to replace.
  * Nothing is asserted that was not computed. Sheets covering a run that has
    not happened say so rather than showing a blank that reads like a pass.
"""

from __future__ import annotations

import io
import json
from datetime import UTC, datetime
from typing import Any

from backend.studio.model import MethodDefinition
from backend.studio.validation import ValidationPack

#: One sheet per question a reviewer asks, in the order they ask them.
SHEETS = [
    "Cover", "Methodology", "Decisions", "Required Data", "Analytical Plan",
    "SQL", "Parameters", "Fixture", "Test Cases", "Expected", "Actual",
    "Reconciliation", "Limitations", "Governance", "Version History",
    "Audit Trail",
]

_HEADER = "FFF1F5F9"
_TITLE_SIZE = 14


def build_workbook(method: MethodDefinition, pack: ValidationPack, *,
                   generated_by: str = "") -> bytes:
    """Render the pack as .xlsx bytes."""
    from openpyxl import Workbook
    from openpyxl.styles import Alignment, Font, PatternFill
    from openpyxl.utils import get_column_letter

    book = Workbook()
    book.remove(book.active)

    header_fill = PatternFill("solid", fgColor=_HEADER)
    header_font = Font(bold=True)
    wrap = Alignment(vertical="top", wrap_text=True)

    def sheet(name: str):
        ws = book.create_sheet(name[:31])
        return ws

    def table(ws, headers: list[str], rows: list[list[Any]],
              widths: list[int] | None = None) -> None:
        ws.append(headers)
        for index in range(1, len(headers) + 1):
            cell = ws.cell(row=1, column=index)
            cell.fill = header_fill
            cell.font = header_font
        for row in rows:
            ws.append([_cell(v) for v in row])
        for index, width in enumerate(widths or [], start=1):
            ws.column_dimensions[get_column_letter(index)].width = width
        ws.freeze_panes = "A2"
        for row in ws.iter_rows(min_row=2):
            for cell in row:
                cell.alignment = wrap

    def prose(ws, title: str, blocks: list[tuple[str, str]]) -> None:
        ws["A1"] = title
        ws["A1"].font = Font(bold=True, size=_TITLE_SIZE)
        ws.column_dimensions["A"].width = 28
        ws.column_dimensions["B"].width = 110
        row = 3
        for label, text in blocks:
            ws.cell(row=row, column=1, value=label).font = header_font
            cell = ws.cell(row=row, column=2, value=_cell(text))
            cell.alignment = wrap
            row += 1

    answers = dict((method.plan or {}).get("meta", {}).get("answers") or {})
    ran = bool(pack.ran_at)
    not_run = ("This pack has not been run. The expected results below were "
               "computed independently; nothing has been compared to them yet.")

    # ---- 1. Cover ---------------------------------------------------------
    ws = sheet("Cover")
    prose(ws, "CreditProbe AI — Method Validation Pack", [
        ("Method", method.name),
        ("Method ID", method.id),
        ("Category", method.category),
        ("Version", method.version),
        ("Lifecycle", method.lifecycle_label),
        ("Owner", method.owner),
        ("Source", "Bank-authored" if method.source == "bank"
                   else "CreditProbe library"),
        ("Forked from", method.forked_from or "—"),
        ("Definition", method.definition),
        ("Cases", str(len(pack.cases))),
        ("Passed", str(pack.passed)),
        ("Failed", str(pack.failed)),
        ("Overall", "PASSED" if pack.all_passed
                    else ("FAILED" if pack.failed else "NOT RUN")),
        ("Run at", pack.ran_at or "not run"),
        ("Pack generated", datetime.now(UTC).isoformat()),
        ("Generated by", generated_by or "—"),
        ("Data", "Synthetic fixture rows written for this pack. No client data "
                 "appears in this workbook."),
        ("Expected results", "Computed by a second implementation written from "
                             "the methodology text below, sharing no code with "
                             "the plan, the SQL compiler or the query engine."),
    ])

    # ---- 2. Methodology ---------------------------------------------------
    prose(sheet("Methodology"), "Methodology as written", [
        ("Definition", method.definition),
        ("Purpose", method.purpose),
        ("Methodology", method.methodology),
        ("When to use", method.when_to_use),
        ("When NOT to use", method.when_not_to_use),
        ("Output", method.output_type),
        ("Interpretation", method.interpretation),
    ])

    # ---- 3. Decisions -----------------------------------------------------
    ws = sheet("Decisions")
    ws["A1"] = "The decisions the description left open, and how they were made"
    ws["A1"].font = Font(bold=True, size=_TITLE_SIZE)
    ws["A3"] = ("Each of these changes the answer. They are recorded because a "
                "rate is not reviewable without them.")
    ws["A3"].alignment = wrap
    ws2 = ws
    ws2.append([])
    table_rows = [[key, str(value)] for key, value in sorted(answers.items())]
    if not table_rows:
        table_rows = [["—", "No methodology options were recorded on this plan."]]
    start = 5
    ws2.cell(row=start, column=1, value="Decision").font = header_font
    ws2.cell(row=start, column=2, value="Answer").font = header_font
    ws2.cell(row=start, column=1).fill = header_fill
    ws2.cell(row=start, column=2).fill = header_fill
    for offset, row in enumerate(table_rows, start=1):
        ws2.cell(row=start + offset, column=1, value=row[0])
        ws2.cell(row=start + offset, column=2, value=row[1])
    ws2.column_dimensions["A"].width = 28
    ws2.column_dimensions["B"].width = 60

    # ---- 4. Required Data -------------------------------------------------
    ws = sheet("Required Data")
    table(ws, ["What", "Value"], [
        ["Required grain", method.required_grain],
        ["Required history", method.required_history],
        *[["Governed domain", d] for d in method.required_domains],
        *[["Governed field", f] for f in method.required_fields],
        *[["Weighting option", w] for w in method.weighting_options],
        *[["Applicable segment", s] for s in method.applicable_segments],
    ], widths=[26, 80])

    # ---- 5. Analytical Plan ----------------------------------------------
    ws = sheet("Analytical Plan")
    operations = (method.plan or {}).get("operations") or []
    table(ws, ["#", "Step", "Operation", "Inputs", "Parameters"], [
        [index + 1, op.get("id", ""), op.get("op", ""),
         ", ".join(op.get("inputs") or []), _json(op.get("params") or {})]
        for index, op in enumerate(operations)
    ], widths=[5, 24, 16, 24, 100])

    # ---- 6. SQL -----------------------------------------------------------
    ws = sheet("SQL")
    ws["A1"] = "The statement the fixture was run through"
    ws["A1"].font = Font(bold=True, size=_TITLE_SIZE)
    ws["A3"] = ("Every value is a bound parameter, listed on the next sheet. "
                "No value is concatenated into this statement — that separation "
                "is what makes a model-composed analysis safe to execute.")
    ws["A3"].alignment = wrap
    ws.column_dimensions["A"].width = 140
    for offset, line in enumerate((pack.sql or "").splitlines() or [not_run]):
        ws.cell(row=5 + offset, column=1, value=line)

    # ---- 7. Parameters ----------------------------------------------------
    table(sheet("Parameters"), ["#", "Bound value", "Type"], [
        [index + 1, _cell(value), type(value).__name__]
        for index, value in enumerate(pack.parameters)
    ] or [["—", not_run if not ran else "The statement bound no values.", ""]],
        widths=[6, 60, 18])

    # ---- 8. Fixture -------------------------------------------------------
    ws = sheet("Fixture")
    columns = sorted({k for row in pack.dataset for k in row})
    table(ws, columns or ["(no rows)"],
          [[row.get(c) for c in columns] for row in pack.dataset],
          widths=[18] * max(len(columns), 1))

    # ---- 9. Test Cases ----------------------------------------------------
    table(sheet("Test Cases"),
          ["ID", "Case", "Why it is contentious", "Result", "Note"],
          [[c.id, c.name, c.purpose, _verdict(c.passed), c.note]
           for c in pack.cases],
          widths=[26, 38, 70, 12, 60])

    # ---- 10. Expected -----------------------------------------------------
    table(sheet("Expected"), ["Case", "Measure", "Expected"],
          [[c.id, key, _cell(value)]
           for c in pack.cases for key, value in sorted(c.expected.items())],
          widths=[26, 32, 24])

    # ---- 11. Actual -------------------------------------------------------
    ws = sheet("Actual")
    if ran and pack.actual:
        table(ws, ["Measure", "Returned"],
              [[key, _cell(value)] for key, value in sorted(pack.actual.items())],
              widths=[36, 30])
    else:
        table(ws, ["Measure", "Returned"], [["—", not_run]], widths=[36, 90])

    # ---- 12. Reconciliation ----------------------------------------------
    total = next((c for c in pack.cases if c.id == "portfolio_total"), None)
    rows: list[list[Any]] = []
    if total is not None:
        for key, want in sorted(total.expected.items()):
            got = (total.actual or {}).get(key)
            rows.append([key, _cell(want), _cell(got),
                         _difference(want, got),
                         "agrees" if _agrees(want, got) else "DISAGREES"])
    table(sheet("Reconciliation"),
          ["Measure", "Independent calculation", "Method returned",
           "Difference", "Verdict"],
          rows or [["—", "", "", "", not_run]],
          widths=[32, 24, 22, 16, 16])

    # ---- 13. Limitations --------------------------------------------------
    prose(sheet("Limitations"), "What this method does NOT tell you", [
        ("Limitations", method.limitations
                        or "None recorded — which is itself a finding."),
        ("When NOT to use", method.when_not_to_use),
        ("Fixture scope", pack.note),
        ("Fixture is synthetic",
         "Every row in this workbook was written for this pack. Agreement here "
         "shows the method computes what it says it computes; it says nothing "
         "about the quality of the bank's own data."),
    ])

    # ---- 14. Governance ---------------------------------------------------
    can_certify, gaps = method.can_certify()
    prose(sheet("Governance"), "Certification", [
        ("Lifecycle", method.lifecycle_label),
        ("Eligible for certification", "Yes" if can_certify else "No"),
        ("Outstanding requirements",
         "\n".join(f"• {g}" for g in gaps) or "None"),
        ("Certified at", method.certified_at or "—"),
        ("Certified by", method.certified_by or "—"),
        ("Fingerprint", method.fingerprint()),
        ("What the fingerprint covers",
         "The plan, the engine analysis and the governed fields — what the "
         "method COMPUTES. Renaming a method does not change it."),
    ])

    # ---- 15. Version History ---------------------------------------------
    table(sheet("Version History"),
          ["Version", "Lifecycle", "Created", "Change", "Certified at",
           "Certified by"],
          [[v.version, v.lifecycle, v.created_at, v.change_note,
            v.certified_at, v.certified_by] for v in method.versions]
          or [[method.version, method.lifecycle, method.created_at,
               "First version", method.certified_at or "—",
               method.certified_by or "—"]],
          widths=[12, 18, 26, 60, 24, 24])

    # ---- 16. Audit Trail --------------------------------------------------
    table(sheet("Audit Trail"), ["When", "What", "Detail"], [
        [method.created_at or "—", "Method created", method.owner],
        [method.updated_at or "—", "Last edited", method.owner],
        [pack.ran_at or "—", "Validation pack run",
         f"{pack.passed} passed, {pack.failed} failed"
         if ran else "Not run"],
        [method.certified_at or "—", "Certified",
         method.certified_by or "Not certified"],
        [datetime.now(UTC).isoformat(), "Workbook generated",
         generated_by or "—"],
    ], widths=[30, 30, 60])

    buffer = io.BytesIO()
    book.save(buffer)
    return buffer.getvalue()


def _cell(value: Any) -> Any:
    """Excel takes scalars; everything else becomes readable text."""
    if value is None:
        return ""
    if isinstance(value, bool | int | float | str):
        return value
    return _json(value)


def _json(value: Any) -> str:
    return json.dumps(value, default=str, sort_keys=True)


def _verdict(passed: bool | None) -> str:
    return {True: "PASS", False: "FAIL"}.get(passed, "not run")


def _agrees(want: Any, got: Any) -> bool:
    try:
        return abs(float(want) - float(got)) <= 1e-6
    except (TypeError, ValueError):
        return str(want) == str(got)


def _difference(want: Any, got: Any) -> Any:
    try:
        return round(float(got) - float(want), 6)
    except (TypeError, ValueError):
        return ""


__all__ = ["SHEETS", "build_workbook"]
