"""The Early Warning Score is WIRED: routes, catalogue, readiness, restart.

The failure these gates exist for
---------------------------------
A fresh install on a Mac, at the commit that shipped all of this, reported:

    Governed catalogue: retail_ews_score      ✓ (the file on disk)
    20 monthly partitions                     ✓ (the lake on disk)
    Data Builder registration synced          ✓
    "The retail installation is ready"        ✓
    /openapi.json                             — ZERO /retail/ews routes
    health.data_catalog                       — one dataset, not five
    the Early Warning screen                  — "the domain could not be read"

Three defects behind it, each closed here:

1. `scripts/retail_uat/restart_backend.sh` decided whether the old backend was
   running by looking in `/proc`. macOS has no `/proc`, so the old process was
   never stopped, the new one could not bind the port and exited, and the
   health check passed because the OLD server answered it. The script printed
   "backend ready" naming a pid that no longer existed. The machine kept
   serving whatever code it booted with.

2. `get_catalog()` was `lru_cache(maxsize=1)` over the whole process. The
   bootstrap registers the domain by WRITING the catalogue file, and on a
   fresh install it runs while a backend is already up — so the running server
   went on serving a catalogue from before the domain existed.

3. Readiness never asked the application anything. Every check was about files.

And one thing that made the first one impossible to see from inside the
product: enumerating an application's paths by walking `app.routes` finds four
framework routes, because this FastAPI keeps an included router as a single
wrapper with no path of its own. A gate written that way reports that an
application serving six hundred paths serves none of them — and one written
the other way round would report a healthy app no matter what. The paths here
come from the OpenAPI document, which is what a person inspects.
"""

from __future__ import annotations

import json
import os
import re
import subprocess
import threading
from http.server import BaseHTTPRequestHandler, HTTPServer
from pathlib import Path

import pytest

from backend.retail import profile

pytestmark = pytest.mark.skipif(
    not profile.is_retail(), reason="the corporate profile is active")

ROOT = Path(__file__).resolve().parents[2]
RESTART = ROOT / "scripts" / "retail_uat" / "restart_backend.sh"


@pytest.fixture(scope="module")
def app():
    """The production application, built through its own factory."""
    from backend.retail import readiness

    return readiness.production_app()


# --------------------------------------------------------------- the routes

def test_the_production_app_exposes_every_early_warning_route(app):
    from backend.retail import readiness

    absent = readiness.missing_routes(app)
    assert absent == [], (
        "the application a person's uvicorn serves does not route these: "
        f"{absent}")


def test_the_paths_are_read_the_way_a_person_reads_them(app):
    """A gate that cannot see the application's paths cannot guard them.

    Walking `app.routes` finds four. If this number ever collapses, the
    enumeration has regressed and every other assertion here is worthless.
    """
    from backend.retail import readiness

    served = readiness.routes_of(app)
    assert len(served) > 100, (
        f"only {len(served)} paths were found; the enumeration is broken, not "
        "the application")
    assert any(path.startswith("/api/v1/retail/ews/") for _, path in served)


def test_the_early_warning_endpoints_answer_on_the_production_app(app):
    from backend.retail import readiness

    assert readiness.check_endpoints_answer(app) == []


def test_the_portfolio_endpoint_answers_the_final_payload(app):
    """Not just 200: the shape the workspace cannot open without."""
    from fastapi.testclient import TestClient

    from backend.retail import ews_model, ews_score, readiness

    with TestClient(app) as client:
        assert readiness._sign_in(client), "no demonstration account signed in"
        body = client.get("/api/v1/retail/ews/portfolio").json()

    assert body.get("available") is True, body.get("because")
    assert body["domain"] == ews_score.DOMAIN
    assert body["model_version"] == ews_model.EWS_MODEL_VERSION
    assert len(body["months"]) == ews_score.MONTHS_KEPT
    assert body["month"] == body["months"][-1]
    assert len(body["products"]) == len(ews_model.ALL_PRODUCTS)
    assert body["headline"]["customers"] > 0


# ------------------------------------------------- the frontend's contract

def test_the_frontend_asks_for_paths_the_backend_serves(app):
    """One contract, read off both sides.

    The client is generated by hand, so a route renamed on one side and not
    the other is a screen that loads an error and a backend that looks fine.
    """
    from backend.retail import readiness

    client = (ROOT / "frontend" / "src" / "lib" / "api.ts").read_text()
    wanted = sorted(set(re.findall(r"[\"`](/retail/ews/[A-Za-z0-9_/-]*)", client)))
    assert wanted, "the frontend client asks for no Early Warning route at all"

    served = {path for _, path in readiness.routes_of(app)}
    for path in wanted:
        full = f"/api/v1{path}"
        # A templated path (`/customers/${id}`) reaches here as its prefix.
        if full in served:
            continue
        assert any(one.startswith(full.rstrip("/") + "/") for one in served), (
            f"the frontend calls {full}, which the application does not serve")


def test_the_workspace_opens_on_the_portfolio_endpoint():
    """What /early-warning actually requests, named rather than assumed."""
    workspace = (ROOT / "frontend" / "src" / "app" / "early-warning"
                 / "workspace.tsx").read_text()
    client = (ROOT / "frontend" / "src" / "lib" / "api.ts").read_text()
    assert "ewsScorePortfolio" in workspace
    assert re.search(r"ewsScorePortfolio[\s\S]{0,200}/retail/ews/portfolio",
                     client), (
        "ewsScorePortfolio no longer requests /retail/ews/portfolio")


# ------------------------------------------------------ the runtime catalogue

def test_the_runtime_catalogue_holds_the_domain():
    """The catalogue the RUNNING code reads, not the file on disk.

    Those two disagreed on the Mac — five datasets in the file, one in the
    process — and nothing in the product compared them.
    """
    from backend.data_access.catalog import get_catalog
    from backend.retail import ews_score

    names = set(get_catalog().names())
    assert ews_score.DOMAIN in names, sorted(names)
    assert "retail_facility_month" in names
    assert all(name.startswith("retail_") for name in names), sorted(names)


def test_a_catalogue_written_by_another_process_is_picked_up(tmp_path,
                                                             monkeypatch):
    """A bootstrap that runs while the server is up must not be invisible."""
    import time
    import types

    from backend.data_access import catalog as C

    written = tmp_path / "catalog.json"
    written.write_text(json.dumps({"datasets": []}))
    # `settings` is frozen, so the module's reference to it is replaced
    # rather than edited. Both the stamp and the loader read it from here.
    monkeypatch.setattr(C, "settings", types.SimpleNamespace(
        metadata_dir=tmp_path, has_database=False))
    monkeypatch.setattr(C, "_published_entries_from_db", lambda: [])
    C.reload_catalog()
    assert set(C.get_catalog().names()) == set()

    # Another process rewrites the file. Nothing calls reload_catalog.
    entry = json.loads((ROOT / "metadata" / "retail" / "catalog.json").read_text())
    time.sleep(0.01)
    written.write_text(json.dumps(entry))
    assert "retail_ews_score" in set(C.get_catalog().names()), (
        "the running process is still serving the catalogue it started with")
    C.reload_catalog()


# ------------------------------------------------------------- the readiness

def test_readiness_fails_when_a_route_is_missing(monkeypatch):
    """The check must be able to say no. It could not before."""
    from backend.retail import readiness

    monkeypatch.setattr(
        readiness, "REQUIRED_EWS_ROUTES",
        readiness.REQUIRED_EWS_ROUTES + (("GET", "/api/v1/retail/ews/absent"),))
    assert "GET /api/v1/retail/ews/absent" in readiness.missing_routes()


def test_readiness_fails_against_a_server_serving_older_code():
    """The Mac's exact state: a healthy server with no Early Warning routes."""
    from backend.retail import readiness

    class Stale(BaseHTTPRequestHandler):
        def do_GET(self):  # noqa: N802 - the stdlib's spelling
            body = json.dumps({"paths": {"/api/v1/health": {"get": {}}}})
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.end_headers()
            self.wfile.write(body.encode())

        def log_message(self, *_args):  # keep the test output quiet
            return

    server = HTTPServer(("127.0.0.1", 0), Stale)
    threading.Thread(target=server.serve_forever, daemon=True).start()
    try:
        problems = readiness.check_live_server(
            f"http://127.0.0.1:{server.server_address[1]}")
    finally:
        server.shutdown()

    assert problems, "a server with no Early Warning routes was called ready"
    assert "older than this checkout" in problems[0]
    assert "restart_backend.sh" in problems[0]


def test_readiness_is_quiet_when_nothing_is_listening():
    """Not every installation has a server up; that is not a failure."""
    from backend.retail import readiness

    assert readiness.check_live_server("http://127.0.0.1:9") == []


def test_readiness_checks_the_months_and_the_versions():
    from backend.retail import ews_model, ews_score, readiness

    assert readiness.check_domain_and_versions() == []
    assert len(ews_score.panel_months()) == ews_score.MONTHS_KEPT == 20
    frame = ews_score.read(ews_score.panel_months()[-1])
    assert str(frame["model_version"].iloc[0]) == ews_model.EWS_MODEL_VERSION
    assert str(frame["rulebook_version"].iloc[0]).strip()


def test_the_bootstrap_check_asks_the_application():
    """`--check` must not be able to pass on files alone."""
    source = (ROOT / "scripts" / "bootstrap_retail_installation.py").read_text()
    assert "readiness.check()" in source, (
        "the readiness check no longer asks the application anything")


# --------------------------------------------------------- the restart script

def test_the_restart_script_does_not_depend_on_proc():
    """`/proc` is Linux-only, and this script is run on a Mac."""
    script = RESTART.read_text()
    assert "/proc/" not in script, (
        "the restart script is checking /proc again; on macOS every such "
        "check is false and the old backend is never stopped")
    assert "kill -0" in script
    assert "ps -o command=" in script


def test_the_restart_script_refuses_to_leave_a_stale_server_in_place(tmp_path):
    """The Mac failure, reproduced: something else is holding the port.

    Before, the script started a second server that could not bind, then
    reported "backend ready" because the stranger answered the health check.
    It must refuse instead, and say what is in the way.
    """
    class Healthy(BaseHTTPRequestHandler):
        def do_GET(self):  # noqa: N802
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.end_headers()
            self.wfile.write(b'{"status":"ok"}')

        def log_message(self, *_args):
            return

    server = HTTPServer(("127.0.0.1", 0), Healthy)
    port = server.server_address[1]
    threading.Thread(target=server.serve_forever, daemon=True).start()
    try:
        done = subprocess.run(
            ["bash", str(RESTART), str(tmp_path / "backend.log")],
            cwd=str(ROOT), capture_output=True, text=True,
            env={**os.environ, "API_PORT": str(port)}, timeout=300)
    finally:
        server.shutdown()

    assert done.returncode != 0, (
        "the script reported success while another server held the port:\n"
        f"{done.stdout}")
    assert "still serving port" in (done.stdout + done.stderr)
    assert "backend ready" not in done.stdout
