"""The field audit, as tests rather than as a document.

`docs/cockpit_v3/COCKPIT_FIELD_AUDIT.md` is generated by
`scripts/build_cockpit_field_audit.py`. A generated document is only evidence
while someone remembers to regenerate it, so the audit's two proofs run here
against the release the test suite publishes:

* POSITIVELY, that business groups A-K are present, by naming the fields that
  satisfy each and failing when one goes missing.
* NEGATIVELY, that nothing in the authorized domain belongs to Early Warning,
  Credit Scoring, Scorecard Validation, What-if or Lenses -- checked against the
  physical Parquet columns, not against the declaration alone.

These are structural facts about the dictionary and the release. They prove
nothing about any model's behaviour.
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

import pytest

from backend.cockpit_agentic import catalog as catalog_mod
from backend.cockpit_agentic import fields as F

from .conftest import RELEASE

_ROOT = Path(__file__).resolve().parents[2]


def _load_builder():
    """Import the generator script by path -- `scripts/` is not a package."""
    path = _ROOT / "scripts" / "build_cockpit_field_audit.py"
    spec = importlib.util.spec_from_file_location(
        "build_cockpit_field_audit", path)
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


BUILDER = _load_builder()


@pytest.fixture(scope="module")
def evidence(lake):
    """Run the audit against the release the suite publishes."""
    return BUILDER.audit(RELEASE)


# ------------------------------------------------------- the counts agree

def test_the_three_field_counts_are_all_derivable_from_each_other(evidence):
    """751 definitions, 763 distinct names, 991 addressable columns. Quoting
    one of these without saying which it is has already misled a reader of this
    project's own documents, so the arithmetic is asserted, not narrated."""
    definitions = len(F.ALL_FIELDS)
    keys = len(F.COMMON_KEYS)
    keyed = evidence["keyed_relations"]

    assert len(evidence["rows"]) == definitions + keys * keyed
    assert keyed == len(catalog_mod.QUERYABLE_RELATIONS) - 1  # the pivot view
    assert len(evidence["distinct_names"]) <= definitions + keys


def test_the_family_counts_add_up_to_the_whole_domain(evidence):
    """Every addressable column belongs to exactly one family, so no field can
    hide in the gap between two tables of the audit."""
    assert sum(evidence["families"].values()) == len(evidence["rows"])
    assert "Z_other" not in evidence["families"]


def test_every_published_column_is_declared(evidence):
    """A column in the Parquet the catalogue does not describe is a column the
    model cannot be told about and the validator cannot check."""
    assert evidence["undeclared"] == {}


# ------------------------------------------------------- the positive proof

def test_every_required_business_group_is_present(evidence):
    """Groups A, B, C, D, E, H and I, field by named field."""
    assert evidence["missing_required"] == {}


def test_the_rating_scale_is_the_exact_nineteen_grades(evidence):
    assert evidence["scale_ok"]
    assert list(F.RATING_SCALE) == [
        "AAA", "AA+", "AA", "AA-", "A+", "A", "A-", "BBB+", "BBB", "BBB-",
        "BB+", "BB", "BB-", "B+", "B", "B-", "CCC", "CC", "C"]
    assert len(F.RATING_SCALE) == 19
    assert "D" not in F.RATING_SCALE  # default is a flag, not a grade


def test_there_are_at_least_forty_ratios(evidence):
    assert evidence["ratio_ok"] and len(F.RATIO_NAMES) >= 40


def test_there_are_exactly_twenty_qualitative_questions(evidence):
    assert evidence["qual_ok"] and len(F.QUALITATIVE_QUESTIONS) == 20


def test_the_macro_axis_is_ten_factors_over_the_full_window(evidence):
    """Ten factors, previous four quarters through the next fifteen."""
    assert evidence["macro_ok"] and evidence["offsets_ok"]
    assert len(F.MACRO_PIVOT_FIELDS) == 10 * 20


def test_the_calendar_is_twenty_quarters(evidence):
    assert evidence["quarters_ok"]


def test_the_ifrs9_group_carries_both_pd_axes_at_both_horizons(evidence):
    """PIT and TTC, 12-month and lifetime -- the four cells, not two of them
    and a derivation. A domain missing one of these silently answers a
    lifetime question with a 12-month number."""
    declared = {row["spec"].name for row in evidence["rows"]}
    for name in ("pd_pit_12m", "pd_pit_lifetime",
                 "pd_ttc_12m", "pd_ttc_lifetime"):
        assert name in declared


def test_the_forecast_vintage_survives_into_the_domain(evidence):
    """A forecast made at one anchor must stay labelled a forecast."""
    declared = {row["spec"].name for row in evidence["rows"]}
    for name in ("forecast_vintage", "observation_status", "quarter_offset"):
        assert name in declared


# ------------------------------------------------------- the negative proof

def test_no_declared_field_belongs_to_another_module(evidence):
    assert evidence["declared_hits"] == []


def test_no_published_column_belongs_to_another_module(evidence):
    """Checked against the Parquet, so a column added by the generator without
    a declaration would still be caught."""
    assert evidence["published_hits"] == []


def test_no_readable_relation_belongs_to_another_module(evidence):
    assert evidence["relation_hits"] == []


def test_the_marker_search_would_actually_catch_a_leak():
    """The negative proof is worthless if the search cannot find anything, so
    feed it names from each excluded module and require every one to be hit."""
    leaks = ["ews_alert_score", "early_warning_trigger", "credit_score_value",
             "scorecard_segment", "psi_by_bucket", "gini_coefficient",
             "whatif_run_id", "shock_magnitude", "lens_document_id",
             "extracted_text", "playbook_step_id"]
    hits = {name for name, _module, _marker in BUILDER.foreign_hits(leaks)}
    assert hits == set(leaks)


def test_the_only_exceptions_are_the_stored_ifrs9_scenarios():
    """`scenario_*` trips the what-if marker and is nonetheless legitimate:
    these are scenario outputs the source system already computed and stored.
    Reading a stored scenario is not running a new one -- the boundary is the
    action. Any NEW exception must be added deliberately and justified in
    writing, which is what this assertion forces."""
    assert set(BUILDER.ALLOWED_DESPITE_MARKER) == {
        "scenario_id", "scenario_name", "scenario_weight", "scenario_ecl",
        "scenario_pd_pit_12m", "scenario_pd_pit_lifetime", "scenario_lgd",
        "scenario_ead"}
    for name, why in BUILDER.ALLOWED_DESPITE_MARKER.items():
        assert why.strip(), f"{name} is exempted with no reason given"


def test_all_five_excluded_modules_are_searched_for():
    """The instruction names the modules Cockpit must not reach. If one is
    dropped from the search, the negative proof quietly stops covering it."""
    modules = {module for module, _markers in BUILDER.FOREIGN_MARKERS}
    assert modules == {"Early Warning", "Credit Scoring",
                       "Scorecard Validation", "What-if / Stress",
                       "Lenses / documents", "Playbook / Planner"}


# ------------------------------------------------------------ the verdict

def test_the_audit_passes_as_a_whole(evidence):
    assert evidence["passed"], {
        k: v for k, v in evidence.items()
        if k in ("missing_required", "declared_hits", "published_hits",
                 "relation_hits", "undeclared") and v}


def test_the_checked_in_document_is_not_stale(evidence):
    """The committed audit must describe the domain the code currently
    declares. Regenerate with:

        COCKPIT_AGENTIC_V3=true python scripts/build_cockpit_field_audit.py
    """
    doc = _ROOT / "docs" / "cockpit_v3" / "COCKPIT_FIELD_AUDIT.md"
    assert doc.exists(), "the audit document has not been generated"
    text = doc.read_text()
    assert f"**{len(evidence['rows'])}**" in text
    assert "**PASS**" in text
    for title in BUILDER.FAMILY_TITLES.values():
        assert title in text, f"family missing from the document: {title}"
