"""Reading real documents into located evidence. PB-004, PB-032, PB-036.

Every file here is generated by the fixtures, opened by the real reader, and
asserted on. Nothing is mocked, because the failures worth catching — a formula
read as a figure, a hidden sheet read as visible, a scan read as an empty page —
all live in the parser rather than around it.
"""

from __future__ import annotations

import io
import zipfile

import pytest

from backend.playbook import ingest
from backend.playbook.ingest import validate
from backend.playbook.ingest.types import UnreadableSource


class TestWordStructure:
    def test_headings_tables_and_paragraphs_are_all_read(self, committee_report_docx):
        _, result = ingest.read("report.docx", committee_report_docx)
        kinds = {c.kind for c in result.chunks}
        assert {"heading", "paragraph", "table"} <= kinds

    def test_every_chunk_has_a_locator(self, committee_report_docx):
        _, result = ingest.read("report.docx", committee_report_docx)
        assert all(c.locator for c in result.chunks)

    def test_a_paragraph_knows_which_section_it_is_in(self, committee_report_docx):
        _, result = ingest.read("report.docx", committee_report_docx)
        summary = next(c for c in result.chunks
                       if c.kind == "paragraph" and "20.90" in c.text)
        assert summary.path == ["1. Executive summary"]

    def test_nested_headings_produce_a_trail(self, committee_report_docx):
        _, result = ingest.read("report.docx", committee_report_docx)
        weights = next(c for c in result.chunks if "60/15/25" in c.text)
        assert weights.path == ["2. Scenario results", "2.1 Weighted outcome"]

    def test_the_table_keeps_its_columns_and_rows(self, committee_report_docx):
        _, result = ingest.read("report.docx", committee_report_docx)
        table = next(c for c in result.chunks if c.kind == "table")
        assert table.data["columns"] == ["Scenario", "ECL, SAR million"]
        assert ["Base", "18.00"] in table.data["rows"]

    def test_the_header_is_read_because_the_period_often_lives_there(
            self, committee_report_docx):
        _, result = ingest.read("report.docx", committee_report_docx)
        assert any("Q1 2026" in c.text for c in result.chunks if c.kind == "note")

    def test_document_order_is_preserved_across_tables_and_paragraphs(
            self, committee_report_docx):
        _, result = ingest.read("report.docx", committee_report_docx)
        ordinals = [c.ordinal for c in result.chunks]
        assert ordinals == sorted(ordinals)
        texts = [c.text for c in result.chunks]
        assert texts.index("3. Limitations") > texts.index("2. Scenario results")


class TestWorkbookHonesty:
    def test_a_formula_without_a_cached_value_is_not_reported_as_a_number(
            self, results_workbook_xlsx):
        _, result = ingest.read("results.xlsx", results_workbook_xlsx)
        ecl = next(c for c in result.chunks if c.data.get("sheet") == "ECL")
        flat = [cell for row in ecl.data["rows"] for cell in row]
        assert "<uncomputed formula>" in flat
        assert any("uncomputed" in w for w in result.manifest.warnings)

    def test_a_hidden_sheet_is_skipped_and_said_to_be_skipped(
            self, results_workbook_xlsx):
        _, result = ingest.read("results.xlsx", results_workbook_xlsx)
        sheets_read = {c.data.get("sheet") for c in result.chunks}
        assert "Working" not in sheets_read
        assert any("Working" in s["what"] for s in result.manifest.skipped)

    def test_a_skipped_sheet_makes_the_read_incomplete(self, results_workbook_xlsx):
        _, result = ingest.read("results.xlsx", results_workbook_xlsx)
        assert result.manifest.complete is False

    def test_visible_sheets_are_all_read(self, results_workbook_xlsx):
        _, result = ingest.read("results.xlsx", results_workbook_xlsx)
        sheets_read = {c.data.get("sheet") for c in result.chunks}
        assert {"ECL", "Exposure"} <= sheets_read

    def test_sheet_locators_name_the_sheet(self, results_workbook_xlsx):
        _, result = ingest.read("results.xlsx", results_workbook_xlsx)
        assert any(c.locator.startswith("xlsx://ECL!") for c in result.chunks)


class TestPdfClassification:
    def test_a_text_pdf_is_read_page_by_page(self, text_pdf):
        _, result = ingest.read("validation.pdf", text_pdf)
        pages = [c for c in result.chunks if c.kind == "page"]
        assert len(pages) == 2
        assert pages[0].locator == "pdf://p1"

    def test_an_image_only_pdf_is_refused_rather_than_read_as_empty(
            self, image_only_pdf):
        with pytest.raises(UnreadableSource, match="scan|image"):
            ingest.read("scan.pdf", image_only_pdf)


class TestDeckStructure:
    def test_slides_keep_their_numbers(self, simple_deck_pptx):
        _, result = ingest.read("deck.pptx", simple_deck_pptx)
        slides = [c for c in result.chunks if c.kind == "slide"]
        assert [c.locator for c in slides] == ["pptx://slide/1", "pptx://slide/2"]

    def test_speaker_notes_are_read(self, simple_deck_pptx):
        _, result = ingest.read("deck.pptx", simple_deck_pptx)
        assert any("coverage ratio" in c.text for c in result.chunks
                   if c.kind == "note")

    def test_a_slide_table_is_read_as_data(self, simple_deck_pptx):
        _, result = ingest.read("deck.pptx", simple_deck_pptx)
        table = next(c for c in result.chunks if c.kind == "table")
        assert table.data["columns"] == ["Scenario", "ECL"]


class TestUploadsAreUntrustedInput:
    def test_the_bytes_decide_the_type_not_the_extension(self, committee_report_docx):
        accepted, _ = ingest.read("report.txt", committee_report_docx)
        assert accepted.kind == validate.DOCX

    def test_a_macro_enabled_workbook_is_refused(self, results_workbook_xlsx):
        with pytest.raises(validate.RejectedUpload, match="macros"):
            ingest.accept("results.xlsm", results_workbook_xlsx)

    def test_an_oversized_file_is_refused(self, monkeypatch):
        from backend.playbook.ingest import validate as v
        monkeypatch.setattr(type(v.settings), "max_upload_bytes",
                            property(lambda self: 10), raising=False)
        with pytest.raises(v.RejectedUpload, match="limit"):
            v.check("big.txt", b"x" * 100)

    def test_an_empty_file_is_refused(self):
        with pytest.raises(validate.RejectedUpload, match="empty"):
            ingest.accept("nothing.docx", b"")

    def test_an_unknown_format_is_refused_with_the_list_of_known_ones(self):
        with pytest.raises(validate.RejectedUpload, match="DOCX, PDF"):
            ingest.accept("thing.exe", b"MZ\x90\x00binary")

    def test_a_zip_bomb_is_refused_before_extraction(self):
        buf = io.BytesIO()
        with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
            zf.writestr("word/document.xml", b"\0" * (40 * 1024 * 1024))
        with pytest.raises(validate.RejectedUpload, match="expands"):
            ingest.accept("bomb.docx", buf.getvalue())

    def test_a_zip_that_is_not_an_office_document_is_refused(self):
        buf = io.BytesIO()
        with zipfile.ZipFile(buf, "w") as zf:
            zf.writestr("hello.txt", "hi")
        with pytest.raises(validate.RejectedUpload, match="not a Word"):
            ingest.accept("thing.docx", buf.getvalue())

    def test_a_corrupt_office_file_fails_as_unreadable_not_as_a_crash(self):
        with pytest.raises(validate.RejectedUpload):
            ingest.read("broken.docx", b"PK\x03\x04not really a zip")
