"use client";

import { useRouter } from "next/navigation";
import * as React from "react";
import {
  ArrowRight,
  Check,
  Loader2,
  Plus,
  Sparkles,
  Trash2,
} from "lucide-react";

import { BackLink } from "@/components/layout/back-link";
import { PageHeader } from "@/components/layout/page-header";
import { LensScopeForm } from "@/components/lenses/lens-scope";
import { MetricPicker } from "@/components/metrics/metric-picker";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import {
  api,
  type LensScope,
  type LensSuggestion,
  type MetricHit,
} from "@/lib/api";

/**
 * Creating a lens, by being asked three things rather than twenty.
 *
 * §8. The old route into this was a single text box that turned a sentence
 * into a lens in one shot: you described everything at once, and whatever the
 * matcher did not understand was silently absent. This is the same matcher,
 * asked one thing at a time, with what it understood on screen before
 * anything is stored.
 *
 * Three steps, and the order is the point:
 *
 *   1. **The name.** Nothing else is asked until there is one, because the
 *      name is what CreditProbe matches against to suggest the rest.
 *   2. **What it is for.** A short definition panel — purpose, audience,
 *      portfolio, domains, period, visibility — with suggested values the
 *      person edits. A lens whose scope is decided after its tiles is a lens
 *      whose tiles decided its scope, and it ends up being about whatever was
 *      easy to find.
 *   3. **What it shows.** Suggestions first, then a typeahead. Never the whole
 *      catalogue: seventy-odd metrics in a scrolling list is a list nobody
 *      reads, and people rebuild a number they already had.
 *
 * The suggestions are not generated by a model. The name is matched against
 * the Metric Catalogue deterministically, so the same name suggests the same
 * thing on every machine and nothing is invented.
 */
export default function NewLensPage() {
  const router = useRouter();

  const [name, setName] = React.useState("");
  const [named, setNamed] = React.useState("");
  const [suggestion, setSuggestion] = React.useState<LensSuggestion | null>(
    null,
  );
  const [scope, setScope] = React.useState<LensScope | null>(null);
  const [chosen, setChosen] = React.useState<MetricHit[]>([]);
  const [description, setDescription] = React.useState("");
  const [busy, setBusy] = React.useState(false);
  const [error, setError] = React.useState<string | null>(null);

  async function nameIt() {
    const wanted = name.trim();
    if (!wanted || busy) return;
    setBusy(true);
    setError(null);
    try {
      const body = await api.suggestLens(wanted);
      setSuggestion(body);
      setScope(body.scope);
      setNamed(wanted);
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    } finally {
      setBusy(false);
    }
  }

  function add(hit: MetricHit) {
    setChosen((current) =>
      current.some((m) => m.metric_id === hit.metric_id)
        ? current
        : [...current, hit],
    );
  }

  async function save() {
    if (!named || chosen.length === 0 || busy) return;
    setBusy(true);
    setError(null);
    try {
      const lens = await api.createLens({
        name: named,
        description,
        audience: scope?.audience ?? "",
        scope: scope ?? undefined,
        panels: chosen.map((hit) => ({
          kind: "metric" as const,
          metric_id: hit.metric_id,
          visual: "kpi",
        })),
      });
      router.push(`/lenses/${lens.id}`);
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
      setBusy(false);
    }
  }

  return (
    <div className="space-y-6">
      <BackLink href="/lenses" label="Lenses" />
      <PageHeader
        title="Create a lens"
        description="Name it, say what it is for, then choose what it shows. Everything CreditProbe suggests is a default you can change, and every metric it offers is one that calculates against this deployment's governed data."
      />

      {/* ------------------------------------------------------- the name */}

      <Card className="p-5">
        <Step number={1} title="What would you like to call this lens?" done={!!named} />
        <div className="mt-3 flex flex-wrap gap-2">
          <input
            value={name}
            autoFocus
            onChange={(e) => setName(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === "Enter") void nameIt();
            }}
            placeholder="Retail Collections Watch"
            aria-label="What this lens is called"
            className="h-9 min-w-0 flex-1 rounded-md border border-border bg-surface px-3 text-sm text-text-primary placeholder:text-text-muted focus:border-accent focus:outline-none"
          />
          <Button size="sm" onClick={nameIt} disabled={busy || !name.trim()}>
            {busy ? (
              <Loader2 className="animate-spin" aria-hidden />
            ) : (
              <Sparkles aria-hidden />
            )}
            {named ? "Suggest again" : "Continue"}
          </Button>
        </div>
        {suggestion && (
          <p className="mt-2 text-[11px] leading-relaxed text-text-muted">
            {suggestion.because}
          </p>
        )}
        {suggestion?.shipped && (
          <p className="mt-2 text-xs text-warning">
            CreditProbe already ships this one.{" "}
            <a
              href={`/lenses`}
              className="underline underline-offset-2"
            >
              Open it from the library
            </a>{" "}
            rather than rebuilding it, unless you want a variant of your own.
          </p>
        )}
        {error && <p className="mt-2 text-xs text-negative">{error}</p>}
      </Card>

      {/* ------------------------------------------------- what it is for */}

      {named && scope && (
        <Card className="p-5">
          <Step number={2} title="What is it for?" done={!!scope.purpose} />
          <p className="mt-1 text-[11px] leading-relaxed text-text-muted">
            Settled before the metrics, on purpose. A lens whose scope is
            decided after its tiles ends up being about whatever was easy to
            find.
          </p>
          <LensScopeForm
            lensId={null}
            scope={scope}
            periods={null}
            onSaved={(saved) => setScope(saved)}
          />
        </Card>
      )}

      {/* ------------------------------------------------ what it shows */}

      {named && (
        <Card className="p-5">
          <Step
            number={3}
            title="What should it show?"
            done={chosen.length > 0}
          />

          {chosen.length > 0 && (
            <ul className="mt-3 divide-y divide-border overflow-hidden rounded-md border border-border">
              {chosen.map((hit) => (
                <li
                  key={hit.metric_id}
                  className="flex items-start justify-between gap-3 px-3 py-2"
                >
                  <div className="min-w-0">
                    <p className="flex flex-wrap items-baseline gap-x-2">
                      <span className="text-sm text-text-primary">
                        {hit.name}
                      </span>
                      <span className="rounded border border-border px-1 text-[10px] text-text-muted">
                        {hit.unit}
                      </span>
                      {!hit.governed && (
                        <Badge variant="warning">User built</Badge>
                      )}
                    </p>
                    <p className="mt-0.5 truncate font-mono text-[10px] text-text-muted">
                      {hit.formula}
                    </p>
                  </div>
                  <Button
                    variant="ghost"
                    size="sm"
                    aria-label={`Remove ${hit.name}`}
                    onClick={() =>
                      setChosen((current) =>
                        current.filter((m) => m.metric_id !== hit.metric_id),
                      )
                    }
                  >
                    <Trash2 aria-hidden />
                  </Button>
                </li>
              ))}
            </ul>
          )}

          {suggestion && suggestion.metrics.length > 0 && (
            <div className="mt-4">
              <p className="text-[10px] font-medium uppercase tracking-[0.14em] text-text-muted">
                Suggested for this lens
              </p>
              <div className="mt-2 flex flex-wrap gap-1.5">
                {suggestion.metrics
                  .filter(
                    (hit) =>
                      !chosen.some((m) => m.metric_id === hit.metric_id),
                  )
                  .map((hit) => (
                    <button
                      key={hit.metric_id}
                      type="button"
                      onClick={() => add(hit)}
                      className="inline-flex items-center gap-1 rounded-full border border-border px-2.5 py-1 text-[11px] text-text-secondary transition-colors hover:bg-surface-hover"
                    >
                      <Plus className="size-3" aria-hidden />
                      {hit.name}
                    </button>
                  ))}
              </div>
            </div>
          )}

          <div className="mt-4">
            <p className="text-[10px] font-medium uppercase tracking-[0.14em] text-text-muted">
              Or search for one
            </p>
            <p className="mb-2 mt-1 text-[11px] leading-relaxed text-text-muted">
              Type the first few letters of what you call it. The search knows
              the words people actually use — &ldquo;bad rate&rdquo; and
              &ldquo;NPL rate&rdquo; both reach the default rate — and each
              word you add narrows the list rather than widening it.
            </p>
            {/*
              The scope ranks these, it does not filter them. A lens scoped to
              one domain still reaches a metric that lives in another — which
              matters, because a retail risk lens legitimately carries
              scorecard validation figures and an analytics lens legitimately
              carries behavioural ones.
            */}
            <MetricPicker
              onPick={add}
              domain={scope?.domains[0] ?? ""}
              portfolio={scope?.portfolio ?? ""}
              placeholder="del · stage 2 · coverage · gini"
            />
          </div>

          <div className="mt-4 border-t border-border pt-4">
            <label className="block">
              <span className="text-[11px] font-medium text-text-secondary">
                Description
              </span>
              <span className="ml-1.5 text-[11px] text-text-muted">
                One line, for the library card.
              </span>
              <input
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                placeholder="Where the retail book is behind, and whether it is coming back."
                className="mt-1 h-8 w-full rounded-md border border-border bg-surface px-2.5 text-xs text-text-primary placeholder:text-text-muted focus:border-accent focus:outline-none"
              />
            </label>
          </div>
        </Card>
      )}

      {named && (
        <div className="flex flex-wrap items-center gap-3">
          <Button onClick={save} disabled={busy || chosen.length === 0}>
            {busy ? (
              <Loader2 className="animate-spin" aria-hidden />
            ) : (
              <ArrowRight aria-hidden />
            )}
            Create the lens
          </Button>
          <p className="text-[11px] text-text-muted">
            {chosen.length === 0
              ? "Choose at least one metric. A lens with nothing on it cannot be saved."
              : `${chosen.length} ${chosen.length === 1 ? "metric" : "metrics"} — charts and layout come next, on the lens itself.`}
          </p>
        </div>
      )}
    </div>
  );
}

function Step({
  number,
  title,
  done,
}: {
  number: number;
  title: string;
  done: boolean;
}) {
  return (
    <div className="flex items-center gap-2">
      <span
        className={`inline-flex size-5 shrink-0 items-center justify-center rounded-full text-[10px] font-semibold ${
          done
            ? "bg-accent text-white"
            : "border border-border text-text-muted"
        }`}
        aria-hidden
      >
        {done ? <Check className="size-3" /> : number}
      </span>
      <h2 className="text-sm font-semibold tracking-tight text-text-primary">
        {title}
      </h2>
    </div>
  );
}
