"""data builder — uploads, mappings, relationships and published versions

Adds the tables behind the Data Builder workflow
(Domain -> Dataset -> Upload -> Inspect -> Map -> Dictionary -> Relationships
-> Validate -> Publish):

  dataset_uploads        one uploaded source file, its RAW path, checksum and
                         automatic profile. The bytes are never modified.
  field_mappings         source column -> governed field, with the mapping
                         status (mapped / unmapped / ignored / proposed).
  dataset_relationships  governed joins, e.g. portfolio.account_id -> ecl.account_id
  data_versions          an immutable published release: row counts, periods,
                         the catalogue snapshot and the quality report.

dataset_definitions also gains its lifecycle columns. Only a dataset at
lifecycle='published' is visible to the analytical engine.

Revision ID: 0003
Revises: 0002
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('from_dataset', sa.String(length=160), nullable=False),
    sa.Column('from_field', sa.String(length=160), nullable=False),
    sa.Column('to_dataset', sa.String(length=160), nullable=False),
    sa.Column('to_field', sa.String(length=160), nullable=False),
    sa.Column('cardinality', sa.String(length=24), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_dataset', 'from_field', 'to_dataset', 'to_field', name='uq_relationship')
    )
    op.create_table('dataset_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('file_format', sa.String(length=16), nullable=False),
    sa.Column('sheet_name', sa.String(length=120), nullable=True),
    sa.Column('raw_path', sa.Text(), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('column_count', sa.Integer(), nullable=False),
    sa.Column('profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('field_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('source_column', sa.String(length=300), nullable=False),
    sa.Column('governed_field', sa.String(length=160), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'source_column', name='uq_mapping_per_source_column')
    )
    op.create_table('data_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('field_count', sa.Integer(), nullable=False),
    sa.Column('periods', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('analytics_path', sa.Text(), nullable=False),
    sa.Column('curated_path', sa.Text(), nullable=False),
    sa.Column('catalog_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('quality_report', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('published_by', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['dataset_uploads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'version', name='uq_data_version')
    )
    op.add_column('dataset_definitions', sa.Column('lifecycle', sa.String(length=24), nullable=False))
    op.add_column('dataset_definitions', sa.Column('source_type', sa.String(length=24), nullable=False))
    op.add_column('dataset_definitions', sa.Column('published_version', sa.Integer(), nullable=True))
    op.add_column('dataset_definitions', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset_definitions', 'published_at')
    op.drop_column('dataset_definitions', 'published_version')
    op.drop_column('dataset_definitions', 'source_type')
    op.drop_column('dataset_definitions', 'lifecycle')
    op.drop_table('data_versions')
    op.drop_table('field_mappings')
    op.drop_table('dataset_uploads')
    op.drop_table('dataset_relationships')
    # ### end Alembic commands ###
