"""investigations, notifications and the data control plane

Three things arrive together because they are one product idea: an answer that
someone keeps, and the people who need to see it.

  investigations          a saved analytical object — a question with a name, an
                          owner, and optionally a project. Distinct from an
                          analysis_run, which is one execution and never changes.
  investigation_versions  one answer the investigation has had. A refresh
                          re-executes the plan against the published data and
                          writes a new version with IPM's account of what moved.
                          Figures are never carried forward.
  notifications           in-app only. Work assigned to you is visible when you
                          open IPM; email and push are a deployment concern.

dataset_definitions also gains the three columns that make Data Builder a
control plane rather than an inventory: where a dataset came from (demo or
client), which family it belongs to, and which governed purposes it is
AUTHORITATIVE for. That last column is what lets client data replace the
bundled demonstration book without a code change — and what stops a certified
analysis quietly reading demo data once client data exists.

Revision ID: 0004
Revises: 0003
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('object_type', sa.String(length=48), nullable=False),
    sa.Column('object_id', sa.String(length=120), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_user', 'notifications', ['user_id', 'read_at', 'created_at'], unique=False)
    op.create_table('investigations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('plan', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_investigations_owner', 'investigations', ['owner_id', 'updated_at'], unique=False)
    op.create_index('ix_investigations_project', 'investigations', ['project_id', 'updated_at'], unique=False)
    op.create_table('investigation_versions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('investigation_id', sa.BigInteger(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('analysis_run_id', sa.BigInteger(), nullable=True),
    sa.Column('from_period', sa.String(length=64), nullable=True),
    sa.Column('to_period', sa.String(length=64), nullable=True),
    sa.Column('narrative', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('change_narrative', sa.Text(), nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('investigation_id', 'version_number', name='uq_investigation_version')
    )
    # Server defaults so the columns can be added to a table that already has
    # rows. Existing datasets are the bundled demonstration book, which is
    # exactly what origin='demo' means, so the default is also the correct value.
    op.add_column(
        'dataset_definitions',
        sa.Column('origin', sa.String(length=24), nullable=False, server_default='demo'),
    )
    op.add_column(
        'dataset_definitions',
        sa.Column('dataset_family', sa.String(length=160), nullable=False, server_default=''),
    )
    op.add_column(
        'dataset_definitions',
        sa.Column(
            'authoritative_for',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
    )
    # The defaults did their job on the existing rows; the application supplies
    # the value from here on, so they are dropped rather than left to make a
    # future insert silently succeed with the wrong origin.
    op.alter_column('dataset_definitions', 'origin', server_default=None)
    op.alter_column('dataset_definitions', 'dataset_family', server_default=None)
    op.alter_column('dataset_definitions', 'authoritative_for', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset_definitions', 'authoritative_for')
    op.drop_column('dataset_definitions', 'dataset_family')
    op.drop_column('dataset_definitions', 'origin')
    op.drop_table('investigation_versions')
    op.drop_index('ix_investigations_project', table_name='investigations')
    op.drop_index('ix_investigations_owner', table_name='investigations')
    op.drop_table('investigations')
    op.drop_index('ix_notifications_user', table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
