"""Update requests: a chase is a reminder somebody is expected to answer.

Adds the follow-up state to `planner_reminders` rather than creating a second
table. A chase and a reminder are the same event seen at two moments — the ask
and the answer — and the fingerprint that already stops a reminder repeating is
exactly the key that stops one person being chased twice for one thing.

Written by hand rather than autogenerated, for the reason recorded in 0034: the
live schema has drifted from the models elsewhere (type widenings and index
drops on agent_runs, analysis_runs, investigations, review_queue_items,
risk_cases and the workflow tables), and an autogenerated revision would carry
those unrelated changes under a name that says "planner update requests".

Revision ID: 0035
Revises: 0034
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0035"
down_revision = "0034"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        "planner_reminders",
        sa.Column("state", sa.String(length=16), nullable=False,
                  server_default=sa.text("'sent'")))
    op.add_column(
        "planner_reminders",
        sa.Column("asked", sa.Boolean(), nullable=False,
                  server_default=sa.text("false")))
    op.add_column(
        "planner_reminders",
        sa.Column("reason", sa.Text(), nullable=False,
                  server_default=sa.text("''")))
    op.add_column(
        "planner_reminders",
        sa.Column("requested_by", sa.BigInteger(), nullable=True))
    op.add_column(
        "planner_reminders",
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "planner_reminders",
        sa.Column("response_update_id", sa.BigInteger(), nullable=True))

    op.create_foreign_key(
        "fk_planner_reminders_requested_by", "planner_reminders", "users",
        ["requested_by"], ["id"], ondelete="SET NULL")
    op.create_foreign_key(
        "fk_planner_reminders_response", "planner_reminders",
        "planner_updates", ["response_update_id"], ["id"], ondelete="SET NULL")

    op.create_index("ix_planner_reminders_asked", "planner_reminders",
                    ["project_id", "asked", "state"])
    op.create_index("ix_planner_reminders_user", "planner_reminders",
                    ["user_id", "state"])


def downgrade() -> None:
    op.drop_index("ix_planner_reminders_user", table_name="planner_reminders")
    op.drop_index("ix_planner_reminders_asked", table_name="planner_reminders")
    op.drop_constraint("fk_planner_reminders_response", "planner_reminders",
                       type_="foreignkey")
    op.drop_constraint("fk_planner_reminders_requested_by",
                       "planner_reminders", type_="foreignkey")
    for column in ("response_update_id", "responded_at", "requested_by",
                   "reason", "asked", "state"):
        op.drop_column("planner_reminders", column)
