"""The metric catalogue: user-built metrics and their verification records.

Two tables, and neither holds a governed metric. The governed library lives in
code (`backend/metrics/library.py`) because a definition of "default rate" that
can be edited in a database row is not a governed definition. What lives here is
what a person built, and what a person checked.

`metric_verifications.metric_id` is deliberately not a foreign key. A governed
metric has no row to point at and still deserves a verification history — the
whole value of §10 is that somebody can put their own number beside CreditProbe's
and record what they found, whoever wrote the metric.

Written by hand rather than autogenerated, for the reason recorded in 0034 and
0035: the live schema has drifted from the models elsewhere, and an
autogenerated revision would carry those unrelated changes under this name.

Revision ID: 0037
Revises: 0036
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0037"
down_revision = "0036"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "user_metrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("metric_id", sa.String(length=160), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("definition_text", sa.Text(), nullable=False,
                  server_default=""),
        sa.Column("definition", postgresql.JSONB(astext_type=sa.Text()),
                  nullable=False, server_default="{}"),
        sa.Column("presentation", postgresql.JSONB(astext_type=sa.Text()),
                  nullable=False, server_default="{}"),
        sa.Column("unit", sa.String(length=24), nullable=False,
                  server_default="number"),
        sa.Column("domain", sa.String(length=120), nullable=False,
                  server_default=""),
        sa.Column("portfolio", sa.String(length=120), nullable=False,
                  server_default=""),
        sa.Column("status", sa.String(length=32), nullable=False,
                  server_default="DRAFT"),
        sa.Column("version", sa.String(length=16), nullable=False,
                  server_default="1.0.0"),
        sa.Column("owner", sa.String(length=160), nullable=False,
                  server_default=""),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("verified_by", sa.Integer(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verification_note", sa.Text(), nullable=False,
                  server_default=""),
        sa.Column("shared", sa.Boolean(), nullable=False,
                  server_default=sa.text("false")),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"]),
        sa.ForeignKeyConstraint(["verified_by"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("metric_id"),
    )
    op.create_index("ix_user_metrics_owner", "user_metrics",
                    ["created_by", "status"])
    op.create_index("ix_user_metrics_domain", "user_metrics", ["domain"])

    op.create_table(
        "metric_verifications",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("metric_id", sa.String(length=160), nullable=False),
        sa.Column("period", sa.String(length=32), nullable=False,
                  server_default=""),
        sa.Column("computed", sa.Float(), nullable=True),
        sa.Column("run_id", sa.String(length=48), nullable=False,
                  server_default=""),
        sa.Column("expected", sa.Float(), nullable=True),
        sa.Column("expected_source", sa.String(length=240), nullable=False,
                  server_default=""),
        sa.Column("difference", sa.Float(), nullable=True),
        sa.Column("outcome", sa.String(length=24), nullable=False,
                  server_default="NOT_COMPARED"),
        sa.Column("tolerance", sa.Float(), nullable=False,
                  server_default="0"),
        sa.Column("note", sa.Text(), nullable=False, server_default=""),
        sa.Column("decision", sa.String(length=24), nullable=False,
                  server_default="RECORDED"),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_metric_verifications_metric", "metric_verifications",
                    ["metric_id", "created_at"])


def downgrade() -> None:
    op.drop_index("ix_metric_verifications_metric",
                  table_name="metric_verifications")
    op.drop_table("metric_verifications")
    op.drop_index("ix_user_metrics_domain", table_name="user_metrics")
    op.drop_index("ix_user_metrics_owner", table_name="user_metrics")
    op.drop_table("user_metrics")
