"""Demo projects say so, and say what day their dates were anchored to.

Two columns on `planner_projects`, and both exist to make one operation safe:
re-anchoring a demonstration's relative dates to today without touching a
project somebody actually runs their work in.

`demo_origin` is the marker. Empty on every project a person created, and
non-empty only on programmes CreditProbe seeded. Nothing reads it to decide
what to *show*; it exists so the refresh can decide what it may *move*, and so
that decision is a stored fact rather than a guess from a project code.

`demo_anchor_date` is the day those dates were relative to. The seed writes
every date as an offset from the day it ran — a task due "in three days" — and
that is true on the day and decays afterwards: on the next day it is due in
two, which is not a reminder threshold, and the demonstration's centrepiece
stops being able to fire. Storing the anchor turns "roll this forward" into
arithmetic anybody can check: shift every canonical scheduling field by
`today - anchor`, and set the anchor to today. Run twice on one day the shift
is zero and nothing moves, which is what makes the refresh idempotent.

Written by hand rather than autogenerated, for the reason recorded in 0034,
0035 and 0037: the live schema has drifted from the models elsewhere, and an
autogenerated revision would carry those unrelated changes under this name.

Revision ID: 0038
Revises: 0037
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0038"
down_revision = "0037"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        "planner_projects",
        sa.Column("demo_origin", sa.String(length=40), nullable=False,
                  server_default=sa.text("''")))
    op.add_column(
        "planner_projects",
        sa.Column("demo_anchor_date", sa.Date(), nullable=True))
    # Only demo rows are ever looked up by this, and there are four of them
    # among however many real projects a bank has.
    op.create_index("ix_planner_projects_demo", "planner_projects",
                    ["demo_origin"],
                    postgresql_where=sa.text("demo_origin <> ''"))

    # Adopt a portfolio that was already seeded, rather than making somebody
    # re-run the seed to get the marker — which would mean rebuilding, which
    # is the destructive thing this whole change exists to avoid.
    #
    # Scoped to the four codes the seed itself owns. A project a person created
    # is untouched: it has none of these codes, and if one somehow did, the
    # marker would be wrong rather than dangerous — the refresh moves dates, it
    # never deletes.
    #
    # The anchor is the row's own creation date: that IS the day the seed ran
    # and the day its offsets were measured from, and unlike anything derived
    # from the task dates it cannot be moved by a person finishing a piece of
    # work. It is exactly right for the population that needs adopting — a
    # portfolio seeded before this column existed, and therefore never
    # refreshed.
    #
    # One caveat, and it is a developer-only path: a downgrade drops the
    # anchor, so a later upgrade re-derives it from the creation date, which
    # is one day stale per refresh that had happened in between. `apply`
    # refuses to roll dates BACKWARDS for exactly this reason, so the failure
    # mode is a refusal rather than a demonstration quietly moved into the
    # past. Run `--refresh-dates --dry-run` after a downgrade and check the
    # shift before letting it write.
    op.execute(sa.text("""
        UPDATE planner_projects p
           SET demo_origin = 'creditprobe.retail_demo',
               demo_anchor_date = p.created_at::date
         WHERE p.code IN ('RET-IFRS9', 'RET-SCORECARD',
                          'RET-COLLECTIONS', 'RET-DATA-REM')
           AND p.demo_origin = ''
    """))


def downgrade() -> None:
    # The anchor is dropped with the column, and the upgrade recovers it from
    # the newest completion date rather than needing it kept anywhere else.
    op.drop_index("ix_planner_projects_demo", table_name="planner_projects")
    op.drop_column("planner_projects", "demo_anchor_date")
    op.drop_column("planner_projects", "demo_origin")
