"""Playbook means the committee pack now, and the old Playbooks feature is gone.

Two halves of one change, in one revision on purpose. The earlier Playbooks
feature — a standing instruction that ran certified analyses and tested
thresholds — has been removed at the product owner's direction, and the name
Playbook has been given to the committee pack intelligence system. Splitting
those into two revisions would leave a head at which the product has no
Playbook at all and a `playbooks` table nothing reads, which is a state nobody
should have to deploy through.

What goes
---------
`playbooks` and `playbook_runs`, and the rows in them. There is no data to
carry across: a standing analytical instruction and a governance pack are not
the same object under two names, and there is no honest mapping between a
threshold condition and a committee section. Pretending otherwise would put
invented committee packs in front of a client.

What arrives
------------
Fifteen tables, all prefixed `playbook_`, described in
`backend/models/playbook.py`. Three properties of the schema are worth naming
here because they are what a reviewer should check:

  * `playbook_snapshots` is append-only and carries the formula hash, metric
    version, period, filters and calculation trace beside every value, which
    is what makes an approved pack reproducible six months later.
  * `playbook_events` is append-only, in the shape `planner_updates` already
    uses, so one person reading a committee's history and a project's history
    reads one vocabulary.
  * `playbook_committees` and `playbook_templates` reference each other. The
    committee's `default_template_id` foreign key is therefore added after
    both tables exist rather than inline, and dropped before them.

Nothing outside the Playbook feature is touched. No column is added to a
CreditProbe table, no index on an unrelated one is changed, and the only rows
this revision deletes are the ones in the two tables it drops.

Written by hand rather than autogenerated, for the reason recorded in 0034,
0035, 0037 and 0038: the live schema has drifted from the models elsewhere,
and an autogenerated revision would carry those unrelated changes under this
name. The `playbook_*` tables below were generated from the models and then
read through, which is safe precisely because they are new — there is no
drift possible in a table that does not exist yet.

Revision ID: 0039
Revises: 0038
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0039"
down_revision = "0038"
branch_labels = None
depends_on = None

#: Dropped newest-dependency-first on downgrade. Written out rather than
#: reversed from a create order, because getting it wrong fails halfway
#: through and leaves the schema in neither state.
DROP_ORDER = (
    "playbook_sources",
    "playbook_reminders",
    "playbook_events",
    "playbook_versions",
    "playbook_reviews",
    "playbook_actions",
    "playbook_decisions",
    "playbook_findings",
    "playbook_blocks",
    "playbook_snapshots",
    "playbook_sections",
    "playbook_packs",
    "playbook_members",
    "playbook_templates",
    "playbook_committees",
)


def upgrade() -> None:
    # ---- the earlier feature ------------------------------------------
    # Runs first, and children before parents. `playbook_runs` also points at
    # `investigations`, which stays: dropping the table takes the reference
    # with it and leaves the Investigation alone, which is right — the
    # Investigation was somebody's analytical work and outlives the
    # instruction that started it.
    op.drop_index("ix_playbook_runs_playbook", table_name="playbook_runs")
    op.drop_table("playbook_runs")
    op.drop_table("playbooks")

    # ---- the committee pack -------------------------------------------
    op.create_table(
        "playbook_committees",
        sa.Column("id", sa.Integer(), nullable=False, primary_key=True),
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("purpose", sa.Text(), nullable=False),
        sa.Column("business_area", sa.String(length=120), nullable=False),
        sa.Column("chair_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=True),
        sa.Column(
            "secretary_id",
            sa.Integer(),
            sa.ForeignKey("users.id"), nullable=True),
        sa.Column("cadence", sa.String(length=24), nullable=False),
        sa.Column("meeting_weekday", sa.Integer(), nullable=True),
        sa.Column("default_template_id", sa.Integer(), nullable=True),
        sa.Column(
            "standard_agenda", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "workflow_offsets", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("confidentiality", sa.String(length=32), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "demo_origin",
            sa.String(length=40), server_default=sa.text("''"), nullable=False),
        sa.Column("demo_anchor_date", sa.Date(), nullable=True),
        sa.Column("created_by", sa.Integer(), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("updated_by", sa.Integer(), sa.ForeignKey("users.id"), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.UniqueConstraint("code",
                            name="uq_playbook_committee_code"),
    )
    op.create_index("ix_playbook_committees_active", "playbook_committees",
                    ["active", "business_area"])
    op.create_index("ix_playbook_committees_demo", "playbook_committees",
                    ["demo_origin"],
                    postgresql_where=sa.text("demo_origin <> ''"))
    op.create_table(
        "playbook_templates",
        sa.Column("id", sa.Integer(), nullable=False, primary_key=True),
        sa.Column(
            "committee_id",
            sa.Integer(),
            sa.ForeignKey("playbook_committees.id", ondelete="CASCADE"), nullable=True),
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("sections", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "materiality", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "required_domains", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "required_datasets", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "export_settings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("confidentiality", sa.String(length=32), nullable=False),
        sa.Column(
            "demo_origin",
            sa.String(length=40), server_default=sa.text("''"), nullable=False),
        sa.Column("created_by", sa.Integer(), sa.ForeignKey("users.id"), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.UniqueConstraint("code", "version",
                            name="uq_playbook_template_version"),
    )
    op.create_index("ix_playbook_templates_committee", "playbook_templates",
                    ["committee_id", "status"])
    op.create_table(
        "playbook_members",
        sa.Column("id", sa.Integer(), nullable=False, primary_key=True),
        sa.Column(
            "committee_id",
            sa.Integer(),
            sa.ForeignKey("playbook_committees.id", ondelete="CASCADE"), nullable=False),
        sa.Column(
            "user_id",
            sa.Integer(),
            sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("business_role", sa.String(length=32), nullable=False),
        sa.Column("access_role", sa.String(length=24), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("notify", sa.Boolean(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.UniqueConstraint("committee_id", "user_id",
                            name="uq_playbook_member"),
    )
    op.create_index("ix_playbook_members_user", "playbook_members",
                    ["user_id", "active"])
    op.create_table(
        "playbook_packs",
        sa.Column("id", sa.Integer(), nullable=False, primary_key=True),
        sa.Column("code", sa.String(length=48), nullable=False),
        sa.Column(
            "committee_id",
            sa.Integer(),
            sa.ForeignKey("playbook_committees.id", ondelete="CASCADE"), nullable=False),
        sa.Column(
            "template_id",
            sa.Integer(),
            sa.ForeignKey("playbook_templates.id", ondelete="SET NULL"), nullable=True),
        sa.Column("name", sa.String(length=240), nullable=False),
        sa.Column("period", sa.String(length=32), nullable=False),
        sa.Column("comparison_period", sa.String(length=32), nullable=False),
        sa.Column("meeting_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("as_of_date", sa.Date(), nullable=True),
        sa.Column("data_freeze_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("owner_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("confidentiality", sa.String(length=32), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("approved_version", sa.Integer(), nullable=True),
        sa.Column(
            "amends_pack_id",
            sa.Integer(),
            sa.ForeignKey("playbook_packs.id", ondelete="SET NULL"), nullable=True),
        sa.Column("amendment_reason", sa.Text(), nullable=False),
        sa.Column(
            "previous_pack_id",
            sa.Integer(),
            sa.ForeignKey("playbook_packs.id", ondelete="SET NULL"), nullable=True),
        sa.Column("readiness_percent", sa.Integer(), nullable=False),
        sa.Column("readiness_state", sa.String(length=16), nullable=False),
        sa.Column("readiness_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "readiness_reasons", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("data_state", sa.String(length=16), nullable=False),
        sa.Column(
            "approved_by",
            sa.Integer(),
            sa.ForeignKey("users.id"), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("minutes", sa.Text(), nullable=False),
        sa.Column(
            "demo_origin",
            sa.String(length=40), server_default=sa.text("''"), nullable=False),
        sa.Column("created_by", sa.Integer(), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("updated_by", sa.Integer(), sa.ForeignKey("users.id"), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.UniqueConstraint("code",
                            name="uq_playbook_pack_code"),
    )
    op.create_index("ix_playbook_packs_committee", "playbook_packs",
                    ["committee_id", "meeting_at"])
    op.create_index("ix_playbook_packs_demo", "playbook_packs",
                    ["demo_origin"],
                    postgresql_where=sa.text("demo_origin <> ''"))
    op.create_index("ix_playbook_packs_owner", "playbook_packs",
                    ["owner_id", "status"])
    op.create_index("ix_playbook_packs_status", "playbook_packs",
                    ["status", "meeting_at"])
    op.create_table(
        "playbook_sections",
        sa.Column("id", sa.Integer(), nullable=False, primary_key=True),
        sa.Column(
            "pack_id",
            sa.Integer(),
            sa.ForeignKey("playbook_packs.id", ondelete="CASCADE"), nullable=False),
        sa.Column("template_key", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("purpose", sa.Text(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=True),
        sa.Column(
            "reviewer_id",
            sa.Integer(),
            sa.ForeignKey("users.id"), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("narrative_instructions", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "submitted_by",
            sa.Integer(),
            sa.ForeignKey("users.id"), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "approved_by",
            sa.Integer(),
            sa.ForeignKey("users.id"), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_by", sa.Integer(), sa.ForeignKey("users.id"), nullable=True),
    )
    op.create_index("ix_playbook_sections_owner", "playbook_sections",
                    ["owner_id", "status"])
    op.create_index("ix_playbook_sections_pack", "playbook_sections",
                    ["pack_id", "position"])
    op.create_index("ix_playbook_sections_reviewer", "playbook_sections",
                    ["reviewer_id", "status"])
    op.create_table(
        "playbook_snapshots",
        sa.Column("id", sa.BigInteger(), nullable=False, primary_key=True),
        sa.Column(
            "pack_id",
            sa.Integer(),
            sa.ForeignKey("playbook_packs.id", ondelete="CASCADE"), nullable=False),
        sa.Column("pack_version", sa.Integer(), nullable=False),
        sa.Column("metric_id", sa.String(length=160), nullable=False),
        sa.Column("metric_name", sa.String(length=200), nullable=False),
        sa.Column("metric_version", sa.String(length=24), nullable=False),
        sa.Column("formula_hash", sa.String(length=64), nullable=False),
        sa.Column("period", sa.String(length=32), nullable=False),
        sa.Column("comparison_period", sa.String(length=32), nullable=False),
        sa.Column("filters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("comparison_value", sa.Float(), nullable=True),
        sa.Column("display_value", sa.String(length=64), nullable=False),
        sa.Column("unit", sa.String(length=24), nullable=False),
        sa.Column("decimals", sa.Integer(), nullable=False),
        sa.Column("higher_is_better", sa.Boolean(), nullable=True),
        sa.Column("numerator", sa.Float(), nullable=True),
        sa.Column("denominator", sa.Float(), nullable=True),
        sa.Column("rows_considered", sa.Integer(), nullable=False),
        sa.Column("series", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("availability", sa.String(length=32), nullable=False),
        sa.Column("unavailable_reason", sa.Text(), nullable=False),
        sa.Column("dataset", sa.String(length=160), nullable=False),
        sa.Column("dataset_version", sa.String(length=64), nullable=False),
        sa.Column(
            "source_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "calculation", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("run_id", sa.String(length=48), nullable=False),
        sa.Column("sql", sa.Text(), nullable=False),
        sa.Column(
            "lens_id",
            sa.Integer(),
            sa.ForeignKey("lenses.id", ondelete="SET NULL"), nullable=True),
        sa.Column("verification_state", sa.String(length=24), nullable=False),
        sa.Column("governed", sa.Boolean(), nullable=False),
        sa.Column(
            "calculated_at",
            sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column(
            "calculated_by",
            sa.Integer(),
            sa.ForeignKey("users.id"), nullable=True),
    )
    op.create_index("ix_playbook_snapshots_metric", "playbook_snapshots",
                    ["pack_id", "metric_id"])
    op.create_index("ix_playbook_snapshots_pack", "playbook_snapshots",
                    ["pack_id", "pack_version"])
    op.create_table(
        "playbook_blocks",
        sa.Column("id", sa.Integer(), nullable=False, primary_key=True),
        sa.Column(
            "section_id",
            sa.Integer(),
            sa.ForeignKey("playbook_sections.id", ondelete="CASCADE"), nullable=False),
        sa.Column(
            "pack_id",
            sa.Integer(),
            sa.ForeignKey("playbook_packs.id", ondelete="CASCADE"), nullable=False),
        sa.Column("block_type", sa.String(length=32), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("statement_kind", sa.String(length=24), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("filters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("period", sa.String(length=32), nullable=False),
        sa.Column(
            "snapshot_id",
            sa.BigInteger(),
            sa.ForeignKey("playbook_snapshots.id", ondelete="SET NULL"), nullable=True),
        sa.Column("import_class", sa.String(length=32), nullable=False),
        sa.Column("author_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("ai_accepted", sa.Boolean(), nullable=False),
        sa.Column("stale", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_index("ix_playbook_blocks_pack", "playbook_blocks",
                    ["pack_id", "block_type"])
    op.create_index("ix_playbook_blocks_section", "playbook_blocks",
                    ["section_id", "position"])
    op.create_table(
        "playbook_findings",
        sa.Column("id", sa.Integer(), nullable=False, primary_key=True),
        sa.Column(
            "pack_id",
            sa.Integer(),
            sa.ForeignKey("playbook_packs.id", ondelete="CASCADE"), nullable=False),
        sa.Column(
            "section_id",
            sa.Integer(),
            sa.ForeignKey("playbook_sections.id", ondelete="SET NULL"), nullable=True),
        sa.Column("finding_type", sa.String(length=32), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("factual_basis", sa.Text(), nullable=False),
        sa.Column("metric_id", sa.String(length=160), nullable=False),
        sa.Column(
            "snapshot_id",
            sa.BigInteger(),
            sa.ForeignKey("playbook_snapshots.id", ondelete="SET NULL"), nullable=True),
        sa.Column("period", sa.String(length=32), nullable=False),
        sa.Column("rule_key", sa.String(length=80), nullable=False),
        sa.Column(
            "rule_detail", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("fingerprint", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("owner_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("response", sa.Text(), nullable=False),
        sa.Column("dismissed_reason", sa.Text(), nullable=False),
        sa.Column(
            "dismissed_by",
            sa.Integer(),
            sa.ForeignKey("users.id"), nullable=True),
        sa.Column("dismissed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.UniqueConstraint("pack_id", "fingerprint",
                            name="uq_playbook_finding_print"),
    )
    op.create_index("ix_playbook_findings_pack", "playbook_findings",
                    ["pack_id", "severity", "status"])
    op.create_table(
        "playbook_decisions",
        sa.Column("id", sa.Integer(), nullable=False, primary_key=True),
        sa.Column(
            "committee_id",
            sa.Integer(),
            sa.ForeignKey("playbook_committees.id", ondelete="CASCADE"), nullable=False),
        sa.Column(
            "pack_id",
            sa.Integer(),
            sa.ForeignKey("playbook_packs.id", ondelete="SET NULL"), nullable=True),
        sa.Column(
            "section_id",
            sa.Integer(),
            sa.ForeignKey("playbook_sections.id", ondelete="SET NULL"), nullable=True),
        sa.Column("reference", sa.String(length=40), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("recommendation", sa.Text(), nullable=False),
        sa.Column(
            "alternatives", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("impact", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "requested_by",
            sa.Integer(),
            sa.ForeignKey("users.id"), nullable=True),
        sa.Column("owner_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("decided_by", sa.Integer(), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decision_text", sa.Text(), nullable=False),
        sa.Column("conditions", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_index("ix_playbook_decisions_committee", "playbook_decisions",
                    ["committee_id", "status"])
    op.create_index("ix_playbook_decisions_pack", "playbook_decisions",
                    ["pack_id", "status"])
    op.create_table(
        "playbook_actions",
        sa.Column("id", sa.Integer(), nullable=False, primary_key=True),
        sa.Column(
            "committee_id",
            sa.Integer(),
            sa.ForeignKey("playbook_committees.id", ondelete="CASCADE"), nullable=False),
        sa.Column(
            "pack_id",
            sa.Integer(),
            sa.ForeignKey("playbook_packs.id", ondelete="SET NULL"), nullable=True),
        sa.Column(
            "decision_id",
            sa.Integer(),
            sa.ForeignKey("playbook_decisions.id", ondelete="SET NULL"), nullable=True),
        sa.Column("reference", sa.String(length=40), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("owner_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("priority", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("latest_update", sa.Text(), nullable=False),
        sa.Column("closure_evidence", sa.Text(), nullable=False),
        sa.Column(
            "planner_project_id",
            sa.BigInteger(),
            sa.ForeignKey("planner_projects.id", ondelete="SET NULL"), nullable=True),
        sa.Column(
            "planner_task_id",
            sa.BigInteger(),
            sa.ForeignKey("planner_tasks.id", ondelete="SET NULL"), nullable=True),
        sa.Column("linked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("linked_by", sa.Integer(), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("created_by", sa.Integer(), sa.ForeignKey("users.id"), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index("ix_playbook_actions_committee", "playbook_actions",
                    ["committee_id", "status"])
    op.create_index("ix_playbook_actions_owner", "playbook_actions",
                    ["owner_id", "status", "due_date"])
    op.create_index("ix_playbook_actions_task", "playbook_actions",
                    ["planner_task_id"])
    op.create_table(
        "playbook_reviews",
        sa.Column("id", sa.Integer(), nullable=False, primary_key=True),
        sa.Column(
            "pack_id",
            sa.Integer(),
            sa.ForeignKey("playbook_packs.id", ondelete="CASCADE"), nullable=False),
        sa.Column(
            "section_id",
            sa.Integer(),
            sa.ForeignKey("playbook_sections.id", ondelete="CASCADE"), nullable=True),
        sa.Column("scope", sa.String(length=16), nullable=False),
        sa.Column(
            "reviewer_id",
            sa.Integer(),
            sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("decision", sa.String(length=24), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("conditions", sa.Text(), nullable=False),
        sa.Column("at_version", sa.Integer(), nullable=False),
        sa.Column(
            "requested_at",
            sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column(
            "requested_by",
            sa.Integer(),
            sa.ForeignKey("users.id"), nullable=True),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index("ix_playbook_reviews_pack", "playbook_reviews",
                    ["pack_id", "decision"])
    op.create_index("ix_playbook_reviews_reviewer", "playbook_reviews",
                    ["reviewer_id", "decision"])
    op.create_index("ix_playbook_reviews_section", "playbook_reviews",
                    ["section_id", "decision"])
    op.create_table(
        "playbook_versions",
        sa.Column("id", sa.BigInteger(), nullable=False, primary_key=True),
        sa.Column(
            "pack_id",
            sa.Integer(),
            sa.ForeignKey("playbook_packs.id", ondelete="CASCADE"), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("created_by", sa.Integer(), sa.ForeignKey("users.id"), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.UniqueConstraint("pack_id", "version", "kind",
                            name="uq_playbook_version"),
    )
    op.create_index("ix_playbook_versions_pack", "playbook_versions",
                    ["pack_id", "version"])
    op.create_table(
        "playbook_events",
        sa.Column("id", sa.BigInteger(), nullable=False, primary_key=True),
        sa.Column(
            "pack_id",
            sa.Integer(),
            sa.ForeignKey("playbook_packs.id", ondelete="CASCADE"), nullable=True),
        sa.Column(
            "committee_id",
            sa.Integer(),
            sa.ForeignKey("playbook_committees.id", ondelete="CASCADE"), nullable=True),
        sa.Column("entity_type", sa.String(length=24), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=True),
        sa.Column("entity_ref", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("changes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("narrative", sa.Text(), nullable=False),
        sa.Column("at_version", sa.Integer(), nullable=True),
        sa.Column("author_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_index("ix_playbook_events_entity", "playbook_events",
                    ["entity_type", "entity_id"])
    op.create_index("ix_playbook_events_pack", "playbook_events",
                    ["pack_id", "created_at"])
    op.create_table(
        "playbook_reminders",
        sa.Column("id", sa.BigInteger(), nullable=False, primary_key=True),
        sa.Column(
            "pack_id",
            sa.Integer(),
            sa.ForeignKey("playbook_packs.id", ondelete="CASCADE"), nullable=True),
        sa.Column(
            "committee_id",
            sa.Integer(),
            sa.ForeignKey("playbook_committees.id", ondelete="CASCADE"), nullable=True),
        sa.Column("entity_type", sa.String(length=24), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=True),
        sa.Column(
            "user_id",
            sa.Integer(),
            sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("trigger", sa.String(length=32), nullable=False),
        sa.Column("fingerprint", sa.String(length=200), nullable=False),
        sa.Column("notification_id", sa.BigInteger(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.UniqueConstraint("fingerprint",
                            name="uq_playbook_reminder_print"),
    )
    op.create_index("ix_playbook_reminders_pack", "playbook_reminders",
                    ["pack_id", "trigger"])
    op.create_index("ix_playbook_reminders_user", "playbook_reminders",
                    ["user_id", "created_at"])
    op.create_table(
        "playbook_sources",
        sa.Column("id", sa.Integer(), nullable=False, primary_key=True),
        sa.Column(
            "pack_id",
            sa.Integer(),
            sa.ForeignKey("playbook_packs.id", ondelete="CASCADE"), nullable=False),
        sa.Column(
            "section_id",
            sa.Integer(),
            sa.ForeignKey("playbook_sections.id", ondelete="SET NULL"), nullable=True),
        sa.Column(
            "block_id",
            sa.Integer(),
            sa.ForeignKey("playbook_blocks.id", ondelete="CASCADE"), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("label", sa.String(length=240), nullable=False),
        sa.Column("reference", sa.String(length=240), nullable=False),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=120), nullable=False),
        sa.Column("byte_size", sa.BigInteger(), nullable=False),
        sa.Column("stored_path", sa.String(length=500), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("import_class", sa.String(length=32), nullable=False),
        sa.Column("warnings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "uploaded_by",
            sa.Integer(),
            sa.ForeignKey("users.id"), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_index("ix_playbook_sources_block", "playbook_sources",
                    ["block_id"])
    op.create_index("ix_playbook_sources_pack", "playbook_sources",
                    ["pack_id", "kind"])

    # Deferred until both tables exist. See the note at the top.
    op.create_foreign_key(
        "fk_playbook_committee_default_template",
        "playbook_committees", "playbook_templates",
        ["default_template_id"], ["id"], ondelete="SET NULL")


def downgrade() -> None:
    op.drop_constraint("fk_playbook_committee_default_template",
                       "playbook_committees", type_="foreignkey")
    for table in DROP_ORDER:
        op.drop_table(table)

    # ---- the earlier feature, restored ---------------------------------
    # A downgrade rebuilds the tables so that the revision is reversible and a
    # deployment can be rolled back. It does NOT restore the rows: this
    # revision deleted them and a migration cannot invent them back. Nor does
    # it restore the code — `backend/services/playbooks.py` and its router are
    # gone from the tree, so a database downgraded to 0038 has two empty
    # tables and no feature reading them. That is stated here rather than
    # discovered, because a reversible schema is not the same thing as a
    # reversible product change.
    op.create_table(
        "playbooks",
        sa.Column("id", sa.Integer(), nullable=False, primary_key=True),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("trigger", sa.String(length=32), nullable=False),
        sa.Column("schedule", sa.String(length=64), nullable=False),
        sa.Column("scope", postgresql.JSONB(astext_type=sa.Text()),
                  nullable=False),
        sa.Column("analyses", postgresql.JSONB(astext_type=sa.Text()),
                  nullable=False),
        sa.Column("conditions", postgresql.JSONB(astext_type=sa.Text()),
                  nullable=False),
        sa.Column("actions", postgresql.JSONB(astext_type=sa.Text()),
                  nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("origin", sa.String(length=24), nullable=False),
        sa.Column("owner", sa.String(length=160), nullable=False),
        sa.Column("owner_id", sa.Integer(), sa.ForeignKey("users.id"),
                  nullable=True),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_run_hint", sa.String(length=120), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=True),
        sa.UniqueConstraint("slug", name="playbooks_slug_key"),
    )
    op.create_table(
        "playbook_runs",
        sa.Column("id", sa.BigInteger(), nullable=False, primary_key=True),
        sa.Column("playbook_id", sa.Integer(),
                  sa.ForeignKey("playbooks.id", ondelete="CASCADE"),
                  nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("period", postgresql.JSONB(astext_type=sa.Text()),
                  nullable=False),
        sa.Column("results", postgresql.JSONB(astext_type=sa.Text()),
                  nullable=False),
        sa.Column("evaluations", postgresql.JSONB(astext_type=sa.Text()),
                  nullable=False),
        sa.Column("actions_taken", postgresql.JSONB(astext_type=sa.Text()),
                  nullable=False),
        sa.Column("alerted", sa.Boolean(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("error", sa.Text(), nullable=False),
        sa.Column("investigation_id", sa.Integer(),
                  sa.ForeignKey("investigations.id", ondelete="SET NULL"),
                  nullable=True),
        sa.Column("created_by", sa.Integer(), sa.ForeignKey("users.id"),
                  nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=True),
    )
    op.create_index("ix_playbook_runs_playbook", "playbook_runs",
                    ["playbook_id", "created_at"])
