"""A validation run becomes a record rather than a screen's memory.

Why this revision exists
------------------------
The Scorecard Validation engine is deterministic: the same model over the same
window gives the same numbers in any process at any hour. That was the
argument for storing nothing, and it is the wrong argument for a model-risk
function.

Six months after a validation, somebody has to open the run **a committee
saw** — not a run that agrees with it. Those diverge the moment the data moves
underneath: the parquet lake gains a month, a limit is revised, a binning
specification is re-approved. The recomputation is then a defensible number
about a different book, and a committee paper that silently follows the latest
data is one nobody can defend.

Four tables arrive
------------------
  scv_runs      one execution, with everything needed to say what was tested
                and against what
  scv_results   one row per test result, written once
  scv_findings  the findings as that run's engine read them
  scv_reports   a report bound by foreign key to its run

The `scv_` prefix is not decoration. `scorecard_validation_runs` is ALREADY
TAKEN — revision 0028 created it for the earlier retail scorecard module, one
row per model per period, and that table is still in service. Two different
things called the same name is how a migration silently drops somebody else's
data, so this module takes its own prefix and leaves 0028's table alone.

Three properties are worth naming here, because they are what a reviewer
should check:

  * `scv_results.value` is NULLABLE and stays nullable. Six
    of the ten result states mean "there is no number here", and the engine
    refuses to construct a result claiming one of those while carrying a
    value. A NOT NULL column with a zero default would undo that in storage,
    and a NOT_MATURED cohort would come back out of the database as a zero
    default rate.

  * `scv_reports.run_id` is ON DELETE RESTRICT, not CASCADE.
    A report is evidence of what a run said; deleting the run beneath a
    finalised report would leave a document nobody can reproduce. The database
    refuses rather than the service remembering to.

  * Five version columns on the run rather than one. The test registry, the
    threshold profile, the calculation kernel, the state vocabulary and the
    findings engine move independently, and a reader comparing two runs needs
    to know WHICH of them changed.

What this revision does NOT touch
---------------------------------
Nothing outside the Scorecard Validation module. No column is added to a
CreditProbe table, no index on an unrelated one is changed, and this revision
deletes no rows at all. The only foreign keys leaving these four tables point
at `users`, which already exists.

Written by hand rather than autogenerated, for the reason recorded in 0034,
0035, 0037, 0038 and 0039: the live schema has drifted from the models
elsewhere, and an autogenerated revision would carry those unrelated changes
under this one's name.

Downgrade drops the four tables and their rows. That is the honest inverse —
there is nowhere else for a validation run to go — and it is why the upgrade
is additive: nothing that existed before this revision depends on it.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0040"
down_revision = "0039"
branch_labels = None
depends_on = None

#: `server_default=sa.text("'{}'::jsonb")` on every JSONB column. A NOT NULL
#: JSONB with no default fails on any INSERT that omits it, and an ORM default
#: only helps a caller going through the ORM.
EMPTY_OBJECT = sa.text("'{}'::jsonb")
EMPTY_ARRAY = sa.text("'[]'::jsonb")


def upgrade() -> None:
    op.create_table(
        "scv_runs",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("run_key", sa.String(length=64), nullable=False),

        sa.Column("model_id", sa.String(length=64), nullable=False),
        sa.Column("model_name", sa.String(length=160), nullable=False,
                  server_default=""),
        sa.Column("model_version", sa.String(length=32), nullable=False,
                  server_default=""),
        sa.Column("model_kind", sa.String(length=24), nullable=False,
                  server_default="CHAMPION"),
        sa.Column("scorecard_type", sa.String(length=32), nullable=False,
                  server_default=""),
        sa.Column("domain", sa.String(length=64), nullable=False,
                  server_default=""),

        sa.Column("dataset", sa.String(length=128), nullable=False,
                  server_default=""),
        sa.Column("reference_dataset", sa.String(length=128), nullable=False,
                  server_default=""),
        sa.Column("decisions_dataset", sa.String(length=128), nullable=False,
                  server_default=""),
        sa.Column("dataset_as_of", sa.String(length=64), nullable=False,
                  server_default=""),
        sa.Column("dataset_version", sa.String(length=64), nullable=False,
                  server_default=""),

        sa.Column("requested_periods", postgresql.JSONB(), nullable=False,
                  server_default=EMPTY_ARRAY),
        sa.Column("matured_window", sa.String(length=64), nullable=False,
                  server_default=""),
        sa.Column("latest_period", sa.String(length=32), nullable=False,
                  server_default=""),
        sa.Column("reference_period", sa.String(length=32), nullable=False,
                  server_default=""),
        sa.Column("segment", sa.String(length=128), nullable=False,
                  server_default=""),
        sa.Column("segment_field", sa.String(length=128), nullable=False,
                  server_default=""),

        sa.Column("periods_available", sa.Integer(), nullable=False,
                  server_default="0"),
        sa.Column("periods_matured", sa.Integer(), nullable=False,
                  server_default="0"),
        sa.Column("periods_immature", sa.Integer(), nullable=False,
                  server_default="0"),
        sa.Column("performance_window_months", sa.Integer(), nullable=False,
                  server_default="0"),

        sa.Column("scope", sa.String(length=24), nullable=False,
                  server_default="FULL"),
        sa.Column("requested_categories", postgresql.JSONB(), nullable=False,
                  server_default=EMPTY_ARRAY),
        sa.Column("requested_tests", postgresql.JSONB(), nullable=False,
                  server_default=EMPTY_ARRAY),

        sa.Column("registry_version", sa.String(length=24), nullable=False,
                  server_default=""),
        sa.Column("threshold_profile_version", sa.String(length=24),
                  nullable=False, server_default=""),
        sa.Column("calculation_version", sa.String(length=24), nullable=False,
                  server_default=""),
        sa.Column("states_version", sa.String(length=24), nullable=False,
                  server_default=""),
        sa.Column("findings_version", sa.String(length=24), nullable=False,
                  server_default=""),

        sa.Column("returned", sa.Integer(), nullable=False,
                  server_default="0"),
        sa.Column("measured", sa.Integer(), nullable=False,
                  server_default="0"),
        sa.Column("tally", postgresql.JSONB(), nullable=False,
                  server_default=EMPTY_OBJECT),
        sa.Column("coverage", postgresql.JSONB(), nullable=False,
                  server_default=EMPTY_OBJECT),
        sa.Column("regulatory_coverage", postgresql.JSONB(), nullable=False,
                  server_default=EMPTY_OBJECT),
        sa.Column("findings_summary", postgresql.JSONB(), nullable=False,
                  server_default=EMPTY_OBJECT),

        sa.Column("initiated_by_id", sa.Integer(), nullable=True),
        sa.Column("initiated_by_name", sa.String(length=160), nullable=False,
                  server_default=""),
        sa.Column("initiated_by_role", sa.String(length=32), nullable=False,
                  server_default=""),
        sa.Column("source", sa.String(length=24), nullable=False,
                  server_default="UI"),
        sa.Column("source_detail", sa.Text(), nullable=False,
                  server_default=""),

        sa.Column("status", sa.String(length=24), nullable=False,
                  server_default="COMPLETE"),
        sa.Column("failure", sa.Text(), nullable=False, server_default=""),

        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=False,
                  server_default="0"),
        sa.Column("duplicated_from_id", sa.BigInteger(), nullable=True),

        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_key"),
        sa.ForeignKeyConstraint(["initiated_by_id"], ["users.id"],
                                ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["duplicated_from_id"],
                                ["scv_runs.id"],
                                ondelete="SET NULL"),
    )
    op.create_index("ix_scv_runs_model", "scv_runs",
                    ["model_id", "started_at"])
    op.create_index("ix_scv_runs_status", "scv_runs",
                    ["status", "started_at"])
    op.create_index("ix_scv_runs_user", "scv_runs",
                    ["initiated_by_id", "started_at"])

    op.create_table(
        "scv_results",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=False),

        sa.Column("test_id", sa.String(length=64), nullable=False),
        sa.Column("test_name", sa.String(length=200), nullable=False,
                  server_default=""),
        sa.Column("category", sa.String(length=48), nullable=False,
                  server_default=""),

        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("state_label", sa.String(length=48), nullable=False,
                  server_default=""),
        sa.Column("measured", sa.Boolean(), nullable=False,
                  server_default=sa.text("false")),
        sa.Column("severity", sa.Integer(), nullable=False,
                  server_default="0"),

        # Nullable, and it must stay that way. See the module docstring.
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("limit_value", sa.Float(), nullable=True),
        sa.Column("limit_source", sa.String(length=64), nullable=False,
                  server_default=""),
        sa.Column("comparison_value", sa.Float(), nullable=True),

        sa.Column("detail", sa.Text(), nullable=False, server_default=""),
        sa.Column("remedy", sa.Text(), nullable=False, server_default=""),
        sa.Column("method", sa.Text(), nullable=False, server_default=""),
        sa.Column("limitations", postgresql.JSONB(), nullable=False,
                  server_default=EMPTY_ARRAY),

        sa.Column("period", sa.String(length=64), nullable=False,
                  server_default=""),
        sa.Column("reference_period", sa.String(length=64), nullable=False,
                  server_default=""),
        sa.Column("segment", sa.String(length=128), nullable=False,
                  server_default=""),
        sa.Column("observations", sa.Integer(), nullable=False,
                  server_default="0"),
        sa.Column("matured_observations", sa.Integer(), nullable=False,
                  server_default="0"),
        sa.Column("events", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("excluded", sa.Integer(), nullable=False,
                  server_default="0"),

        sa.Column("score_direction", sa.String(length=32), nullable=False,
                  server_default=""),
        sa.Column("calculation_version", sa.String(length=24), nullable=False,
                  server_default=""),

        sa.Column("chart", postgresql.JSONB(), nullable=False,
                  server_default=EMPTY_OBJECT),
        sa.Column("result_table", postgresql.JSONB(), nullable=False,
                  server_default=EMPTY_ARRAY),
        sa.Column("lineage", postgresql.JSONB(), nullable=False,
                  server_default=EMPTY_OBJECT),

        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["run_id"], ["scv_runs.id"],
                                ondelete="CASCADE"),
        sa.UniqueConstraint("run_id", "test_id", "segment",
                            name="uq_scv_result_run_test_segment"),
    )
    op.create_index("ix_scv_results_test", "scv_results",
                    ["test_id", "state"])

    op.create_table(
        "scv_findings",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=False),

        sa.Column("finding_key", sa.String(length=96), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False,
                  server_default=""),
        sa.Column("severity", sa.String(length=24), nullable=False,
                  server_default=""),
        sa.Column("severity_rank", sa.Integer(), nullable=False,
                  server_default="0"),
        sa.Column("category", sa.String(length=48), nullable=False,
                  server_default=""),
        sa.Column("burning", sa.Boolean(), nullable=False,
                  server_default=sa.text("false")),
        sa.Column("pattern", sa.String(length=64), nullable=False,
                  server_default=""),

        sa.Column("what", sa.Text(), nullable=False, server_default=""),
        sa.Column("why_it_matters", sa.Text(), nullable=False,
                  server_default=""),
        sa.Column("remediation", sa.Text(), nullable=False, server_default=""),
        sa.Column("verify_by", sa.Text(), nullable=False, server_default=""),

        sa.Column("evidence", postgresql.JSONB(), nullable=False,
                  server_default=EMPTY_ARRAY),
        sa.Column("cbuae", postgresql.JSONB(), nullable=False,
                  server_default=EMPTY_ARRAY),
        sa.Column("values", postgresql.JSONB(), nullable=False,
                  server_default=EMPTY_OBJECT),
        sa.Column("confidence", sa.String(length=32), nullable=False,
                  server_default=""),
        sa.Column("period", sa.String(length=64), nullable=False,
                  server_default=""),
        sa.Column("segment", sa.String(length=128), nullable=False,
                  server_default=""),

        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["run_id"], ["scv_runs.id"],
                                ondelete="CASCADE"),
        sa.UniqueConstraint("run_id", "finding_key", "segment",
                            name="uq_scv_finding_run_key_segment"),
    )
    op.create_index("ix_scv_findings_severity",
                    "scv_findings", ["severity", "burning"])

    op.create_table(
        "scv_reports",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("report_key", sa.String(length=128), nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=False),
        sa.Column("source_run_keys", postgresql.JSONB(), nullable=False,
                  server_default=EMPTY_ARRAY),

        sa.Column("model_id", sa.String(length=64), nullable=False),
        sa.Column("model_version", sa.String(length=32), nullable=False,
                  server_default=""),
        sa.Column("title", sa.String(length=300), nullable=False,
                  server_default=""),
        sa.Column("opinion", sa.String(length=64), nullable=False,
                  server_default=""),
        sa.Column("status", sa.String(length=24), nullable=False,
                  server_default="DRAFT"),
        sa.Column("version", sa.Integer(), nullable=False, server_default="1"),

        sa.Column("structure_version", sa.String(length=24), nullable=False,
                  server_default=""),
        sa.Column("registry_version", sa.String(length=24), nullable=False,
                  server_default=""),
        sa.Column("calculation_version", sa.String(length=24), nullable=False,
                  server_default=""),
        sa.Column("dataset_as_of", sa.String(length=64), nullable=False,
                  server_default=""),
        sa.Column("content_hash", sa.String(length=64), nullable=False,
                  server_default=""),
        sa.Column("document", postgresql.JSONB(), nullable=False,
                  server_default=EMPTY_OBJECT),

        sa.Column("generated_by_id", sa.Integer(), nullable=True),
        sa.Column("generated_by_name", sa.String(length=160), nullable=False,
                  server_default=""),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        sa.Column("finalised_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finalised_by_id", sa.Integer(), nullable=True),
        sa.Column("finalised_by_name", sa.String(length=160), nullable=False,
                  server_default=""),
        sa.Column("supersedes_id", sa.BigInteger(), nullable=True),

        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("report_key"),
        # RESTRICT, not CASCADE. Deleting the run beneath a finalised report
        # would leave a document nobody can reproduce; the database refuses
        # rather than the service remembering to.
        sa.ForeignKeyConstraint(["run_id"], ["scv_runs.id"],
                                ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["generated_by_id"], ["users.id"],
                                ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["finalised_by_id"], ["users.id"],
                                ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["supersedes_id"],
                                ["scv_reports.id"],
                                ondelete="SET NULL"),
    )
    op.create_index("ix_scv_reports_run", "scv_reports",
                    ["run_id"])
    op.create_index("ix_scv_reports_model", "scv_reports",
                    ["model_id", "generated_at"])


def downgrade() -> None:
    # Reports first: their foreign key to runs is RESTRICT, so a run cannot be
    # dropped while a report points at it.
    op.drop_index("ix_scv_reports_model",
                  table_name="scv_reports")
    op.drop_index("ix_scv_reports_run",
                  table_name="scv_reports")
    op.drop_table("scv_reports")

    op.drop_index("ix_scv_findings_severity",
                  table_name="scv_findings")
    op.drop_table("scv_findings")

    op.drop_index("ix_scv_results_test",
                  table_name="scv_results")
    op.drop_table("scv_results")

    op.drop_index("ix_scv_runs_user", table_name="scv_runs")
    op.drop_index("ix_scv_runs_status", table_name="scv_runs")
    op.drop_index("ix_scv_runs_model", table_name="scv_runs")
    op.drop_table("scv_runs")
