"""
Cockpit Intelligence V2 — governed credit intelligence for the Cockpit only.

Everything in this package is inert unless `settings.cockpit_intelligence_v2`
is true. The switch is Cockpit-scoped by design (brief §1.3): Early Warning,
What-if, Scorecards, Planner, Lenses and Playbook must behave exactly as they
do on the base commit whether the switch is on or off, and the flag-off path
is tested rather than assumed.

What lives here
---------------
``policy``       versioned synthetic demonstration policies — rating scales,
                 rating-to-PD maps, SICR rules, recovery rules, macro
                 sensitivities, scenario weights, overlays. Every coefficient
                 is labelled a demonstration assumption. None of it is
                 calibrated, validated or regulatory.
``ecl``          the governed ECL calculator. Hazards, survival, marginal
                 default probabilities, EAD paths, discounting, per-scenario
                 measurement, scenario weighting and separately identified
                 overlays. Runs in the backend; a model never computes any of
                 it.
``attribution``  genuine factor attribution — exact Shapley allocation across
                 non-overlapping factor groups, evaluated through ``ecl``
                 itself — plus additive movement, ratio and history tools.
``generate``     the deterministic longitudinal generator behind the quarterly
                 demo datasets.
``schema``       the machine-readable data dictionary and semantic rules.
``catalogue``    registration of the quarterly packages into the governed
                 catalogue as a new ``Cockpit Demo`` domain.
``history``      the ``cockpit_credit_history`` interface over the quarters.
``scope``        the backend-enforced Cockpit read scope.
``validate``     dataset and calculator integrity gates.
``answer``       the deterministic Cockpit V2 answer composer.
``guard``        the seed/reset destination guard.

Nothing here describes a real borrower, a real bank's book or a real economy.
"""

from __future__ import annotations

#: Bumped whenever the generated data changes shape or content. Part of every
#: run key and every cache key, so a regenerated dataset can never be answered
#: from a cache built over the previous one.
DATA_VERSION = "2.0.0"

#: The ECL calculator's method version. Separate from DATA_VERSION because a
#: change here invalidates attributions computed under the old method even when
#: the data is untouched.
MODEL_VERSION = "1.0.0"

#: The demonstration policy set version — thresholds, maps, sensitivities.
POLICY_VERSION = "1.0.0"

#: The factor-attribution method version.
ATTRIBUTION_VERSION = "1.0.0"

#: The answer contract version.
ANSWER_VERSION = "1.0.0"

#: Stamped on every generated row and every catalogue entry.
ORIGIN = "SYNTHETIC_DEMO"
NOT_CLIENT_DATA = (
    "Synthetic demonstration data. Generated by CreditProbe for the Cockpit "
    "Intelligence V2 demonstration. It describes no real borrower, no real "
    "facility and no real bank's book, and no parameter in it is calibrated, "
    "validated or approved for any regulatory purpose."
)

#: The Data Builder domain the quarterly packages are published under.
DOMAIN = "Cockpit Demo"


def enabled() -> bool:
    """Whether Cockpit Intelligence V2 is switched on in this runtime."""
    from backend.config import settings

    return bool(settings.cockpit_intelligence_v2)


__all__ = ["ANSWER_VERSION", "ATTRIBUTION_VERSION", "DATA_VERSION", "DOMAIN",
           "MODEL_VERSION", "NOT_CLIENT_DATA", "ORIGIN", "POLICY_VERSION",
           "enabled"]
