"""
The product explaining itself, as answers rather than as data.

`knowledge.py` and `methodology.py` hold the facts. This module turns them into
the answer a credit officer reads — sections of prose and tables, composed
deterministically from the registries, with no model call anywhere in the path.

That last point is the design. A product explanation generated by a language
model is a product explanation nobody has reviewed, and it will differ every
time it is asked. These answers are assembled from reviewed narrative plus live
counts, so the same question returns the same answer, and changing what the
product says means changing a registry somebody owns.

Every answer is TEXT AND TABLES. None of them proposes a chart: a question
about what a module does has no quantitative shape, and a bar chart of feature
counts is decoration pretending to be analysis.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from backend.product import knowledge as pk
from backend.product import methodology as me

#: Every product answer declares this. §19: no quantitative chart by default
#: for product, methodology, feature, inventory or catalogue questions.
NO_CHART = {"kind": "none",
            "reason": "A product or methodology explanation has no "
                      "quantitative shape. This is text and tables."}

TABLE = "table"


@dataclass
class Section:
    """One heading and its body."""

    key: str
    title: str
    body: list[str] = field(default_factory=list)
    #: An optional table: {"columns": [...], "rows": [[...], ...]}.
    table: dict[str, Any] | None = None
    #: An optional ordered flow, rendered as steps rather than as a chart.
    flow: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        out: dict[str, Any] = {"key": self.key, "title": self.title,
                               "body": list(self.body)}
        if self.table:
            out["table"] = self.table
        if self.flow:
            out["flow"] = list(self.flow)
        return out


@dataclass
class Answer:
    """A composed product answer."""

    topic: str
    headline: str
    sections: list[Section] = field(default_factory=list)
    #: What the answer was built from, so a reader can check it.
    sources: list[str] = field(default_factory=list)
    follow_ups: list[str] = field(default_factory=list)

    def text(self) -> str:
        """The whole answer as plain prose, for a channel with no sections."""
        parts = [self.headline]
        for section in self.sections:
            parts.append("")
            parts.append(section.title.upper())
            parts.extend(section.body)
            if section.flow:
                parts.append("  " + "  ->  ".join(section.flow))
            if section.table:
                columns = section.table.get("columns") or []
                parts.append("  " + " | ".join(str(c) for c in columns))
                for row in (section.table.get("rows") or []):
                    parts.append("  " + " | ".join(str(c) for c in row))
        return "\n".join(parts)

    def to_dict(self) -> dict[str, Any]:
        return {"topic": self.topic, "headline": self.headline,
                "sections": [s.to_dict() for s in self.sections],
                "sources": list(self.sources),
                "follow_ups": list(self.follow_ups),
                "visualization": dict(NO_CHART),
                "answer": self.text()}


def _counts() -> dict[str, Any]:
    return pk.installation()


# ============================================================ the product itself


def get_creditprobe_overview() -> Answer:
    """"What is CreditProbe AI?" — the executive answer."""
    facts = _counts()
    capabilities = pk.capabilities()

    sections = [
        Section(key="purpose", title="What CreditProbe is",
                body=[pk.PURPOSE]),
        Section(key="problem", title="The problem it solves",
                body=[pk.PROBLEM]),
        Section(
            key="capabilities", title="Core capabilities",
            body=["Each of these is a governed part of the platform rather "
                  "than a view over the same table."],
            table={"columns": ["Capability", "What it is"],
                   "rows": [[c.name, c.summary] for c in capabilities]}),
        Section(
            key="different", title="Why it is different",
            body=[f"{title}. {detail}"
                  for title, detail in pk.DIFFERENTIATORS]),
        Section(
            key="flow", title="How the pieces fit together",
            body=["One continuum, rather than a set of tools that happen to "
                  "share a login:"],
            flow=list(pk.VALUE_FLOW)),
        Section(
            key="continuum", title="From the book to the action",
            body=["The same investigation moves down the whole chain without "
                  "changing tool or losing the population it settled:"],
            flow=list(pk.CONTINUUM)),
        Section(
            key="installation", title="This installation",
            body=["The figures below are read from this installation now, "
                  "not quoted from a brochure."],
            table={"columns": ["Measure", "Value"], "rows": [
                ["Governed data domains", facts.get("domains", "-")],
                ["Published datasets", facts.get("datasets", "-")],
                ["Declared dataset relationships",
                 facts.get("governed_relationships", "-")],
                ["Certified analytical methods",
                 facts.get("certified_methods", "-")],
                ["Early Warning signals", facts.get("signals", "-")],
                ["Early Warning signal families", facts.get("families", "-")],
            ]}),
    ]
    return Answer(
        topic="overview",
        headline=(f"{pk.PRODUCT_NAME} is an AI-enabled credit-risk "
                  "intelligence platform for corporate portfolios: one "
                  "governed environment in which a credit officer can "
                  "investigate the book conversationally, and every figure "
                  "behind the answer stays computed, permissioned and "
                  "traceable."),
        sections=sections,
        sources=["product capability registry", "governed data catalogue",
                 "Early Warning taxonomy", "relationship graph",
                 "method registry"],
        follow_ups=["Explain every major CreditProbe capability and why it "
                    "matters to a corporate credit risk team.",
                    "How does CreditProbe use AI?",
                    "What is the CreditProbe Early Warning methodology?"])


def list_creditprobe_capabilities() -> Answer:
    """"What can CreditProbe do?" — the capability list."""
    capabilities = pk.capabilities()
    return Answer(
        topic="capabilities",
        headline=(f"CreditProbe delivers {len(capabilities)} governed "
                  "capabilities across the credit-risk lifecycle, from the "
                  "portfolio view down to the evidence behind a single "
                  "facility and the workflow that acts on it."),
        sections=[
            Section(key="list", title="Capabilities",
                    body=[],
                    table={"columns": ["Capability", "What it does",
                                       "Why it matters"],
                           "rows": [[c.name, c.does, c.matters]
                                    for c in capabilities]}),
            Section(key="ask", title="How you reach them",
                    body=["Every capability is reachable from its own screen "
                          "and from Ask CreditProbe. A question does not need "
                          "to name the module it will use — the investigation "
                          "resolves which governed data answers it."]),
        ],
        sources=["product capability registry"],
        follow_ups=[f"Why is {capabilities[1].name} useful?",
                    "What makes CreditProbe different from a normal "
                    "dashboard?"])


def describe_creditprobe_capability(key: str = "") -> Answer | None:
    """One capability, in depth.

    `key` is optional so the tool is callable by name with no arguments, which
    is how a dispatcher that knows only the tool's name reaches it. Without a
    key it answers with the capability list, because "tell me about a
    capability" with none named is a request for the list.
    """
    if not str(key or "").strip():
        return list_creditprobe_capabilities()
    found = pk.capability(key)
    if found is None:
        return None
    facts = found.facts()
    sections = [
        Section(key="does", title="What it does", body=[found.does]),
        Section(key="matters", title="Why it matters to credit risk",
                body=[found.matters]),
        Section(key="used", title="How a risk team uses it",
                body=[found.used_by]),
    ]
    if found.domains:
        sections.append(Section(
            key="data", title="Governed data it reads",
            body=["It reads only from published domains, so what it can "
                  "answer is exactly what a steward has made available."],
            table={"columns": ["Domain"], "rows": [[d] for d in found.domains]}))
    if facts:
        sections.append(Section(
            key="installation", title="In this installation",
            body=[],
            table={"columns": ["Measure", "Value"],
                   "rows": [[str(k).replace("_", " ").capitalize(), v]
                            for k, v in facts.items()
                            if not isinstance(v, list)]}))
    return Answer(
        topic=f"capability:{found.key}",
        headline=f"{found.name} — {found.summary}",
        sections=sections,
        sources=["product capability registry", "governed data catalogue"],
        follow_ups=["What can CreditProbe do?",
                    "How does CreditProbe use AI?"])


def describe_creditprobe_architecture() -> Answer:
    """How the product is put together, without engineering jargon."""
    return Answer(
        topic="architecture",
        headline=("CreditProbe separates three responsibilities that most "
                  "AI analytics tools combine: understanding the question, "
                  "running the investigation, and owning the truth."),
        sections=[
            Section(key=entry.key, title=entry.name,
                    body=[f"Owns {entry.owns}.", *entry.does, *entry.does_not])
            for entry in pk.LAYERS
        ] + [
            Section(key="why", title="Why the separation matters",
                    body=[pk.WHY_THE_SPLIT]),
            Section(key="flow", title="The path an answer takes",
                    body=[], flow=list(pk.VALUE_FLOW)),
        ],
        sources=["product architecture registry"],
        follow_ups=["What does Agentic AI do?",
                    "What does the governed CreditProbe engine do?"])


def _layer_answer(key: str, topic: str, headline: str) -> Answer:
    entry = pk.layer(key)
    assert entry is not None  # the three layers are a closed set
    return Answer(
        topic=topic, headline=headline,
        sections=[
            Section(key="owns", title="What it owns", body=[f"It owns {entry.owns}."]),
            Section(key="does", title="What it does", body=list(entry.does)),
            Section(key="does_not", title="What it does not do",
                    body=list(entry.does_not)),
            Section(key="why", title="Why the boundary matters",
                    body=[pk.WHY_THE_SPLIT]),
        ],
        sources=["product architecture registry"],
        follow_ups=["Explain the CreditProbe architecture.",
                    "What is the CreditProbe Early Warning methodology?"])


def describe_ai_role() -> Answer:
    """"What is the role of AI in CreditProbe?" — all three layers."""
    return Answer(
        topic="ai_role",
        headline=("AI in CreditProbe does the reading and the reasoning; it "
                  "does not do the arithmetic. Understanding the question, "
                  "planning the investigation and owning the figures are "
                  "three separate responsibilities, and keeping them separate "
                  "is what makes the answers both conversational and "
                  "reproducible."),
        sections=[
            Section(key=entry.key, title=entry.name,
                    body=[f"Owns {entry.owns}.", *entry.does, *entry.does_not])
            for entry in pk.LAYERS
        ] + [
            Section(key="why", title="Why this architecture",
                    body=[pk.WHY_THE_SPLIT]),
        ],
        sources=["product architecture registry"],
        follow_ups=["What does Agentic AI do?",
                    "What does the governed CreditProbe engine do?"])


def describe_agentic_ai() -> Answer:
    return _layer_answer(
        pk.AGENTIC_LAYER, "agentic_ai",
        "The agentic layer turns a question into an investigation: a bounded "
        "sequence of governed tool calls that gathers evidence across domains "
        "and stops when it has enough, or when its budget says so.")


def describe_governed_engine() -> Answer:
    return _layer_answer(
        pk.ENGINE_LAYER, "governed_engine",
        "The governed engine owns factual truth. Every figure in every answer "
        "is computed here from published data, under declared definitions and "
        "enforced permissions, and recorded on the Trace.")


def why_creditprobe() -> Answer:
    """The business narrative, kept grounded."""
    return Answer(
        topic="value",
        headline=("CreditProbe's value is continuity: one investigation that "
                  "runs from the portfolio down to the evidence and out into "
                  "an action somebody owns, without the analyst rebuilding "
                  "the context at every step."),
        sections=[
            Section(key="flow", title="The continuum", body=[],
                    flow=list(pk.VALUE_FLOW)),
            Section(key="scope", title="From portfolio to action", body=[],
                    flow=list(pk.CONTINUUM)),
            Section(key="different",
                    title="What a reporting tool structurally cannot do",
                    body=[f"{title}. {detail}"
                          for title, detail in pk.DIFFERENTIATORS]),
        ],
        sources=["product capability registry"],
        follow_ups=["What is CreditProbe AI?",
                    "Why is Early Warning valuable to a credit risk "
                    "officer?"])


# ========================================================= the Early Warning side


def describe_early_warning_methodology() -> Answer:
    """The full methodology, in the order §16 asks for it."""
    described = me.describe()
    layers = me.layers()

    sections = [
        Section(key="purpose", title="Purpose", body=[described["purpose"]]),
        Section(
            key="layers", title="The four layers",
            body=["Signals are organised across four credit-risk "
                  "perspectives. Underneath, the engine groups them into "
                  f"{len(described['families'])} governed signal families; "
                  "the layers are how those families read to a credit "
                  "officer."],
            table={"columns": ["Layer", "What it watches", "Signal families"],
                   "rows": [[f"{layer.number}. {layer.name}", layer.watches,
                             ", ".join(described["families"].get(f, f)
                                       for f in layer.families) or "none "
                             "configured"]
                            for layer in layers]}),
    ]
    for layer in layers:
        entries = me.catalogue(layer_key=layer.key)
        body = [layer.matters]
        if layer.gap:
            body.append(layer.gap)
        table = None
        if entries:
            table = {"columns": ["Signal", "What it means", "Source",
                                 "Frequency", "Severity"],
                     "rows": [[e.label, e.means, e.dataset, e.frequency,
                               e.severity] for e in entries]}
        sections.append(Section(
            key=f"layer_{layer.number}",
            title=f"Layer {layer.number} — {layer.name}",
            body=body, table=table))

    sections.extend([
        Section(
            key="aggregation", title="Signal aggregation",
            body=["Signals are assessed together rather than one at a time. "
                  "A borrower showing one CONCERN in one family is a "
                  "different proposition from one showing three across "
                  "fundamentals, behaviour and credit quality at once, and "
                  "the aggregation is what tells them apart.",
                  described["tac"]["statement"], described["tac"]["nearest"]]),
        Section(
            key="severity", title="Severity",
            body=["Severity is a property of the signal's configuration, set "
                  "by the threshold owner, not a judgement made per borrower "
                  "by a model."],
            table={"columns": ["Severity", "What it means"],
                   "rows": [[k, v] for k, v in described["severities"].items()]}),
        Section(
            key="persistence", title="Persistence and trend",
            body=[described["persistence"]],
            table={"columns": ["State", "What it means"],
                   "rows": [[s["state"], s["means"]]
                            for s in described["warning_states"]]}),
        Section(key="cases", title="How a signal becomes a Risk Case",
                body=[described["case_promotion"]]),
        Section(
            key="investigation", title="AI investigation",
            body=["A case can be handed to the agentic layer, which gathers "
                  "the borrower's evidence across domains, reads the group "
                  "position, and proposes a next action. The proposal is a "
                  "recommendation for a person to approve; the autonomy level "
                  "configured for the agent decides whether it may do more."]),
        Section(
            key="trace", title="Trace and governance",
            body=[f"Every threshold is owned by {described['owner']} and "
                  f"versioned (taxonomy {described['taxonomy_version']}). "
                  "Every evaluation records the dataset, field, threshold and "
                  "periods behind it, so a warning can be defended or "
                  "disputed specifically.",
                  "Signals are evaluated at the grain of "
                  f"{described['grain'].lower()}."]),
        Section(key="flow", title="From signal to action", body=[],
                flow=list(described["flow"])),
    ])

    return Answer(
        topic="early_warning_methodology",
        headline=(f"CreditProbe evaluates {described['signal_count']} governed "
                  f"Early Warning signals across four credit-risk layers and "
                  f"{len(described['families'])} signal families, grades each "
                  "by severity, tracks whether it is new, persistent, "
                  "worsening or resolved, and promotes what matters into a "
                  "Risk Case with an owner."),
        sections=sections,
        sources=["Early Warning taxonomy", "governed data catalogue"],
        follow_ups=["Would you like the current Early Warning signal "
                    "catalogue?",
                    "How does an Early Warning signal become a Risk Case?",
                    "What signals are used for liquidity risk?"])


def describe_tac_methodology() -> Answer:
    """What is TAC? — it is not defined here, and this says so."""
    found = me.tac()
    return Answer(
        topic="tac",
        headline=("CreditProbe has no definition of TAC. The term does not "
                  "appear anywhere in this system, so rather than guess what "
                  "it stands for, here is what was searched and what "
                  "CreditProbe does implement."),
        sections=[
            Section(key="status", title="What was searched",
                    body=[found.statement],
                    table={"columns": ["Searched"],
                           "rows": [[s] for s in found.searched]}),
            Section(key="nearest", title="What CreditProbe does implement",
                    body=[found.nearest]),
            Section(key="next", title="To publish it",
                    body=["Supply the methodology paper, policy document or "
                          "specification that defines TAC and it can be "
                          "published as a versioned methodology alongside the "
                          "four-layer framework, with the same reconciliation "
                          "tests that keep the framework honest."]),
        ],
        sources=["repository search", "Early Warning taxonomy"],
        follow_ups=["What is the CreditProbe Early Warning methodology?",
                    "Explain the four layers of Early Warning."])


def list_early_warning_signals(family: str = "", layer_key: str = "") -> Answer:
    """The governed signal catalogue, whole or narrowed."""
    entries = me.catalogue(family=family, layer_key=layer_key)
    described = me.describe()
    scope = ""
    if family:
        scope = f" in the {described['families'].get(family, family)} family"
    elif layer_key:
        named = next((entry.name for entry in me.layers()
                      if entry.key == layer_key), layer_key)
        scope = f" in {named}"

    if not entries:
        return Answer(
            topic="signals",
            headline=f"No Early Warning signal is configured{scope}.",
            sections=[Section(
                key="gap", title="Why",
                body=[next((entry.gap for entry in me.layers()
                            if entry.key == layer_key and entry.gap),
                           "The catalogue holds no signal matching that "
                           "request.")])],
            sources=["Early Warning taxonomy"])

    return Answer(
        topic="signals",
        headline=(f"{len(entries)} governed Early Warning signal"
                  f"{'s' if len(entries) != 1 else ''}{scope}, each with a "
                  "declared source, threshold, direction of deterioration and "
                  "severity."),
        sections=[
            Section(
                key="catalogue", title="Signal catalogue",
                body=[f"Thresholds are owned by {described['owner']} and "
                      f"versioned at {described['taxonomy_version']}."],
                table={"columns": ["Signal", "Family", "Layer", "Means",
                                   "Source", "Field", "Frequency", "Test",
                                   "Threshold", "Direction", "Severity"],
                       "rows": [[e.label, e.family_label, e.layer_name,
                                 e.means, e.dataset, ", ".join(e.fields),
                                 e.frequency, e.test,
                                 "-" if e.threshold is None else e.threshold,
                                 e.direction, e.severity]
                                for e in entries]}),
            Section(
                key="frequency", title="How often they are collected",
                body=["Frequency is read from the periods each source dataset "
                      "actually publishes, not asserted. A signal is assessed "
                      "when its source publishes a new period."],
                table={"columns": ["Source dataset", "Frequency"],
                       "rows": [[k, v]
                                for k, v in described["frequencies"].items()]}),
            Section(key="grain", title="Grain",
                    body=[described["grain"] + "."]),
        ],
        sources=["Early Warning taxonomy", "governed data catalogue"],
        follow_ups=["What is the CreditProbe Early Warning methodology?",
                    "How does an Early Warning signal become a Risk Case?"])


def describe_case_promotion() -> Answer:
    described = me.describe()
    return Answer(
        topic="case_promotion",
        headline="How a signal becomes a Risk Case.",
        sections=[
            Section(key="rule", title="Promotion",
                    body=[described["case_promotion"]]),
            Section(key="severity", title="Severity", body=[],
                    table={"columns": ["Severity", "What it means"],
                           "rows": [[k, v] for k, v in
                                    described["severities"].items()]}),
            Section(key="persistence", title="Persistence",
                    body=[described["persistence"]]),
            Section(key="flow", title="The path", body=[],
                    flow=list(described["flow"])),
        ],
        sources=["Early Warning taxonomy", "Risk Case lifecycle"],
        follow_ups=["What does a persistent warning mean?"])


def describe_warning_states() -> Answer:
    described = me.describe()
    return Answer(
        topic="warning_states",
        headline=("A warning is described by what the borrower is doing, not "
                  "by what the rule did. Every state is defined against the "
                  "current and previous observation periods."),
        sections=[Section(
            key="states", title="Warning states", body=[],
            table={"columns": ["State", "What it means"],
                   "rows": [[s["state"], s["means"]]
                            for s in described["warning_states"]]})],
        sources=["Early Warning taxonomy"],
        follow_ups=["What is the CreditProbe Early Warning methodology?"])


# ------------------------------------------------------------------ the tools
#
# The names the remediation asks for, as a dispatch table. Each is a plain
# function returning a composed Answer; nothing here calls a model.

TOOLS: dict[str, Any] = {
    "get_creditprobe_overview": get_creditprobe_overview,
    "list_creditprobe_capabilities": list_creditprobe_capabilities,
    "describe_creditprobe_capability": describe_creditprobe_capability,
    "describe_creditprobe_architecture": describe_creditprobe_architecture,
    "describe_ai_role": describe_ai_role,
    "describe_agentic_ai": describe_agentic_ai,
    "describe_governed_engine": describe_governed_engine,
    "describe_early_warning_methodology": describe_early_warning_methodology,
    "describe_tac_methodology": describe_tac_methodology,
    "list_early_warning_signals": list_early_warning_signals,
    "describe_case_promotion": describe_case_promotion,
    "describe_warning_states": describe_warning_states,
    "why_creditprobe": why_creditprobe,
}

#: The per-capability tools the remediation names, each resolving to the same
#: capability describer. Declared explicitly so a missing capability is a
#: KeyError at import rather than an empty answer at runtime.
_CAPABILITY_TOOLS: dict[str, str] = {
    "describe_ifrs9_intelligence": "ifrs9",
    "describe_rating_intelligence": "ratings",
    "describe_borrower360": "borrower360",
    "describe_data_builder": "data_builder",
    "describe_analysis_studio": "analysis_studio",
    "describe_stress_testing": "stress_testing",
    "describe_scorecard_validation": "scorecard_validation",
    "describe_trace_lineage": "trace",
    "describe_external_intelligence": "external_intelligence",
    "describe_workflow": "workflow",
    "describe_governance_controls": "ai_governance",
    "describe_early_warning": "early_warning",
    "describe_portfolio_intelligence": "portfolio_intelligence",
    "describe_covenants": "covenants",
    "describe_collateral": "collateral",
    "describe_liquidity": "liquidity",
    "describe_group_risk": "group_risk",
    "describe_ask": "ask",
}

for _name, _key in _CAPABILITY_TOOLS.items():
    if pk.capability(_key) is None:  # pragma: no cover - a registry error
        raise RuntimeError(
            f"{_name} names the capability {_key!r}, which the product "
            "knowledge registry does not have.")
    TOOLS[_name] = (lambda key: lambda: describe_creditprobe_capability(key))(_key)


def call(tool: str, **arguments: Any) -> Answer | None:
    """Run one product-knowledge tool by name."""
    handler = TOOLS.get(str(tool or ""))
    if handler is None:
        return None
    return handler(**arguments)


def tool_names() -> tuple[str, ...]:
    return tuple(sorted(TOOLS))


__all__ = [
    "Answer",
    "NO_CHART",
    "Section",
    "TOOLS",
    "call",
    "describe_agentic_ai",
    "describe_ai_role",
    "describe_case_promotion",
    "describe_creditprobe_architecture",
    "describe_creditprobe_capability",
    "describe_early_warning_methodology",
    "describe_governed_engine",
    "describe_tac_methodology",
    "describe_warning_states",
    "get_creditprobe_overview",
    "list_creditprobe_capabilities",
    "list_early_warning_signals",
    "tool_names",
    "why_creditprobe",
]
