"""
The product explaining itself, as answers rather than as documentation.

`knowledge.py` and `methodology.py` hold the facts. `compose.py` holds the
rules about shape and size. This module decides, question by question, WHICH
facts a reader needs and how they should read - and it composes them
deterministically, with no model call anywhere in the path.

That last point is the design. A product explanation generated by a language
model is a product explanation nobody has reviewed, and it will differ every
time it is asked. These answers are assembled from reviewed narrative plus live
counts, so the same question returns the same answer, and changing what the
product says means changing a registry somebody owns.

What changed, and why
---------------------
The first version returned everything the registries held, every time, as one
run of prose. "What is CreditProbe AI?" came back as five thousand characters
of accurate, unreadable product documentation. Three rules now govern instead:

*   **Answer the question that was asked.** An overview is an introduction, not
    a manual. A capability question is about that capability. What is held back
    is offered in the follow-ups rather than dropped.
*   **Fit the question's band.** Every answer declares SHORT, MEDIUM or
    DETAILED, and the composer checks it.
*   **Speak like a senior credit professional.** Headings, bold, bullets, short
    paragraphs and whitespace; first person where the reader is addressing
    CreditProbe itself; no marketing language and no implementation vocabulary.

Every answer is TEXT AND STRUCTURE. None of them proposes a chart: a question
about what a module does has no quantitative shape, and a bar chart of feature
counts is decoration pretending to be analysis. Process flows are drawn as
text.
"""

from __future__ import annotations

import re
from typing import Any

from backend.product import knowledge as pk
from backend.product import methodology as me
from backend.product.compose import (
    DETAILED,
    MEDIUM,
    NO_CHART,
    SHORT,
    Answer,
    Section,
    compose,
)

TABLE = "table"

#: Prose in the registries was written as whole thoughts, some of them long.
#: A paragraph over this many words reads as a wall on a laptop, so long prose
#: is split at sentence boundaries on the way out. Splitting here rather than
#: rewriting eighteen registry entries keeps the fix at the mechanism.
_PARAGRAPH_WORDS = 55

_SENTENCE = re.compile(r"(?<=[.!?])\s+(?=[A-Z“\"(])")


def _paragraphs(text: str, limit: int = _PARAGRAPH_WORDS) -> list[str]:
    """One piece of registry prose as one or more short paragraphs."""
    said = str(text or "").strip()
    if not said:
        return []
    if len(said.split()) <= limit:
        return [said]
    out: list[str] = []
    current: list[str] = []
    for sentence in _SENTENCE.split(said):
        sentence = sentence.strip()
        if current and len((" ".join(current) + " " + sentence).split()) > limit:
            out.append(" ".join(current))
            current = []
        current.append(sentence)
    if current:
        out.append(" ".join(current))
    return out or [said]


def _lead(title: str, detail: str) -> str:
    """A bullet that leads with its point in bold, then earns it."""
    return f"**{title}.** {detail}"


def _counts() -> dict[str, Any]:
    return pk.installation()


# ============================================================ the product itself


def get_creditprobe_overview() -> Answer:
    """"What is CreditProbe AI?" - the executive introduction.

    An introduction, deliberately: the reader asked what this is, not for the
    manual. Modules, methodologies, domains, controls and the signal catalogue
    are all reachable from here and none of them is here.
    """
    picture = ", ".join(pk.connected_picture()[:-1]) \
        + f" and {pk.connected_picture()[-1]}"

    return compose(Answer(
        topic="overview",
        band=MEDIUM,
        headline=pk.IDENTITY,
        sections=[
            Section(
                key="mission", title="",
                body=[f"My job is simple: **{pk.MISSION}**",
                      "Instead of waiting for reports, committee packs and "
                      "three teams to tell you what changed, ask me:"],
                bullets=[f"**{q}**" for q in pk.ASK_EXAMPLES]),
            Section(
                key="reach", title="",
                body=[f"I read the risk picture across {picture} — as one "
                      "book rather than as eleven systems."]),
            Section(
                key="outcomes",
                title="What that means day to day",
                body=[],
                bullets=[_lead(title, detail)
                         for title, detail in pk.OUTCOMES]),
            Section(
                key="grounding", title="Where the numbers come from",
                body=[pk.GROUNDING, pk.POSITIONING]),
            Section(key="arc", title="", body=[], flow=list(pk.ARC)),
            Section(
                key="shift", title="",
                body=[f"So the conversation moves from *“{pk.SHIFT_FROM}”* "
                      f"to *“{pk.SHIFT_TO}”*"]),
        ],
        sources=["product capability registry", "governed data catalogue"],
        follow_ups=["What is the role of AI in CreditProbe?",
                    "What is the Early Warning methodology?",
                    "How can CreditProbe help a corporate credit risk team?"]))


def list_creditprobe_capabilities() -> Answer:
    """"What can CreditProbe do?" / "What features does it have?"

    Section 7: a glance, with a heading per capability and one line each. Not
    an exhaustive explanation of any of them - that is what the capability
    questions are for.
    """
    entries = pk.capabilities()
    sections: list[Section] = [
        Section(key="glance", title="CreditProbe at a glance", depth=2,
                body=["Each of these is a governed part of the platform "
                      "rather than another view over the same table."])]
    sections += [
        Section(key=f"cap_{c.key}", title=c.name, depth=3, body=[c.summary])
        for c in entries]
    sections.append(Section(
        key="closing", title="How you reach them",
        body=["Every one of these has its own screen, and every one of them "
              "is reachable by asking. A question does not need to name the "
              "module that will answer it.",
              "Ask about any of them by name and I will go into depth on that "
              "one rather than on all of them."]))

    return compose(Answer(
        topic="capabilities",
        band=MEDIUM,
        headline=(f"Here's how I help a credit-risk team — "
                  f"{len(entries)} governed capabilities spanning the "
                  "portfolio view, the borrower behind it and the action "
                  "that follows."),
        sections=sections,
        sources=["product capability registry"],
        follow_ups=["What is Borrower 360?",
                    "Why should a credit risk officer use CreditProbe?",
                    "What is the Early Warning methodology?"]))


def describe_creditprobe_capability(key: str = "") -> Answer | None:
    """One capability, on its own.

    `key` is optional so the tool is callable by name with no arguments, which
    is how a dispatcher that knows only the tool's name reaches it. Without a
    key it answers with the capability list, because "tell me about a
    capability" with none named is a request for the list.
    """
    if not str(key or "").strip():
        return list_creditprobe_capabilities()
    found = pk.capability(key)
    if found is None:
        return None

    sections = [
        Section(key="does", title="What it does", body=_paragraphs(found.does)),
        Section(key="matters", title="Why it matters",
                body=_paragraphs(found.matters)),
        Section(key="used", title="How a risk team uses it",
                body=_paragraphs(found.used_by)),
    ]
    if found.domains:
        sections.append(Section(
            key="data", title="What it reads", optional=True,
            body=["It reads only from published governed data, so what it can "
                  "answer is exactly what a steward has made available: "
                  + ", ".join(found.domains) + "."]))
    facts = found.facts()
    plain = {k: v for k, v in facts.items() if not isinstance(v, list)}
    if plain:
        sections.append(Section(
            key="installation", title="In this installation", detail=True,
            body=[], bullets=[f"**{str(k).replace('_', ' ').capitalize()}:** {v}"
                              for k, v in plain.items()]))

    # The nudges are questions the reader can actually ask next, and every one
    # of them has to route back to a product answer - a suggestion the product
    # cannot answer is worse than no suggestion at all.
    nearby = {"borrower360": "What is the Early Warning methodology?",
              "early_warning": "How does an Early Warning signal become a "
                               "Risk Case?",
              "trace": "What is the role of AI in CreditProbe?",
              "ifrs9": "What is Borrower 360?"}
    return compose(Answer(
        topic=f"capability:{found.key}",
        band=SHORT,
        deep=False,
        headline=f"**{found.name}.** {found.summary}",
        sections=sections,
        sources=["product capability registry", "governed data catalogue"],
        follow_ups=[nearby.get(found.key,
                               "What is the Early Warning methodology?"),
                    "What can CreditProbe do?"]))


def _layer_bullets(entry: pk.Layer) -> list[str]:
    """What a layer does, and where it stops.

    The boundary belongs with the job rather than in a footnote. "It does not
    compute figures" is the single most important sentence in an answer about
    what the AI does, and a reader who stops after the first section still
    needs to have read it.
    """
    return [*entry.does, *(f"*{line}*" for line in entry.does_not)]


def describe_creditprobe_architecture() -> Answer:
    """How the product is put together, without engineering vocabulary."""
    answer = describe_ai_role()
    answer.topic = "architecture"
    answer.headline = ("CreditProbe keeps three jobs apart that most AI "
                       "analytics tools run together: understanding the "
                       "question, running the investigation, and owning the "
                       "figures.")
    return answer


def describe_ai_role() -> Answer:
    """"What is the role of AI in CreditProbe?" - section 9's structure."""
    ai = pk.layer(pk.AI_LAYER)
    agentic = pk.layer(pk.AGENTIC_LAYER)
    engine = pk.layer(pk.ENGINE_LAYER)
    assert ai and agentic and engine  # the three layers are a closed set

    return compose(Answer(
        topic="ai_role",
        band=MEDIUM,
        headline=("AI in CreditProbe does the reading and the reasoning. It "
                  "does not do the arithmetic. Three jobs, kept apart on "
                  "purpose."),
        sections=[
            Section(key="thinking", title="AI does the thinking",
                    body=[], bullets=_layer_bullets(ai)),
            Section(key="investigating",
                    title="Agentic AI does the investigating",
                    body=[], bullets=_layer_bullets(agentic)),
            Section(key="truth",
                    title="The CreditProbe engine protects the truth",
                    body=[], bullets=_layer_bullets(engine)),
            Section(key="why", title="Why the line is drawn there",
                    body=_paragraphs(pk.WHY_THE_SPLIT)),
            Section(key="control", title="",
                    body=[f"**{pk.CONTROL_LINE}**"]),
        ],
        sources=["product architecture registry"],
        follow_ups=["What is Agentic AI doing inside CreditProbe?",
                    "What is Trace and why does it matter?",
                    "Why is CreditProbe different from a normal BI dashboard?"]))


def _layer_answer(key: str, topic: str, headline: str,
                  follow_ups: list[str]) -> Answer:
    entry = pk.layer(key)
    assert entry is not None  # the three layers are a closed set
    return compose(Answer(
        topic=topic, band=SHORT, headline=headline,
        sections=[
            Section(key="does", title="What it does", body=[],
                    bullets=list(entry.does)),
            Section(key="does_not", title="Where it stops", body=[],
                    bullets=list(entry.does_not)),
            Section(key="control", title="",
                    body=[f"**{pk.CONTROL_LINE}**"]),
        ],
        sources=["product architecture registry"],
        follow_ups=follow_ups))


def describe_agentic_ai() -> Answer:
    return _layer_answer(
        pk.AGENTIC_LAYER, "agentic_ai",
        "Agentic AI is what turns a question into an investigation: a bounded "
        "sequence of governed steps that gathers evidence across domains and "
        "stops when it has enough, or when its budget says so.",
        ["What is the role of AI in CreditProbe?",
         "What is Trace and why does it matter?"])


def describe_governed_engine() -> Answer:
    return _layer_answer(
        pk.ENGINE_LAYER, "governed_engine",
        "The engine owns factual truth. Every figure in every answer is "
        "computed here from published data, under declared definitions and "
        "enforced permissions, and recorded on the Trace.",
        ["What is the role of AI in CreditProbe?",
         "What is Trace and why does it matter?"])


def why_creditprobe() -> Answer:
    """"Why should a credit risk officer use CreditProbe?" - outcomes."""
    return compose(Answer(
        topic="value",
        band=MEDIUM,
        headline=("Because the job is to see deterioration early enough to do "
                  "something about it — and most of the work of getting there "
                  "is assembling evidence that already exists."),
        sections=[
            Section(key="outcomes", title="What you get",
                    body=[], bullets=[_lead(t, d) for t, d in pk.OUTCOMES]),
            Section(
                key="continuity", title="Why it holds together",
                body=["The value is continuity. One investigation runs from "
                      "the book down to the evidence and out into an action "
                      "somebody owns, without rebuilding the context at every "
                      "step."],
                flow=list(pk.CONTINUUM)),
            Section(key="grounding", title="", body=[pk.GROUNDING]),
        ],
        sources=["product capability registry"],
        follow_ups=["How can CreditProbe help a corporate credit risk team?",
                    "Why is CreditProbe different from a normal BI dashboard?",
                    "What is the Early Warning methodology?"]))


def how_creditprobe_helps_a_team() -> Answer:
    """"How can CreditProbe help a corporate credit risk team?" - the week."""
    return compose(Answer(
        topic="team_workflow",
        band=MEDIUM,
        headline=("Practically: it shortens the distance between noticing "
                  "something and being able to defend a view on it. Here's "
                  "how that runs through a credit team's week."),
        sections=[
            Section(key="workflow", title="A working week",
                    body=[], bullets=[_lead(t, d)
                                      for t, d in pk.TEAM_WORKFLOW]),
            Section(key="flow", title="Where a question can take you",
                    body=[], flow=list(pk.INVESTIGATION_FLOW)),
            Section(
                key="closing", title="",
                body=["Nothing in that sequence needs a new extract, a new "
                      "spreadsheet or a request to another team — which is "
                      "usually where the days go."]),
        ],
        sources=["product capability registry"],
        follow_ups=["What is the Early Warning methodology?",
                    "What is Borrower 360?",
                    "Why is CreditProbe different from a normal BI dashboard?"]))


def creditprobe_versus_a_dashboard() -> Answer:
    """"Why is CreditProbe different from a normal BI dashboard?"."""
    return compose(Answer(
        topic="versus_dashboard",
        band=MEDIUM,
        headline=("A dashboard reports. CreditProbe investigates — and then "
                  "shows you exactly how it got there."),
        sections=[
            Section(key="contrast", title="Four differences that matter",
                    body=[], bullets=[_lead(t, d)
                                      for t, d in pk.DASHBOARD_CONTRAST]),
            Section(key="flow", title="What happens when you ask",
                    body=[], flow=list(pk.ANSWER_FLOW)),
            Section(
                key="closing", title="",
                body=["A prepared view can only answer the question somebody "
                      "anticipated. The questions that matter in credit are "
                      "usually the ones nobody anticipated.", pk.GROUNDING]),
        ],
        sources=["product capability registry"],
        follow_ups=["What is Trace and why does it matter?",
                    "What is the role of AI in CreditProbe?",
                    "Why should a credit risk officer use CreditProbe?"]))


def explain_creditprobe_end_to_end() -> Answer:
    """"Explain CreditProbe end to end." - the long form, and only here."""
    facts = _counts()
    entries = pk.capabilities()

    sections: list[Section] = [
        Section(key="problem", title="The problem",
                body=_paragraphs(pk.PROBLEM)),
        Section(key="purpose", title="What CreditProbe is",
                body=_paragraphs(pk.PURPOSE)),
        Section(key="glance", title="What it covers",
                body=[], bullets=[f"**{c.name}.** {c.summary}"
                                  for c in entries]),
        Section(key="architecture", title="How an answer is produced",
                body=["Three responsibilities, kept apart: the AI reads the "
                      "question, the agentic layer runs the investigation, "
                      "and the engine owns every figure."],
                flow=list(pk.ANSWER_FLOW)),
        Section(key="split", title="Why that split matters",
                body=_paragraphs(pk.WHY_THE_SPLIT)),
        Section(key="continuum", title="From the book to the action",
                body=["The same thread moves down the whole chain without "
                      "changing tool or losing the population it settled."],
                flow=list(pk.CONTINUUM)),
        Section(key="different", title="What a reporting tool cannot do",
                body=[], bullets=[_lead(t, d)
                                  for t, d in pk.DASHBOARD_CONTRAST]),
        Section(
            key="installation", title="This installation",
            body=["Read from this installation now, rather than quoted from "
                  "a brochure."],
            bullets=[f"**{label}:** {facts.get(field, '-')}" for label, field in
                     (("Governed data domains", "domains"),
                      ("Published datasets", "datasets"),
                      ("Declared dataset relationships",
                       "governed_relationships"),
                      ("Certified analytical methods", "certified_methods"),
                      ("Early Warning signals", "signals"),
                      ("Early Warning signal families", "families"))]),
        Section(key="control", title="", body=[f"**{pk.CONTROL_LINE}**"]),
    ]

    return compose(Answer(
        topic="end_to_end",
        band=DETAILED,
        headline=(f"{pk.IDENTITY} Here is the whole picture — the problem, "
                  "what I cover, how an answer is produced, and what this "
                  "installation actually holds."),
        sections=sections,
        sources=["product capability registry", "governed data catalogue",
                 "Early Warning taxonomy", "relationship graph",
                 "method registry"],
        follow_ups=["What is the Early Warning methodology?",
                    "What is the role of AI in CreditProbe?",
                    "What is Trace and why does it matter?"]))


# ========================================================= the Early Warning side


def describe_early_warning_methodology(detail: bool = False) -> Answer:
    """The methodology.

    Section 10: purpose, the four layers, and how a signal becomes a case -
    then an OFFER to expand the catalogue. The per-layer signal listings are
    marked as detail and appear only when the question asks for depth.
    """
    described = me.describe()
    layers = me.layers()

    sections: list[Section] = [
        Section(key="purpose", title="What it is for",
                body=_paragraphs(described["purpose"])),
        Section(
            key="layers", title="Four layers",
            body=["Signals are organised across four credit-risk "
                  "perspectives. Underneath, the engine groups them into "
                  f"{len(described['families'])} governed families; the "
                  "layers are how those families read to a credit officer."],
            bullets=[
                f"**Layer {layer.number} — {layer.name}.** {layer.watches} "
                f"({len(me.catalogue(layer_key=layer.key))} signals)"
                for layer in layers]),
        Section(
            key="path", title="How a signal becomes something you act on",
            body=["A signal crossing its threshold is not yet a finding. It "
                  "has to persist, it has to be material, and it has to be "
                  "corroborated across domains before it becomes a case with "
                  "an owner."],
            flow=list(described["flow"])),
        Section(
            key="states", title="What a warning is telling you",
            body=["A warning is described by what the borrower is doing, not "
                  "by what the rule did. Every state is defined against the "
                  "current and previous observation periods."],
            bullets=[f"**{s['state']}.** {s['means']}"
                     for s in described["warning_states"]]),
        Section(
            key="severity", title="Severity and ownership",
            body=[f"Severity is set by the threshold owner "
                  f"({described['owner']}) as part of the signal's "
                  "configuration, not judged per borrower by a model. Every "
                  "evaluation records the data, the threshold and the periods "
                  "behind it, so a warning can be defended or disputed "
                  "specifically."]),
    ]

    for layer in layers:
        entries = me.catalogue(layer_key=layer.key)
        body = _paragraphs(layer.matters)
        if layer.gap:
            body += _paragraphs(layer.gap)
        sections.append(Section(
            key=f"layer_{layer.number}", detail=True,
            title=f"Layer {layer.number} — {layer.name}",
            body=body,
            bullets=[f"**{e.label}.** {e.means} ({e.severity}, {e.frequency})"
                     for e in entries]))

    sections.append(Section(
        key="investigation", title="AI investigation", detail=True,
        body=["A case can be handed to the agentic layer, which gathers the "
              "borrower's evidence across domains, reads the group position "
              "and proposes a next action.",
              "The proposal is a recommendation for a person to approve; the "
              "autonomy level configured for the agent decides whether it "
              "may do more."]))
    sections.append(Section(
        key="trace", title="Trace and governance", detail=True,
        body=[f"Every threshold is owned by {described['owner']} and "
              f"versioned at {described['taxonomy_version']}.",
              "Every evaluation records the data, the field, the threshold "
              "and the periods behind it, so a warning can be defended or "
              "disputed specifically.",
              f"Signals are assessed at the grain of "
              f"{described['grain'].lower()}, and each is assessed when its "
              "source publishes a new period."],
        bullets=[f"**{k}:** {v}"
                 for k, v in described["frequencies"].items()]))
    sections.append(Section(
        key="aggregation", title="Signals read together", detail=True,
        body=(["A borrower showing one concern in one family is a different "
               "proposition from one showing three across fundamentals, "
               "behaviour and credit quality at once."]
              + _paragraphs(described["tac"]["statement"])
              + _paragraphs(described["tac"]["nearest"]))))

    if not detail:
        sections.append(Section(
            key="offer", title="",
            body=["That is the framework. Would you like me to expand the "
                  "signal catalogue for each layer?"]))

    return compose(Answer(
        topic="early_warning_methodology",
        band=DETAILED if detail else MEDIUM,
        deep=bool(detail),
        headline=(f"I watch {described['signal_count']} governed signals "
                  "across four credit-risk layers, grade each by severity, "
                  "track whether it is new, persistent, worsening or "
                  "resolved, and promote what matters into a Risk Case with "
                  "an owner."),
        sections=sections,
        sources=["Early Warning taxonomy", "governed data catalogue"],
        follow_ups=(
            ["What signals are used for liquidity risk?",
             "How does an Early Warning signal become a Risk Case?"]
            if detail else
            ["Expand the signal catalogue for each layer.",
             "How does an Early Warning signal become a Risk Case?",
             "What signals are used for liquidity risk?"])))


def describe_tac_methodology() -> Answer:
    """What is TAC? - it is not defined here, and this says so."""
    found = me.tac()
    return compose(Answer(
        topic="tac",
        band=SHORT,
        headline=("I have no definition of TAC. The term does not appear "
                  "anywhere in this system, so rather than guess what it "
                  "stands for, here is what I looked at and what I do "
                  "implement."),
        sections=[
            Section(key="status", title="What was searched",
                    body=_paragraphs(found.statement),
                    bullets=list(found.searched)),
            Section(key="nearest", title="What I do implement",
                    body=_paragraphs(found.nearest)),
            Section(key="next", title="To publish it",
                    body=["Send me the methodology paper or policy document "
                          "that defines TAC and it can be published as a "
                          "versioned methodology alongside the four-layer "
                          "framework, held to the same checks."]),
        ],
        sources=["repository search", "Early Warning taxonomy"],
        follow_ups=["What is the Early Warning methodology?"]))


def list_early_warning_signals(family: str = "", layer_key: str = "",
                               detail: bool = False) -> Answer:
    """The governed signal catalogue, whole or narrowed."""
    entries = me.catalogue(family=family, layer_key=layer_key)
    described = me.describe()
    scope = ""
    if family:
        scope = f" for {described['families'].get(family, family)}"
    elif layer_key:
        named = next((entry.name for entry in me.layers()
                      if entry.key == layer_key), layer_key)
        scope = f" in {named}"

    if not entries:
        return compose(Answer(
            topic="signals", band=SHORT,
            headline=f"No Early Warning signal is configured{scope}.",
            sections=[Section(
                key="gap", title="Why",
                body=_paragraphs(
                    next((entry.gap for entry in me.layers()
                          if entry.key == layer_key and entry.gap),
                         "The catalogue holds no signal matching that "
                         "request.")))],
            sources=["Early Warning taxonomy"],
            follow_ups=["What is the Early Warning methodology?"]))

    by_layer: dict[str, list[Any]] = {}
    for entry in entries:
        by_layer.setdefault(entry.layer_name, []).append(entry)

    sections: list[Section] = []
    for name, group in by_layer.items():
        sections.append(Section(
            key=f"group_{name}", title=name, depth=3, body=[],
            bullets=[f"**{e.label}.** {e.means}" for e in group]))

    sections.append(Section(
        key="frequency", title="How often they are assessed",
        body=["Frequency is read from the periods each source publishes, "
              "never asserted. A signal is assessed when its source publishes "
              "a new period.",
              described["grain"] + "."],
        bullets=[f"**{k}:** {v}"
                 for k, v in described["frequencies"].items()]))

    sections.append(Section(
        key="thresholds", title="Thresholds", detail=True,
        body=[f"Owned by {described['owner']}, versioned at "
              f"{described['taxonomy_version']}."],
        table={"columns": ["Signal", "Source", "Test", "Threshold",
                           "Direction", "Severity"],
               "rows": [[e.label, e.dataset, e.test,
                         "-" if e.threshold is None else e.threshold,
                         e.direction, e.severity] for e in entries]}))

    return compose(Answer(
        topic="signals",
        band=DETAILED if len(entries) > 12 else MEDIUM,
        deep=bool(detail),
        headline=(f"{len(entries)} governed Early Warning signal"
                  f"{'s' if len(entries) != 1 else ''}{scope}, each with a "
                  "declared source, threshold, direction of deterioration "
                  "and severity."),
        sections=sections,
        sources=["Early Warning taxonomy", "governed data catalogue"],
        follow_ups=["What is the Early Warning methodology?",
                    "How does an Early Warning signal become a Risk Case?"]))


def describe_case_promotion() -> Answer:
    described = me.describe()
    return compose(Answer(
        topic="case_promotion",
        band=SHORT,
        headline=("A signal is an observation. A Risk Case is work somebody "
                  "owns — and the gap between them is deliberate."),
        sections=[
            Section(key="rule", title="What promotes it",
                    body=_paragraphs(described["case_promotion"])),
            Section(key="severity", title="Severity", body=[],
                    bullets=[f"**{k}.** {v}"
                             for k, v in described["severities"].items()]),
            Section(key="persistence", title="Persistence",
                    body=_paragraphs(described["persistence"])),
            Section(key="flow", title="", body=[],
                    flow=list(described["flow"])),
        ],
        sources=["Early Warning taxonomy", "Risk Case lifecycle"],
        follow_ups=["What does a persistent warning mean?",
                    "What is the Early Warning methodology?"]))


def describe_warning_states() -> Answer:
    described = me.describe()
    return compose(Answer(
        topic="warning_states",
        band=SHORT,
        headline=("A warning is described by what the borrower is doing, not "
                  "by what the rule did."),
        sections=[
            Section(key="states", title="The five states", body=[],
                    bullets=[f"**{s['state']}.** {s['means']}"
                             for s in described["warning_states"]]),
            Section(
                key="why", title="Why it is put that way",
                body=["Engine wording — fired, still firing — describes a "
                      "rule evaluating. A credit officer needs to know "
                      "whether the borrower is getting worse, holding, or "
                      "recovering, and against which periods."]),
        ],
        sources=["Early Warning taxonomy"],
        follow_ups=["What is the Early Warning methodology?",
                    "How does an Early Warning signal become a Risk Case?"]))


# ------------------------------------------------------------------ the tools
#
# The names the remediation asks for, as a dispatch table. Each is a plain
# function returning a composed Answer; nothing here calls a model.

TOOLS: dict[str, Any] = {
    "get_creditprobe_overview": get_creditprobe_overview,
    "list_creditprobe_capabilities": list_creditprobe_capabilities,
    "describe_creditprobe_capability": describe_creditprobe_capability,
    "describe_creditprobe_architecture": describe_creditprobe_architecture,
    "describe_ai_role": describe_ai_role,
    "describe_agentic_ai": describe_agentic_ai,
    "describe_governed_engine": describe_governed_engine,
    "describe_early_warning_methodology": describe_early_warning_methodology,
    "describe_tac_methodology": describe_tac_methodology,
    "list_early_warning_signals": list_early_warning_signals,
    "describe_case_promotion": describe_case_promotion,
    "describe_warning_states": describe_warning_states,
    "why_creditprobe": why_creditprobe,
    "how_creditprobe_helps_a_team": how_creditprobe_helps_a_team,
    "creditprobe_versus_a_dashboard": creditprobe_versus_a_dashboard,
    "explain_creditprobe_end_to_end": explain_creditprobe_end_to_end,
}

#: The per-capability tools the remediation names, each resolving to the same
#: capability describer. Declared explicitly so a missing capability is a
#: KeyError at import rather than an empty answer at runtime.
_CAPABILITY_TOOLS: dict[str, str] = {
    "describe_ifrs9_intelligence": "ifrs9",
    "describe_rating_intelligence": "ratings",
    "describe_borrower360": "borrower360",
    "describe_data_builder": "data_builder",
    "describe_analysis_studio": "analysis_studio",
    "describe_stress_testing": "stress_testing",
    "describe_scorecard_validation": "scorecard_validation",
    "describe_trace_lineage": "trace",
    "describe_external_intelligence": "external_intelligence",
    "describe_workflow": "workflow",
    "describe_governance_controls": "ai_governance",
    "describe_early_warning": "early_warning",
    "describe_portfolio_intelligence": "portfolio_intelligence",
    "describe_covenants": "covenants",
    "describe_collateral": "collateral",
    "describe_liquidity": "liquidity",
    "describe_group_risk": "group_risk",
    "describe_ask": "ask",
}

for _name, _key in _CAPABILITY_TOOLS.items():
    if pk.capability(_key) is None:  # pragma: no cover - a registry error
        raise RuntimeError(
            f"{_name} names the capability {_key!r}, which the product "
            "knowledge registry does not have.")
    TOOLS[_name] = (lambda key: lambda: describe_creditprobe_capability(key))(_key)


def call(tool: str, **arguments: Any) -> Answer | None:
    """Run one product-knowledge tool by name."""
    handler = TOOLS.get(str(tool or ""))
    if handler is None:
        return None
    return handler(**arguments)


def tool_names() -> tuple[str, ...]:
    return tuple(sorted(TOOLS))


__all__ = [
    "Answer",
    "NO_CHART",
    "Section",
    "TOOLS",
    "call",
    "creditprobe_versus_a_dashboard",
    "describe_agentic_ai",
    "describe_ai_role",
    "describe_case_promotion",
    "describe_creditprobe_architecture",
    "describe_creditprobe_capability",
    "describe_early_warning_methodology",
    "describe_governed_engine",
    "describe_tac_methodology",
    "describe_warning_states",
    "explain_creditprobe_end_to_end",
    "get_creditprobe_overview",
    "how_creditprobe_helps_a_team",
    "list_creditprobe_capabilities",
    "list_early_warning_signals",
    "tool_names",
    "why_creditprobe",
]
