#!/usr/bin/env python3
"""
Produce sanitized example traces, one per outcome class.

Every trace here is generated by an ACTUAL run through the real worker, the
real store and the real event stream — not written by hand. The analyst is a
stub, and each trace says so in its own header.

The point of shipping these is that an operator can see what each outcome
looks like *before* meeting it at 4pm on a Friday, and can check that nothing
in a downloadable trace carries a secret.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "tests" / "cockpit_v4"))

import oracles  # noqa: E402
from conftest import (ScriptedProvider, ScriptedResult, final, intent,  # noqa: E402
                      tool_call)

from backend.cockpit_v4.capability import Capability, PriceCard  # noqa: E402
from backend.cockpit_v4.config import V4Config  # noqa: E402
from backend.cockpit_v4.run_store import RunStore  # noqa: E402
from backend.cockpit_v4.service import Runtime, load_release  # noqa: E402
from backend.cockpit_v4.worker import Worker  # noqa: E402

RELEASE = "v4-uat-20q-v1"
SECRET_MARKERS = ("sk-", "Bearer ", "api_key", "authorization", "cookie",
                  "password", "secret")


def _runtime(tmp: Path) -> tuple[Runtime, RunStore, V4Config]:
    cfg = V4Config(
        enabled=True, provider="anthropic", reasoning_model="stub-analyst",
        runtime_dir=tmp, state_database=str(tmp / "traces.sqlite3"),
        release_id=RELEASE, api_port=8414, ui_port=5414,
        local_demo_auth=True, price_card_path="", memory_enabled=False,
        memory_model="", default_mode="standard", heartbeat_seconds=5.0,
        lease_heartbeat_seconds=2.0, lease_stale_seconds=10.0,
        supervisor_poll_seconds=2.0, credential_present=True, missing=())
    capability = Capability(
        provider="anthropic", model_id="stub-analyst", sdk_version="traces",
        context_tokens=200_000, max_output_tokens=8192, supports_tools=True,
        supports_token_counting=True, price=PriceCard(15.0, 75.0, 18.75, 1.5),
        source="trace fixture", verified_at="2026-09-10T00:00:00Z",
        live_verified=True)
    catalog, _, summary = load_release(cfg)
    store = RunStore(cfg.state_database)
    runtime = Runtime(cfg=cfg, capability=capability, provider=None,
                      catalog=catalog, coverage=None,
                      release_summary=summary)
    return runtime, store, cfg


def _run(runtime, store, question: str, script) -> dict:
    runtime.provider = ScriptedProvider(script)
    thread_id = store.create_thread(tenant_id="demo-tenant",
                                    principal_id="uat-user")
    record, _ = store.accept_run(
        thread_id=thread_id, tenant_id="demo-tenant", principal_id="uat-user",
        question=question, mode="standard", release_id=RELEASE,
        ui_filters={}, idempotency_key="", body_digest="",
        startup_sha="0000000000000000000000000000000000000000",
        deadline_at="")
    outcome = Worker(store=store, runtime=runtime).execute(record)
    settled = store.get_run(record.run_id)
    events = []
    for event in store.events_since(record.run_id):
        body = event.to_dict()
        detail = (store.get_detail(event.detail_ref) or {}).get("body") \
            if event.detail_ref else None
        events.append({
            "seq": body["seq"], "at_ms": body["elapsed_ms"],
            "event": body["event_type"], "stage": body["stage"],
            "operation": body["operation"], "status": body["status"],
            "message": body["public_message"],
            **({"error_id": body["error_id"]} if body["error_id"] else {}),
            **({"operator_detail": detail} if detail else {})})
    return {
        "run_id": record.run_id,
        "question": question,
        "terminal_state": settled.state,
        "error_code": settled.error_code,
        "budget": settled.budget,
        "response": settled.final_response,
        "events": events,
    }


def _ead_sql() -> str:
    quarter = oracles.latest_quarter(RELEASE)
    return (f"SELECT sector_name, SUM(ead_reported) AS ead_crore\n"
            f"FROM cockpit_facility_quarter\n"
            f"WHERE reporting_quarter = '{quarter}'\n"
            f"GROUP BY sector_name\nORDER BY ead_crore DESC")


def _exec_call(sql: str, call_id="tu-1", step_id="s1"):
    quarter = oracles.latest_quarter(RELEASE)
    return tool_call("execute_analysis", {
        "intent": intent("DATA_ANALYSIS", "COCKPIT",
                         understood="reported EAD by sector, latest quarter"),
        "objective": "Reported EAD by sector for the latest quarter",
        "subquestions": ["EAD by sector for the latest quarter"],
        "scope": {"reporting_quarters": [quarter], "filters": {}},
        "metadata_receipt_ids": [],
        "fields_required": ["cockpit_facility_quarter.ead_reported",
                            "cockpit_facility_quarter.sector_name"],
        "expected_output_grain": "sector", "expected_units": "INR crore",
        "steps": [{"step_id": step_id, "language": "sql", "code": sql,
                   "parameters": {}, "purpose": "EAD by sector",
                   "input_artifact_ids": [], "depends_on_step_ids": []}],
        "repair_of_submission_id": ""}, call_id)


def _finish_from_result(call_id="tu-2"):
    def build(messages):
        body = json.loads(messages[-1]["content"][0]["content"])
        step = body["steps"][0]
        cell = step["preview"][0]
        return ScriptedResult(tool_calls=[tool_call(
            "finalize_response",
            final(intent=intent("DATA_ANALYSIS", "COCKPIT",
                                understood="reported EAD by sector"),
                  narrative=("The largest reported exposure this quarter is "
                             "{{claim.top}}."),
                  coverage=[{"subquestion": "EAD by sector",
                             "status": "answered",
                             "evidence_refs": [
                                 {"artifact_id": step["artifact_id"],
                                  "row_key": f"sector_name="
                                             f"{cell['sector_name']}",
                                  "column_id": "ead_crore"}]}],
                  numeric_claims=[{
                      "claim_id": "top",
                      "decimal_value": repr(float(cell["ead_crore"])),
                      "unit": "INR crore", "display_precision": 2,
                      "evidence": {"artifact_id": step["artifact_id"],
                                   "row_key": f"sector_name="
                                              f"{cell['sector_name']}",
                                   "column_id": "ead_crore"}}]),
            call_id)])
    return build


def main() -> int:
    import tempfile

    tmp = Path(tempfile.mkdtemp(prefix="v4-traces-"))
    runtime, store, cfg = _runtime(tmp)
    out = ROOT / "docs" / "cockpit_v4" / "evidence" / "traces"
    out.mkdir(parents=True, exist_ok=True)

    traces: dict[str, dict] = {}

    traces["01_help_succeeded"] = _run(
        runtime, store, "Who are you?",
        [ScriptedResult(tool_calls=[tool_call("finalize_response", final(
            intent=intent("PRODUCT_HELP", "COCKPIT",
                          understood="who this assistant is"),
            narrative="CreditProbe Cockpit analyses the recorded corporate "
                      "credit book."))])])

    traces["02_analysis_succeeded"] = _run(
        runtime, store, "What is the EAD by sector for the latest quarter?",
        [ScriptedResult(tool_calls=[_exec_call(_ead_sql())]),
         _finish_from_result()])

    broken = _ead_sql().replace("ead_reported", "exposure_at_default")
    traces["03_query_repaired"] = _run(
        runtime, store, "EAD by sector, please",
        [ScriptedResult(tool_calls=[_exec_call(broken)]),
         ScriptedResult(tool_calls=[_exec_call(_ead_sql(), "tu-2", "s2")]),
         _finish_from_result("tu-3")])

    traces["04_code_error_unrecovered"] = _run(
        runtime, store, "show me made-up column",
        [ScriptedResult(tool_calls=[_exec_call(
            "SELECT nonexistent FROM cockpit_facility_quarter LIMIT 1")]),
         ScriptedResult(tool_calls=[tool_call("finalize_response", final(
             intent=intent("DATA_ANALYSIS", "COCKPIT"),
             disposition="partial_answer",
             narrative="That column does not exist in this release, and "
                       "nothing was substituted for it.",
             limitations=["the requested column is not in the catalog"]),
             "tu-2")])])

    traces["05_provider_error"] = _run(
        runtime, store, "Who are you?",
        [RuntimeError("connection reset by peer")])

    traces["06_referral"] = _run(
        runtime, store, "Why did this borrower's EWS score rise?",
        [ScriptedResult(tool_calls=[tool_call("finalize_response", final(
            intent=intent("OTHER_FUNCTIONALITY", "EWS",
                          understood="an EWS score movement"),
            disposition="referral", referral_owner="EWS",
            referral_reason="Early Warning owns alert scores.",
            narrative="Early Warning owns score movements. Nothing was read "
                      "from its data here.",
            coverage=[{"subquestion": "why the EWS score rose",
                       "status": "referred", "evidence_refs": []}]))])])

    # Deadline: a stub that stalls past a shortened deadline.
    import backend.cockpit_v4.config as config_mod
    from dataclasses import replace

    class Stalling(ScriptedProvider):
        def converse(self, **kwargs):
            import time

            time.sleep(0.4)
            return super().converse(**kwargs)

    original = config_mod.STANDARD_LIMITS
    try:
        config_mod.STANDARD_LIMITS = replace(original, deadline_seconds=0.5)
        runtime.provider = Stalling([
            ScriptedResult(tool_calls=[tool_call(
                "inspect_catalog",
                {"intent": intent("DATA_ANALYSIS", "COCKPIT"),
                 "query": "exposure", "relation_ids": [], "field_ids": [],
                 "detail": ["discovery"], "reporting_quarters": [],
                 "sample_rows": 0, "cursor": ""}, f"tu-{i}")])
            for i in range(20)])
        thread_id = store.create_thread(tenant_id="demo-tenant",
                                        principal_id="uat-user")
        record, _ = store.accept_run(
            thread_id=thread_id, tenant_id="demo-tenant",
            principal_id="uat-user", question="a slow question",
            mode="standard", release_id=RELEASE, ui_filters={},
            idempotency_key="", body_digest="", startup_sha="0" * 40,
            deadline_at="")
        Worker(store=store, runtime=runtime).execute(record)
        settled = store.get_run(record.run_id)
        traces["07_deadline_expired"] = {
            "run_id": record.run_id, "question": "a slow question",
            "terminal_state": settled.state,
            "error_code": settled.error_code, "budget": settled.budget,
            "response": settled.final_response,
            "events": [{"seq": e.seq, "at_ms": e.elapsed_ms,
                        "event": e.event_type, "stage": e.stage,
                        "status": e.status, "message": e.public_message}
                       for e in store.events_since(record.run_id)]}
    finally:
        config_mod.STANDARD_LIMITS = original

    # Cancellation: the flag is set before the worker claims the run.
    runtime.provider = ScriptedProvider([
        ScriptedResult(tool_calls=[tool_call("finalize_response", final())])])
    thread_id = store.create_thread(tenant_id="demo-tenant",
                                    principal_id="uat-user")
    record, _ = store.accept_run(
        thread_id=thread_id, tenant_id="demo-tenant", principal_id="uat-user",
        question="never mind", mode="standard", release_id=RELEASE,
        ui_filters={}, idempotency_key="", body_digest="",
        startup_sha="0" * 40, deadline_at="")
    store.request_cancel(record.run_id)
    Worker(store=store, runtime=runtime).execute(
        store.get_run(record.run_id))
    settled = store.get_run(record.run_id)
    traces["08_cancelled"] = {
        "run_id": record.run_id, "question": "never mind",
        "terminal_state": settled.state, "error_code": settled.error_code,
        "budget": settled.budget, "response": settled.final_response,
        "events": [{"seq": e.seq, "at_ms": e.elapsed_ms,
                    "event": e.event_type, "stage": e.stage,
                    "status": e.status, "message": e.public_message}
                   for e in store.events_since(record.run_id)]}

    header = {
        "label": "MODEL STUB · REAL RUNNER · REAL DATABASE · REAL EVENTS",
        "note": ("Generated by an actual run through the real worker, store "
                 "and event stream. The analyst is scripted, so these show "
                 "the SHAPE of each outcome, not model behaviour."),
        "release": RELEASE,
    }
    written = []
    for name, trace in traces.items():
        body = json.dumps({**header, **trace}, indent=2, default=str)
        leaked = [m for m in SECRET_MARKERS if m.lower() in body.lower()]
        if leaked:
            print(f"REFUSING to write {name}: it contains {leaked}")
            return 1
        path = out / f"{name}.json"
        path.write_text(body + "\n", encoding="utf-8")
        written.append((name, trace["terminal_state"],
                        trace.get("error_code") or "—", len(trace["events"])))

    print(f"{'trace':<28} {'state':<18} {'code':<20} events")
    for name, state, code, count in written:
        print(f"{name:<28} {state:<18} {code:<20} {count}")
    print(f"\nwritten to {out}")
    print("no secret marker appears in any trace")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
