"""
Where a turn's progress can be read while the turn is still running.

The problem
-----------
`pipeline.answer` is one synchronous call that takes fifteen to sixty seconds
and returns everything at the end. The events that say what it is doing exist
the whole time; they are simply unreachable until the call returns, which is
too late to be progress.

So the turn writes its events here as it emits them, and a second, very small
request reads them back. The pipeline is untouched apart from being handed an
observer — it decides nothing differently, spends nothing extra, and calls no
model it would not otherwise have called.

Why polling rather than a stream
--------------------------------
Because the Cockpit already polls, through `GET /agentic/runs/{id}/live` and
`pollAfter`, and a second transport in the same product is a second thing to
operate, to authenticate and to get wrong. This is the same shape against a
turn key instead of a run id. The brief asks for the established pattern to be
reused where it is suitable, and it is.

Why in-process
--------------
The reader and the writer are the same FastAPI process: `/ask` is a sync
handler, so Starlette runs it in the threadpool and a concurrent `GET` is
served on another thread. That makes a dictionary and a lock sufficient, and
sufficient is the right size — progress is worth a few kilobytes of memory,
not a database table.

What that costs, stated plainly: behind several worker processes a poll can
land on a worker that never saw the turn. That degrades to "no progress
document", which the client renders as a plain working state. It never
degrades to a WRONG progress document, because a turn key is only ever written
by the worker running that turn.

What is kept
------------
The turn's own events, and nothing else. No question text beyond what the
caller already has, no answer, no model output, no prompt. The events are the
same ones the audit trail records.
"""

from __future__ import annotations

import threading
import time
from dataclasses import dataclass, field
from typing import Any

from backend.early_warning.conversation import progress as progress_mod

#: How long a finished turn stays readable. Long enough that a client polling
#: on a four-second cadence always sees the completed document at least once,
#: short enough that nothing accumulates.
TTL_SECONDS = 300.0

#: How many turns are held at once. A bound rather than a hope: an endpoint
#: that can be called in a loop must not be able to grow memory without limit.
MAX_TURNS = 256

#: Keys are client-supplied, so they are constrained here rather than trusted.
MAX_KEY_LENGTH = 64


#: What a turn IS, as the backend knows it. The client renders from this and
#: from nothing else — which is the whole point of the change that introduced
#: it. A browser that decided for itself when a turn had failed showed "the
#: backend did not respond within 60 seconds" above a completed answer,
#: because a certified turn takes forty to seventy-five seconds and a fetch
#: timeout is not a fact about the analysis.
RUNNING = "running"
COMPLETED = "completed"
FAILED = "failed"

TERMINAL: frozenset[str] = frozenset({COMPLETED, FAILED})


@dataclass
class _Turn:
    """One turn being watched."""

    key: str
    owner: str
    started: float = field(default_factory=time.perf_counter)
    touched: float = field(default_factory=time.monotonic)
    events: list[Any] = field(default_factory=list)
    active: bool = True
    #: The authoritative state. Only this module writes it, and only the turn
    #: itself moves it out of `running`.
    state: str = RUNNING
    #: The finished answer, held for the poll that collects it. Kept on the
    #: turn rather than returned from the POST so that a client which lost
    #: its connection mid-turn can still collect what it asked for.
    result: dict[str, Any] | None = None
    #: Why it failed, in the reader's language. Never a provider message, a
    #: stack trace or an HTTP status.
    failure: str = ""
    #: The question, so a failed turn can be offered back for retry without
    #: the client having to have kept it.
    question: str = ""

    @property
    def elapsed_ms(self) -> int:
        return int((time.perf_counter() - self.started) * 1000)


_lock = threading.Lock()
_turns: dict[str, _Turn] = {}


def valid_key(key: str) -> bool:
    """Whether a client-supplied turn key is one we will store.

    Printable, bounded, no path separators. The key is never used to build a
    filesystem path or a query, but a value that arrives from a browser and is
    stored under its own name gets checked anyway.
    """
    text = str(key or "")
    if not text or len(text) > MAX_KEY_LENGTH:
        return False
    return all(c.isalnum() or c in "-_:." for c in text)


def _owner(principal: Any) -> str:
    """Who a turn belongs to.

    Used to refuse a read from anybody else. Turn keys are generated by the
    client and are therefore guessable, so the check is on identity rather
    than on the key being secret.
    """
    user = getattr(principal, "user_id", None)
    role = getattr(principal, "role", "")
    return f"{user}:{getattr(role, 'value', role)}"


def _evict(now: float) -> None:
    """Drop what has expired, then the oldest if we are still over the bound.

    Called with the lock held.
    """
    dead = [k for k, t in _turns.items() if now - t.touched > TTL_SECONDS]
    for key in dead:
        _turns.pop(key, None)
    if len(_turns) <= MAX_TURNS:
        return
    oldest = sorted(_turns.items(), key=lambda kv: kv[1].touched)
    for key, _ in oldest[: len(_turns) - MAX_TURNS]:
        _turns.pop(key, None)


def open_turn(key: str, principal: Any, *, question: str = "") -> str:
    """Begin watching a turn. Returns the key actually used, or "".

    An invalid key is refused rather than sanitised: a client that sent one
    gets no progress and its answer is unaffected, which is better than
    storing a turn under a name the client will not ask for.
    """
    if not valid_key(key):
        return ""
    now = time.monotonic()
    with _lock:
        _turns[key] = _Turn(key=key, owner=_owner(principal),
                            question=str(question or ""))
        # After the insert rather than before it, so the bound counts the
        # turn being opened. Evicting first leaves the registry one over.
        _evict(now)
    return key


def record(key: str, event: Any) -> None:
    """Append one event. Never raises — this runs inside the turn."""
    if not key:
        return
    with _lock:
        turn = _turns.get(key)
        if turn is None:
            return
        turn.events.append(event)
        turn.touched = time.monotonic()


def close_turn(key: str) -> None:
    """The turn has finished. Its document stops being live and stays readable."""
    if not key:
        return
    with _lock:
        turn = _turns.get(key)
        if turn is None:
            return
        turn.active = False
        turn.touched = time.monotonic()


def finish(key: str, result: dict[str, Any]) -> None:
    """The turn completed and this is its answer.

    Held on the turn rather than only returned from the request that started
    it, so a client whose connection dropped mid-turn collects the answer on
    its next poll instead of being told the analysis failed. The analysis did
    not fail; a socket did.
    """
    if not key:
        return
    with _lock:
        turn = _turns.get(key)
        if turn is None:
            return
        turn.result = dict(result)
        turn.state = COMPLETED
        turn.active = False
        turn.touched = time.monotonic()


def fail(key: str, reason: str) -> None:
    """The turn ended without an answer, and this is what to tell the reader.

    `reason` is written for a credit officer. A provider error, an HTTP
    status and a Python traceback are all facts about the plumbing, and none
    of them belongs on a screen that was asked about a loan book.
    """
    if not key:
        return
    with _lock:
        turn = _turns.get(key)
        if turn is None:
            return
        turn.failure = str(reason or "")
        turn.state = FAILED
        turn.active = False
        turn.touched = time.monotonic()


def state_of(key: str) -> str:
    """Where a turn has got to, or "" if this worker has never seen it."""
    with _lock:
        turn = _turns.get(key)
        return turn.state if turn is not None else ""


def read(key: str, principal: Any) -> dict[str, Any] | None:
    """The progress document for one turn, or None if there is not one.

    None is a perfectly ordinary answer: the turn may have finished and
    expired, or this worker may never have run it. The client shows a plain
    working state for it rather than an error, because nothing is wrong.
    """
    if not valid_key(key):
        return None
    with _lock:
        turn = _turns.get(key)
        if turn is None:
            return None
        if turn.owner != _owner(principal):
            return None
        events = list(turn.events)
        active = turn.active
        elapsed = turn.elapsed_ms
        state = turn.state
        result = dict(turn.result) if turn.result is not None else None
        failure = turn.failure
        question = turn.question
    document = progress_mod.build(events, turn_id=key, active=active,
                                  elapsed_ms=elapsed)
    out: dict[str, Any] = {
        **document.to_dict(),
        # The state the client renders from. A turn is running until this
        # says otherwise, however long that takes and whatever a socket did.
        "state": state,
        "elapsed_ms": elapsed,
    }
    if result is not None:
        out["answer"] = result
    if failure:
        out["failure"] = failure
        out["question"] = question
    return out


def forget(key: str) -> None:
    """Drop a turn now rather than at its TTL. Used by the tests."""
    with _lock:
        _turns.pop(key, None)


def reset() -> None:
    """Empty the registry. Used by the tests."""
    with _lock:
        _turns.clear()


def watching() -> int:
    with _lock:
        return len(_turns)


__all__ = ["COMPLETED", "FAILED", "MAX_KEY_LENGTH", "MAX_TURNS", "RUNNING",
           "TERMINAL", "TTL_SECONDS", "close_turn", "fail", "finish",
           "forget", "open_turn", "read", "record", "reset", "state_of",
           "valid_key", "watching"]
