"""Generate docs/SAUDI_SME_SCORECARD_DATA_DICTIONARY.md from the live modules.

Generated rather than written so it cannot drift from the catalogue. A data
dictionary that disagrees with the data is worse than none.
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from backend.scorecard.sme import catalogue as cat  # noqa: E402
from backend.scorecard.sme import variables as v  # noqa: E402
from backend.scorecard.validation import (  # noqa: E402
    models as model_registry,
)

SOURCE_NOTE = {
    "BANK_INTERNAL":
        "The bank's own systems — accounts, transactions, limits, arrears. "
        "The only family here that a real deployment would not have to "
        "source externally.",
    "SUBMITTED_FINANCIALS":
        "Financial statements the applicant submitted with the application. "
        "Self-reported, and the scorecard treats them as such.",
    "APPLICATION_FORM":
        "What the applicant stated on the form.",
    "COMMERCIAL_BUREAU_PROXY":
        "Stands in for a commercial credit bureau enquiry (SIMAH in the "
        "Saudi market). **Synthetic. Not a bureau connection.**",
    "TAX_AUTHORITY_PROXY":
        "Stands in for VAT registration and filing behaviour held by a tax "
        "authority (ZATCA in the Saudi market). **Synthetic. Not a ZATCA "
        "connection.**",
    "E_INVOICING_PROXY":
        "Stands in for e-invoicing platform participation (FATOORA in the "
        "Saudi market). **Synthetic. Not a platform connection.**",
    "SOCIAL_INSURANCE_PROXY":
        "Stands in for social-insurance and payroll registration (GOSI, "
        "Qiwa, Mudad in the Saudi market). **Synthetic. Not a connection to "
        "any of them.**",
    "COMMERCIAL_REGISTRY_PROXY":
        "Stands in for the commercial register and enterprise-size "
        "certification (Ministry of Commerce, Monsha'at in the Saudi "
        "market). **Synthetic. Not a registry connection.**",
}

HELD_BY = {
    "BANK_INTERNAL": "the bank",
    "SUBMITTED_FINANCIALS": "the applicant (self-reported)",
    "APPLICATION_FORM": "the applicant (declared)",
    "COMMERCIAL_BUREAU_PROXY": "**an external authority — PROXY**",
    "TAX_AUTHORITY_PROXY": "**an external authority — PROXY**",
    "E_INVOICING_PROXY": "**an external authority — PROXY**",
    "SOCIAL_INSURANCE_PROXY": "**an external authority — PROXY**",
    "COMMERCIAL_REGISTRY_PROXY": "**an external authority — PROXY**",
}

FAMILY_NOTE = {
    "Enterprise profile":
        "What the business is: size class, sector, age, legal form, "
        "ownership and the registration facts that go with them.",
    "Financial performance":
        "What the submitted statements say: revenue, margin, leverage, "
        "coverage, working capital and their trends.",
    "Banking and cash-flow behaviour":
        "What the account actually does: turnover, balance behaviour, "
        "returned items, limit utilisation, salary payments.",
    "Commercial credit and bureau proxies":
        "Obligations and conduct outside this bank, as a commercial bureau "
        "would report them.",
    "Digitalisation and compliance proxies":
        "Whether the business is formalised and observable — VAT "
        "registration, e-invoicing, payroll compliance — which in an SME "
        "book is itself a risk signal.",
    "Security and support":
        "Collateral, guarantees and the support a parent or owner provides.",
}

RISK_WORD = {
    "HIGHER_IS_RISKIER": "higher = riskier",
    "LOWER_IS_RISKIER": "lower = riskier",
}


def main() -> None:
    out: list[str] = []
    w = out.append

    sme = list(v.SME)
    model_early = model_registry.get("sme_champion")
    proxy_count = sum(1 for x in sme if v.SOURCE_OF[x.name] in v.PROXY_FAMILIES)
    model = model_early

    w("# Saudi SME Scorecard — Data Dictionary")
    w("")
    w("**Generated from the live catalogue** by "
      "`scripts/generate_sme_data_dictionary.py`. Do not hand-edit: a data "
      "dictionary that disagrees with the data is worse than no data "
      "dictionary, because it is believed.")
    w("")
    w(f"Catalogue version `{cat.CATALOGUE_VERSION}` · variables version "
      f"`{v.VARIABLES_VERSION}` · domain **{cat.DOMAIN_NAME}** · owner "
      f"{cat.OWNER}")
    w("")
    w("---")
    w("")

    # ------------------------------------------------------- the warning
    w("## 1. What this data is, said plainly")
    w("")
    w("Every row in every dataset here is **synthetic**. It was generated by "
      "`backend/scorecard/sme/synthetic.py` from a seeded random number "
      "generator. No row describes a real business, a real applicant, a real "
      "facility or a real default.")
    w("")
    w(f"Of the {len(sme)} variables in the SME universe, "
      f"**{proxy_count} are proxies** for data that a real Saudi deployment "
      "would source from an external authority. They carry names ending "
      "`_proxy` and a source family ending `_PROXY`, and they are marked ⚠ "
      "in §4.")
    w("")
    w(f"The champion scorecard itself is fitted on "
      f"**{len(model.binned_variables)}** of those variables (§5). The "
      "remainder are carried because a validation needs more than the "
      "characteristics that were selected: a variable rejected at "
      "development is exactly what `VAR-*` has to look at when the "
      "selected ones weaken.")
    w("")
    w("The distinction matters more than any other statement in this "
      "document, so it is made once without hedging:")
    w("")
    w("> **CreditProbe is not connected to SIMAH, ZATCA, FATOORA, GOSI, "
      "Qiwa, Mudad, Monsha'at, the Ministry of Commerce, a credit bureau, "
      "or any core banking system.** The variables below are shaped like "
      "what those sources return, so that the validation machinery can be "
      "exercised against realistic distributions. They are not those "
      "sources, and a demonstration that describes them as a live feed is "
      "making a false statement about the product.")
    w("")
    w("The generator is seeded through a BLAKE2b digest rather than "
      "Python's `hash()`, so the universe is identical in every process and "
      "on every machine. That is a validation requirement, not a "
      "convenience: two validators computing the same AUC must get the same "
      "number.")
    w("")
    w("---")
    w("")

    # ---------------------------------------------------------- datasets
    w("## 2. Datasets")
    w("")
    for d in cat.datasets():
        w(f"### `{d['name']}`")
        w("")
        w(f"**{d.get('business_name') or ''}** · {d.get('grain') or ''} · "
          f"{len(d.get('fields') or [])} fields")
        w("")
        w(str(d.get("purpose") or "").strip())
        w("")
    w("**Relationships**")
    w("")
    w("| From | To | Kind | On | Why |")
    w("|---|---|---|---|---|")
    for r in cat.RELATIONSHIPS:
        on = ", ".join(f"`{c}`" for c in r["on"])
        w(f"| `{r['from_dataset']}` | `{r['to_dataset']}` | {r['kind']} "
          f"| {on} | {r['why']} |")
    w("")
    w("The baseline relationship is the one the stability tests depend on. "
      "`sme_scorecard_development_reference` is the frozen out-of-time "
      "population the approved binning was fitted on; every PSI and CSI in "
      "the module is measured against it rather than against last month. "
      "Drifting the baseline forward is how a scorecard passes stability "
      "testing for three years while moving a long way from what was "
      "approved.")
    w("")
    w("---")
    w("")

    # ------------------------------------------------------------ sources
    w("## 3. Source families")
    w("")
    w("| Source family | Variables | Held by | What it stands for |")
    w("|---|---:|---|---|")
    for fam in v.SOURCE_FAMILIES:
        n = sum(1 for x in sme if v.SOURCE_OF[x.name] == fam)
        w(f"| `{fam}` | {n} | {HELD_BY.get(fam, '—')} "
          f"| {SOURCE_NOTE.get(fam, '')} |")
    w("")
    w("---")
    w("")

    # -------------------------------------------------------- variables
    w("## 4. Scorecard variables")
    w("")
    w(f"{len(sme)} variables in six families. `Direction` is the risk "
      "direction the approved binning asserts; `VAR-SIGN` fails if the "
      "observed weight of evidence contradicts it, which is the test that "
      "catches a variable that has inverted since development.")
    w("")
    for fam in v.FAMILIES:
        members = [x for x in sme if v.FAMILY_OF[x.name] == fam]
        w(f"### {fam} ({len(members)})")
        w("")
        note = FAMILY_NOTE.get(fam)
        if note:
            w(note)
            w("")
        w("| Variable | Label | Type | Direction | Source | Definition |")
        w("|---|---|---|---|---|---|")
        for x in members:
            src = v.SOURCE_OF[x.name]
            mark = " ⚠" if src in v.PROXY_FAMILIES else ""
            direction = RISK_WORD.get(x.risk_direction,
                                      x.risk_direction or "—")
            meaning = (x.definition or "").replace("|", "\\|").strip()
            w(f"| `{x.name}` | {x.label} | {x.kind} | {direction} "
              f"| `{src}`{mark} | {meaning} |")
        w("")
    w("⚠ marks a variable whose source is a synthetic proxy for an external "
      "authority. See §1.")
    w("")
    w("---")
    w("")

    # ------------------------------------------------------------- model
    w("## 5. The champion model as the registry holds it")
    w("")
    w("| Property | Value |")
    w("|---|---|")
    w(f"| Model ID | `{model.model_id}` |")
    w(f"| Name | {model.name} |")
    w(f"| Domain | `{model.domain}` |")
    w(f"| Score column | `{model.score_column}` |")
    w(f"| Score direction | `{model.score_direction}` |")
    w(f"| PD column | `{model.pd_column}` |")
    w(f"| Outcome column | `{model.outcome_column}` |")
    w(f"| Maturity flag | `{model.matured_column}` |")
    w(f"| Default definition | {model.default_definition} |")
    w(f"| Performance window | {model.performance_window_months} months |")
    w(f"| Observation window | {model.observation_window} |")
    w(f"| Development population | {model.development_population} |")
    w(f"| Score range | {model.score_range[0]:.0f}–{model.score_range[1]:.0f} |")
    w(f"| Cut-off | {model.cut_off:.0f} |")
    w(f"| Scaling | base score {model.base_score:.0f} at odds "
      f"{model.base_odds:.0f}:1, {model.points_to_double_odds:.0f} points to double the odds |")
    w(f"| Reference | {model.reference_number} v{model.version} "
      f"(challenger {model.challenger_version}) |")
    w(f"| Tier / materiality | {model.tier} / {model.materiality} |")
    w(f"| Binned variables | {len(model.binned_variables)} |")
    w(f"| Configured limits | {len(model.limits)} |")
    segments = ", ".join(f"`{s}`" for s in model.segmentation_fields)
    w(f"| Segmentation fields | {segments or '—'} |")
    w("")
    w("`score_direction` is stated explicitly rather than inferred. A "
      "scorecard where a high score means a good customer and one where a "
      "high score means a bad one produce AUCs that are reflections of each "
      "other, and a module that guesses will eventually report 0.35 as a "
      "failure when the model is fine and the reader is holding it upside "
      "down.")
    w("")
    if model.known_limitations:
        w("**Known limitations recorded at approval**")
        w("")
        for lim in model.known_limitations:
            w(f"- {lim}")
        w("")
    w("---")
    w("")
    w("## 6. Where the numbers in a report come from")
    w("")
    w("Every statistic computed on this data goes through "
      "`backend/scorecard/metrics.py` or `backend/scorecard/binning.py`. "
      "Nothing in the validation package computes a statistic itself, and "
      "no language model computes one at all. See "
      "`docs/SCORECARD_VALIDATION_ARCHITECTURE.md` §5.")

    text = "\n".join(out).rstrip() + "\n"
    (ROOT / "docs" / "SAUDI_SME_SCORECARD_DATA_DICTIONARY.md").write_text(text)
    print(f"wrote {len(text.splitlines())} lines")


if __name__ == "__main__":
    main()
