#!/usr/bin/env python
"""
Generate the retail reference documentation FROM the code that implements it.

    .venv/bin/python scripts/write_retail_docs.py

The data dictionary, the model and transform specification, the Early Warning
rulebook and the What-If operations list are all written from the registries the
running product reads. A hand-maintained copy of any of them would be wrong
within a week, and a documentation forest that no longer matches the code is
worse than none.

The prose documents — the inventory, the assumptions register, the traceability
matrix, the UAT report and the handover — are written by hand and are not
touched by this script.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import pandas as pd  # noqa: E402

from backend.retail import ecl as ecl_mod  # noqa: E402
from backend.retail import ews  # noqa: E402
from backend.retail import taxonomy as tax  # noqa: E402
from backend.retail import whatif as wif  # noqa: E402
from backend.retail.config import load_config  # noqa: E402
from backend.retail.generate import (  # noqa: E402
    IFRS9_PD_MAP_A, IFRS9_PD_MAP_B, PIT_CYCLE_KAPPA, SCORE_TO_IFRS9_PD_MAPPING_VERSION,
)
from backend.retail.models_registry import all_scorecards, registry_manifest  # noqa: E402
from backend.retail.policy import policy_manifest  # noqa: E402
from backend.retail.scorecards import (  # noqa: E402
    BASE_ODDS_GOOD, BASE_SCORE, FACTOR, OFFSET, PDO, SCORE_BAND_EDGES, SCORE_BAND_LABELS,
)
from backend.retail.schema import build_dictionary  # noqa: E402

DOCS = ROOT / "docs"
DISCLOSURE = (
    "> **Synthetic Saudi retail demonstration data — not ANB customer data or "
    "approved models.** Every threshold, coefficient, bin boundary and "
    "distribution in this document is a demonstration assumption. None of it is "
    "an ANB policy, a SAMA requirement or a validated model.\n"
)
GENERATED = (
    "*Generated by `scripts/write_retail_docs.py` from the registries the running "
    "product reads. Do not edit by hand — edit the code and regenerate.*\n"
)


def _sample_columns() -> list[str]:
    from backend.retail.generate import PERIOD_FIELD
    cfg = load_config()
    path = (ROOT / "data" / "retail" / "analytics" / "retail_facility_month"
            / f"{PERIOD_FIELD}={cfg.demo_as_of_month}" / "data.parquet")
    if not path.exists():
        raise SystemExit(
            "The retail lake has not been built, so the dictionary cannot be "
            "written from it. Run scripts/build_retail_demo.py first."
        )
    return list(pd.read_parquet(path).columns)


def write_dictionary() -> Path:
    columns = _sample_columns()
    specs = build_dictionary(columns)
    by_semantics: dict[str, list] = {}
    for s in specs:
        by_semantics.setdefault(s.semantics, []).append(s)

    lines = [
        "# Retail canonical data dictionary",
        "",
        f"`retail_facility_month` — **{len(specs)} columns**, one row per retail "
        "customer's ONE facility at ONE month-end.",
        "",
        DISCLOSURE,
        GENERATED,
        "",
        "## How to read the aggregation column",
        "",
        "| Semantics | What it means | How it aggregates |",
        "|---|---|---|",
        "| STOCK | A level at a point in time | Sum within ONE snapshot. Never across months. |",
        "| FLOW | An amount for a period | Sum across the months of the period wanted. |",
        "| RATIO | A quotient | Recompute from summed numerator over summed denominator. Never average a ratio. |",
        "| COUNT | An occurrence count over a window | Read the window in the name. |",
        "| DESCRIPTOR | A label | Count, do not sum. |",
        "| IDENTIFIER | A key | Count distinct. |",
        "| EVENT_DATE | When something happened | Not summable. |",
        "| EVALUATION_LABEL | Forward-looking outcome knowledge | Evaluation only. Never a predictor. |",
        "",
        "A column whose grain is CUSTOMER is repeated on each of that customer's "
        "facilities. Summing it over facility rows counts one person's income, or "
        "one person's obligations, several times over.",
        "",
    ]
    for semantics in sorted(by_semantics):
        group = sorted(by_semantics[semantics], key=lambda s: s.name)
        lines += [
            f"## {semantics} ({len(group)} columns)",
            "",
            "| Column | Business name | Type | Unit | Grain | Products | Aggregation | Definition |",
            "|---|---|---|---|---|---|---|---|",
        ]
        for s in group:
            products = "all" if len(s.products) == 4 else ", ".join(s.products)
            definition = s.definition.replace("|", "\\|").replace("\n", " ")
            null_policy = f" **Null policy:** {s.null_policy}" if s.null_policy else ""
            lines.append(
                f"| `{s.name}` | {s.business_name} | {s.data_type} | {s.unit or '—'} | "
                f"{s.grain} | {products} | {s.aggregation or '—'} | {definition}{null_policy} |"
            )
        lines.append("")
    path = DOCS / "RETAIL_DATA_DICTIONARY.md"
    path.write_text("\n".join(lines))
    return path


def write_model_spec() -> Path:
    manifest = registry_manifest()
    lines = [
        "# Retail scorecards: models, transformations and reconstruction",
        "",
        DISCLOSURE,
        GENERATED,
        "",
        "## The scale",
        "",
        f"- Base score **{BASE_SCORE:g}** at good:bad odds of **{BASE_ODDS_GOOD:g}:1**",
        f"- Points to double the odds **{PDO:g}**",
        f"- `factor = pdo / ln(2) = {FACTOR:.6f}`",
        f"- `offset = base_score - factor * ln(base_odds) = {OFFSET:.6f}`",
        "- Direction **HIGHER SCORE = LOWER DEFAULT RISK**, recorded on every row",
        "",
        "This is a demonstration scale. It is not a bureau's range and not ANB's.",
        "",
        "## The arithmetic, in full",
        "",
        "```text",
        "woe          = ln(P(good in bin) / P(bad in bin))     higher is safer",
        "logit        = intercept - sum(coefficient * woe)     log-odds of DEFAULT",
        "predicted_pd = 1 / (1 + exp(-logit))",
        "score        = offset - factor * logit",
        "base_points  = offset - factor * intercept",
        "points_i     = factor * coefficient_i * woe_i",
        "score        = base_points + sum(points_i)            <- exact identity",
        "```",
        "",
        "The last line is a gate (RET-013), not a claim: it is checked to within "
        "1e-6 on every published row of every model.",
        "",
        "## Score bands",
        "",
        "| Band | Score range |",
        "|---|---|",
    ]
    edges = list(SCORE_BAND_EDGES)
    labels = list(SCORE_BAND_LABELS)
    lines.append(f"| {labels[0]} | below {edges[0]:g} |")
    for i in range(len(edges) - 1):
        lines.append(f"| {labels[i + 1]} | {edges[i]:g} to below {edges[i + 1]:g} |")
    lines.append(f"| {labels[-1]} | {edges[-1]:g} and above |")
    lines += [
        "",
        "## Targets",
        "",
        f"**Application** — `{manifest['application_target']['target_definition_id']}`  ",
        f"{manifest['application_target']['target_event']}  ",
        f"Horizon {manifest['application_target']['horizon_months']} months.",
        "",
        f"**Behavioural** — `{manifest['behavioural_target']['target_definition_id']}`  ",
        f"{manifest['behavioural_target']['target_event']}  ",
        f"Horizon {manifest['behavioural_target']['horizon_months']} months.",
        "",
        "These are the models' own targets. The IFRS 9 PD answers a different "
        "question and reaches it through an explicit versioned mapping "
        f"(`{SCORE_TO_IFRS9_PD_MAPPING_VERSION}`), never by assuming they are the "
        "same number.",
        "",
    ]
    for sc in all_scorecards():
        lines += [
            f"## `{sc.model_id}` v{sc.model_version}",
            "",
            f"- Product **{sc.product_code}**, subject grain **{sc.subject_grain}**",
            f"- Transform version `{sc.transform_version}`",
            f"- Intercept `{sc.intercept:+.4f}`, base points `{sc.base_points:.4f}`",
            f"- **{len(sc.features)} inputs**, every one of which has "
            f"`_raw`, `_transformed`, `_bin`, `_missing_flag` and `_points` columns",
            "",
            "| Input | Source column | Coefficient | Bins | WoE by bin | Missing WoE |",
            "|---|---|---|---|---|---|",
        ]
        for f in sc.features:
            woe = ", ".join(f"{b}:{f.woe[b]:+.2f}" for b in f.labels)
            lines.append(
                f"| {f.business_name} | `{f.source}` | {f.coefficient:.2f} | "
                f"{len(f.labels)} | {woe} | {f.woe_missing:+.2f} |"
            )
        lines.append("")
    path = DOCS / "RETAIL_MODEL_AND_TRANSFORM_SPEC.md"
    path.write_text("\n".join(lines))
    return path


def write_ews_rulebook() -> Path:
    book = ews.rulebook()
    lines = [
        "# Retail Early Warning rulebook",
        "",
        DISCLOSURE,
        GENERATED,
        "",
        f"Rulebook version `{book['rulebook_version']}` — "
        f"**{len(book['rules'])} facility and customer rules**, "
        f"**{len(book['segment_rules'])} segment rules**.",
        "",
        "Every rule reads the canonical `retail_facility_month` rows. There is no "
        "separate Early Warning seed, which is why an alert's affected exposure and "
        "the portfolio's exposure are the same number rather than two numbers that "
        "happen to be close.",
        "",
        f"**Thresholds.** {book['threshold_source']}",
        "",
        f"**Actions.** {book['note']}",
        "",
        "## Scope, and why it matters",
        "",
        "A salary interruption is a fact about a PERSON. Raising it once per "
        "facility would show one customer three times and count their exposure "
        "three times over. Customer-scope rules raise one alert and attach the "
        "affected facilities; `affected_exposure_sar` counts each facility once "
        "even when two rules cover it.",
        "",
        "## Rules",
        "",
    ]
    by_family: dict[str, list] = {}
    for r in book["rules"]:
        by_family.setdefault(r["family"], []).append(r)
    for family in sorted(by_family):
        lines += [f"### {family.replace('_', ' ').title()}", ""]
        for r in by_family[family]:
            products = ("all products" if len(r["products"]) == 4
                        else ", ".join(r["products"]))
            lines += [
                f"#### `{r['rule_id']}` v{r['version']} — {r['name']}",
                "",
                f"- **Scope** {r['scope']} | **Products** {products} | "
                f"**Severity** {r['severity']}",
                f"- **Trigger** `{r['trigger_expression']}`",
                f"- **Threshold** {r['threshold']} {r['unit']}, lookback "
                f"{r['lookback_months']} month(s)",
                f"- **Inputs** {', '.join('`' + f + '`' for f in r['features'])}",
                f"- **Suggested review** {r['recommended_review']}",
                "",
            ]
    lines += ["## Segment and portfolio rules", ""]
    for r in book["segment_rules"]:
        lines += [
            f"#### `{r['rule_id']}` v{r['version']} — {r['name']}",
            "",
            f"- **Grouped by** `{r['group_by']}` | **Measure** {r['measure']}",
            f"- **Threshold** {r['threshold']} | minimum population "
            f"{r['min_customers']} | severity {r['severity']}",
            f"- **Suggested review** {r['recommended_review']}",
            "",
        ]
    path = DOCS / "RETAIL_EWS_RULEBOOK.md"
    path.write_text("\n".join(lines))
    return path


def write_whatif_operations() -> Path:
    lines = [
        "# Retail What-If: what it supports, and what it refuses",
        "",
        DISCLOSURE,
        GENERATED,
        "",
        f"Methodology version `{wif.METHODOLOGY_VERSION}`.",
        "",
        "A scenario rebuilds each facility's hazard curve, exposure path and loss "
        "given default from the inputs the canonical row already carries, applies "
        "the shock to those inputs, and runs the same ECL engine that produced the "
        "published figure. It never multiplies a total by a percentage, and it "
        "never mutates canonical data.",
        "",
        "## Supported methodologies",
        "",
        "| Methodology | What it does |",
        "|---|---|",
    ]
    for name, description in sorted(wif.SUPPORTED_METHODOLOGIES.items()):
        lines.append(f"| `{name}` | {description} |")
    lines += [
        "",
        "An unsupported request returns this list. It never falls through to "
        "another engine.",
        "",
        "## Distinctions the engine will not blur",
        "",
        "| | |",
        "|---|---|",
        "| Relative vs percentage point | +20% relative on a PD of 0.02 is **0.024**. +2 percentage points is **0.04**. A card utilisation move from 40% to 60% is **+20 percentage points**, not a 20% relative increase. |",
        "| Baseline vs base scenario | The BASELINE is the snapshot's weighted, final ECL. The scenario `base` ECL is one of the three macroeconomic scenarios inside it. Different quantities, different field names. |",
        "| Assumption vs observation | A shock to current income reaches affordability, the behavioural evidence and the mapped IFRS 9 PD. It does not reach the application score, the origination inputs or the bureau score at origination. |",
        "| Frozen vs re-evaluated staging | `frozen_stage` is a parameter sensitivity at fixed stages. `reevaluate_stage` re-runs the staging policy and lets facilities migrate. |",
        "| Performing vs defaulted | A defaulted facility has no performing PD to shock. It responds to recovery and delay assumptions; a PD multiplier on it is disclosed as inapplicable rather than silently clipped at one. |",
        "",
        "## The retrospective cutoff replay",
        "",
        "What it can say: which historically funded accounts a tighter cutoff "
        "would have excluded, and what those accounts actually went on to do.",
        "",
        "What it cannot say, and does not pretend to:",
        "",
    ]
    sample = wif.cutoff_replay(
        pd.DataFrame({
            "facility_id": ["RF-1"], "product_code": ["PERSONAL_LOAN"],
            "application_score_at_origination": [600.0],
            "gross_carrying_amount_sar": [1000.0],
            "observed_default_within_window": [False],
        }),
        {"PERSONAL_LOAN": 650.0})
    for limitation in sample["limitations"]:
        lines.append(f"- {limitation}")
    lines += [
        "",
        "No row is manufactured to fill the gap where the declined applications "
        "would be.",
        "",
    ]
    path = DOCS / "RETAIL_WHATIF_SUPPORTED_OPERATIONS.md"
    path.write_text("\n".join(lines))
    return path


def write_ecl_methodology() -> Path:
    cfg = load_config()
    policy = policy_manifest()
    scen = cfg.scenarios
    lines = [
        "# Retail IFRS 9: the demonstration methodology",
        "",
        DISCLOSURE,
        GENERATED,
        "",
        f"Engine version `{ecl_mod.ECL_MODEL_VERSION}`. A transparent monthly-hazard "
        "formulation, written so every number can be re-derived from the inputs "
        "stored beside it. It is not ANB's approved accounting model and it has "
        "had no independent validation.",
        "",
        "## Quantities kept separate",
        "",
        "| Quantity | What it is |",
        "|---|---|",
        "| `pd_ttc_12m` | A through-the-cycle 12-month reference probability. |",
        "| `pd_pit_12m_<scenario>` | Point-in-time, conditioned on one scenario. |",
        "| `pd_pit_lifetime_<scenario>` | Cumulative over the applicable remaining life. |",
        "| `application_predicted_pd_12m` | The application model's answer to ITS target. |",
        "| `behavioural_predicted_pd_12m` | The behavioural model's answer to ITS target. |",
        "",
        "The last two reach IFRS 9 only through the versioned mapping "
        f"`{SCORE_TO_IFRS9_PD_MAPPING_VERSION}`:",
        "",
        "```text",
        f"logit_ttc      = {IFRS9_PD_MAP_A} + {IFRS9_PD_MAP_B} * logit(model_pd)",
        f"logit_pit_base = logit_ttc + {PIT_CYCLE_KAPPA} * cycle_factor",
        "```",
        "",
        "The coefficients are demo assumptions. No empirical Saudi macroeconomic "
        "relationship is claimed.",
        "",
        "## The hazard curve",
        "",
        "```text",
        "h(t)            = conditional probability of default in month t, given survival",
        "S(0)            = 1",
        "S(t)            = S(t-1) * (1 - h(t))",
        "marginal_pd(t)  = S(t-1) * h(t)",
        "cumulative_pd(T)= sum(marginal_pd(t), t = 1..T)",
        "```",
        "",
        "`h` is anchored so that `sum(marginal_pd(1..12)) == pd_12m` exactly, then "
        "shaped by a documented seasoning curve. Survival is never double counted.",
        "",
        "## Horizons",
        "",
        "| Stage | Default events counted over | Note |",
        "|---|---|---|",
        "| 1 | 12 months, or the shorter remaining life | It does NOT truncate the loss from those defaults. LGD embeds recoveries discounted back to the DEFAULT date, so a default in month 11 whose recovery arrives in month 35 is fully costed. |",
        "| 2 | The applicable remaining expected life | Revolving facilities use a behavioural expected life of "
        f"{cfg.ecl['revolving_behavioural_life_months']} months, not a contractual twelve. |",
        "| 3 | Not a hazard calculation at all | The facility has defaulted. The loss is the shortfall between the gross carrying amount and the present value of expected recoveries. |",
        "",
        f"Lifetime curves are evaluated to {ecl_mod.LIFETIME_HORIZON_CAP_MONTHS} "
        "months and every row records the horizon it actually used in "
        "`ecl_horizon_months`. Nothing is truncated silently.",
        "",
        "## Loss given default",
        "",
        f"{policy['recovery']['lgd_definition']}",
        "",
        "```text",
        "lgd = 1 - recovery_rate_nominal * (1 + monthly_rate) ** -delay_months",
        "```",
        "",
        "Each cash flow is discounted across each interval exactly once: from "
        "receipt back to the default date inside LGD, and from the default month "
        "back to the reporting date inside ECL.",
        "",
        "## Scenario ECL and the weighted identity",
        "",
        "```text",
        "scenario_ECL = sum_t[ marginal_pd_s(t) * EAD_s(t) * LGD_s * discount(t) ]",
        "",
        f"weights           base {scen.weights['base']}  upturn {scen.weights['upturn']}  "
        f"downturn {scen.weights['downturn']}",
        "0 <= each weight <= 1     and     sum(weights) == 1",
        "",
        "ecl_weighted_sar = w_base*ecl_base + w_upturn*ecl_upturn + w_downturn*ecl_downturn",
        "ecl_final_sar    = ecl_weighted_sar + management_overlay_sar",
        "```",
        "",
        "The weighted ECL weights the complete scenario RESULTS. It does not "
        "average PD, LGD and EAD and then multiply them, which would discard "
        "exactly the non-linearity multiple scenarios exist to capture.",
        "",
        "Invalid weights are **refused**, not silently normalised.",
        "",
        "## Scenario ordering",
        "",
        "```text",
        "ecl_upturn_sar <= ecl_base_sar <= ecl_downturn_sar",
        "```",
        "",
        "This holds because the inputs are ordered, not because the outputs are "
        "sorted:",
        "",
        "| Multiplier | Upturn | Base | Downturn |",
        "|---|---|---|---|",
        f"| Hazard | {scen.hazard_multiplier['upturn']} | {scen.hazard_multiplier['base']} | {scen.hazard_multiplier['downturn']} |",
        f"| LGD | {scen.lgd_multiplier['upturn']} | {scen.lgd_multiplier['base']} | {scen.lgd_multiplier['downturn']} |",
        f"| EAD | {scen.ead_multiplier['upturn']} | {scen.ead_multiplier['base']} | {scen.ead_multiplier['downturn']} |",
        f"| Recovery delay (months added) | {scen.recovery_delay_add_months['upturn']} | {scen.recovery_delay_add_months['base']} | {scen.recovery_delay_add_months['downturn']} |",
        "",
        "It is a deliberate demonstration invariant for this synthetic book, not a "
        "universal mathematical requirement for every real portfolio.",
        "",
        "## Precision",
        "",
        "Each scenario ECL is published rounded to the halala, because that is the "
        "figure a reader quotes. The weighted and final allowance are the exact "
        "weighted combination of those published values, so the identity a reader "
        "can check on screen holds rather than drifting into real riyals once "
        "twenty thousand rows are added up.",
        "",
        "## Staging policy",
        "",
        f"Version `{policy['staging']['version']}` — {policy['staging']['source_label']}.",
        "",
        "| Rule | Setting |",
        "|---|---|",
        f"| Stage 2 DPD backstop | {policy['staging']['stage2_dpd_backstop']} days |",
        f"| Stage 3 / default backstop | {policy['staging']['stage3_dpd_backstop']} days |",
        f"| Quantitative SICR, PD ratio | {policy['staging']['sicr_pd_ratio_threshold']}x |",
        f"| Quantitative SICR, PD absolute | {policy['staging']['sicr_pd_absolute_threshold']} |",
        f"| Cure probation | {policy['staging']['cure_probation_months']} months |",
        f"| Default definition | `{policy['staging']['default_definition_id']}` |",
        "",
        "Stage 2 is reachable **before** arrears where SICR evidence exists. "
        "Stage 3 is reachable **before** 90 days on documented unlikeliness to pay. "
        "The quantitative SICR test compares like horizons: current remaining-life "
        "PD against the origination curve's remaining-life reference, never a "
        "12-month PD divided by an origination lifetime PD.",
        "",
        f"{policy['disclaimer']}",
        "",
    ]
    path = DOCS / "RETAIL_ECL_METHODOLOGY.md"
    path.write_text("\n".join(lines))
    return path


def main() -> int:
    written = [
        write_dictionary(), write_model_spec(), write_ews_rulebook(),
        write_whatif_operations(), write_ecl_methodology(),
    ]
    for path in written:
        size = path.stat().st_size
        print(f"  {path.relative_to(ROOT)}  ({size:,} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
