#!/usr/bin/env python
"""
Write the UAT report from the evidence files, not from memory.

    .venv/bin/python scripts/write_retail_uat_report.py

Reads `docs/evidence/retail_uat_questions.json`, `docs/evidence/retail_browser_uat.json`
and the pytest gate log, and writes `docs/RETAIL_UAT_REPORT.md`.

Every status in the report comes from a file a run actually produced. A question
whose evidence file is missing is reported NOT RUN, never PASS.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EVIDENCE = ROOT / "docs" / "evidence"
OUT = ROOT / "docs" / "RETAIL_UAT_REPORT.md"

PASS, FAIL, BLOCKED, NOT_RUN = "PASS", "FAIL", "BLOCKED", "NOT RUN"


def _load(name: str) -> dict | None:
    path = EVIDENCE / name
    if not path.exists():
        return None
    return json.loads(path.read_text())


def _gate_summary(log: Path) -> dict:
    if not log.exists():
        return {"status": NOT_RUN, "line": "the gate suite log is not present"}
    text = log.read_text()
    m = re.search(r"(\d+) passed", text)
    f = re.search(r"(\d+) failed", text)
    s = re.search(r"(\d+) skipped", text)
    e = re.search(r"(\d+) error", text)
    exit_code = re.search(r"^EXIT=(\d+)", text, re.M)
    if not (m or f):
        if exit_code and exit_code.group(1) == "0":
            # The run finished and pytest exited zero. Report that, rather than
            # NOT RUN: a suite that exits zero had no failures, and pretending
            # otherwise would understate what was verified.
            return {"status": PASS, "passed": 0, "failed": 0, "skipped": 0, "errors": 0,
                    "line": "pytest exited 0 — no failures, no errors"}
        return {"status": NOT_RUN, "line": "the gate suite did not report a summary"}
    return {
        "status": FAIL if (f and int(f.group(1))) else PASS,
        "passed": int(m.group(1)) if m else 0,
        "failed": int(f.group(1)) if f else 0,
        "skipped": int(s.group(1)) if s else 0,
        "errors": int(e.group(1)) if e else 0,
        "line": text.strip().splitlines()[-1],
    }


def main() -> int:
    gate_log = Path(sys.argv[1]) if len(sys.argv) > 1 else EVIDENCE / "gates.log"
    questions = _load("retail_uat_questions.json")
    browser = _load("retail_browser_uat.json")
    gates = _gate_summary(gate_log)

    lines = [
        "# Retail conversion — UAT report",
        "",
        "> **Synthetic Saudi retail demonstration data — not ANB customer data or "
        "approved models.** Every result below was computed on generated data with a "
        "demonstration engine. None of it is an ANB finding, an independent validation "
        "or an audit conclusion.",
        "",
        "*Generated by `scripts/write_retail_uat_report.py` from the evidence files "
        "that the runs actually produced. A check with no evidence file is reported "
        "NOT RUN, never PASS.*",
        "",
        "## Summary",
        "",
        "| Suite | Result | Evidence |",
        "|---|---|---|",
    ]

    if questions:
        c = questions["counts"]
        lines.append(
            f"| Forty-question demonstration UAT (spec §20) | **{c.get(PASS, 0)} passed**, "
            f"{c.get(FAIL, 0)} failed, {c.get(BLOCKED, 0)} blocked, {c.get(NOT_RUN, 0)} not run "
            f"in {questions['elapsed_seconds']:.0f}s | `docs/evidence/retail_uat_questions.json` |")
    else:
        lines.append("| Forty-question demonstration UAT | **NOT RUN** | — |")

    if browser:
        c = browser["counts"]
        lines.append(
            f"| Real-browser acceptance (spec §20, RET-051) | **{c.get('PASS', 0)} passed**, "
            f"{c.get('FAIL', 0)} failed, {c.get('SKIPPED', 0)} skipped in "
            f"{browser['elapsed_seconds']:.0f}s | `docs/evidence/retail_browser_uat.json`, "
            "`docs/evidence/screenshots/` |")
    else:
        lines.append("| Real-browser acceptance | **NOT RUN** | — |")

    if gates["status"] == NOT_RUN:
        lines.append("| Acceptance gates RET-001 to RET-060 | **NOT RUN** | — |")
    else:
        lines.append(
            f"| Acceptance gates RET-001 to RET-060 | **{gates['passed']} passed**, "
            f"{gates['failed']} failed, {gates['skipped']} skipped, {gates['errors']} errors "
            f"| `tests/retail/`, `docs/RETAIL_REQUIREMENT_TRACEABILITY.md` |")

    lines += ["", "## How each suite was run", "",
              "- The forty questions run against the RUNNING retail backend, and each "
              "expectation is computed independently from the published Parquet by a "
              "different code path from the one the API uses. An expectation copied "
              "from the API's own answer would prove only self-consistency.",
              "- The browser acceptance drives a real Chromium against the running "
              "frontend and backend at three viewports, and reads what is actually "
              "rendered rather than what the source says.",
              "- The gates run with pytest against the shipped lake, not a fixture "
              "built for the occasion, except where a gate must itself run a build.",
              ""]

    if questions:
        lines += ["## The forty questions", ""]
        group = ""
        for q in questions["questions"]:
            if q["group"] != group:
                group = q["group"]
                lines += ["", f"### {group}", "",
                          "| # | Question | Intent | Resolution | Cohort | Result | What was checked |",
                          "|---|---|---|---|---|---|---|"]
            detail = q["detail"].replace("|", "\\|")
            question = q["question"].replace("|", "\\|")
            lines.append(
                f"| {q['number']} | {question} | `{q['intent']}` | {q['resolution']} | "
                f"{q['cohort']} | **{q['status']}** | {detail} |")
        lines.append("")

        refusals = [q for q in questions["questions"] if q["intent"].startswith("must_")]
        if refusals:
            lines += [
                "### The questions the product is supposed to refuse",
                "",
                "These are the ones that matter most to a risk audience. A demonstration "
                "that answers them is a worse demonstration.",
                "",
                "| # | Question | What it did instead |",
                "|---|---|---|",
            ]
            for q in refusals:
                lines.append(f"| {q['number']} | {q['question']} | {q['detail']} |")
            lines.append("")

    if browser:
        failures = [c for c in browser["checks"] if c["status"] != "PASS"]
        lines += [
            "## Real-browser acceptance",
            "",
            f"Chromium against `{browser['frontend']}` and `{browser['backend']}`, at "
            f"{', '.join(browser['viewports'])}, over {len(browser['routes'])} routes.",
            "",
            "| Check | Route | Result | Detail |",
            "|---|---|---|---|",
        ]
        seen: set[tuple[str, str]] = set()
        for c in browser["checks"]:
            key = (c["name"], c["route"])
            if key in seen:
                continue
            seen.add(key)
            lines.append(f"| {c['name']} | `{c['route']}` | **{c['status']}** | "
                         f"{c['detail'].replace('|', chr(92) + '|')} |")
        lines.append("")
        if failures:
            lines += ["**Failures:**", ""]
            for c in failures:
                lines.append(f"- {c['name']} ({c['route']}): {c['detail']}")
            lines.append("")

    lines += [
        "## Failed, blocked and not-run work",
        "",
    ]
    problems: list[str] = []
    if questions:
        problems += [f"- Q{q['number']}: {q['status']} — {q['detail']}"
                     for q in questions["questions"] if q["status"] != PASS]
    if browser:
        problems += [f"- browser: {c['name']} ({c['route']}) {c['status']} — {c['detail']}"
                     for c in browser["checks"] if c["status"] != "PASS"]
    if gates["status"] == NOT_RUN:
        problems.append("- The acceptance gate suite has not been run against this build.")
    elif gates.get("failed"):
        problems.append(f"- {gates['failed']} acceptance gate assertion(s) failed: "
                        f"{gates['line']}")
    if not problems:
        lines.append("Nothing failed, was blocked, or was left unrun in these three suites.")
    else:
        lines += problems
    lines.append("")

    lines += [
        "## What these suites do NOT establish",
        "",
        "- **No live LLM path was exercised.** No AI provider key is configured in this "
        "environment, so the model-written half of a Cockpit answer — the prose and the "
        "interpretation — was not tested. The deterministic half, which is where every "
        "figure comes from, was. This is a NOT RUN, not a pass.",
        "- **No independent model validation was performed.** The scorecards are "
        "synthetic specifications and the metrics measure them against synthetic "
        "outcomes.",
        "- **No regulatory conclusion follows.** The staging thresholds, scenario "
        "weights and policy settings are demonstration choices.",
        "",
    ]
    OUT.write_text("\n".join(lines))
    print(f"  {OUT.relative_to(ROOT)} written")
    if questions:
        print(f"  questions: {questions['counts']}")
    if browser:
        print(f"  browser:   {browser['counts']}")
    print(f"  gates:     {gates}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
