"""
The overnight analytical benchmark: twenty senior-credit-risk questions.

Three evidence layers, kept apart on purpose.

LAYER A — the ORACLE. `oracle()` computes the expected answer with pandas,
straight from the published Parquet. It imports nothing from the query path,
the catalog, the validator or the executor. It is allowed to disagree, and
while this file was being written it did — twice.

LAYER B — the INDEPENDENT ANALYST. `sql_for()` is SQL authored against the
catalogue by a reader of the question, not generated by the product. In the
harness it stands in for what Opus would write. If it disagrees with Layer A,
one of the two is wrong and the test says so rather than averaging them.

LAYER C — the PRODUCT. The test module drives the real V4: intake, context,
tool contracts, validator, bind proof, DuckDB, artifacts, finalizer, events.

Nothing here is hard-coded. Every expected number is calculated from the
pinned release at test time, so the bank travels to a different release and
still means something.
"""

from __future__ import annotations

import os
from typing import Any

import pandas as pd

RELEASE = os.environ.get("COCKPIT_V4_TEST_RELEASE", "v4-uat-20q-v1")


def _frame(relation: str, release_id: str = "") -> pd.DataFrame:
    os.environ.setdefault("COCKPIT_AGENTIC_V3_NAMESPACE", "cockpit_v4")
    from backend.cockpit_agentic import store

    return pd.read_parquet(
        store.relation_path(release_id or RELEASE, relation))


def quarters(release_id: str = "") -> list[str]:
    frame = _frame("cockpit_facility_quarter", release_id)
    return sorted(str(q) for q in frame["reporting_quarter"].dropna().unique())


def periods(release_id: str = "") -> dict[str, str]:
    slots = quarters(release_id)
    return {"latest": slots[-1], "prior": slots[-2], "year_ago": slots[-5],
            "last_four": slots[-4:]}


def _facility(release_id: str = "") -> pd.DataFrame:
    frame = _frame("cockpit_facility_quarter", release_id)
    return frame[frame["sector_name"].notna()]


def _borrower_ratings(release_id: str = "") -> pd.DataFrame:
    return _frame("cockpit_rating_ratio_quarter", release_id)[
        ["reporting_quarter", "borrower_id", "risk_rating", "rating_rank"]]


# ---- the twenty questions ----------------------------------------------

#: Chart policy, stated per question rather than applied mechanically.
BAR, LINE, STACKED, WATERFALL, NONE = (
    "horizontal_bar", "line", "stacked_bar", "waterfall", "none")

QUESTIONS: list[dict[str, Any]] = [
    # --- Part 11: filtering / data pull ---
    {"id": "Q01", "category": "data_pull",
     "text": "What is total exposure at default by sector in the latest "
             "quarter?",
     "owner": "COCKPIT", "mode": "DATA_ANALYSIS",
     "measures": ["ead_reported"], "group": ["sector_name"],
     "aggregation": "sum", "periods": ["latest"],
     "chart": BAR, "chart_reason": "a ranked sector comparison reads faster "
                                   "as a bar than as a column of numbers",
     "insight": ["total reconciles", "top sector share"]},
    {"id": "Q02", "category": "data_pull",
     "text": "Show the top 10 borrowers by recorded ECL in the latest "
             "quarter, with sector, IFRS 9 stage, EAD and ECL.",
     "owner": "COCKPIT", "mode": "DATA_ANALYSIS",
     "measures": ["ecl_reported", "ead_reported", "ifrs9_stage"],
     "group": ["borrower_id"], "aggregation": "sum", "periods": ["latest"],
     "chart": BAR, "chart_reason": "ten named contributors rank usefully",
     "insight": ["concentration of the top names"]},
    {"id": "Q03", "category": "data_pull",
     "text": "Show Stage 2 exposure at default by sector in the latest "
             "quarter and each sector's share of total Stage 2 EAD.",
     "owner": "COCKPIT", "mode": "DATA_ANALYSIS",
     "measures": ["ead_reported"], "group": ["sector_name"],
     "aggregation": "sum", "periods": ["latest"],
     "chart": BAR, "chart_reason": "shares of one total compare well as bars",
     "insight": ["shares sum to 100%"]},
    {"id": "Q04", "category": "data_pull",
     "text": "Which borrowers had a recorded covenant breach in any of the "
             "latest four quarters, and was a waiver recorded?",
     "owner": "COCKPIT", "mode": "DATA_ANALYSIS",
     "measures": ["breach_date", "waiver_flag"], "group": ["borrower_id"],
     "aggregation": "distinct", "periods": ["last_four"],
     "chart": NONE, "chart_reason": "a list of names and flags is a table; a "
                                    "chart of it would add nothing",
     "insight": ["how many are unwaived"]},
    {"id": "Q05", "category": "data_pull",
     "text": "Which borrowers were downgraded in the latest quarter? Show "
             "previous rating, current rating, EAD and recorded ECL.",
     "owner": "COCKPIT", "mode": "DATA_ANALYSIS",
     "measures": ["rating_rank", "ead_reported", "ecl_reported"],
     "group": ["borrower_id"], "aggregation": "sum",
     "periods": ["latest", "prior"],
     "chart": NONE, "chart_reason": "a short named list with before/after "
                                    "grades reads better as a table",
     "insight": ["exposure carried by the downgraded names"]},

    # --- Part 12: deeper diagnostic ---
    {"id": "Q06", "category": "diagnostic",
     "text": "Which sectors saw the largest increase in Stage 2 exposure "
             "over the latest year?",
     "owner": "COCKPIT", "mode": "DATA_ANALYSIS",
     "measures": ["ead_reported"], "group": ["sector_name"],
     "aggregation": "sum", "periods": ["latest", "year_ago"],
     "chart": BAR, "chart_reason": "a ranked movement compares as bars",
     "insight": ["entering and exiting sectors are kept"]},
    {"id": "Q07", "category": "diagnostic",
     "text": "Which sectors had ECL grow faster than EAD in the latest "
             "quarter?",
     "owner": "COCKPIT", "mode": "DATA_ANALYSIS",
     "measures": ["ecl_reported", "ead_reported"], "group": ["sector_name"],
     "aggregation": "sum", "periods": ["latest", "prior"],
     "chart": BAR, "chart_reason": "two rates per sector compare as paired "
                                   "bars; the gap is the finding",
     "insight": ["zero-base growth is undefined, not 100%"]},
    {"id": "Q08", "category": "diagnostic",
     "text": "Which sectors contributed most to the change in total ECL from "
             "the previous quarter?",
     "owner": "COCKPIT", "mode": "DATA_ANALYSIS",
     "measures": ["ecl_reported"], "group": ["sector_name"],
     "aggregation": "sum", "periods": ["latest", "prior"],
     "chart": WATERFALL, "chart_reason": "the parts sum exactly to the whole "
                                         "movement, which is what a bridge is "
                                         "for",
     "insight": ["contributions reconcile to the book delta"]},
    {"id": "Q09", "category": "diagnostic",
     "text": "Which borrowers were downgraded and also moved into Stage 2 in "
             "the latest quarter? How much EAD and ECL do they represent?",
     "owner": "COCKPIT", "mode": "DATA_ANALYSIS",
     "measures": ["rating_rank", "ifrs9_stage", "ead_reported",
                  "ecl_reported"],
     "group": ["borrower_id"], "aggregation": "sum",
     "periods": ["latest", "prior"],
     "chart": NONE, "chart_reason": "an intersection of two conditions is a "
                                    "short list, possibly empty",
     "insight": ["say plainly when the intersection is empty"]},
    {"id": "Q10", "category": "diagnostic",
     "text": "Which sectors had deterioration in collateral coverage "
             "together with an increase in recorded ECL?",
     "owner": "COCKPIT", "mode": "DATA_ANALYSIS",
     "measures": ["collateral_coverage_ratio", "ecl_reported"],
     "group": ["sector_name"], "aggregation": "sum",
     "periods": ["latest", "prior"],
     "chart": NONE, "chart_reason": "two movements per sector on different "
                                    "scales; the table is honest, a dual "
                                    "axis is not",
     "insight": ["coincides with, never caused by"]},

    # --- Part 13: diagnostic + remediation ---
    {"id": "Q11", "category": "remediation",
     "text": "For the sector with the largest ECL increase this quarter, "
             "show the five borrowers contributing most to that increase and "
             "tell me what I should review next.",
     "owner": "COCKPIT", "mode": "DATA_ANALYSIS",
     "measures": ["ecl_reported"], "group": ["sector_name", "borrower_id"],
     "aggregation": "sum", "periods": ["latest", "prior"],
     "chart": BAR, "chart_reason": "five named contributors to one movement",
     "insight": ["review steps are evidence-backed"],
     "requires_review_actions": True},
    {"id": "Q12", "category": "remediation",
     "text": "Prioritise borrowers with covenant breaches, material EAD and "
             "rating deterioration. Explain why each deserves review and "
             "what evidence should be checked.",
     "owner": "COCKPIT", "mode": "DATA_ANALYSIS",
     "measures": ["breach_date", "ead_reported", "rating_rank"],
     "group": ["borrower_id"], "aggregation": "sum",
     "periods": ["latest", "prior"],
     "chart": NONE, "chart_reason": "a prioritised review list is a table",
     "insight": ["the prioritisation rule is stated, not opaque"],
     "requires_review_actions": True},
    {"id": "Q13", "category": "remediation",
     "text": "Which borrowers combine past-due deterioration, Stage 2 status "
             "and weakening collateral coverage? What should a senior credit "
             "officer investigate next?",
     "owner": "COCKPIT", "mode": "DATA_ANALYSIS",
     "measures": ["days_past_due", "ifrs9_stage",
                  "collateral_coverage_ratio"],
     "group": ["borrower_id"], "aggregation": "sum",
     "periods": ["latest", "prior"],
     "chart": NONE, "chart_reason": "a three-way intersection, possibly "
                                    "empty",
     "insight": ["if none, say none"],
     "requires_review_actions": True},
    {"id": "Q14", "category": "remediation",
     "text": "Which sectors have both rising concentration and rising ECL? "
             "Should any of them be taken into a targeted What-If review?",
     "owner": "COCKPIT", "mode": "DATA_ANALYSIS",
     "measures": ["ead_reported", "ecl_reported"], "group": ["sector_name"],
     "aggregation": "sum", "periods": ["latest", "prior"],
     "chart": NONE, "chart_reason": "two movements and a referral; the "
                                    "recommendation is the output",
     "insight": ["What-If is named as the owner of the hypothetical, and no "
                 "scenario is run here"],
     "requires_review_actions": True, "refers_to": "WHAT_IF"},
    {"id": "Q15", "category": "remediation",
     "text": "Show the borrowers with the largest rating deterioration and "
             "ECL increase over the latest year. What review actions would "
             "you prioritise?",
     "owner": "COCKPIT", "mode": "DATA_ANALYSIS",
     "measures": ["rating_rank", "ecl_reported"], "group": ["borrower_id"],
     "aggregation": "sum", "periods": ["latest", "year_ago"],
     "chart": NONE, "chart_reason": "notches and money on one row read as a "
                                    "table",
     "insight": ["rank by both, not by one"],
     "requires_review_actions": True},

    # --- Part 14: mixed / multi-part ---
    {"id": "Q16", "category": "multi_part",
     "text": "For the latest quarter, show the top five sectors by EAD, "
             "their Stage 2 share and ECL. Compare them with the previous "
             "quarter and tell me which two deserve the most attention.",
     "owner": "COCKPIT", "mode": "DATA_ANALYSIS",
     "measures": ["ead_reported", "ecl_reported", "ifrs9_stage"],
     "group": ["sector_name"], "aggregation": "sum",
     "periods": ["latest", "prior"],
     "chart": BAR, "chart_reason": "five sectors on one measure; the other "
                                   "columns belong in the table",
     "insight": ["names exactly two and says why"], "parts": 3},
    {"id": "Q17", "category": "multi_part",
     "text": "For Construction, show EAD, ECL and Stage 2 share in the "
             "latest quarter, compare each with a year ago, then show the "
             "five borrowers carrying the most ECL.",
     "owner": "COCKPIT", "mode": "DATA_ANALYSIS",
     "measures": ["ead_reported", "ecl_reported", "ifrs9_stage"],
     "group": ["sector_name", "borrower_id"], "aggregation": "sum",
     "periods": ["latest", "year_ago"], "filters": {"sector": "Construction"},
     "chart": NONE, "chart_reason": "three KPIs and a five-row list; a chart "
                                    "of three numbers is decoration",
     "insight": ["the sector filter holds across all three parts"],
     "parts": 3},
    {"id": "Q18", "category": "multi_part",
     "text": "For Information Technology, compare covenant-breach exposure, "
             "collateral coverage and ECL with the previous quarter and a "
             "year ago. Which borrowers matter most?",
     "owner": "COCKPIT", "mode": "DATA_ANALYSIS",
     "measures": ["breach_date", "collateral_coverage_ratio",
                  "ecl_reported"],
     "group": ["sector_name", "borrower_id"], "aggregation": "sum",
     "periods": ["latest", "prior", "year_ago"],
     "filters": {"sector": "Information Technology"},
     "chart": NONE, "chart_reason": "three measures across three periods is a "
                                    "table; charting it would need three "
                                    "charts",
     "insight": ["no causal claim between the three"], "parts": 4},
    {"id": "Q19", "category": "multi_part",
     "text": "Give me the latest-quarter portfolio EAD, recorded ECL, "
             "ECL/EAD and Stage 2 share, show how each changed "
             "quarter-on-quarter, and identify the largest sector and "
             "borrower ECL contributors.",
     "owner": "COCKPIT", "mode": "DATA_ANALYSIS",
     "measures": ["ead_reported", "ecl_reported", "ifrs9_stage"],
     "group": ["sector_name", "borrower_id"], "aggregation": "sum",
     "periods": ["latest", "prior"],
     "chart": NONE, "chart_reason": "four KPIs with movements is a KPI table; "
                                    "a chart of four scalars is decoration",
     "insight": ["names the largest sector AND the largest borrower"],
     "parts": 3},
    {"id": "Q20", "category": "multi_part",
     "text": "Which sectors deteriorated on at least two of these measures "
             "over the latest quarter: ECL, Stage 2 share, rating quality "
             "and past-due exposure? Show the evidence and rank the result.",
     "owner": "COCKPIT", "mode": "DATA_ANALYSIS",
     "measures": ["ecl_reported", "ifrs9_stage", "rating_rank",
                  "days_past_due"],
     "group": ["sector_name"], "aggregation": "sum",
     "periods": ["latest", "prior"],
     "chart": NONE, "chart_reason": "a count of measures with the evidence "
                                    "behind each is a table",
     "insight": ["the inclusion rule is stated, not an opaque score"],
     "parts": 2},
]

BY_ID = {q["id"]: q for q in QUESTIONS}


# ---- LAYER A: the oracle ------------------------------------------------

def _sector_totals(quarter: str, release_id: str = "") -> pd.DataFrame:
    slice_ = _facility(release_id)
    slice_ = slice_[slice_["reporting_quarter"] == quarter]
    grouped = slice_.groupby("sector_name", observed=True).agg(
        ead=("ead_reported", "sum"), ecl=("ecl_reported", "sum"),
        facilities=("facility_id", "count"))
    stage2 = slice_[slice_["ifrs9_stage"] == 2].groupby(
        "sector_name", observed=True)["ead_reported"].sum()
    grouped["stage2_ead"] = stage2.reindex(grouped.index).fillna(0.0)
    grouped["stage2_share"] = grouped["stage2_ead"] / grouped["ead"]
    grouped["coverage"] = grouped["ecl"] / grouped["ead"]
    return grouped.reset_index()


def _borrower_totals(quarter: str, release_id: str = "") -> pd.DataFrame:
    slice_ = _facility(release_id)
    slice_ = slice_[slice_["reporting_quarter"] == quarter]
    grouped = slice_.groupby(["borrower_id", "borrower_name", "sector_name"],
                             observed=True).agg(
        ead=("ead_reported", "sum"), ecl=("ecl_reported", "sum"),
        worst_stage=("ifrs9_stage", "max"),
        max_dpd=("days_past_due", "max")).reset_index()
    return grouped


def _rating_at(quarter: str, release_id: str = "") -> pd.DataFrame:
    ratings = _borrower_ratings(release_id)
    return ratings[ratings["reporting_quarter"] == quarter][
        ["borrower_id", "risk_rating", "rating_rank"]]


def _q01(release_id: str) -> dict[str, Any]:
    period = periods(release_id)["latest"]
    totals = _sector_totals(period, release_id).sort_values(
        ["ead", "sector_name"], ascending=[False, True])
    rows = [{"sector_name": r.sector_name, "ead": float(r.ead)}
            for r in totals.itertuples()]
    total = sum(r["ead"] for r in rows)
    return {"period": period, "rows": rows, "total_ead": total,
            "top_sector": rows[0]["sector_name"],
            "top_share": rows[0]["ead"] / total, "row_count": len(rows)}


def _q02(release_id: str) -> dict[str, Any]:
    period = periods(release_id)["latest"]
    borrowers = _borrower_totals(period, release_id).sort_values(
        ["ecl", "borrower_id"], ascending=[False, True]).head(10)
    rows = [{"borrower_id": r.borrower_id, "borrower_name": r.borrower_name,
             "sector_name": r.sector_name, "stage": int(r.worst_stage),
             "ead": float(r.ead), "ecl": float(r.ecl)}
            for r in borrowers.itertuples()]
    book = _sector_totals(period, release_id)["ecl"].sum()
    return {"period": period, "rows": rows, "row_count": len(rows),
            "book_ecl": float(book),
            "top10_share": sum(r["ecl"] for r in rows) / float(book)}


def _q03(release_id: str) -> dict[str, Any]:
    period = periods(release_id)["latest"]
    totals = _sector_totals(period, release_id)
    stage2_total = float(totals["stage2_ead"].sum())
    rows = [{"sector_name": r.sector_name, "stage2_ead": float(r.stage2_ead),
             "share": float(r.stage2_ead) / stage2_total if stage2_total else
             None}
            for r in totals.itertuples() if float(r.stage2_ead) > 0]
    rows.sort(key=lambda row: (-row["stage2_ead"], row["sector_name"]))
    return {"period": period, "rows": rows, "row_count": len(rows),
            "total_stage2_ead": stage2_total,
            "shares_sum": sum(r["share"] for r in rows) if rows else 0.0}


def _q04(release_id: str) -> dict[str, Any]:
    window = periods(release_id)["last_four"]
    covenant = _frame("cockpit_covenant_quarter", release_id)
    slice_ = covenant[covenant["reporting_quarter"].isin(window)]
    breached = slice_[slice_["breach_date"].notna()]
    grouped = breached.groupby(["borrower_id", "reporting_quarter"],
                               observed=True).agg(
        breaches=("covenant_id", "nunique"),
        waived=("waiver_flag", "max")).reset_index()
    rows = [{"borrower_id": r.borrower_id, "quarter": r.reporting_quarter,
             "breaches": int(r.breaches), "waiver": bool(r.waived)}
            for r in grouped.sort_values(
                ["borrower_id", "reporting_quarter"]).itertuples()]
    return {"periods": window, "rows": rows, "row_count": len(rows),
            "borrowers": sorted({r["borrower_id"] for r in rows}),
            "unwaived": sorted({r["borrower_id"] for r in rows
                                if not r["waiver"]})}


def _downgrades(new_q: str, old_q: str, release_id: str) -> pd.DataFrame:
    """A downgrade is a rating_rank that got WORSE. A higher rank is weaker."""
    now, then = _rating_at(new_q, release_id), _rating_at(old_q, release_id)
    joined = now.merge(then, on="borrower_id", suffixes=("_now", "_then"))
    return joined[joined["rating_rank_now"] > joined["rating_rank_then"]]


def _q05(release_id: str) -> dict[str, Any]:
    period = periods(release_id)
    moved = _downgrades(period["latest"], period["prior"], release_id)
    totals = _borrower_totals(period["latest"], release_id).set_index(
        "borrower_id")
    rows = []
    for row in moved.itertuples():
        if row.borrower_id not in totals.index:
            continue
        entry = totals.loc[row.borrower_id]
        rows.append({"borrower_id": row.borrower_id,
                     "previous_rating": row.risk_rating_then,
                     "current_rating": row.risk_rating_now,
                     "notches": int(row.rating_rank_now - row.rating_rank_then),
                     "ead": float(entry["ead"]), "ecl": float(entry["ecl"])})
    rows.sort(key=lambda r: (-r["notches"], -r["ead"], r["borrower_id"]))
    return {"period": period["latest"], "comparison": period["prior"],
            "rows": rows, "row_count": len(rows),
            "ead_downgraded": sum(r["ead"] for r in rows),
            "ecl_downgraded": sum(r["ecl"] for r in rows)}


def _q06(release_id: str) -> dict[str, Any]:
    period = periods(release_id)
    now = _sector_totals(period["latest"], release_id).set_index("sector_name")
    then = _sector_totals(period["year_ago"], release_id).set_index(
        "sector_name")
    rows = []
    for sector in sorted(set(now.index) | set(then.index)):
        current = float(now["stage2_ead"].get(sector, 0.0))
        prior = float(then["stage2_ead"].get(sector, 0.0))
        rows.append({
            "sector_name": sector, "prior": prior, "current": current,
            "change": current - prior,
            "status": ("entered" if sector not in then.index else
                       "exited" if sector not in now.index else "present")})
    rows.sort(key=lambda r: (-r["change"], r["sector_name"]))
    return {"period": period["latest"], "comparison": period["year_ago"],
            "rows": rows, "row_count": len(rows),
            "sectors_in_either": len(rows),
            "total_change": sum(r["change"] for r in rows)}


def _growth(new: float, old: float) -> float | None:
    """A zero base has no growth RATE. Undefined is the honest answer."""
    return None if old == 0 else (new - old) / old


def _q07(release_id: str) -> dict[str, Any]:
    period = periods(release_id)
    now = _sector_totals(period["latest"], release_id).set_index("sector_name")
    then = _sector_totals(period["prior"], release_id).set_index("sector_name")
    rows, undefined = [], []
    for sector in sorted(set(now.index) & set(then.index)):
        ecl_growth = _growth(float(now["ecl"][sector]),
                             float(then["ecl"][sector]))
        ead_growth = _growth(float(now["ead"][sector]),
                             float(then["ead"][sector]))
        if ecl_growth is None or ead_growth is None:
            undefined.append(sector)
            continue
        if ecl_growth > ead_growth:
            rows.append({"sector_name": sector, "ecl_growth": ecl_growth,
                         "ead_growth": ead_growth,
                         "gap": ecl_growth - ead_growth})
    rows.sort(key=lambda r: (-r["gap"], r["sector_name"]))
    return {"period": period["latest"], "comparison": period["prior"],
            "rows": rows, "row_count": len(rows),
            "growth_undefined": undefined}


def _q08(release_id: str) -> dict[str, Any]:
    period = periods(release_id)
    now = _sector_totals(period["latest"], release_id).set_index("sector_name")
    then = _sector_totals(period["prior"], release_id).set_index("sector_name")
    rows = []
    for sector in sorted(set(now.index) | set(then.index)):
        current = float(now["ecl"].get(sector, 0.0))
        prior = float(then["ecl"].get(sector, 0.0))
        rows.append({"sector_name": sector, "prior": prior,
                     "current": current, "contribution": current - prior})
    rows.sort(key=lambda r: (r["contribution"], r["sector_name"]))
    book_delta = float(now["ecl"].sum()) - float(then["ecl"].sum())
    return {"period": period["latest"], "comparison": period["prior"],
            "rows": rows, "row_count": len(rows),
            "book_delta": book_delta,
            "contributions_sum": sum(r["contribution"] for r in rows)}


def _q09(release_id: str) -> dict[str, Any]:
    period = periods(release_id)
    moved = set(_downgrades(period["latest"], period["prior"],
                            release_id)["borrower_id"])
    now = _borrower_totals(period["latest"], release_id).set_index(
        "borrower_id")
    then = _borrower_totals(period["prior"], release_id).set_index(
        "borrower_id")
    rows = []
    for borrower in sorted(moved):
        if borrower not in now.index or borrower not in then.index:
            continue
        if int(now.loc[borrower, "worst_stage"]) >= 2 > int(
                then.loc[borrower, "worst_stage"]):
            rows.append({"borrower_id": borrower,
                         "ead": float(now.loc[borrower, "ead"]),
                         "ecl": float(now.loc[borrower, "ecl"])})
    return {"period": period["latest"], "comparison": period["prior"],
            "rows": rows, "row_count": len(rows),
            "total_ead": sum(r["ead"] for r in rows),
            "total_ecl": sum(r["ecl"] for r in rows),
            "empty": not rows}


def _weighted_collateral(quarter: str, release_id: str) -> pd.Series:
    """Exposure with recorded cover below 1x, as a share. Bounded and robust."""
    slice_ = _facility(release_id)
    slice_ = slice_[slice_["reporting_quarter"] == quarter]
    total = slice_.groupby("sector_name", observed=True)["ead_reported"].sum()
    uncovered = slice_[
        slice_["collateral_coverage_ratio"].notna()
        & (slice_["collateral_coverage_ratio"] < 1)].groupby(
        "sector_name", observed=True)["ead_reported"].sum()
    return (uncovered.reindex(total.index).fillna(0.0) / total)


def _q10(release_id: str) -> dict[str, Any]:
    period = periods(release_id)
    now_unc = _weighted_collateral(period["latest"], release_id)
    then_unc = _weighted_collateral(period["prior"], release_id)
    now = _sector_totals(period["latest"], release_id).set_index("sector_name")
    then = _sector_totals(period["prior"], release_id).set_index("sector_name")
    rows = []
    for sector in sorted(set(now.index) & set(then.index)
                         & set(now_unc.index) & set(then_unc.index)):
        cover_move = float(now_unc[sector] - then_unc[sector])
        ecl_move = float(now["ecl"][sector] - then["ecl"][sector])
        if cover_move > 0 and ecl_move > 0:
            rows.append({"sector_name": sector,
                         "uncovered_share_change": cover_move,
                         "ecl_change": ecl_move})
    rows.sort(key=lambda r: (-r["ecl_change"], r["sector_name"]))
    return {"period": period["latest"], "comparison": period["prior"],
            "rows": rows, "row_count": len(rows)}


def _q11(release_id: str) -> dict[str, Any]:
    movement = _q08(release_id)
    rising = [r for r in movement["rows"] if r["contribution"] > 0]
    if not rising:
        return {"period": movement["period"], "sector": None, "rows": [],
                "row_count": 0, "empty": True}
    target = max(rising, key=lambda r: (r["contribution"], r["sector_name"]))
    sector = target["sector_name"]
    period = periods(release_id)
    now = _borrower_totals(period["latest"], release_id)
    then = _borrower_totals(period["prior"], release_id)
    now = now[now["sector_name"] == sector].set_index("borrower_id")
    then = then[then["sector_name"] == sector].set_index("borrower_id")
    rows = []
    for borrower in sorted(set(now.index) | set(then.index)):
        current = float(now["ecl"].get(borrower, 0.0))
        prior = float(then["ecl"].get(borrower, 0.0))
        rows.append({"borrower_id": borrower, "contribution": current - prior,
                     "ecl": current})
    rows.sort(key=lambda r: (-r["contribution"], r["borrower_id"]))
    top = rows[:5]
    return {"period": period["latest"], "comparison": period["prior"],
            "sector": sector, "sector_contribution": target["contribution"],
            "rows": top, "row_count": len(top), "empty": False,
            "top5_share": (sum(r["contribution"] for r in top)
                           / target["contribution"]
                           if target["contribution"] else None)}


def _q12(release_id: str) -> dict[str, Any]:
    period = periods(release_id)
    covenant = _frame("cockpit_covenant_quarter", release_id)
    breached = covenant[(covenant["reporting_quarter"] == period["latest"])
                        & covenant["breach_date"].notna()]
    names = set(breached["borrower_id"])
    downgraded = dict(
        (row.borrower_id, int(row.rating_rank_now - row.rating_rank_then))
        for row in _downgrades(period["latest"], period["prior"],
                               release_id).itertuples())
    totals = _borrower_totals(period["latest"], release_id).set_index(
        "borrower_id")
    rows = []
    for borrower in sorted(names):
        if borrower not in totals.index:
            continue
        rows.append({"borrower_id": borrower,
                     "ead": float(totals.loc[borrower, "ead"]),
                     "ecl": float(totals.loc[borrower, "ecl"]),
                     "notches_down": downgraded.get(borrower, 0),
                     "breach": True})
    # Published rule: a downgrade outranks none, then exposure. Stated, not
    # an opaque composite.
    rows.sort(key=lambda r: (-r["notches_down"], -r["ead"], r["borrower_id"]))
    return {"period": period["latest"], "comparison": period["prior"],
            "rows": rows, "row_count": len(rows),
            "with_downgrade": [r["borrower_id"] for r in rows
                               if r["notches_down"] > 0],
            "rule": ("breach in the latest quarter, then rating notches "
                     "down, then exposure")}


def _q13(release_id: str) -> dict[str, Any]:
    period = periods(release_id)
    now = _borrower_totals(period["latest"], release_id).set_index(
        "borrower_id")
    then = _borrower_totals(period["prior"], release_id).set_index(
        "borrower_id")
    facility = _facility(release_id)
    def uncovered(quarter):
        slice_ = facility[facility["reporting_quarter"] == quarter]
        total = slice_.groupby("borrower_id", observed=True)[
            "ead_reported"].sum()
        low = slice_[slice_["collateral_coverage_ratio"].notna()
                     & (slice_["collateral_coverage_ratio"] < 1)].groupby(
            "borrower_id", observed=True)["ead_reported"].sum()
        return (low.reindex(total.index).fillna(0.0) / total)
    now_unc, then_unc = uncovered(period["latest"]), uncovered(period["prior"])
    rows = []
    for borrower in sorted(set(now.index) & set(then.index)):
        dpd_worse = float(now.loc[borrower, "max_dpd"] or 0) > float(
            then.loc[borrower, "max_dpd"] or 0)
        stage2 = int(now.loc[borrower, "worst_stage"]) >= 2
        cover_worse = float(now_unc.get(borrower, 0.0)) > float(
            then_unc.get(borrower, 0.0))
        if dpd_worse and stage2 and cover_worse:
            rows.append({"borrower_id": borrower,
                         "ead": float(now.loc[borrower, "ead"]),
                         "ecl": float(now.loc[borrower, "ecl"])})
    return {"period": period["latest"], "comparison": period["prior"],
            "rows": rows, "row_count": len(rows), "empty": not rows}


def _q14(release_id: str) -> dict[str, Any]:
    period = periods(release_id)
    now = _sector_totals(period["latest"], release_id).set_index("sector_name")
    then = _sector_totals(period["prior"], release_id).set_index("sector_name")
    book_now, book_then = float(now["ead"].sum()), float(then["ead"].sum())
    rows = []
    for sector in sorted(set(now.index) & set(then.index)):
        share_move = (float(now["ead"][sector]) / book_now
                      - float(then["ead"][sector]) / book_then)
        ecl_move = float(now["ecl"][sector]) - float(then["ecl"][sector])
        if share_move > 0 and ecl_move > 0:
            rows.append({"sector_name": sector,
                         "concentration_change": share_move,
                         "ecl_change": ecl_move})
    rows.sort(key=lambda r: (-r["ecl_change"], r["sector_name"]))
    return {"period": period["latest"], "comparison": period["prior"],
            "rows": rows, "row_count": len(rows), "refer_to": "WHAT_IF"}


def _q15(release_id: str) -> dict[str, Any]:
    period = periods(release_id)
    moved = _downgrades(period["latest"], period["year_ago"], release_id)
    now = _borrower_totals(period["latest"], release_id).set_index(
        "borrower_id")
    then = _borrower_totals(period["year_ago"], release_id).set_index(
        "borrower_id")
    rows = []
    for row in moved.itertuples():
        borrower = row.borrower_id
        if borrower not in now.index:
            continue
        ecl_change = float(now.loc[borrower, "ecl"]) - float(
            then["ecl"].get(borrower, 0.0))
        if ecl_change <= 0:
            continue
        rows.append({"borrower_id": borrower,
                     "notches_down": int(row.rating_rank_now
                                         - row.rating_rank_then),
                     "previous_rating": row.risk_rating_then,
                     "current_rating": row.risk_rating_now,
                     "ecl_change": ecl_change,
                     "ecl": float(now.loc[borrower, "ecl"])})
    rows.sort(key=lambda r: (-r["notches_down"], -r["ecl_change"],
                             r["borrower_id"]))
    return {"period": period["latest"], "comparison": period["year_ago"],
            "rows": rows, "row_count": len(rows)}


def _q16(release_id: str) -> dict[str, Any]:
    period = periods(release_id)
    now = _sector_totals(period["latest"], release_id).sort_values(
        ["ead", "sector_name"], ascending=[False, True]).head(5)
    then = _sector_totals(period["prior"], release_id).set_index("sector_name")
    rows = []
    for row in now.itertuples():
        sector = row.sector_name
        rows.append({
            "sector_name": sector, "ead": float(row.ead),
            "ecl": float(row.ecl), "stage2_share": float(row.stage2_share),
            "ead_prior": float(then["ead"].get(sector, 0.0)),
            "ecl_prior": float(then["ecl"].get(sector, 0.0)),
            "stage2_share_prior": float(then["stage2_share"].get(sector, 0.0)),
        })
    for row in rows:
        row["ecl_change"] = row["ecl"] - row["ecl_prior"]
        row["stage2_share_change"] = (row["stage2_share"]
                                      - row["stage2_share_prior"])
    # The two that deserve attention: deterioration on either measure, worst
    # first. The rule is published with the answer.
    ranked = sorted(rows, key=lambda r: (-(max(r["ecl_change"], 0.0)
                                           + max(r["stage2_share_change"], 0.0)
                                           * r["ead"]), r["sector_name"]))
    return {"period": period["latest"], "comparison": period["prior"],
            "rows": rows, "row_count": len(rows),
            "attention": [r["sector_name"] for r in ranked[:2]],
            "rule": "deterioration in ECL or in Stage 2 share, weighted by "
                    "exposure"}


def _q17(release_id: str) -> dict[str, Any]:
    period = periods(release_id)
    sector = "Construction"
    now = _sector_totals(period["latest"], release_id).set_index("sector_name")
    then = _sector_totals(period["year_ago"], release_id).set_index(
        "sector_name")
    borrowers = _borrower_totals(period["latest"], release_id)
    borrowers = borrowers[borrowers["sector_name"] == sector].sort_values(
        ["ecl", "borrower_id"], ascending=[False, True]).head(5)
    return {
        "period": period["latest"], "comparison": period["year_ago"],
        "sector": sector,
        "kpis": {
            "ead": float(now["ead"][sector]),
            "ecl": float(now["ecl"][sector]),
            "stage2_share": float(now["stage2_share"][sector]),
            "ead_year_ago": float(then["ead"][sector]),
            "ecl_year_ago": float(then["ecl"][sector]),
            "stage2_share_year_ago": float(then["stage2_share"][sector])},
        "rows": [{"borrower_id": r.borrower_id, "ecl": float(r.ecl),
                  "ead": float(r.ead)} for r in borrowers.itertuples()],
        "row_count": int(len(borrowers))}


def _q18(release_id: str) -> dict[str, Any]:
    period = periods(release_id)
    sector = "Information Technology"
    covenant = _frame("cockpit_covenant_quarter", release_id)
    out: dict[str, Any] = {"sector": sector, "periods": {}}
    for label, quarter in (("latest", period["latest"]),
                           ("prior", period["prior"]),
                           ("year_ago", period["year_ago"])):
        borrowers = _borrower_totals(quarter, release_id)
        here = borrowers[borrowers["sector_name"] == sector]
        names = set(here["borrower_id"])
        breached = covenant[(covenant["reporting_quarter"] == quarter)
                            & covenant["breach_date"].notna()
                            & covenant["borrower_id"].isin(names)]
        breach_ead = float(here[here["borrower_id"].isin(
            set(breached["borrower_id"]))]["ead"].sum())
        unc = _weighted_collateral(quarter, release_id)
        out["periods"][label] = {
            "quarter": quarter,
            "breach_ead": breach_ead,
            "ecl": float(here["ecl"].sum()),
            "uncovered_share": float(unc.get(sector, 0.0))}
    latest = _borrower_totals(period["latest"], release_id)
    latest = latest[latest["sector_name"] == sector].sort_values(
        ["ecl", "borrower_id"], ascending=[False, True]).head(5)
    out["rows"] = [{"borrower_id": r.borrower_id, "ecl": float(r.ecl),
                    "ead": float(r.ead)} for r in latest.itertuples()]
    out["row_count"] = int(len(latest))
    out["period"] = period["latest"]
    return out


def _q19(release_id: str) -> dict[str, Any]:
    period = periods(release_id)
    now = _sector_totals(period["latest"], release_id)
    then = _sector_totals(period["prior"], release_id)

    def book(frame):
        ead, ecl = float(frame["ead"].sum()), float(frame["ecl"].sum())
        stage2 = float(frame["stage2_ead"].sum())
        return {"ead": ead, "ecl": ecl, "coverage": ecl / ead,
                "stage2_share": stage2 / ead}

    current, prior = book(now), book(then)
    top_sector = now.sort_values(["ecl", "sector_name"],
                                 ascending=[False, True]).iloc[0]
    borrowers = _borrower_totals(period["latest"], release_id).sort_values(
        ["ecl", "borrower_id"], ascending=[False, True]).iloc[0]
    return {
        "period": period["latest"], "comparison": period["prior"],
        "kpis": current, "kpis_prior": prior,
        "changes": {k: current[k] - prior[k] for k in current},
        "top_sector": {"sector_name": top_sector.sector_name,
                       "ecl": float(top_sector.ecl)},
        "top_borrower": {"borrower_id": borrowers.borrower_id,
                         "ecl": float(borrowers.ecl)},
        "row_count": 1}


def _q20(release_id: str) -> dict[str, Any]:
    """Deterioration on at least two of four measures. The rule is published."""
    period = periods(release_id)
    now = _sector_totals(period["latest"], release_id).set_index("sector_name")
    then = _sector_totals(period["prior"], release_id).set_index("sector_name")
    facility = _facility(release_id)

    def weighted_rank(quarter):
        slice_ = facility[facility["reporting_quarter"] == quarter]
        ratings = _rating_at(quarter, release_id).set_index("borrower_id")
        merged = slice_.join(ratings, on="borrower_id")
        rated = merged[merged["rating_rank"].notna()]
        if rated.empty:
            return pd.Series(dtype=float)
        weight = rated.groupby("sector_name", observed=True).apply(
            lambda d: float((d["ead_reported"] * d["rating_rank"]).sum()
                            / d["ead_reported"].sum()),
            include_groups=False)
        return weight

    def past_due_share(quarter):
        slice_ = facility[facility["reporting_quarter"] == quarter]
        total = slice_.groupby("sector_name", observed=True)[
            "ead_reported"].sum()
        overdue = slice_[slice_["days_past_due"].fillna(0) > 0].groupby(
            "sector_name", observed=True)["ead_reported"].sum()
        return overdue.reindex(total.index).fillna(0.0) / total

    rank_now, rank_then = weighted_rank(period["latest"]), weighted_rank(
        period["prior"])
    dpd_now, dpd_then = past_due_share(period["latest"]), past_due_share(
        period["prior"])

    rows = []
    for sector in sorted(set(now.index) & set(then.index)):
        measures = {
            "ecl": float(now["ecl"][sector] - then["ecl"][sector]),
            "stage2_share": float(now["stage2_share"][sector]
                                  - then["stage2_share"][sector]),
            "rating_rank": (float(rank_now[sector] - rank_then[sector])
                            if sector in rank_now and sector in rank_then
                            else None),
            "past_due_share": float(dpd_now[sector] - dpd_then[sector]),
        }
        worse = sorted(k for k, v in measures.items()
                       if v is not None and v > 0)
        missing = sorted(k for k, v in measures.items() if v is None)
        if len(worse) >= 2:
            rows.append({"sector_name": sector, "deteriorated_on": worse,
                         "count": len(worse), "measures": measures,
                         "missing_measures": missing})
    rows.sort(key=lambda r: (-r["count"], r["sector_name"]))
    return {"period": period["latest"], "comparison": period["prior"],
            "rows": rows, "row_count": len(rows),
            "rule": ("a measure counts as deteriorated when it moved in the "
                     "adverse direction between the two quarters; a sector "
                     "qualifies on two or more, and a measure with no value "
                     "is reported as missing rather than counted")}


_ORACLES = {f"Q{i:02d}": globals()[f"_q{i:02d}"] for i in range(1, 21)}


def oracle(question_id: str, release_id: str = "") -> dict[str, Any]:
    """The expected answer, computed from the release. Never hard-coded."""
    return _ORACLES[question_id](release_id or RELEASE)


__all__ = ["BY_ID", "QUESTIONS", "RELEASE", "oracle", "periods", "quarters"]
