"""
LAYER B: SQL authored against the catalogue by a reader of the question.

Not generated by the product, and not derived from the oracle. In the harness
it stands in for what Opus would write, so that a disagreement between this
and `uat_question_bank.oracle()` means one of the two is wrong rather than
that the product agrees with itself.

Every statement uses the canonical fields the semantics layer publishes:
`ead_reported`, `ecl_reported`, `ifrs9_stage`, `sector_name`, `borrower_id`,
`days_past_due`, `collateral_coverage_ratio`, and `rating_rank` from the
borrower-grain rating relation.
"""

from __future__ import annotations

from typing import Any

SECTOR_TOTALS = """
SELECT sector_name,
       SUM(ead_reported) AS ead,
       SUM(ecl_reported) AS ecl,
       SUM(CASE WHEN ifrs9_stage = 2 THEN ead_reported ELSE 0 END)
           AS stage2_ead
FROM cockpit_facility_quarter
WHERE reporting_quarter = $q AND sector_name IS NOT NULL
GROUP BY 1
"""

BORROWER_TOTALS = """
SELECT borrower_id, ANY_VALUE(borrower_name) AS borrower_name,
       ANY_VALUE(sector_name) AS sector_name,
       SUM(ead_reported) AS ead, SUM(ecl_reported) AS ecl,
       MAX(ifrs9_stage) AS worst_stage, MAX(days_past_due) AS max_dpd
FROM cockpit_facility_quarter
WHERE reporting_quarter = $q AND sector_name IS NOT NULL
GROUP BY 1
"""


def sql_for(question_id: str) -> str:
    """One statement per question. Parameters are bound, never interpolated."""
    return _SQL[question_id]


_SQL: dict[str, str] = {
    "Q01": """
SELECT sector_name, SUM(ead_reported) AS ead
FROM cockpit_facility_quarter
WHERE reporting_quarter = $q AND sector_name IS NOT NULL
GROUP BY 1
ORDER BY ead DESC, sector_name ASC
""",
    "Q02": """
SELECT borrower_id,
       ANY_VALUE(borrower_name) AS borrower_name,
       ANY_VALUE(sector_name)   AS sector_name,
       MAX(ifrs9_stage)         AS stage,
       SUM(ead_reported)        AS ead,
       SUM(ecl_reported)        AS ecl
FROM cockpit_facility_quarter
WHERE reporting_quarter = $q AND sector_name IS NOT NULL
GROUP BY 1
ORDER BY ecl DESC, borrower_id ASC
LIMIT 10
""",
    "Q03": """
WITH s2 AS (
  SELECT sector_name, SUM(ead_reported) AS stage2_ead
  FROM cockpit_facility_quarter
  WHERE reporting_quarter = $q AND ifrs9_stage = 2 AND sector_name IS NOT NULL
  GROUP BY 1)
SELECT sector_name, stage2_ead,
       stage2_ead / SUM(stage2_ead) OVER () AS share
FROM s2
WHERE stage2_ead > 0
ORDER BY stage2_ead DESC, sector_name ASC
""",
    "Q04": """
SELECT borrower_id,
       reporting_quarter AS quarter,
       COUNT(DISTINCT covenant_id) AS breaches,
       MAX(CASE WHEN waiver_flag THEN 1 ELSE 0 END) AS waiver
FROM cockpit_covenant_quarter
WHERE reporting_quarter IN ($q1, $q2, $q3, $q4)
  AND breach_date IS NOT NULL
GROUP BY 1, 2
ORDER BY borrower_id ASC, quarter ASC
""",
    "Q05": """
WITH now_r AS (
  SELECT borrower_id, risk_rating, rating_rank
  FROM cockpit_rating_ratio_quarter WHERE reporting_quarter = $q),
prev_r AS (
  SELECT borrower_id, risk_rating, rating_rank
  FROM cockpit_rating_ratio_quarter WHERE reporting_quarter = $p),
totals AS (
  SELECT borrower_id, SUM(ead_reported) AS ead, SUM(ecl_reported) AS ecl
  FROM cockpit_facility_quarter
  WHERE reporting_quarter = $q AND sector_name IS NOT NULL GROUP BY 1)
SELECT n.borrower_id,
       p.risk_rating AS previous_rating,
       n.risk_rating AS current_rating,
       CAST(n.rating_rank - p.rating_rank AS INTEGER) AS notches,
       t.ead, t.ecl
FROM now_r n
JOIN prev_r p ON p.borrower_id = n.borrower_id
JOIN totals t ON t.borrower_id = n.borrower_id
WHERE n.rating_rank > p.rating_rank
ORDER BY notches DESC, ead DESC, n.borrower_id ASC
""",
    "Q06": """
WITH now_s AS (
  SELECT sector_name, SUM(ead_reported) AS s2
  FROM cockpit_facility_quarter
  WHERE reporting_quarter = $q AND ifrs9_stage = 2 AND sector_name IS NOT NULL
  GROUP BY 1),
then_s AS (
  SELECT sector_name, SUM(ead_reported) AS s2
  FROM cockpit_facility_quarter
  WHERE reporting_quarter = $y AND ifrs9_stage = 2 AND sector_name IS NOT NULL
  GROUP BY 1),
present AS (
  SELECT DISTINCT sector_name FROM cockpit_facility_quarter
  WHERE reporting_quarter IN ($q, $y) AND sector_name IS NOT NULL)
SELECT p.sector_name,
       COALESCE(t.s2, 0) AS prior,
       COALESCE(n.s2, 0) AS current,
       COALESCE(n.s2, 0) - COALESCE(t.s2, 0) AS change
FROM present p
LEFT JOIN now_s  n ON n.sector_name = p.sector_name
LEFT JOIN then_s t ON t.sector_name = p.sector_name
ORDER BY change DESC, p.sector_name ASC
""",
    "Q07": """
WITH n AS (SELECT sector_name, SUM(ecl_reported) AS ecl,
                  SUM(ead_reported) AS ead
           FROM cockpit_facility_quarter
           WHERE reporting_quarter = $q AND sector_name IS NOT NULL
           GROUP BY 1),
     p AS (SELECT sector_name, SUM(ecl_reported) AS ecl,
                  SUM(ead_reported) AS ead
           FROM cockpit_facility_quarter
           WHERE reporting_quarter = $p AND sector_name IS NOT NULL
           GROUP BY 1)
SELECT n.sector_name,
       (n.ecl - p.ecl) / p.ecl AS ecl_growth,
       (n.ead - p.ead) / p.ead AS ead_growth,
       (n.ecl - p.ecl) / p.ecl - (n.ead - p.ead) / p.ead AS gap
FROM n JOIN p ON p.sector_name = n.sector_name
WHERE p.ecl <> 0 AND p.ead <> 0
  AND (n.ecl - p.ecl) / p.ecl > (n.ead - p.ead) / p.ead
ORDER BY gap DESC, n.sector_name ASC
""",
    "Q08": """
WITH present AS (
  SELECT DISTINCT sector_name FROM cockpit_facility_quarter
  WHERE reporting_quarter IN ($q, $p) AND sector_name IS NOT NULL),
n AS (SELECT sector_name, SUM(ecl_reported) AS ecl
      FROM cockpit_facility_quarter WHERE reporting_quarter = $q
        AND sector_name IS NOT NULL GROUP BY 1),
o AS (SELECT sector_name, SUM(ecl_reported) AS ecl
      FROM cockpit_facility_quarter WHERE reporting_quarter = $p
        AND sector_name IS NOT NULL GROUP BY 1)
SELECT s.sector_name,
       COALESCE(o.ecl, 0) AS prior,
       COALESCE(n.ecl, 0) AS current,
       COALESCE(n.ecl, 0) - COALESCE(o.ecl, 0) AS contribution
FROM present s
LEFT JOIN n ON n.sector_name = s.sector_name
LEFT JOIN o ON o.sector_name = s.sector_name
ORDER BY contribution ASC, s.sector_name ASC
""",
    "Q09": """
WITH now_r AS (SELECT borrower_id, rating_rank
               FROM cockpit_rating_ratio_quarter WHERE reporting_quarter = $q),
prev_r AS (SELECT borrower_id, rating_rank
           FROM cockpit_rating_ratio_quarter WHERE reporting_quarter = $p),
now_b AS (SELECT borrower_id, SUM(ead_reported) AS ead,
                 SUM(ecl_reported) AS ecl, MAX(ifrs9_stage) AS stage
          FROM cockpit_facility_quarter WHERE reporting_quarter = $q
            AND sector_name IS NOT NULL GROUP BY 1),
prev_b AS (SELECT borrower_id, MAX(ifrs9_stage) AS stage
           FROM cockpit_facility_quarter WHERE reporting_quarter = $p
             AND sector_name IS NOT NULL GROUP BY 1)
SELECT nb.borrower_id, nb.ead, nb.ecl
FROM now_b nb
JOIN prev_b pb ON pb.borrower_id = nb.borrower_id
JOIN now_r nr  ON nr.borrower_id = nb.borrower_id
JOIN prev_r pr ON pr.borrower_id = nb.borrower_id
WHERE nr.rating_rank > pr.rating_rank
  AND nb.stage >= 2 AND pb.stage < 2
ORDER BY nb.borrower_id ASC
""",
    "Q10": """
WITH unc AS (
  SELECT reporting_quarter, sector_name,
         SUM(CASE WHEN collateral_coverage_ratio IS NOT NULL
                    AND collateral_coverage_ratio < 1
                  THEN ead_reported ELSE 0 END) / SUM(ead_reported)
             AS uncovered_share,
         SUM(ecl_reported) AS ecl
  FROM cockpit_facility_quarter
  WHERE reporting_quarter IN ($q, $p) AND sector_name IS NOT NULL
  GROUP BY 1, 2)
SELECT n.sector_name,
       n.uncovered_share - o.uncovered_share AS uncovered_share_change,
       n.ecl - o.ecl AS ecl_change
FROM unc n JOIN unc o
  ON o.sector_name = n.sector_name AND o.reporting_quarter = $p
WHERE n.reporting_quarter = $q
  AND n.uncovered_share > o.uncovered_share
  AND n.ecl > o.ecl
ORDER BY ecl_change DESC, n.sector_name ASC
""",
    "Q11": """
WITH now_b AS (
  SELECT borrower_id, ANY_VALUE(sector_name) AS sector_name,
         SUM(ecl_reported) AS ecl
  FROM cockpit_facility_quarter
  WHERE reporting_quarter = $q AND sector_name IS NOT NULL GROUP BY 1),
prev_b AS (
  SELECT borrower_id, ANY_VALUE(sector_name) AS sector_name,
         SUM(ecl_reported) AS ecl
  FROM cockpit_facility_quarter
  WHERE reporting_quarter = $p AND sector_name IS NOT NULL GROUP BY 1),
moved AS (
  SELECT COALESCE(n.sector_name, o.sector_name) AS sector_name,
         SUM(COALESCE(n.ecl, 0) - COALESCE(o.ecl, 0)) AS contribution
  FROM now_b n FULL OUTER JOIN prev_b o ON o.borrower_id = n.borrower_id
  GROUP BY 1),
target AS (
  SELECT sector_name FROM moved WHERE contribution > 0
  ORDER BY contribution DESC, sector_name ASC LIMIT 1)
SELECT COALESCE(n.borrower_id, o.borrower_id) AS borrower_id,
       COALESCE(n.ecl, 0) - COALESCE(o.ecl, 0) AS contribution,
       COALESCE(n.ecl, 0) AS ecl
FROM now_b n FULL OUTER JOIN prev_b o ON o.borrower_id = n.borrower_id
WHERE COALESCE(n.sector_name, o.sector_name)
        = (SELECT sector_name FROM target)
ORDER BY contribution DESC, borrower_id ASC
LIMIT 5
""",
    "Q12": """
WITH breached AS (
  SELECT DISTINCT borrower_id FROM cockpit_covenant_quarter
  WHERE reporting_quarter = $q AND breach_date IS NOT NULL),
totals AS (
  SELECT borrower_id, SUM(ead_reported) AS ead, SUM(ecl_reported) AS ecl
  FROM cockpit_facility_quarter
  WHERE reporting_quarter = $q AND sector_name IS NOT NULL GROUP BY 1),
now_r AS (SELECT borrower_id, rating_rank FROM cockpit_rating_ratio_quarter
          WHERE reporting_quarter = $q),
prev_r AS (SELECT borrower_id, rating_rank FROM cockpit_rating_ratio_quarter
           WHERE reporting_quarter = $p)
SELECT t.borrower_id, t.ead, t.ecl,
       GREATEST(COALESCE(nr.rating_rank - pr.rating_rank, 0), 0)
           AS notches_down
FROM breached b
JOIN totals t ON t.borrower_id = b.borrower_id
LEFT JOIN now_r  nr ON nr.borrower_id = b.borrower_id
LEFT JOIN prev_r pr ON pr.borrower_id = b.borrower_id
ORDER BY notches_down DESC, t.ead DESC, t.borrower_id ASC
""",
    "Q13": """
WITH b AS (
  SELECT reporting_quarter, borrower_id,
         SUM(ead_reported) AS ead, SUM(ecl_reported) AS ecl,
         MAX(ifrs9_stage) AS worst_stage,
         MAX(days_past_due) AS max_dpd,
         SUM(CASE WHEN collateral_coverage_ratio IS NOT NULL
                    AND collateral_coverage_ratio < 1
                  THEN ead_reported ELSE 0 END) / SUM(ead_reported)
             AS uncovered_share
  FROM cockpit_facility_quarter
  WHERE reporting_quarter IN ($q, $p) AND sector_name IS NOT NULL
  GROUP BY 1, 2)
SELECT n.borrower_id, n.ead, n.ecl
FROM b n JOIN b o
  ON o.borrower_id = n.borrower_id AND o.reporting_quarter = $p
WHERE n.reporting_quarter = $q
  AND COALESCE(n.max_dpd, 0) > COALESCE(o.max_dpd, 0)
  AND n.worst_stage >= 2
  AND n.uncovered_share > o.uncovered_share
ORDER BY n.borrower_id ASC
""",
    "Q14": """
WITH s AS (
  SELECT reporting_quarter, sector_name,
         SUM(ead_reported) AS ead, SUM(ecl_reported) AS ecl
  FROM cockpit_facility_quarter
  WHERE reporting_quarter IN ($q, $p) AND sector_name IS NOT NULL
  GROUP BY 1, 2),
w AS (SELECT reporting_quarter, sector_name, ead, ecl,
             ead / SUM(ead) OVER (PARTITION BY reporting_quarter) AS share
      FROM s)
SELECT n.sector_name,
       n.share - o.share AS concentration_change,
       n.ecl - o.ecl     AS ecl_change
FROM w n JOIN w o
  ON o.sector_name = n.sector_name AND o.reporting_quarter = $p
WHERE n.reporting_quarter = $q
  AND n.share > o.share AND n.ecl > o.ecl
ORDER BY ecl_change DESC, n.sector_name ASC
""",
    "Q15": """
WITH now_r AS (SELECT borrower_id, risk_rating, rating_rank
               FROM cockpit_rating_ratio_quarter WHERE reporting_quarter = $q),
prev_r AS (SELECT borrower_id, risk_rating, rating_rank
           FROM cockpit_rating_ratio_quarter WHERE reporting_quarter = $y),
now_b AS (SELECT borrower_id, SUM(ecl_reported) AS ecl
          FROM cockpit_facility_quarter
          WHERE reporting_quarter = $q AND sector_name IS NOT NULL GROUP BY 1),
prev_b AS (SELECT borrower_id, SUM(ecl_reported) AS ecl
           FROM cockpit_facility_quarter
           WHERE reporting_quarter = $y AND sector_name IS NOT NULL GROUP BY 1)
SELECT nb.borrower_id,
       nr.rating_rank - pr.rating_rank AS notches_down,
       pr.risk_rating AS previous_rating,
       nr.risk_rating AS current_rating,
       nb.ecl - COALESCE(pb.ecl, 0) AS ecl_change,
       nb.ecl AS ecl
FROM now_b nb
JOIN now_r  nr ON nr.borrower_id = nb.borrower_id
JOIN prev_r pr ON pr.borrower_id = nb.borrower_id
LEFT JOIN prev_b pb ON pb.borrower_id = nb.borrower_id
WHERE nr.rating_rank > pr.rating_rank
  AND nb.ecl - COALESCE(pb.ecl, 0) > 0
ORDER BY notches_down DESC, ecl_change DESC, nb.borrower_id ASC
""",
    "Q16": """
WITH s AS (
  SELECT reporting_quarter, sector_name,
         SUM(ead_reported) AS ead, SUM(ecl_reported) AS ecl,
         SUM(CASE WHEN ifrs9_stage = 2 THEN ead_reported ELSE 0 END)
             / SUM(ead_reported) AS stage2_share
  FROM cockpit_facility_quarter
  WHERE reporting_quarter IN ($q, $p) AND sector_name IS NOT NULL
  GROUP BY 1, 2),
top5 AS (SELECT sector_name FROM s WHERE reporting_quarter = $q
         ORDER BY ead DESC, sector_name ASC LIMIT 5)
SELECT n.sector_name, n.ead, n.ecl, n.stage2_share,
       o.ead AS ead_prior, o.ecl AS ecl_prior,
       o.stage2_share AS stage2_share_prior,
       n.ecl - o.ecl AS ecl_change,
       n.stage2_share - o.stage2_share AS stage2_share_change
FROM s n
JOIN s o ON o.sector_name = n.sector_name AND o.reporting_quarter = $p
WHERE n.reporting_quarter = $q
  AND n.sector_name IN (SELECT sector_name FROM top5)
ORDER BY n.ead DESC, n.sector_name ASC
""",
    "Q17": """
WITH s AS (
  SELECT reporting_quarter,
         SUM(ead_reported) AS ead, SUM(ecl_reported) AS ecl,
         SUM(CASE WHEN ifrs9_stage = 2 THEN ead_reported ELSE 0 END)
             / SUM(ead_reported) AS stage2_share
  FROM cockpit_facility_quarter
  WHERE reporting_quarter IN ($q, $y) AND sector_name = $sector
  GROUP BY 1),
b AS (
  SELECT borrower_id, SUM(ead_reported) AS ead, SUM(ecl_reported) AS ecl
  FROM cockpit_facility_quarter
  WHERE reporting_quarter = $q AND sector_name = $sector
  GROUP BY 1 ORDER BY ecl DESC, borrower_id ASC LIMIT 5)
SELECT b.borrower_id, b.ead, b.ecl,
       (SELECT ead FROM s WHERE reporting_quarter = $q) AS sector_ead,
       (SELECT ecl FROM s WHERE reporting_quarter = $q) AS sector_ecl,
       (SELECT stage2_share FROM s WHERE reporting_quarter = $q)
           AS sector_stage2_share,
       (SELECT ead FROM s WHERE reporting_quarter = $y) AS sector_ead_year_ago,
       (SELECT ecl FROM s WHERE reporting_quarter = $y) AS sector_ecl_year_ago,
       (SELECT stage2_share FROM s WHERE reporting_quarter = $y)
           AS sector_stage2_share_year_ago
FROM b
ORDER BY b.ecl DESC, b.borrower_id ASC
""",
    "Q18": """
WITH b AS (
  SELECT reporting_quarter, borrower_id,
         SUM(ead_reported) AS ead, SUM(ecl_reported) AS ecl
  FROM cockpit_facility_quarter
  WHERE reporting_quarter IN ($q, $p, $y) AND sector_name = $sector
  GROUP BY 1, 2),
breach AS (
  SELECT DISTINCT reporting_quarter, borrower_id
  FROM cockpit_covenant_quarter
  WHERE reporting_quarter IN ($q, $p, $y) AND breach_date IS NOT NULL),
cover AS (
  SELECT reporting_quarter,
         SUM(CASE WHEN collateral_coverage_ratio IS NOT NULL
                    AND collateral_coverage_ratio < 1
                  THEN ead_reported ELSE 0 END) / SUM(ead_reported)
             AS uncovered_share
  FROM cockpit_facility_quarter
  WHERE reporting_quarter IN ($q, $p, $y) AND sector_name = $sector
  GROUP BY 1)
SELECT b.reporting_quarter,
       SUM(CASE WHEN br.borrower_id IS NOT NULL THEN b.ead ELSE 0 END)
           AS breach_ead,
       SUM(b.ecl) AS ecl,
       ANY_VALUE(c.uncovered_share) AS uncovered_share
FROM b
LEFT JOIN breach br ON br.borrower_id = b.borrower_id
                   AND br.reporting_quarter = b.reporting_quarter
LEFT JOIN cover  c  ON c.reporting_quarter = b.reporting_quarter
GROUP BY 1
ORDER BY 1 DESC
""",
    "Q19": """
WITH f AS (
  SELECT reporting_quarter, sector_name, borrower_id,
         ead_reported, ecl_reported, ifrs9_stage
  FROM cockpit_facility_quarter
  WHERE reporting_quarter IN ($q, $p) AND sector_name IS NOT NULL),
book AS (
  SELECT reporting_quarter, SUM(ead_reported) AS ead,
         SUM(ecl_reported) AS ecl,
         SUM(ecl_reported) / SUM(ead_reported) AS coverage,
         SUM(CASE WHEN ifrs9_stage = 2 THEN ead_reported ELSE 0 END)
             / SUM(ead_reported) AS stage2_share
  FROM f GROUP BY 1)
SELECT n.ead, n.ecl, n.coverage, n.stage2_share,
       o.ead AS ead_prior, o.ecl AS ecl_prior,
       o.coverage AS coverage_prior,
       o.stage2_share AS stage2_share_prior,
       (SELECT sector_name FROM f WHERE reporting_quarter = $q
        GROUP BY 1 ORDER BY SUM(ecl_reported) DESC, sector_name ASC LIMIT 1)
           AS top_sector,
       (SELECT SUM(ecl_reported) FROM f WHERE reporting_quarter = $q
        GROUP BY sector_name
        ORDER BY SUM(ecl_reported) DESC, sector_name ASC LIMIT 1)
           AS top_sector_ecl,
       (SELECT borrower_id FROM f WHERE reporting_quarter = $q
        GROUP BY 1 ORDER BY SUM(ecl_reported) DESC, borrower_id ASC LIMIT 1)
           AS top_borrower,
       (SELECT SUM(ecl_reported) FROM f WHERE reporting_quarter = $q
        GROUP BY borrower_id
        ORDER BY SUM(ecl_reported) DESC, borrower_id ASC LIMIT 1)
           AS top_borrower_ecl
FROM book n JOIN book o ON o.reporting_quarter = $p
WHERE n.reporting_quarter = $q
""",
    "Q20": """
WITH f AS (
  SELECT reporting_quarter, sector_name, borrower_id, ead_reported,
         ecl_reported, ifrs9_stage, days_past_due
  FROM cockpit_facility_quarter
  WHERE reporting_quarter IN ($q, $p) AND sector_name IS NOT NULL),
r AS (SELECT reporting_quarter, borrower_id, rating_rank
      FROM cockpit_rating_ratio_quarter
      WHERE reporting_quarter IN ($q, $p)),
m AS (
  SELECT f.reporting_quarter, f.sector_name,
         SUM(f.ecl_reported) AS ecl,
         SUM(CASE WHEN f.ifrs9_stage = 2 THEN f.ead_reported ELSE 0 END)
             / SUM(f.ead_reported) AS stage2_share,
         SUM(CASE WHEN COALESCE(f.days_past_due, 0) > 0
                  THEN f.ead_reported ELSE 0 END)
             / SUM(f.ead_reported) AS past_due_share,
         SUM(CASE WHEN r.rating_rank IS NOT NULL
                  THEN f.ead_reported * r.rating_rank END)
             / SUM(CASE WHEN r.rating_rank IS NOT NULL
                        THEN f.ead_reported END) AS rating_rank
  FROM f LEFT JOIN r ON r.borrower_id = f.borrower_id
                    AND r.reporting_quarter = f.reporting_quarter
  GROUP BY 1, 2),
scored AS (
  SELECT n.sector_name,
         n.ecl - o.ecl                       AS ecl_change,
         n.stage2_share - o.stage2_share     AS stage2_share_change,
         n.rating_rank - o.rating_rank       AS rating_rank_change,
         n.past_due_share - o.past_due_share AS past_due_share_change,
         (CASE WHEN n.ecl > o.ecl THEN 1 ELSE 0 END
          + CASE WHEN n.stage2_share > o.stage2_share THEN 1 ELSE 0 END
          + CASE WHEN n.rating_rank > o.rating_rank THEN 1 ELSE 0 END
          + CASE WHEN n.past_due_share > o.past_due_share THEN 1 ELSE 0 END)
             AS deteriorated_count
  FROM m n JOIN m o
    ON o.sector_name = n.sector_name AND o.reporting_quarter = $p
  WHERE n.reporting_quarter = $q)
SELECT * FROM scored
WHERE deteriorated_count >= 2
ORDER BY deteriorated_count DESC, sector_name ASC
""",
}


def parameters_for(question_id: str, period: dict[str, Any]
                   ) -> dict[str, Any]:
    """The bound values each statement expects."""
    latest, prior = period["latest"], period["prior"]
    year_ago, last_four = period["year_ago"], period["last_four"]
    mapping = {
        "Q01": {"q": latest},
        "Q02": {"q": latest},
        "Q03": {"q": latest},
        "Q04": {f"q{i + 1}": q for i, q in enumerate(last_four)},
        "Q05": {"q": latest, "p": prior},
        "Q06": {"q": latest, "y": year_ago},
        "Q07": {"q": latest, "p": prior},
        "Q08": {"q": latest, "p": prior},
        "Q09": {"q": latest, "p": prior},
        "Q10": {"q": latest, "p": prior},
        "Q11": {"q": latest, "p": prior},
        "Q12": {"q": latest, "p": prior},
        "Q13": {"q": latest, "p": prior},
        "Q14": {"q": latest, "p": prior},
        "Q15": {"q": latest, "y": year_ago},
        "Q16": {"q": latest, "p": prior},
        "Q17": {"q": latest, "y": year_ago, "sector": "Construction"},
        "Q18": {"q": latest, "p": prior, "y": year_ago,
                "sector": "Information Technology"},
        "Q19": {"q": latest, "p": prior},
        "Q20": {"q": latest, "p": prior},
    }
    return mapping[question_id]


__all__ = ["BORROWER_TOTALS", "SECTOR_TOTALS", "parameters_for", "sql_for"]
