"""Lenses V3, driven through a real browser against a real book. §52.

Ten journeys, A through J, each one of §33–§43:

    A  formula → code → user approval → preview → lock → persists
    B  unconventional formula: flagged, offered, and nothing applied
    C  cross-domain formula: Cockpit and Early Warning in one metric
    D  invalid code: refused before execution, with what would fix it
    E  live refresh with a real change in the source data
    F  no-change refresh: no fabricated movement
    G  a definition change between two refreshes, not read as risk movement
    H  a filter change between two refreshes, not read as risk movement
    I  Cockpit and Early Warning corroboration, without invented causality
    J  the first-ever refresh: a baseline that says so

    .venv/bin/python scripts/acceptance/lens_v3_journeys.py
    .venv/bin/python scripts/acceptance/lens_v3_journeys.py --json
    .venv/bin/python scripts/acceptance/lens_v3_journeys.py --only A,E

Requires the backend on :8000 and the frontend on :3000, both with
REQUIRE_LOGIN, and a database. Every journey signs in as a real user through
the real sign-in screen.

Honest in either environment
-----------------------------
This sandbox has no AI provider configured, and a deployment that does will
behave differently at three points: the code is written by a model rather than
assembled by CreditProbe, the change reading is prose rather than a list of
movements, and the metric names are better. Each journey checks whichever the
backend actually reports — `author` and `verified` say which — rather than one
hard-coded shape. A journey that passed only with a key would be a journey
nobody could run.

What these do NOT do
--------------------
They do not assert particular figures. The book is regenerated by
`bootstrap_demo.py` and a journey pinned to 74,017.555 would fail on a rebuild
for a reason that has nothing to do with the feature. What they assert is the
RELATIONSHIPS: that the preview's two sides divide to the result shown, that a
kept formula and the conventional one produce different numbers, that a
no-change refresh reports no change.
"""

from __future__ import annotations

import argparse
import glob
import json
import os
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

WEB = os.environ.get("LENS_WEB", "http://127.0.0.1:3000")
API = os.environ.get("LENS_API", "http://127.0.0.1:8000")
ANALYST = os.environ.get("LENS_USER", "priya.raman")

EXIT_OK = 0
EXIT_FAILED = 1
EXIT_CANNOT_RUN = 2

#: The Lens each journey uses. CRO Portfolio spans both domains, which is what
#: §41's corroboration needs; the others follow it so one refresh history
#: serves several journeys.
LENS_SLUG = "cro-portfolio"

#: Metrics locked by a journey, removed at the end whether it passed or not.
MADE: list[str] = []


@dataclass
class Step:
    journey: str
    name: str
    ok: bool
    detail: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {"journey": self.journey, "check": self.name, "ok": self.ok,
                "detail": self.detail}


@dataclass
class Report:
    steps: list[Step] = field(default_factory=list)
    error: str = ""
    live: bool = True
    notes: list[str] = field(default_factory=list)

    def check(self, journey: str, name: str, ok: bool, detail: str = "") -> bool:
        step = Step(journey, name, bool(ok), detail)
        self.steps.append(step)
        if self.live:
            print(f"  [{'PASS' if step.ok else 'FAIL'}] {journey}  {name}",
                  flush=True)
            if not step.ok and detail:
                print(f"         {detail[:400]}", flush=True)
        return bool(ok)

    def note(self, text: str) -> None:
        self.notes.append(text)
        if self.live:
            print(f"         · {text}", flush=True)

    @property
    def failures(self) -> list[Step]:
        return [s for s in self.steps if not s.ok]

    def to_dict(self) -> dict[str, Any]:
        return {"steps": [s.to_dict() for s in self.steps],
                "passed": len(self.steps) - len(self.failures),
                "failed": len(self.failures), "notes": list(self.notes),
                "error": self.error}


# ---------------------------------------------------------------- plumbing


def _chromium() -> str | None:
    for pattern in ("chromium-*/chrome-linux/chrome",
                    "chromium_headless_shell-*/chrome-linux/headless_shell"):
        found = sorted(glob.glob(
            str(Path(os.environ.get("PLAYWRIGHT_BROWSERS_PATH",
                                    "/opt/pw-browsers")) / pattern)))
        if found:
            return found[-1]
    return None


def _open(page: Any, path: str = "/") -> None:
    """Load a page and wait for the app to hydrate.

    `load` rather than `networkidle`: this application holds long-lived
    connections and polls, so `networkidle` does not settle and the wait times
    out on a page that rendered perfectly. What is actually being waited for is
    React having mounted, which is what a rendered element says.
    """
    page.goto(f"{WEB}{path}", wait_until="load")
    try:
        page.wait_for_selector("main, form, [data-testid]", timeout=30_000)
    except Exception:  # noqa: BLE001 - reported by whatever asked for the page
        pass
    page.wait_for_timeout(2000)


def _whoami(page: Any) -> str:
    """Who the browser's session actually belongs to, asked of the API.

    The presence or absence of a form on screen is a guess about the session;
    this is the session. A suite that guessed wrong would run every journey
    against 401s and report the failures as product defects.
    """
    try:
        answer = _api(page, "/api/v1/auth/me")
    except Exception:  # noqa: BLE001 - before any page is loaded
        return ""
    if answer.get("status") != 200 or not isinstance(answer.get("body"), dict):
        return ""
    user = answer["body"].get("user")
    if not isinstance(user, dict):
        return ""
    return str(user.get("username") or "")


def _sign_in(page: Any, report: Report, username: str = ANALYST) -> bool:
    from backend.services.demo_users import DEMO_PASSWORD

    _open(page, "/")
    if _whoami(page) == username:
        return report.check("sign in", f"signed in as {username}", True,
                            "the session was already open")

    try:
        page.wait_for_selector("input[name=password], #password",
                               timeout=30_000)
    except Exception:  # noqa: BLE001
        return report.check(
            "sign in", f"signed in as {username}", False,
            "no sign-in form appeared and no session was open — the app did "
            "not reach a state this suite can run against")

    page.fill("input[name=username], #username", username)
    page.fill("input[name=password], #password", DEMO_PASSWORD)
    page.get_by_role("button", name="Sign in").click()
    try:
        page.wait_for_selector("input[name=password], #password",
                               state="detached", timeout=20_000)
    except Exception:  # noqa: BLE001
        return report.check("sign in", f"signed in as {username}", False,
                            "the sign-in form is still on screen")
    page.wait_for_timeout(1500)

    who = _whoami(page)
    return report.check("sign in", f"signed in as {username}",
                        who == username,
                        f"the session belongs to {who!r}")


def _lens_id(slug: str = LENS_SLUG) -> int | None:
    from backend.services import lenses as service

    try:
        return service.by_slug(slug).id
    except Exception:  # noqa: BLE001
        return None


def _clear_history(lens_id: int) -> None:
    from sqlalchemy import delete

    from backend.db.engine import get_session
    from backend.models.platform import LensRefresh

    with get_session() as session:
        session.execute(delete(LensRefresh).where(
            LensRefresh.lens_id == lens_id))
        session.commit()


def _api(page: Any, path: str, *, method: str = "GET",
         body: Any = None) -> Any:
    """Call the API through the browser's own session.

    Through the page rather than with `requests`, so the call carries the real
    signed-in cookie and exercises the same authorisation a click would. A
    journey that bypassed the session would prove the pipeline works for
    nobody in particular.
    """
    return page.evaluate(
        """async ({path, method, body}) => {
            const response = await fetch(path, {
                method,
                headers: {"Content-Type": "application/json"},
                body: body === null ? undefined : JSON.stringify(body),
                credentials: "same-origin",
            });
            const text = await response.text();
            try { return {status: response.status, body: JSON.parse(text)}; }
            catch (e) { return {status: response.status, body: text}; }
        }""",
        {"path": path, "method": method, "body": body})


def _restore_demo_data() -> None:
    import subprocess

    subprocess.run(
        [sys.executable, "scripts/acceptance/../lens_demo_change.py",
         "--restore"],
        cwd=str(Path(__file__).resolve().parents[2]),
        capture_output=True, check=False)


def _change_demo_data() -> bool:
    import subprocess

    done = subprocess.run(
        [sys.executable, "scripts/lens_demo_change.py", "--apply"],
        cwd=str(Path(__file__).resolve().parents[2]),
        capture_output=True, text=True, check=False)
    return done.returncode == 0 and "Moved" in done.stdout


# ============================================================== JOURNEY A
#
# §33. The whole sequence, on screen: type a formula, read the code, approve
# it, see the exact arithmetic, lock it, and find it still there after a
# reload.


def journey_a(page: Any, report: Report, lens_id: int) -> None:
    tag = "A formula→code→approve→preview→lock"
    _open(page, f"/lenses/{lens_id}")

    if not _open_formula_builder(page, report, tag):
        return

    said = ("Add QoQ Exposure Change: (Current Quarter Exposure / "
            "Previous Quarter Exposure) - 1")
    page.fill("[data-testid=formula-input]", said)
    page.click("[data-testid=formula-write-code]")
    page.wait_for_selector("[data-testid=metric-definition-card]",
                           timeout=150_000)
    page.wait_for_timeout(1500)

    # §5: the formula on screen is the formula that was typed.
    shown = page.inner_text("[data-testid=user-formula]").strip()
    report.check(tag, "the formula is shown exactly as it was typed",
                 shown == "(Current Quarter Exposure / "
                          "Previous Quarter Exposure) - 1",
                 f"on screen: {shown!r}")

    # §6: the definition card carries what a person needs to approve it.
    for testid, what in (("metric-name", "a name"),
                         ("interpreted-formula", "the interpreted formula"),
                         ("plain-english", "the plain-English steps"),
                         ("generated-sql", "the code"),
                         ("code-datasets", "the dataset(s)"),
                         ("code-grain", "the grain")):
        report.check(tag, f"the definition card shows {what}",
                     page.locator(f"[data-testid={testid}]").count() > 0
                     and bool(page.inner_text(
                         f"[data-testid={testid}]").strip()))

    author = page.inner_text("[data-testid=code-author]").strip()
    report.note(f"the code was {author.lower()}")

    stage = page.inner_text("[data-testid=code-stage]").strip()
    if "Rejected" in stage:
        failures = page.inner_text("[data-testid=code-failures]")
        report.check(tag, "CreditProbe accepted the generated code", False,
                     failures[:400])
        return
    report.check(tag, "CreditProbe validated the generated code", True)

    # §12: approve, then the exact arithmetic.
    page.fill("[data-testid=approval-note]", "Checked against the pack.")
    page.click("[data-testid=approve-and-preview]")
    page.wait_for_selector("[data-testid=metric-preview]", timeout=150_000)
    page.wait_for_timeout(1000)

    numerator = _number(page.inner_text("[data-testid=preview-numerator]"))
    denominator = _number(page.inner_text("[data-testid=preview-denominator]"))
    value = page.inner_text("[data-testid=preview-value]").strip()
    final = page.inner_text("[data-testid=preview-final]").strip()
    report.check(tag, "the preview shows both sides and the result",
                 numerator is not None and denominator is not None
                 and bool(value),
                 f"numerator={numerator} denominator={denominator} "
                 f"value={value!r}")

    # The arithmetic on screen is the arithmetic that produced the figure.
    # Not a pinned figure — a RELATIONSHIP, which survives a rebuilt book.
    if numerator is not None and denominator and denominator != 0:
        expected = (numerator / denominator - 1) * 100
        shown_value = _number(value)
        report.check(
            tag, "the two sides divide to the figure shown",
            shown_value is not None and abs(shown_value - expected) < 0.02,
            f"({numerator} / {denominator}) - 1 = {expected:.4f}%, "
            f"screen shows {value}")
    report.check(tag, "the preview names the exact calculation",
                 "/" in final and "=" in final, final[:120])

    page.click("[data-testid=lock-metric]")
    page.wait_for_selector("[data-testid=metric-locked]", timeout=90_000)
    report.check(tag, "the metric locks", True)

    # §33.9: it persists across a reload, on the Lens.
    page.wait_for_timeout(2500)
    _open(page, f"/lenses/{lens_id}")
    page.wait_for_timeout(3000)
    body = page.inner_text("body")
    report.check(tag, "the metric is still on the Lens after a reload",
                 "QoQ Exposure Change" in body,
                 "the locked metric's name is not on the reloaded page")

    made = _find_made(page, "QoQ Exposure Change")
    if made:
        MADE.append(made)


def _open_formula_builder(page: Any, report: Report, tag: str) -> bool:
    """Get to the formula builder from a rendered Lens.

    Waits for the Lens to have FINISHED rendering first. Opening a Lens runs
    the whole refresh pipeline — every panel, the snapshot, the comparison —
    and the Edit control is not on the page until that returns. Clicking too
    early found nothing and reported the builder as unreachable, which was a
    fact about the wait rather than about the product.
    """
    try:
        page.wait_for_selector("[data-testid=lens-changes], [data-testid=edit-lens]",
                               timeout=240_000)
    except Exception:  # noqa: BLE001 - reported by the check below
        pass
    page.wait_for_timeout(2000)
    for selector in ("[data-testid=edit-lens]", "button:has-text('Edit')"):
        found = page.locator(selector)
        if found.count():
            found.first.click()
            page.wait_for_timeout(1200)
            break
    add = page.locator("[data-testid=add-metric], button:has-text('Add metric')")
    if add.count():
        add.first.click()
        page.wait_for_timeout(1500)
    ready = page.locator("[data-testid=formula-builder]").count() > 0
    return report.check(tag, "the formula builder is on screen", ready,
                        "could not reach the formula builder from the Lens")


def _find_made(page: Any, name: str) -> str:
    from backend.metrics import service

    for metric in service.catalogue():
        if metric.name == name and metric.origin == "USER":
            return metric.metric_id
    return ""


def _number(text: str) -> float | None:
    import re

    if not text:
        return None
    found = re.search(r"-?[\d,]+(?:\.\d+)?", text)
    if not found:
        return None
    try:
        return float(found.group(0).replace(",", ""))
    except ValueError:
        return None


# ============================================================== JOURNEY B
#
# §34. An unconventional formula is flagged, offered an alternative, and
# NOTHING is applied. The two choices must produce different numbers, or the
# preservation rule means nothing.


def journey_b(page: Any, report: Report, lens_id: int) -> None:
    tag = "B unconventional formula"
    said = "Previous Quarter Exposure / Current Quarter Exposure - 1"

    read = _api(page, "/api/v1/formula/read", method="POST",
                body={"said": said})
    if read["status"] != 200:
        report.check(tag, "the formula is read", False, str(read)[:300])
        return
    intake = read["body"]
    report.check(tag, "the formula is preserved exactly",
                 intake["formula"] == said, repr(intake["formula"]))
    unconventional = intake.get("unconventional")
    report.check(tag, "the unconventional direction is flagged",
                 bool(unconventional),
                 "no flag was raised on an inverted growth formula")
    if not unconventional:
        return
    report.check(tag, "the three choices are offered",
                 [c["id"] for c in unconventional["choices"]]
                 == ["keep", "conventional", "edit"])
    report.check(tag, "the conventional alternative is offered separately",
                 unconventional["conventional"]
                 == "Current Quarter Exposure / Previous Quarter Exposure - 1",
                 repr(unconventional["conventional"]))

    # The screen shows it, with the buttons.
    _open(page, f"/lenses/{lens_id}")
    if _open_formula_builder(page, report, tag):
        page.fill("[data-testid=formula-input]", said)
        page.click("[data-testid=formula-write-code]")
        page.wait_for_selector("[data-testid=unconventional-warning]",
                               timeout=60_000)
        report.check(tag, "the warning is on screen with the three buttons",
                     page.locator("[data-testid=keep-my-formula]").count() > 0
                     and page.locator(
                         "[data-testid=use-conventional-formula]").count() > 0
                     and page.locator("[data-testid=edit-formula]").count() > 0)
        report.check(tag, "the person's own formula is shown unchanged",
                     page.inner_text("[data-testid=your-formula]").strip()
                     == said)

    # And the two choices genuinely differ. This is the check the whole rule
    # exists for: if keeping their formula produced the conventional number,
    # the flag would be theatre.
    kept = _api(page, "/api/v1/formula/draft", method="POST",
                body={"said": said, "keep_formula": said,
                      "period": "Q2 2026"})
    swapped = _api(page, "/api/v1/formula/draft", method="POST",
                   body={"said": said,
                         "keep_formula": unconventional["conventional"],
                         "period": "Q2 2026"})
    values = []
    for label, drafted in (("kept", kept), ("conventional", swapped)):
        if drafted["status"] != 200 or not drafted["body"]["ready"]:
            report.check(tag, f"the {label} formula produces a metric", False,
                         str(drafted)[:300])
            return
        code = drafted["body"]["code"]
        approved = _api(page, "/api/v1/formula/approve", method="POST",
                        body={"code": code, "period": "Q2 2026"})
        shown = _api(page, "/api/v1/formula/preview", method="POST",
                     body={"code": approved["body"]["code"],
                           "period": "Q2 2026",
                           "approved_checksum": approved["body"]["checksum"]})
        values.append(shown["body"]["preview"]["value"])
    report.check(tag, "keeping the formula computes a different number "
                      "from the conventional one",
                 values[0] is not None and values[1] is not None
                 and abs(values[0] - values[1]) > 1e-9,
                 f"kept={values[0]}, conventional={values[1]}")


# ============================================================== JOURNEY C
#
# §35. A formula that crosses the two domains, with the lineage showing both.


def journey_c(page: Any, report: Report, lens_id: int) -> None:
    tag = "C cross-domain formula"
    said = "High EWS exposure divided by total corporate exposure"

    drafted = _api(page, "/api/v1/formula/draft", method="POST",
                   body={"said": said, "period": "Q2 2026",
                         "lens_id": lens_id})
    if drafted["status"] != 200:
        report.check(tag, "the formula produces a definition", False,
                     str(drafted)[:300])
        return
    code = drafted["body"]["code"]
    report.check(tag, "CreditProbe validated it",
                 drafted["body"]["ready"],
                 json.dumps(drafted["body"]["validation"]["failures"])[:400])
    report.check(tag, "both domains are named on the definition",
                 set(code["domains"]) == {"cockpit", "ews"},
                 f"domains: {code['domains']}")
    report.check(tag, "the code names the governed datasets it reads",
                 bool(code["datasets"]), f"datasets: {code['datasets']}")
    if not drafted["body"]["ready"]:
        return

    approved = _api(page, "/api/v1/formula/approve", method="POST",
                    body={"code": code, "period": "Q2 2026"})
    shown = _api(page, "/api/v1/formula/preview", method="POST",
                 body={"code": approved["body"]["code"], "period": "Q2 2026",
                       "approved_checksum": approved["body"]["checksum"]})
    preview = shown["body"]["preview"]
    report.check(tag, "the preview reconciles on real data",
                 preview["available"], preview.get("unavailable", "")[:200])
    report.check(tag, "the lineage shows both domains",
                 set(preview["domains"]) == {"cockpit", "ews"}
                 or {"cockpit", "ews"} <= (
                     set(preview["numerator"].get("domains") or [])
                     | set(preview["denominator"].get("domains") or [])),
                 f"preview domains: {preview['domains']}, "
                 f"numerator: {preview['numerator'].get('domains')}, "
                 f"denominator: {preview['denominator'].get('domains')}")

    locked = _api(page, "/api/v1/formula/lock", method="POST",
                  body={"code": shown["body"]["code"], "period": "Q2 2026",
                        "approved_checksum": shown["body"]["checksum"]})
    report.check(tag, "it locks", locked["status"] == 200
                 and locked["body"].get("locked"), str(locked)[:300])
    if locked["status"] == 200 and locked["body"].get("metric_id"):
        MADE.append(locked["body"]["metric_id"])


# ============================================================== JOURNEY D
#
# §36. Code that names a field the dataset does not have is refused BEFORE
# anything runs, and the refusal says what would fix it.


def journey_d(page: Any, report: Report, lens_id: int) -> None:
    tag = "D invalid code refused"
    drafted = _api(page, "/api/v1/formula/draft", method="POST",
                   body={"said": "Add Stage 2 Exposure / Total Exposure.",
                         "period": "Q2 2026"})
    if drafted["status"] != 200 or not drafted["body"]["ready"]:
        report.check(tag, "a valid definition to start from", False,
                     str(drafted)[:300])
        return
    code = dict(drafted["body"]["code"])

    # Somebody edits the SQL to read a field nobody has.
    code["sql"] = ("SELECT SUM(p.ead_amount) / SUM(p.exposure) AS ratio "
                   "FROM portfolio_facility p WHERE p.period = ?")
    code["formula"] = {
        "kind": "percentage",
        "numerator": {"terms": [{"id": "n", "label": "EAD",
                                 "dataset": "portfolio_facility",
                                 "aggregate": "sum", "field": "ead_amount",
                                 "where": []}], "combine": "add"},
        "denominator": {"terms": [{"id": "d", "label": "Total",
                                   "dataset": "portfolio_facility",
                                   "aggregate": "sum", "field": "exposure",
                                   "where": []}], "combine": "add"},
        "scale": 100.0}
    code["composite"] = None

    revised = _api(page, "/api/v1/formula/revise", method="POST",
                   body={"code": code, "period": "Q2 2026", "edited": True})
    body = revised["body"]
    report.check(tag, "CreditProbe refuses the edited code",
                 not body["ready"], "an unknown field was accepted")
    failures = body["validation"]["failures"]
    report.check(tag, "the refusal names the field that does not exist",
                 any("ead_amount" in f["message"] for f in failures),
                 json.dumps(failures)[:400])
    report.check(tag, "the refusal offers the fields that DO exist",
                 any(f["hints"].get("related_fields") for f in failures),
                 "a repair round with no candidates guesses")
    report.check(tag, "the edited code is marked as the person's",
                 body["code"]["author"] == "USER",
                 f"author: {body['code']['author']}")

    # And nothing may run it.
    ran = _api(page, "/api/v1/formula/preview", method="POST",
               body={"code": body["code"], "period": "Q2 2026"})
    report.check(tag, "nothing runs unapproved, invalid code",
                 ran["status"] in (409, 422),
                 f"preview returned {ran['status']}")

    # Unsafe SQL is refused too, and is not a repairable mistake.
    unsafe = dict(drafted["body"]["code"])
    unsafe["sql"] = ("SELECT SUM(exposure) FROM portfolio_facility; "
                     "DROP TABLE portfolio_facility")
    checked = _api(page, "/api/v1/formula/revise", method="POST",
                   body={"code": unsafe, "period": "Q2 2026", "edited": True})
    report.check(tag, "a second statement is refused",
                 not checked["body"]["ready"]
                 and any("statements" in f["message"]
                         for f in checked["body"]["validation"]["failures"]),
                 json.dumps(checked["body"]["validation"]["failures"])[:300])


# ============================================================== JOURNEY J
#
# §43. The first refresh of a Lens with no history says so, rather than
# reporting nothing or inventing a comparison.


def journey_j(page: Any, report: Report, lens_id: int) -> None:
    tag = "J baseline refresh"
    # Cleared, then OPENED — because opening a Lens is itself the refresh.
    # Calling the API first and then loading the page would make the page the
    # SECOND refresh, which is a comparison rather than a baseline, and the
    # journey would be testing something other than what it says.
    _clear_history(lens_id)

    _open(page, f"/lenses/{lens_id}")
    page.wait_for_selector("[data-testid=lens-changes]", timeout=180_000)
    page.wait_for_timeout(1500)
    report.check(tag, "the What Changed panel is on the Lens",
                 page.locator("[data-testid=lens-changes]").count() > 0)
    report.check(tag, "the header says there is nothing to compare with yet",
                 "baseline" in page.inner_text(
                     "[data-testid=header-compared-with]").lower(),
                 page.inner_text("[data-testid=header-compared-with]")[:120])
    headline = page.inner_text("[data-testid=change-headline]")
    report.check(tag, "the panel says change interpretation comes next time",
                 "next comparable refresh" in headline, headline[:200])

    # …and the stored record agrees with the screen.
    stored = _api(page, f"/api/v1/lenses/{lens_id}/refreshes?limit=5")["body"]
    report.check(tag, "the refresh was recorded", stored["count"] >= 1,
                 str(stored)[:200])
    first = stored["refreshes"][-1]
    report.check(tag, "the first refresh is recorded as a baseline",
                 first["baseline"] and "baseline" in first["classification"],
                 json.dumps(first)[:200])
    report.check(tag, "it records that opening the Lens is what ran it",
                 first["trigger"] == "lens_opened",
                 f"trigger: {first['trigger']}")


# ============================================================== JOURNEY F
#
# §38. Two refreshes over identical data must not manufacture movement.


def journey_f(page: Any, report: Report, lens_id: int) -> None:
    tag = "F no-change refresh"
    _api(page, f"/api/v1/lenses/{lens_id}/refresh", method="POST",
         body={"trigger": "manual"})
    body = _api(page, f"/api/v1/lenses/{lens_id}/refresh", method="POST",
                body={"trigger": "manual"})["body"]
    report.check(tag, "the previous comparable refresh is chosen",
                 body["compared_with"] is not None
                 and body["compared_with"]["exact"],
                 f"compared with: {body['compared_with']}")
    report.check(tag, "it is classified as no change",
                 body["classification"] == ["no_source_change"],
                 f"classification: {body['classification']}")
    reading = body.get("changes") or {}
    report.check(tag, "no movement is fabricated",
                 reading.get("no_material_change") is True,
                 reading.get("headline", "")[:200])
    report.check(tag, "the sentence says so plainly",
                 "No material changes" in reading.get("headline", ""),
                 reading.get("headline", "")[:200])
    report.check(tag, "the supporting facts are given rather than asserted",
                 len(reading.get("material_changes") or []) >= 2,
                 json.dumps(reading.get("material_changes"))[:300])

    _open(page, f"/lenses/{lens_id}")
    page.wait_for_selector("[data-testid=change-headline]", timeout=180_000)
    report.check(tag, "the Lens shows it",
                 "No material changes" in page.inner_text(
                     "[data-testid=change-headline]"),
                 page.inner_text("[data-testid=change-headline]")[:200])


# ============================================================== JOURNEY E, I
#
# §37 and §41. A real change in the source data, reported as a change, with
# the Cockpit and Early Warning movements separated so a reader can see the
# corroboration rather than being told about it.


def journey_e_and_i(page: Any, report: Report, lens_id: int) -> None:
    tag = "E live refresh with a real change"
    _clear_history(lens_id)
    _restore_demo_data()
    before = _api(page, f"/api/v1/lenses/{lens_id}/refresh", method="POST",
                  body={"trigger": "lens_opened"})["body"]
    report.check(tag, "a baseline is recorded before the change",
                 bool(before.get("refresh_id")))

    if not _change_demo_data():
        report.check(tag, "the demonstration data moved", False,
                     "scripts/lens_demo_change.py --apply did not apply")
        return
    report.check(tag, "the demonstration data moved", True)

    # The PAGE performs the refresh that has to notice the change, and this
    # captures that exact response.
    #
    # Calling the API first and loading the Lens afterwards was the earlier
    # shape and it was wrong: the API call is a refresh, so it consumes the
    # change, and the page's own refresh then correctly reports that nothing
    # has moved since. The screen and the payload have to be two readings of
    # ONE refresh or neither is evidence about the other.
    seen: dict[str, Any] = {}

    def _catch(response: Any) -> None:
        if seen or response.request.method != "POST":
            return
        if "/refresh" not in response.url:
            return
        try:
            seen["body"] = response.json()
        except Exception:  # noqa: BLE001 - a body that is not JSON is not ours
            pass

    page.on("response", _catch)
    try:
        _open(page, f"/lenses/{lens_id}")
        page.wait_for_selector("[data-testid=lens-changes]", timeout=180_000)
        page.wait_for_timeout(2000)
    finally:
        page.remove_listener("response", _catch)

    body = seen.get("body") or {}
    if not body:
        report.check(tag, "the Lens refreshed itself when it was opened",
                     False, "no POST /refresh was observed from the page")
        _restore_demo_data()
        return
    report.check(tag, "the Lens refreshed itself when it was opened", True)
    report.check(tag, "the source change is detected from the data itself",
                 bool(body["data_changes"]["datasets"]),
                 f"datasets reported changed: "
                 f"{body['data_changes']['datasets']}")
    report.check(tag, "it is classified as source and value changed",
                 "source_and_value_changed" in body["classification"],
                 f"classification: {body['classification']}")

    delta = body.get("delta") or {}
    material = delta.get("material") or []
    report.check(tag, "figures moved and the movement is reported",
                 len(material) > 0,
                 "no material change was found after the data moved")
    if material:
        first = material[0]
        report.check(tag, "each movement carries both figures and the change",
                     first["previous"] is not None
                     and first["current"] is not None
                     and first["absolute"] is not None,
                     json.dumps(first)[:300])

    reading = body.get("changes") or {}
    report.check(tag, "the reading is verified before it is shown",
                 reading.get("verified") is True,
                 f"ungrounded: {reading.get('ungrounded')}")
    report.check(tag, "no unsupported figure survived",
                 not reading.get("ungrounded"),
                 json.dumps(reading.get("ungrounded"))[:200])

    # §41: the two domains, separately.
    tag_i = "I Cockpit and EWS corroboration"
    report.check(tag_i, "the header reports data changes per domain",
                 body["data_changes"]["cockpit"] or body["data_changes"]["ews"],
                 f"cockpit={body['data_changes']['cockpit']} "
                 f"ews={body['data_changes']['ews']}")
    cockpit = [c for c in material
               if c.get("belongs_to") == "Cockpit"
               or "cockpit" == (c.get("primary_domain") or "")]
    ews = [c for c in material
           if c.get("belongs_to") == "Early Warning"
           or "ews" == (c.get("primary_domain") or "")]
    def _named(changes: list[dict[str, Any]]) -> list[str]:
        return [str(c.get("title") or c.get("metric_id") or c.get("panel_key"))
                for c in changes]

    report.check(tag_i, "both domains moved, and are reported separately",
                 bool(cockpit) and bool(ews),
                 f"cockpit movements: {_named(cockpit)}, "
                 f"early warning movements: {_named(ews)}")
    report.check(tag_i, "no claim asserts causation the data does not show",
                 all(claim.get("basis") != "CONFIRMED_DRIVER"
                     or claim.get("downgraded_from")
                     for section in (reading.get("sections") or {}).values()
                     for claim in section),
                 "an unsupported confirmed-driver claim survived")

    report.check(tag, "the Lens reports the movement",
                 "No material changes" not in page.inner_text(
                     "[data-testid=change-headline]"),
                 page.inner_text("[data-testid=change-headline]")[:200])

    # §32: the metric history, with the two senses labelled apart.
    metric_id = (material[0].get("metric_id") if material else "") or \
        "corporate.watchlist_rate"
    history = _api(page,
                   f"/api/v1/lenses/{lens_id}/metrics/{metric_id}/history"
                   )["body"]
    report.check(tag, "the metric has a refresh history",
                 len(history.get("refresh_history") or []) >= 2,
                 json.dumps(history.get("refresh_history"))[:200])
    report.check(tag, "refresh history and reporting-period history are "
                      "labelled apart",
                 "each time the Lens ran" in history["labels"][
                     "refresh_history"]
                 and "each business period" in history["labels"][
                     "reporting_period_history"])

    _restore_demo_data()


# ============================================================== JOURNEY G
#
# §39. A metric whose DEFINITION changed between two refreshes must not have
# the difference presented as the book moving.


def journey_g(page: Any, report: Report, lens_id: int) -> None:
    tag = "G definition change between refreshes"
    _clear_history(lens_id)

    # Open once, to have something to change FROM. Opening a Lens is itself a
    # refresh, so the ordering matters: change the definition on the LATEST
    # refresh and then open the page, so the page's own refresh is the one
    # that sees the change. Changing it and then calling the API first made
    # the page a third refresh, comparing against a second that had already
    # absorbed the change — and the screen correctly said nothing had moved.
    _open(page, f"/lenses/{lens_id}")
    page.wait_for_selector("[data-testid=lens-changes]", timeout=240_000)

    from sqlalchemy import select

    from backend.db.engine import get_session
    from backend.models.platform import LensMetricSnapshot, LensRefresh

    with get_session() as session:
        latest = session.execute(
            select(LensRefresh).where(LensRefresh.lens_id == lens_id)
            .order_by(LensRefresh.id.desc()).limit(1)).scalars().first()
        if latest is None:
            report.check(tag, "a first refresh to change from", False)
            return
        row = session.query(LensMetricSnapshot).filter(
            LensMetricSnapshot.refresh_id == latest.id).first()
        if row is None:
            report.check(tag, "a snapshot to change", False)
            return
        changed_metric = row.title
        # The definition HASH is what the classifier reads, and it is computed
        # from the definition itself rather than from a version somebody
        # remembered to increment — so this is exactly the signal an edited
        # formula produces.
        row.definition_hash = "edited-between-refreshes"
        session.commit()

    _open(page, f"/lenses/{lens_id}")
    page.wait_for_selector("[data-testid=refresh-classification]",
                           timeout=240_000)
    shown = page.inner_text("[data-testid=refresh-classification]")
    report.check(tag, "the Lens says the definition changed, above the "
                      "figures",
                 "definition changed" in shown.lower(), shown[:300])
    report.check(tag, "the reader is told what that means for the figures",
                 "not purely the book" in shown.lower()
                 or "definition rather than the book" in shown.lower(),
                 shown[:300])

    # Read the RECORD of the refresh the page just performed, rather than
    # asking for the changes again — a second `/changes` call is a third
    # refresh, and it compares against a second that has already absorbed the
    # definition change, so it correctly reports that nothing moved.
    stored = _api(page, f"/api/v1/lenses/{lens_id}/refreshes?limit=3")["body"]
    latest = stored["refreshes"][0]
    report.check(tag, "the stored refresh records the definition change",
                 "definition_changed" in latest["classification"],
                 f"classification: {latest['classification']}")
    report.check(tag, "the metric that changed is named on screen",
                 changed_metric.lower() in page.inner_text("body").lower(),
                 f"looking for {changed_metric!r}")


# ============================================================== JOURNEY H
#
# §40. A filter change is a different POPULATION, and headline figures across
# it are not compared at all.


def journey_h(page: Any, report: Report, lens_id: int) -> None:
    tag = "H filter change between refreshes"
    _clear_history(lens_id)
    _api(page, f"/api/v1/lenses/{lens_id}/refresh", method="POST",
         body={"trigger": "lens_opened"})

    # Narrow the Lens, exactly as a person would.
    scope = _api(page, f"/api/v1/lenses/{lens_id}")["body"]["scope"]
    narrowed = dict(scope)
    narrowed["portfolio"] = "Construction"
    changed = _api(page, f"/api/v1/lenses/{lens_id}/scope", method="PUT",
                   body=narrowed)
    report.check(tag, "the Lens filter can be narrowed",
                 changed["status"] == 200, str(changed)[:200])

    body = _api(page, f"/api/v1/lenses/{lens_id}/refresh", method="POST",
                body={"trigger": "manual"})["body"]
    report.check(tag, "the filter change is recognised",
                 "filter_changed" in body["classification"]
                 or body["compared_with"] is None,
                 f"classification: {body['classification']}, "
                 f"compared with: {body['compared_with']}")
    reading = body.get("changes") or {}
    text = (reading.get("headline", "") + " "
            + reading.get("definition_caveat", "")).lower()
    report.check(tag, "the two refreshes are not compared as movement",
                 ("filter" in text and "population" in text)
                 or "different filter context" in (
                     body.get("why_no_comparison") or "").lower(),
                 f"headline: {reading.get('headline')!r}, "
                 f"caveat: {reading.get('definition_caveat')!r}, "
                 f"why none: {body.get('why_no_comparison')!r}")

    # Put it back, so the Lens is left as it was found.
    _api(page, f"/api/v1/lenses/{lens_id}/scope", method="PUT", body=scope)


# ================================================================== running


JOURNEYS = {
    "A": journey_a,
    "B": journey_b,
    "C": journey_c,
    "D": journey_d,
    "E": journey_e_and_i,
    "F": journey_f,
    "G": journey_g,
    "H": journey_h,
    "J": journey_j,
}


#: The metric names this suite creates. Locking one twice is refused — the
#: product will not let two of a person's metrics share a name — so a run
#: killed before its cleanup would poison every later run with a 422 that
#: looks like a product failure and is not.
SWEPT = (
    "QoQ Exposure Change",
    "High EWS Exposure / Total Corporate Exposure",
    "Previous Quarter Exposure / Current Quarter Exposure",
)


def _sweep() -> None:
    """Remove anything a previous run of THIS suite left behind.

    Only user metrics, and only the exact names this suite creates: a sweep
    that took a governed catalogue metric with it would be a far worse bug
    than the one it is here to prevent.
    """
    from sqlalchemy import delete, select

    from backend.db.engine import get_session
    from backend.models.platform import UserMetric

    wanted = {name.strip().lower() for name in SWEPT}
    try:
        with get_session() as session:
            rows = session.execute(select(UserMetric)).scalars().all()
            doomed = [r.id for r in rows
                      if (r.name or "").strip().lower() in wanted]
            if doomed:
                session.execute(
                    delete(UserMetric).where(UserMetric.id.in_(doomed)))
                session.commit()
    except Exception:  # noqa: BLE001 - a sweep failure is not a test failure
        pass


def _cleanup() -> None:
    from backend.metrics import service

    for metric_id in MADE:
        try:
            service.delete(metric_id)
        except Exception:  # noqa: BLE001
            pass
    _sweep()
    _restore_demo_data()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--json", action="store_true")
    parser.add_argument("--only", default="",
                        help="a comma-separated list of journeys, e.g. A,E")
    args = parser.parse_args()

    report = Report(live=not args.json)
    wanted = ([j.strip().upper() for j in args.only.split(",") if j.strip()]
              or list(JOURNEYS))

    executable = _chromium()
    if executable is None:
        report.error = ("No Chromium found. Set PLAYWRIGHT_BROWSERS_PATH or "
                        "install one.")
        print(json.dumps(report.to_dict()) if args.json else report.error)
        return EXIT_CANNOT_RUN

    lens_id = _lens_id()
    if lens_id is None:
        report.error = (f"The '{LENS_SLUG}' Lens is not installed in this "
                        "database. Run scripts/bootstrap_demo.py first.")
        print(json.dumps(report.to_dict()) if args.json else report.error)
        return EXIT_CANNOT_RUN

    _sweep()

    from playwright.sync_api import sync_playwright

    try:
        with sync_playwright() as playwright:
            browser = playwright.chromium.launch(executable_path=executable,
                                                 headless=True)
            page = browser.new_page(viewport={"width": 1440, "height": 1000})
            page.set_default_timeout(60_000)
            try:
                if not _sign_in(page, report):
                    report.error = "could not sign in"
                else:
                    for name in wanted:
                        journey = JOURNEYS.get(name)
                        if journey is None:
                            continue
                        if report.live:
                            print(f"\n▸ Journey {name}", flush=True)
                        try:
                            journey(page, report, lens_id)
                        except Exception as e:  # noqa: BLE001
                            report.check(name, "journey completed", False,
                                         f"{type(e).__name__}: {e}")
            finally:
                browser.close()
    finally:
        _cleanup()

    if args.json:
        print(json.dumps(report.to_dict(), indent=2))
    else:
        print()
        passed = len(report.steps) - len(report.failures)
        print(f"{passed} of {len(report.steps)} checks passed.")
        for failure in report.failures:
            print(f"  FAILED  {failure.journey}  {failure.name}")
    return EXIT_OK if not report.failures and not report.error else EXIT_FAILED


if __name__ == "__main__":
    raise SystemExit(main())
