"""Nine more episodes, in the book's own records rather than in its captions.

The defect this exists for
--------------------------
Ten Requires Attention cards can be produced in an afternoon by writing ten
titles and ten paragraphs. The result survives one click: the reader asks which
customers, and there is nothing underneath — no identifiers to export, no
facilities to price, no pocket to compare against the rest of the book, and no
way for Early Warning to show the same people at the same date.

So each of the nine episodes here is generated into the facility records, and
everything downstream reacts because the records moved. A payroll interruption
is missing salary credits and a collapsed cash buffer, which the behavioural
scorecard reads as a behavioural scorecard, which the staging rules read as
staging rules, which the ECL engine prices as the ECL engine. Nothing writes a
score, a stage or a loss directly.

How a pocket is made, and why that is honest
--------------------------------------------
Membership is decided first and pressure is applied second. Each episode picks
an eligible population out of the real book (personal loans to financed
employees, auto contracts with a balloon inside ninety days, self-construction
mortgages), then marks a *pocket* inside it, then applies its mechanism mostly
to the pocket and rarely outside it.

The measured concentration is therefore a measurement, not an assertion: the
case predicate runs over the resulting columns exactly as it will in
production, and the incidence inside and outside the pocket is counted. That
is also what a real pocket is — a subgroup where a mechanism actually bites —
so generating one this way is not a shortcut around the finding, it is the
finding.

What the miniature fixture is used for
--------------------------------------
The worked workbook has a hundred observations per case. Those hundred are not
a population; they are a set of RATIOS — how much more often the issue occurs
than in the comparator, what share of the eligible book the pocket holds, what
share of the cases sits in it, how many survive verification at S1 and
corroboration at S3. Those ratios are applied to whatever eligible population
the installed book actually has, which is why a reader is shown the book's own
counts and not the workbook's.

What is deliberately NOT done
-----------------------------
* No episode touches CREDIT_CARD. The Alpha story is generated by
  `_prepare_card_programmes` and its calibration is an accepted regression
  contract; an overlay that also pushed on cards could move it without
  anybody noticing which change did it.
* No episode selects on nationality, sex, religion, marital status or age.
  C09's pocket is a *documented pension transition with an unchanged scheduled
  payment* — a cash-flow mismatch that happens to correlate with age — and the
  column it selects on is the transition, not the birthday.
* C06 does not deteriorate the borrower. Its PD moves by a tenth of a point
  and its behavioural score by three, because the loss in that story is
  entirely in severity, and a generator that quietly worsened the borrower to
  make the ECL move would be manufacturing the evidence the story exists to
  reject.

Everything here is SYNTHETIC. DEMO Employer A, DEMO Housing Project C and
every rate, amount and threshold are invented.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from typing import Any

import numpy as np
import pandas as pd

from backend.retail import episodes as ep
from backend.retail import taxonomy as tax

logger = logging.getLogger(__name__)

VERSION = "retail-episode-overlay-1.0.0"

#: The nine. C01 is the card programme episode and is not generated here.
CASES = tuple(f"C{i:02d}" for i in range(2, 11))

#: Fictitious labels. Named in one place so a search for them finds every use.
EMPLOYER_GROUP = "DEMO Employer A"
EMPLOYER_SECTOR = "PRIVATE_FACILITIES_SERVICES"
EMPLOYER_REGION = "EASTERN"
HOUSING_PROJECT = "DEMO Housing Project C"
DIGITAL_CHANNEL = "DIGITAL_CHANNEL_B"

#: Every column this overlay adds to retail_facility_month. Declared in one
#: place because the schema, the catalogue and the governed views all have to
#: agree with it, and three lists that are maintained separately diverge.
COLUMNS: tuple[str, ...] = (
    # identity of the episode itself
    "episode_code", "episode_role", "episode_evidence_state",
    "episode_pocket_flag", "episode_pocket_label", "episode_eligible_flag",
    # C02 — acquisition quality
    "origination_exception_code", "acquisition_channel_code",
    "first_default_mob", "months_on_book", "vintage_cohort",
    "origination_dbr_ratio",
    # C03 — employer payroll
    "employer_group", "payroll_credit_sar", "payroll_missing_cycles",
    "payroll_evidence_state",
    # C04 — top-up stacking
    "topup_sequence", "months_since_last_topup", "bnpl_obligations_sar",
    "verified_obligations_to_income",
    # C05 — balloon funding
    "balloon_share_of_price", "balloon_funding_coverage_ratio",
    "balloon_funding_evidence_state",
    # C06 — recovery severity
    "vehicle_mileage_km", "recovery_channel", "expected_net_proceeds_sar",
    "net_proceeds_ratio", "valuation_evidence_state",
    # C07 — self-construction
    "housing_project_id", "construction_stage", "milestone_delay_days",
    "rent_finance_overlap_flag", "housing_outgoings_ratio",
    "undrawn_commitment_sar",
    # C08 — housing support reconciliation
    "support_expected_sar", "support_received_sar", "support_gap_cycles",
    "support_reconciliation_code",
    # C09 — pension transition
    "pension_transition_state", "pension_transition_date",
    "documented_pension_income_sar", "pension_income_replacement",
    "pension_obligations_to_income", "payment_stepdown_flag",
    "scheduled_payment_sar",
    # C10 — restructure and cure
    "restructure_strategy", "restructure_payments_met",
    "restructure_payments_due", "redefault_flag", "cure_evidence_state",
)


@dataclass
class _Case:
    """One episode's membership and mechanics, resolved against the book."""

    case_id: str
    opts: dict[str, Any]
    eligible: np.ndarray
    pocket: np.ndarray
    #: Facilities the mechanism is applied to. The issue population is whatever
    #: the case predicate finds afterwards, which is usually these and is never
    #: assumed to be.
    pressed: np.ndarray
    evidence: np.ndarray = field(default_factory=lambda: np.array([]))

    @property
    def product(self) -> str:
        return str(self.opts.get("product") or tax.PERSONAL_LOAN)


class EpisodeOverlay:
    """Assigns the nine episodes and applies their mechanisms month by month.

    Held as a collaborator of the simulation rather than as more methods on it:
    the simulation is already two and a half thousand lines, and an overlay
    that can be constructed, inspected and tested without running a 25-month
    book is worth the indirection.
    """

    def __init__(self, sim: Any) -> None:
        self.sim = sim
        self.cfg = sim.cfg
        self.enabled = bool(
            {k: v for k, v in (sim.cfg.episodes or {}).items()
             if not k.startswith("_")})
        self.cases: dict[str, _Case] = {}
        self.n = sim.fac.n
        self.m = sim.cust.n

        # Per-facility state the mechanisms carry between months.
        self.payroll_credit = np.full(self.n, np.nan)
        self.payroll_missing = np.zeros(self.n, dtype="int64")
        self.balloon_coverage = np.full(self.n, np.nan)
        self.net_proceeds = np.full(self.n, np.nan)
        self.recovery_delay = np.full(self.n, np.nan)
        self.milestone_delay = np.full(self.n, np.nan)
        self.outgoings_ratio = np.full(self.n, np.nan)
        self.support_expected = np.full(self.n, np.nan)
        self.support_received = np.full(self.n, np.nan)
        self.support_gap = np.zeros(self.n, dtype="int64")
        self.pension_income = np.full(self.n, np.nan)
        self.obligations_ratio = np.full(self.n, np.nan)
        self.bnpl = np.full(self.n, np.nan)
        self.payments_met = np.full(self.n, np.nan)
        self.redefault = np.zeros(self.n, dtype=bool)

        # Static labels, filled by assign().
        self.code = np.full(self.n, "", dtype=object)
        self.role = np.full(self.n, "", dtype=object)
        self.evidence_state = np.full(self.n, "", dtype=object)
        self.pocket_flag = np.zeros(self.n, dtype=bool)
        self.pocket_label = np.full(self.n, "", dtype=object)
        self.eligible_flag = np.zeros(self.n, dtype=bool)
        self.employer_group = np.full(self.n, "", dtype=object)
        self.project_id = np.full(self.n, "", dtype=object)
        self.exception_code = np.full(self.n, "", dtype=object)
        self.channel_code = np.full(self.n, "", dtype=object)
        self.recovery_channel = np.full(self.n, "", dtype=object)
        self.mileage = np.full(self.n, np.nan)
        self.topup_sequence = np.zeros(self.n, dtype="int64")
        self.months_since_topup = np.full(self.n, np.nan)
        self.construction_stage = np.full(self.n, "", dtype=object)
        self.rent_overlap = np.zeros(self.n, dtype=bool)
        self.support_code = np.full(self.n, "", dtype=object)
        self.pension_state = np.full(self.n, "", dtype=object)
        self.pension_date = np.full(self.n, None, dtype=object)
        self.stepdown = np.zeros(self.n, dtype=bool)
        self.restructure_strategy = np.full(self.n, "", dtype=object)
        self.cure_state = np.full(self.n, "", dtype=object)
        self.first_default_mob = np.full(self.n, np.nan)
        self.vintage_cohort = np.full(self.n, "", dtype=object)

        # When the adverse window opens, per case. Absolute month indices.
        self.start: dict[str, int] = {}
        self.behaviour_start: dict[str, int] = {}

        # A stable per-facility deviate.
        #
        # Without it every unpressed facility carries the same healthy value —
        # coverage exactly 0.55, a delay of exactly 20 days, exactly zero
        # missed payroll cycles — and the case rule fires for nobody outside
        # the pressed set. The six-window trend is then five zeroes and a
        # spike, and the comparator is zero, which makes every rate ratio
        # infinite and every chart a step function.
        #
        # That is not a presentational problem. A book in which NOBODY outside
        # one cohort ever has a low buffer or a late milestone is a book whose
        # baseline rate is a claim nobody could believe, and the first
        # question a credit officer asks a card is what the normal rate is.
        self.scatter = np.random.default_rng(
            int(self.cfg.seed) + 0x5CA77E4).normal(0.0, 1.0, size=self.n)

    # -- membership -------------------------------------------------------

    def assign(self) -> None:
        """Decide eligibility, the pocket and who the mechanism is applied to.

        Seeded from its own generator so that adding an episode cannot shift
        the draws the accepted Alpha calibration was measured under. That is
        not fastidiousness: the card episode's gates assert a 4.01x multiple
        on a specific book, and a shared random stream would move it.
        """
        if not self.enabled:
            return
        sim = self.sim
        rng = np.random.default_rng(int(self.cfg.seed) + 0xE9150DE)
        last = len(sim.dates)

        for case_id in CASES:
            opts = dict((self.cfg.episodes or {}).get(case_id) or {})
            if not opts:
                continue
            eligible = self._eligible(case_id, opts, rng)
            if not eligible.any():
                logger.warning("episode %s has no eligible population", case_id)
                continue

            months = max(int(opts.get("episode_months", 3)), 1)
            behaviour = max(int(opts.get("behaviour_months", 6)), months)
            self.start[case_id] = last - months
            self.behaviour_start[case_id] = last - behaviour

            pocket = self._pocket(case_id, eligible,
                                  float(opts["pocket_share"]), rng)
            current = self._current_cohort(case_id, eligible)
            pressed = self._pressed(current, pocket & current, opts, rng)
            evidence = self._evidence(pressed, opts, rng)

            case = _Case(case_id=case_id, opts=opts, eligible=eligible,
                         pocket=pocket, pressed=pressed, evidence=evidence)
            self.cases[case_id] = case

            self.eligible_flag |= eligible
            self.code = np.where(eligible, case_id, self.code)
            self.pocket_flag |= pocket
            self.pocket_label = np.where(
                pocket, str(opts.get("pocket") or ""), self.pocket_label)
            self.evidence_state = np.where(
                pressed, evidence, self.evidence_state)
            self.role = np.where(
                eligible,
                np.where(pressed, ep.ISSUE, ep.CONTROL),
                self.role)

            self._label(case_id, case, rng)
            logger.info(
                "episode %s: %d eligible, %d in pocket, %d pressed",
                case_id, int(eligible.sum()), int(pocket.sum()),
                int(pressed.sum()))

    # -- eligibility ------------------------------------------------------

    def _eligible(self, case_id: str, opts: dict[str, Any],
                  rng: np.random.Generator) -> np.ndarray:
        """The population the case's rate is a rate OF.

        Deliberately a real subset of the book rather than a random slice:
        balloon contracts really do mature, self-construction mortgages really
        are a small minority, and a denominator that was drawn at random would
        make every 'share of eligible' figure meaningless.
        """
        sim, fac = self.sim, self.sim.fac
        product = str(opts.get("product"))
        is_product = fac.product_code == product
        # Cards belong to the Alpha story and are never overlaid.
        is_product &= fac.product_code != tax.CREDIT_CARD
        kind = str(opts.get("eligibility"))
        last = len(sim.dates) - 1
        mob = np.maximum(last - fac.origination_month_index, 0)
        sub = self._subsegment()

        if kind == "mature_vintage_mob6_with_history":
            # Two vintages, both matured at the same month-on-book, labelled
            # apart by `vintage_cohort`. The comparator is not this vintage a
            # month ago — that is the same loans and the same episode — but an
            # EARLIER vintage that reached the same age before the episode
            # began. Matching the age is the whole point: the story's own
            # countercheck is that differing months-on-book imitate
            # deterioration.
            return is_product & (((mob >= 6) & (mob <= 8))
                                 | ((mob >= 15) & (mob <= 20)))
        if kind == "mature_restructure_with_history":
            return is_product & (mob >= 12) & (rng.random(self.n) < 0.30)
        if kind == "mature_vintage_mob6":
            # A vintage observed at exactly six months on book, so the outcome
            # window is matured and the same for everybody in it. The
            # comparator is an OLDER matured vintage, which only exists if the
            # mechanism is confined to the recent one — press every vintage
            # and the historical comparison the story rests on compares the
            # episode with itself.
            return is_product & (mob >= 6) & (mob <= 8)
        if kind == "mature_vintage_mob6_historical":
            return is_product & (mob >= 15) & (mob <= 20)
        if kind == "employer_financed":
            # Customers paid by an employer the bank can see a payroll credit
            # from. The affected employer group is a pocket INSIDE this, not
            # this: an employer-level cluster is only visible against the other
            # employers whose staff are financed here.
            status = sim.cust.employment_status[fac.customer_index]
            return is_product & np.isin(
                status, ["PRIVATE_SECTOR", "GOVERNMENT_RELATED"])
        if kind == "top_up_history":
            return is_product & np.isin(sub, ["TOP_UP", "REFINANCE_BUYOUT"])
        if kind == "balloon_within_90_days":
            # Ninety days is the card the story is about; the eligible
            # population is the contracts that reach their final payment
            # inside two quarters, so the 0-30 / 31-60 / 61-90 ladder S1 draws
            # has a band beyond it to compare against.
            balloon = np.nan_to_num(fac.balloon_payment, nan=0.0)
            to_balloon = fac.original_tenor_months - mob
            return is_product & (balloon > 0) & (to_balloon >= 0) & (to_balloon <= 6)
        if kind == "used_vehicle":
            return is_product & np.isin(sub, ["USED"])
        if kind == "self_construction":
            return is_product & np.isin(sub, ["LAND_AND_BUILD", "FIRST_HOME"]) \
                & (rng.random(self.n) < 0.45)
        if kind == "housing_support":
            supported = np.asarray(fac.housing_support, dtype=object) != \
                tax.HOUSING_SUPPORT_TYPES[0]
            return is_product & supported
        if kind == "pension_transition":
            # A DOCUMENTED transition: customers already drawing a pension,
            # plus a seeded share of long-serving employees whose transition
            # has been evidenced. Selected on the documented event and length
            # of service, never on age — the specification is explicit that
            # age is not the mechanism, and a cohort defined by a birthday
            # would be exactly the thing C09 exists to refuse.
            status = sim.cust.employment_status[fac.customer_index]
            tenure = sim.cust.employment_tenure_months_at_start[
                fac.customer_index]
            documented = (status == "RETIRED") | (
                (tenure >= 150) & (rng.random(self.n) < 0.55))
            return is_product & documented
        if kind == "mature_restructure":
            # Arrangements old enough to have a six-month observation window.
            return is_product & (mob >= 12) & (rng.random(self.n) < 0.16)
        raise ValueError(f"{case_id}: unknown eligibility rule {kind!r}")

    def _subsegment(self) -> np.ndarray:
        """The sub-product label, by the same rule the published frame uses.

        Recomputed rather than read off the simulation because the frame
        derives it inside `_month_frame` and the overlay has to decide
        eligibility before any frame exists. The rule is duplicated in exactly
        one direction: if the frame's rule changes, this is wrong, so the
        contract gates compare the two on the published book.
        """
        fac = self.sim.fac
        is_card = fac.product_code == tax.CREDIT_CARD
        is_auto = fac.product_code == tax.AUTO_LOAN
        purpose = np.asarray(fac.purpose, dtype=object)
        return np.where(
            is_card, "CARD",
            np.where(purpose != None, purpose,  # noqa: E711
                     np.where(is_auto, fac.vehicle_new_used,
                              "STANDARD"))).astype(object)

    def _current_cohort(self, case_id: str, eligible: np.ndarray) -> np.ndarray:
        """Which half of an eligible population the episode is allowed to touch.

        For the two outcome-window stories the eligible population deliberately
        contains BOTH the vintage under investigation and the matched
        historical one, so that the comparison can be made inside one dataset
        at one date. The mechanism may only reach the current half; pressing
        both would compare the episode with itself, which is the exact mistake
        the story's own countercheck warns about.

        Every other episode's eligible population is entirely current.
        """
        fac = self.sim.fac
        last = len(self.sim.dates) - 1
        mob = np.maximum(last - fac.origination_month_index, 0)
        if case_id == "C02":
            current = eligible & (mob <= 8)
            self.vintage_cohort = np.where(
                eligible,
                np.where(mob <= 8, "CURRENT_MATURE_MOB6",
                         "HISTORICAL_MATURE_MOB6"),
                self.vintage_cohort)
            return current
        if case_id == "C10":
            current = eligible & (mob <= 24)
            self.vintage_cohort = np.where(
                eligible,
                np.where(mob <= 24, "CURRENT_OBSERVATION_WINDOW",
                         "HISTORICAL_OBSERVATION_WINDOW"),
                self.vintage_cohort)
            return current
        return eligible

    def _pocket(self, case_id: str, eligible: np.ndarray, share: float,
                rng: np.random.Generator) -> np.ndarray:
        """The named concentration inside the eligible population.

        Where the pocket is a property the book already carries, it is read
        off the book. C05's pocket is "balloon at or above 35% of the original
        price": a coin toss at the right rate would produce a pocket whose
        own contracts contradicted its label, and S4's whole job is to show
        that the label and the contracts agree.

        Where the pocket is something the bank would have to go and find — an
        employer's payroll failing, a developer's milestones slipping, an
        approval route being used differently — it is seeded at the fixture's
        share, because there is nothing in a generated book to read it off.
        """
        fac = self.sim.fac
        draw = rng.random(self.n)
        if case_id == "C05":
            amount = np.maximum(fac.original_amount, 1.0)
            balloon_share = np.nan_to_num(fac.balloon_payment, nan=0.0) / amount
            large = balloon_share >= 0.35
            if (eligible & large).sum() >= 8:
                return eligible & large
            # A book with no large balloons cannot demonstrate this story on
            # its contracts. Said in the log rather than silently replaced.
            logger.warning(
                "C05: too few balloons at or above 35%% of price; falling "
                "back to a seeded pocket at the fixture's share")
        if case_id == "C06":
            # Vehicle age is on the contract. Mileage is assigned with it, so
            # the two agree rather than being two independent draws.
            age = np.nan_to_num(fac.vehicle_age_months, nan=0.0)
            old = age > 60
            if (eligible & old).sum() >= 8:
                return eligible & old
        return eligible & (draw < share)

    def _pressed(self, eligible: np.ndarray, pocket: np.ndarray,
                 opts: dict[str, Any], rng: np.random.Generator) -> np.ndarray:
        """Who the mechanism actually bites.

        Solved rather than guessed: given the issue rate the fixture shows and
        the share of cases that sits in the pocket, the incidence inside and
        outside follow arithmetically from the pocket's size. A pocket that is
        30% of the book and holds 80% of an 15% issue rate has an incidence of
        40% inside and 4.3% outside, and those are the two numbers S4 quotes.
        """
        issue_rate = float(opts["issue_rate"])
        case_share = float(opts["pocket_case_share"])
        n_eligible = int(eligible.sum())
        n_pocket = int((eligible & pocket).sum())
        n_outside = n_eligible - n_pocket
        if n_eligible == 0 or n_pocket == 0 or n_outside == 0:
            return np.zeros(self.n, dtype=bool)

        target = issue_rate * n_eligible
        # A pocket where EVERY member is a case is not a finding, it is a
        # definition: S4 would be quoting an incidence of 100% against an
        # outside rate, and a reader would be right to ask what was being
        # measured. Where the book's own pocket is smaller than the fixture's
        # share, the ceiling binds and the remainder is carried outside rather
        # than forced in.
        ceiling = float(self.cfg.episodes.get("_pocket_incidence_ceiling", 0.85)) \
            if isinstance(self.cfg.episodes.get("_pocket_incidence_ceiling"), (int, float)) \
            else 0.85
        inside_rate = min(target * case_share / n_pocket, ceiling)
        spilled = max(target * case_share - inside_rate * n_pocket, 0.0)
        outside_rate = min((target * (1.0 - case_share) + spilled) / n_outside,
                           ceiling)

        draw = rng.random(self.n)
        return np.where(pocket, draw < inside_rate, draw < outside_rate) & eligible

    def _evidence(self, pressed: np.ndarray, opts: dict[str, Any],
                  rng: np.random.Generator) -> np.ndarray:
        """How far each alert survives verification.

        The attrition is the substance of S1 and S3. An alert that turns out to
        be a statement-cycle artefact, a bank-account switch or a reporting lag
        is not a case, and a story that carried all of its alerts through to
        the policy cohort would be a story with no verification step in it.
        """
        detail = float(opts["detail_share"])
        corroborated = float(opts["corroborated_share"])
        draw = rng.random(self.n)
        state = np.full(self.n, "", dtype=object)
        state = np.where(pressed, ep.EV_TIMING, state)
        state = np.where(pressed & (draw < detail), ep.EV_VERIFIED, state)
        state = np.where(pressed & (draw < corroborated), ep.EV_CORROBORATED,
                         state)
        return state

    # -- static labels ----------------------------------------------------

    def _label(self, case_id: str, case: _Case,
               rng: np.random.Generator) -> None:
        """The dimension columns that make the pocket filterable everywhere."""
        sim, fac = self.sim, self.sim.fac
        eligible, pocket = case.eligible, case.pocket
        opts = case.opts

        if case_id == "C02":
            self.channel_code = np.where(
                pocket, DIGITAL_CHANNEL,
                np.where(eligible, "STANDARD_CHANNEL", self.channel_code))
            self.exception_code = np.where(
                pocket & case.pressed, "EXC-TENURE-RESIDUAL",
                np.where(pocket, "EXC-TENURE",
                         np.where(eligible, "NONE", self.exception_code)))
            # `vintage_cohort` is written by _current_cohort, which is the
            # only place that knows which half is which.
        elif case_id == "C03":
            self.employer_group = np.where(
                pocket, EMPLOYER_GROUP,
                np.where(eligible, "OTHER_FINANCED_EMPLOYER",
                         self.employer_group))
        elif case_id == "C04":
            self.topup_sequence = np.where(
                pocket, rng.integers(2, 5, size=self.n),
                np.where(eligible, 1, self.topup_sequence)).astype("int64")
            self.months_since_topup = np.where(
                pocket, rng.integers(1, 6, size=self.n).astype("float64"),
                np.where(eligible,
                         rng.integers(7, 30, size=self.n).astype("float64"),
                         self.months_since_topup))
        elif case_id == "C05":
            share = float(opts.get("balloon_share_of_price", 0.40))
            self.balloon_coverage = np.where(
                eligible, float(opts["coverage_from"]), self.balloon_coverage)
            self.mileage = self.mileage  # not this story's dimension
            self.pocket_label = np.where(
                pocket, f"balloon >= {share:.0%} of price, coverage < 25%",
                self.pocket_label)
        elif case_id == "C06":
            self.mileage = np.where(
                pocket, rng.integers(150_000, 290_000, size=self.n),
                np.where(eligible, rng.integers(30_000, 149_000, size=self.n),
                         self.mileage)).astype("float64")
            self.recovery_channel = np.where(
                pocket, "AUCTION_LOW_RECOVERY",
                np.where(eligible, "DEALER_NETWORK", self.recovery_channel))
            self.net_proceeds = np.where(
                eligible, float(opts["net_proceeds_from_sar"]),
                self.net_proceeds)
            self.recovery_delay = np.where(
                eligible, float(opts["recovery_delay_from_months"]),
                self.recovery_delay)
        elif case_id == "C07":
            self.project_id = np.where(
                pocket, HOUSING_PROJECT,
                np.where(eligible, "OTHER_DEVELOPMENT", self.project_id))
            stages = np.array(["FOUNDATION", "STRUCTURE", "FINISHING"],
                              dtype=object)
            self.construction_stage = np.where(
                eligible, stages[rng.integers(0, 3, size=self.n)],
                self.construction_stage)
            self.rent_overlap = np.where(
                pocket, True, np.where(eligible,
                                       rng.random(self.n) < 0.25,
                                       self.rent_overlap))
        elif case_id == "C08":
            self.support_code = np.where(
                pocket, "REC-UNMATCHED-REPEAT",
                np.where(eligible, "REC-MATCHED", self.support_code))
        elif case_id == "C09":
            self.pension_state = np.where(
                eligible, "DOCUMENTED_TRANSITION", self.pension_state)
            self.stepdown = np.where(
                pocket, False, np.where(eligible, True, self.stepdown))
        elif case_id == "C10":
            self.restructure_strategy = np.where(
                pocket, "PAYMENT_HOLIDAY",
                np.where(eligible, "INSTALMENT_RELIEF",
                         self.restructure_strategy))
            self.cure_state = np.where(
                pocket & case.pressed, "CURE_NOT_EVIDENCED",
                np.where(eligible, "CURE_EVIDENCED", self.cure_state))

    # -- per-month mechanisms ---------------------------------------------

    def ramp(self, case_id: str, t: int) -> np.ndarray:
        """How far into this episode's adverse window month `t` is, 0 to 1.

        A ramp rather than a step, for the same reason the card episode uses
        one: a deterioration that appears at full strength in a single month
        reads as an event, and these are cohorts under pressure rather than
        cohorts struck by lightning. It also puts the feature movement AHEAD
        of the arrears, which is what S3 is asking about.

        Two clocks, because the stories measure two different things. Most
        episodes run on the CALENDAR: something happened to this cohort over
        the last few months, and every member of it is the same number of
        months into it. C02 runs on MONTHS ON BOOK, because a cumulative
        default rate at month-on-book six is a statement about each loan's own
        age — facilities booked in different months have to reach MOB6 at
        their own MOB6, or the vintage is not matched and the whole comparison
        the story rests on is the thing it warns against.
        """
        case = self.cases.get(case_id)
        if case is None:
            return np.zeros(self.n)
        floor = float(case.opts.get("ramp_floor", 0.0))
        if str(case.opts.get("ramp_basis", "calendar")) == "mob":
            span = max(int(case.opts.get("episode_months", 6)), 1)
            mob = np.maximum(t - self.sim.fac.origination_month_index, 0)
            grown = np.clip(mob / span, 0.0, 1.0) ** 0.5
            # A weak underwriting decision is weak from the first instalment.
            # Without a floor the earliest this cohort can reach ninety days
            # is month four, and the story's MOB1-2 first defaults — the ones
            # that say the loan should not have been written — cannot happen
            # at all.
            return floor + (1.0 - floor) * grown
        start = self.behaviour_start.get(case_id)
        if start is None or t < start:
            return np.zeros(self.n)
        last = len(self.sim.dates) - 1
        span = max(last - start, 1)
        grown = float(min((t - start) / span, 1.0)) ** 0.5
        return np.full(self.n, floor + (1.0 - floor) * grown)

    def miss_logit(self, t: int) -> np.ndarray:
        """Added to the monthly miss probability's logit, alongside Alpha's.

        One additive term rather than nine, so the accepted card episode's
        single expression in `_facility_month` gains one summand and no
        branching. Cards are excluded by construction — no episode here has a
        card in its eligible population.
        """
        out = np.zeros(self.n)
        if not self.enabled:
            return out
        for case_id, case in self.cases.items():
            add = float(case.opts.get("miss_logit_add", 0.0))
            if not add:
                continue
            out = out + np.where(case.pressed, add * self.ramp(case_id, t), 0.0)
        return out

    def catch_up_logit(self, t: int) -> np.ndarray:
        """Subtracted from the monthly catch-up logit for the default stories.

        Two of the ten are measured over an OUTCOME window — C02's cumulative
        first default by month-on-book six, and C10's redefault within six
        months of an arrangement. Both need facilities that actually reach
        ninety days past due, and ninety days is three consecutive missed
        cycles. Raising the miss probability alone does not get there: an
        account in arrears is drawn against the catch-up probability instead,
        and at the book's default catch-up rate most of them cure in month one
        and never accumulate a second miss.

        So these two stories suppress catch-up as well as raising misses. That
        is the mechanism they are about — an arrangement that is not being
        kept, an approval that should not have been given — rather than a
        thumb on a number.
        """
        out = np.zeros(self.n)
        if not self.enabled:
            return out
        for case_id, case in self.cases.items():
            sub = float(case.opts.get("catch_up_logit_sub", 0.0))
            if not sub:
                continue
            out = out + np.where(case.pressed, sub * self.ramp(case_id, t), 0.0)
        return out

    def recovery_haircut(self, t: int) -> np.ndarray:
        """A multiplier on the secured recovery rate, for C06. One where absent.

        Applied to the expected net proceeds rather than to the collateral,
        which is the difference between "this asset is worth less" and "less
        of it reaches us, later". Only the second is what the story found, and
        only the second leaves loan-to-value — and therefore the behavioural
        score and the PD — untouched.
        """
        out = np.ones(self.n)
        if not self.enabled:
            return out
        for case_id, case in self.cases.items():
            opts = case.opts
            if "net_proceeds_to_sar" not in opts:
                continue
            frm = float(opts["net_proceeds_from_sar"])
            to = float(opts["net_proceeds_to_sar"])
            factor = 1.0 - (1.0 - to / frm) * self.ramp(case_id, t)
            out = np.where(case.pressed, out * factor, out)
        return out

    def recovery_delay_add(self, t: int) -> np.ndarray:
        """Extra months before a recovery is realised, for C06.

        The book's recovery delay is a per-product policy constant. C06's whole
        finding is that for one evidenced pocket it has doubled, and a delay
        that only appeared in a caption while the ECL discounting used the
        constant would be the narrative-only manipulation the specification
        rules out.
        """
        out = np.zeros(self.n)
        if not self.enabled:
            return out
        for case_id, case in self.cases.items():
            opts = case.opts
            if "recovery_delay_to_months" not in opts:
                continue
            frm = float(opts["recovery_delay_from_months"])
            to = float(opts["recovery_delay_to_months"])
            out = out + np.where(
                case.pressed, (to - frm) * self.ramp(case_id, t), 0.0)
        return out

    def month(self, t: int) -> None:
        """Advance the evidence each episode is diagnosed from.

        Called after the month's payments and arrears, so a trajectory is
        written against the state that produced it rather than against the
        state that is about to.
        """
        if not self.enabled:
            return
        for case_id, case in self.cases.items():
            getattr(self, f"_month_{case_id.lower()}", self._month_noop)(
                case, t, self.ramp(case_id, t))

    def _month_noop(self, case: _Case, t: int, ramp: np.ndarray) -> None:
        return

    def _month_c02(self, case: _Case, t: int, ramp: np.ndarray) -> None:
        sim, fac = self.sim, self.sim.fac
        mob = np.maximum(t - fac.origination_month_index, 0).astype("float64")
        self.months_since_topup = self.months_since_topup
        first = sim.state.first_default_idx
        defaulted = case.eligible & (first >= 0)
        self.first_default_mob = np.where(
            defaulted,
            np.maximum(first - fac.origination_month_index, 0).astype("float64"),
            self.first_default_mob)
        self._mob = mob

    def _month_c03(self, case: _Case, t: int, ramp: np.ndarray) -> None:
        """Salary credits stop, and the household buffer follows them down."""
        sim = self.sim
        opts = case.opts
        payroll_from = float(opts["payroll_from_sar"])
        payroll_to = float(opts["payroll_to_sar"])
        value = payroll_from + (payroll_to - payroll_from) * ramp
        self.payroll_credit = np.where(
            case.eligible, np.where(case.pressed, value, payroll_from),
            self.payroll_credit)
        in_window = t >= self.start[case.case_id]
        # Everybody else's payroll behaves like the book says it does: the
        # simulation already records whether this customer's salary landed,
        # and a few of them have missed two in a row without an employer
        # failing. That is the baseline the card is measured against.
        ci = sim.fac.customer_index
        missed_now = sim.h_salary_missed[ci, -1] > 0
        natural = np.where(missed_now, self.payroll_missing + 1, 0)
        self.payroll_missing = np.where(
            case.eligible,
            np.where(case.pressed & in_window,
                     np.minimum(self.payroll_missing + 1, 6),
                     np.minimum(natural, 6)),
            self.payroll_missing).astype("int64")
        # The real lever: the customer's own account balance, which is what the
        # behavioural buffer feature is computed from.
        if case.pressed.any():
            ci = sim.fac.customer_index[case.pressed]
            # `ramp` is per FACILITY and the balance is per CUSTOMER, so it is
            # indexed down to the pressed facilities before it is used. A
            # scalar here would be right today (this story runs on the
            # calendar clock) and silently wrong the moment it did not.
            keep = 1.0 - 0.72 * ramp[case.pressed]
            np.multiply.at(sim.cust_bank_balance, ci, keep)

    def _month_c04(self, case: _Case, t: int, ramp: np.ndarray) -> None:
        """New external obligations arrive and residual income drains."""
        sim, opts = self.sim, case.opts
        frm, to = (float(opts["obligations_to_income_from"]),
                   float(opts["obligations_to_income_to"]))
        healthy = np.clip(frm + 0.045 * self.scatter, 0.10, 0.95)
        self.obligations_ratio = np.where(
            case.eligible,
            np.where(case.pressed, healthy + (to - frm) * ramp, healthy),
            self.obligations_ratio)
        self.bnpl = np.where(
            case.eligible,
            np.where(case.pressed, 900.0 + 2_100.0 * ramp, 300.0),
            self.bnpl)
        if case.pressed.any() and float(np.max(ramp)) > 0:
            ci = sim.fac.customer_index[case.pressed]
            # Applied as a monthly increment so the obligation series is a
            # series, not a step that appears in one snapshot.
            np.multiply.at(sim.cust_external_obligations, ci,
                           1.0 + 0.085 * ramp[case.pressed])

    def _month_c05(self, case: _Case, t: int, ramp: np.ndarray) -> None:
        """Liquid coverage of a contractual balloon falls. The balloon does not."""
        opts = case.opts
        frm, to = float(opts["coverage_from"]), float(opts["coverage_to"])
        healthy = np.clip(frm + 0.16 * self.scatter, 0.02, 1.4)
        self.balloon_coverage = np.where(
            case.eligible,
            np.where(case.pressed, healthy + (to - frm) * ramp, healthy),
            self.balloon_coverage)

    def _month_c06(self, case: _Case, t: int, ramp: np.ndarray) -> None:
        """Collateral realises less and takes longer. The borrower is unchanged.

        This is the negative control, so the only things that move are the
        recovery assumptions: expected net proceeds, the delay, and through
        them the collateral the LGD model reads. No pressure is applied to
        payments, utilisation or any behavioural input.
        """
        sim, opts = self.sim, case.opts
        frm, to = (float(opts["net_proceeds_from_sar"]),
                   float(opts["net_proceeds_to_sar"]))
        healthy = np.clip(frm * (1.0 + 0.065 * self.scatter), frm * 0.55,
                          frm * 1.5)
        self.net_proceeds = np.where(
            case.eligible,
            np.where(case.pressed, healthy + (to - frm) * ramp, healthy),
            self.net_proceeds)
        dfrm, dto = (float(opts["recovery_delay_from_months"]),
                     float(opts["recovery_delay_to_months"]))
        self.recovery_delay = np.where(
            case.eligible,
            np.where(case.pressed, dfrm + (dto - dfrm) * ramp, dfrm),
            self.recovery_delay)
        # NOTHING here touches the collateral value, the balance, the payments
        # or any behavioural input. The finding is that the RECOVERY on a
        # defaulted contract realises less and lands later; marking the asset
        # down instead would move loan-to-value, which is a behavioural
        # feature, which would move the score and the PD — and a generator
        # that quietly worsened the borrower to make the ECL move would be
        # manufacturing the evidence this story exists to reject.

    def _month_c07(self, case: _Case, t: int, ramp: np.ndarray) -> None:
        """Milestones slip and housing outgoings rise against verified income."""
        sim, opts = self.sim, case.opts
        dfrm, dto = float(opts["delay_from_days"]), float(opts["delay_to_days"])
        healthy_delay = np.clip(dfrm + 28.0 * self.scatter, 0.0, 200.0)
        self.milestone_delay = np.where(
            case.eligible,
            np.where(case.pressed, healthy_delay + (dto - dfrm) * ramp,
                     healthy_delay),
            self.milestone_delay)
        ofrm, oto = float(opts["outgoings_from"]), float(opts["outgoings_to"])
        self.outgoings_ratio = np.where(
            case.eligible,
            np.where(case.pressed, ofrm + (oto - ofrm) * ramp, ofrm),
            self.outgoings_ratio)
        if case.pressed.any() and float(np.max(ramp)) > 0:
            ci = sim.fac.customer_index[case.pressed]
            np.multiply.at(sim.cust_bank_balance, ci,
                           1.0 - 0.86 * ramp[case.pressed])

    def _month_c08(self, case: _Case, t: int, ramp: np.ndarray) -> None:
        """An expected support credit does not post, repeatedly."""
        sim, opts = self.sim, case.opts
        expected = 3_200.0
        self.support_expected = np.where(
            case.eligible, expected, self.support_expected)
        in_window = t >= self.start[case.case_id]
        self.support_received = np.where(
            case.eligible,
            np.where(case.pressed & in_window, 0.0, expected),
            self.support_received)
        # A reconciliation that fails occasionally for everybody is the
        # baseline; the finding is that for one pocket it keeps failing.
        stumble = (self.scatter > 1.85) & ((t + self.sim.fac.customer_index) % 7 == 0)
        self.support_gap = np.where(
            case.eligible,
            np.where(case.pressed & in_window,
                     np.minimum(self.support_gap + 1, 6),
                     np.where(stumble, np.minimum(self.support_gap + 1, 2), 0)),
            self.support_gap).astype("int64")
        if case.pressed.any() and in_window:
            ci = sim.fac.customer_index[case.pressed]
            np.subtract.at(sim.cust_bank_balance, ci, expected * 0.55)
            np.maximum(sim.cust_bank_balance, 0.0, out=sim.cust_bank_balance)

    def _month_c09(self, case: _Case, t: int, ramp: np.ndarray) -> None:
        """Recurring income steps down. The scheduled payment does not.

        The replacement is proportional to THIS customer's own verified
        income rather than a constant, because the card's rule is a ratio —
        scheduled payment over documented income — and a constant denominator
        would make that ratio a statement about how large the instalment
        happens to be rather than about the transition. The pocket would not
        concentrate, and S4 would have nothing to find.
        """
        sim, opts = self.sim, case.opts
        frm, to = float(opts["income_from_sar"]), float(opts["income_to_sar"])
        replacement = to / frm
        ci = sim.fac.customer_index
        growth = (1.0 + 0.0022) ** t
        own = (sim.cust.base_salary_sar[ci] + sim.cust.other_income_sar[ci]) * growth
        # A documented transition that HAS a contractual step-down still
        # replaces less than the salary did, by a varying amount.
        healthy = own * np.clip(1.0 - 0.06 * np.abs(self.scatter), 0.72, 1.0)
        stepped = healthy * (1.0 - (1.0 - replacement) * ramp)
        self.pension_income = np.where(
            case.eligible, np.where(case.pressed, stepped, healthy),
            self.pension_income)
        if case.pressed.any() and float(np.max(ramp)) > 0:
            ci = sim.fac.customer_index[case.pressed]
            np.multiply.at(sim.cust_bank_balance, ci,
                           1.0 - 0.55 * ramp[case.pressed])

    def _month_c10(self, case: _Case, t: int, ramp: np.ndarray) -> None:
        """A mature arrangement is not being kept, and the cure was not evidenced."""
        sim, opts = self.sim, case.opts
        due = float(opts.get("payments_due", 3))
        met = float(opts.get("payments_met", 1))
        self.payments_met = np.where(
            case.eligible,
            np.where(case.pressed, met, due),
            self.payments_met)
        # A redefault is a DEFAULT after an arrangement, not an arrear after
        # one. Read off the state machine's own default flag so the card's
        # count and the book's stage-3 population cannot disagree.
        window_opened = self.behaviour_start[case.case_id]
        redefaulted = (sim.state.latest_default_idx >= window_opened) & \
            sim.state.default_flag
        self.redefault = np.where(case.eligible, redefaulted, self.redefault)
        self.cure_state = np.where(
            case.eligible & redefaulted, "CURE_NOT_EVIDENCED",
            np.where(case.eligible, "CURE_EVIDENCED", self.cure_state))
        if case.pressed.any() and float(np.max(ramp)) > 0:
            ci = sim.fac.customer_index[case.pressed]
            np.multiply.at(sim.cust_bank_balance, ci,
                           1.0 - 0.6 * ramp[case.pressed])

    # -- the columns ------------------------------------------------------

    def columns(self, t: int, rows: np.ndarray,
                frame: pd.DataFrame | None = None) -> pd.DataFrame:
        """This month's episode columns, for the live facilities only.

        `frame` is the month's assembled row, passed in so that the ratios a
        card's own rule is written against — expected proceeds over the
        valuation they were set from, obligations over documented income —
        are PUBLISHED columns rather than something each reader recomputes.
        A rule whose left-hand side does not exist in the data is a rule
        nobody can check, filter on or export.

        Always returns every declared column, even when the overlay is not
        configured. A schema that changes shape depending on configuration is
        a schema two readers disagree about.
        """
        fac, sim = self.sim.fac, self.sim
        take = rows
        mob = np.maximum(t - fac.origination_month_index, 0).astype("float64")
        support_code = np.where(
            (self.support_gap >= 2) & self.eligible_flag,
            "REC-UNMATCHED-REPEAT", self.support_code)

        # C09's two published ratios. The replacement says how much of the
        # customer's verified income the documented pension actually replaces;
        # the obligation ratio says what their existing total debt service
        # costs against it. Neither on its own is the finding: a low
        # replacement with small commitments is affordable, and a high
        # obligation ratio that was already there before the transition is not
        # a transition story.
        pension = self.pension_income[take]
        if frame is not None and "verified_total_monthly_income_sar" in frame:
            income = pd.to_numeric(
                frame["verified_total_monthly_income_sar"],
                errors="coerce").to_numpy(dtype="float64")
            obligations = pd.to_numeric(
                frame["monthly_total_credit_obligations_sar"],
                errors="coerce").to_numpy(dtype="float64")
        else:
            income = np.full(len(take), np.nan)
            obligations = np.full(len(take), np.nan)
        replacement = np.where(
            np.isnan(pension) | ~(income > 0), np.nan, pension / income)
        obligations_ratio = np.where(
            np.isnan(pension) | ~(pension > 0), np.nan, obligations / pension)

        data = {
            "episode_code": self.code[take],
            "episode_role": self.role[take],
            "episode_evidence_state": self.evidence_state[take],
            "episode_pocket_flag": self.pocket_flag[take],
            "episode_pocket_label": self.pocket_label[take],
            "episode_eligible_flag": self.eligible_flag[take],

            "origination_exception_code": self.exception_code[take],
            "acquisition_channel_code": self.channel_code[take],
            "first_default_mob": self.first_default_mob[take],
            "months_on_book": mob[take],
            "vintage_cohort": self.vintage_cohort[take],
            "origination_dbr_ratio": pd.to_numeric(
                sim.orig["origination_debt_burden_ratio"],
                errors="coerce").to_numpy()[take],

            "employer_group": self.employer_group[take],
            "payroll_credit_sar": self.payroll_credit[take],
            "payroll_missing_cycles": self.payroll_missing[take],
            "payroll_evidence_state": np.where(
                self.payroll_missing[take] >= 2, "VERIFIED_INTERRUPTION",
                np.where(self.payroll_missing[take] == 1,
                         "SINGLE_CYCLE_UNVERIFIED", "")),

            "topup_sequence": self.topup_sequence[take],
            "months_since_last_topup": self.months_since_topup[take],
            "bnpl_obligations_sar": self.bnpl[take],
            "verified_obligations_to_income": self.obligations_ratio[take],

            "balloon_share_of_price": np.where(
                np.nan_to_num(fac.balloon_payment, nan=0.0)[take] > 0,
                np.nan_to_num(fac.balloon_payment, nan=0.0)[take]
                / np.maximum(fac.original_amount[take], 1.0), np.nan),
            "balloon_funding_coverage_ratio": self.balloon_coverage[take],
            "balloon_funding_evidence_state": np.where(
                self.balloon_coverage[take] < 0.25, "VERIFIED_FUNDING_GAP",
                np.where(np.isnan(self.balloon_coverage[take]), "",
                         "FUNDING_EVIDENCED")),

            "vehicle_mileage_km": self.mileage[take],
            "recovery_channel": self.recovery_channel[take],
            "expected_net_proceeds_sar": self.net_proceeds[take],
            "net_proceeds_ratio": np.where(
                np.isnan(self.net_proceeds[take]), np.nan,
                self.net_proceeds[take] / 56_000.0),
            "valuation_evidence_state": np.where(
                self.recovery_delay[take] > 6.0, "VALIDATED_REVISION",
                np.where(np.isnan(self.recovery_delay[take]), "",
                         "CURRENT_VALUATION")),

            "housing_project_id": self.project_id[take],
            "construction_stage": self.construction_stage[take],
            "milestone_delay_days": self.milestone_delay[take],
            "rent_finance_overlap_flag": self.rent_overlap[take],
            "housing_outgoings_ratio": self.outgoings_ratio[take],
            "undrawn_commitment_sar": np.where(
                self.project_id[take] != "",
                np.maximum(fac.original_amount[take]
                           - sim.state.balance[take], 0.0), np.nan),

            "support_expected_sar": self.support_expected[take],
            "support_received_sar": self.support_received[take],
            "support_gap_cycles": self.support_gap[take],
            "support_reconciliation_code": support_code[take],

            "pension_transition_state": self.pension_state[take],
            "pension_transition_date": self.pension_date[take],
            "documented_pension_income_sar": self.pension_income[take],
            "pension_income_replacement": replacement,
            "pension_obligations_to_income": obligations_ratio,
            "payment_stepdown_flag": self.stepdown[take],
            "scheduled_payment_sar": sim.state.scheduled_payment[take],

            "restructure_strategy": self.restructure_strategy[take],
            "restructure_payments_met": self.payments_met[take],
            "restructure_payments_due": np.where(
                self.restructure_strategy[take] != "", 3.0, np.nan),
            "redefault_flag": self.redefault[take],
            "cure_evidence_state": self.cure_state[take],
        }
        return pd.DataFrame(data)

    @staticmethod
    def empty_columns(rows: int) -> pd.DataFrame:
        """The same columns, all absent, when no episode is configured."""
        return pd.DataFrame({c: pd.Series([None] * rows, dtype=object)
                             for c in COLUMNS})
