"""The ten stories, as canonical dimensions of the book rather than card text.

The defect this exists for
--------------------------
The quickest way to put ten Requires Attention cards on a Cockpit is to write
ten titles and ten paragraphs. It survives exactly one question: the reader
clicks Investigate, asks which customers, and there is nothing underneath —
no identifiers to export, no facilities to price, no pocket to compare against
the rest of the book, and no way for Early Warning to show the same people.

So an episode here is a *dimension*. Each of the ten names the columns in
`retail_facility_month` that carry it, the predicate that decides whether a
facility is in its issue population, and the scope each of its five steps
narrows to. The card, the drawer, the thread, Borrower 360, the workbook and
What-If all read those same columns, which is what makes the customer list the
same list in six places instead of six lists that agree today.

What is in the config and what is here
--------------------------------------
`config/retail_episodes.json` holds what the specification and the worked
workbook say: titles, the exact prompts, chart specifications, policy clauses,
counterchecks, and the miniature fixture's numbers. It is generated by
`scripts/build_episode_config.py` so it cannot drift from the attachments.

This module holds what only code can say: which column means which thing, how
an issue is decided, and how a step narrows. Those are engineering decisions
about the installed book, not quotations from a document.

The fixture is a calibration target, not an answer
--------------------------------------------------
Every `fixture_*` number reachable from here exists to be compared against the
generated book — is the rate ratio of the right order, does the pocket hold the
right share of the cases, does the score move in the right direction by roughly
the right amount. None of them is ever displayed. A figure a reader sees is
measured from the active bundle at the active date, or it is not shown.
"""

from __future__ import annotations

import functools
import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from backend.retail import metrics_contract as mc

CONFIG = Path("config/retail_episodes.json")

#: Bumped when a predicate or a dimension column below changes meaning.
VERSION = "retail-episodes-1.0.0"

#: The column that says which story a facility belongs to, and in what role.
#: Written by the generator, carried into every governed view, and the reason
#: a pocket exists in Early Warning as well as in the Cockpit.
EPISODE_COLUMN = "episode_code"
ROLE_COLUMN = "episode_role"
EVIDENCE_COLUMN = "episode_evidence_state"

#: What a facility is to its story.
ISSUE = "ISSUE"            #: Meets the case predicate at the reporting date.
COMPARATOR = "COMPARATOR"  #: The matched population the issue is measured against.
CONTROL = "CONTROL"        #: Eligible, in the pocket's product, neither of the above.
ROLES = (ISSUE, COMPARATOR, CONTROL)

#: How far the evidence for one facility has actually been taken. Four states,
#: not a boolean, because "we looked and found nothing" and "we have not looked"
#: are different answers and a case built on the second is not a case.
EV_ALERTED = "ALERTED"                    #: The rule fired. Nothing verified yet.
EV_TIMING = "TIMING_OR_EXCEPTION"         #: Explained by timing, a switch or a
                                          #: documentary exception. Not stress.
EV_VERIFIED = "VERIFIED_DETAIL"           #: The mechanism is evidenced.
EV_CORROBORATED = "VERIFIED_CORROBORATED" #: Evidenced AND independently
                                          #: corroborated by a second source.
EVIDENCE_STATES = (EV_ALERTED, EV_TIMING, EV_VERIFIED, EV_CORROBORATED)


@dataclass(frozen=True)
class Step:
    """One of the six snapshots of a story."""

    step: str
    chip_label: str
    prompt: str
    scope_label: str
    chart: str
    metric_ids: tuple[str, ...]
    #: The miniature example's count at this step. A calibration target.
    fixture_customer_n: int
    fixture_expectation: str


@dataclass(frozen=True)
class Episode:
    """One story, as a dimension of the book."""

    case_id: str
    title: str
    card_measure: str
    severity: str
    #: The specification's own family label — CREDIT_CARD, PERSONAL_FINANCE,
    #: AUTO_FINANCE, HOME_FINANCE. Not the book's product code.
    product_family: str
    #: The book's product code the episode is generated into.
    product: str
    pocket_label: str
    #: The columns in retail_facility_month that carry this pocket. Every
    #: governed view that offers this pocket as a filter offers these.
    dimension_columns: tuple[str, ...]
    #: The evidence columns the story's S1 and S3 decompose.
    evidence_columns: tuple[str, ...]
    #: Which scoring model the diagnosis rests on: application for the
    #: underwriting-quality and vintage stories, behaviour for the rest.
    diagnosis_model: str
    #: What is counted — a facility or a distinct customer.
    grain: str
    #: The metric whose window the card's headline is measured over.
    headline_metric: str
    #: The evidence state each step narrows to.
    step_evidence: dict[str, str]
    policy_id: str
    policy_version: str
    policy_clauses: tuple[str, ...]
    research: tuple[str, ...]
    countercheck: str
    steps: tuple[Step, ...]
    policy_actions: tuple[dict[str, Any], ...]
    fixture: dict[str, Any] = field(default_factory=dict)

    def step_by_id(self, step_id: str) -> Step | None:
        return next((s for s in self.steps if s.step == step_id), None)

    @property
    def chips(self) -> tuple[Step, ...]:
        """The five prompts that sit above the composer. S0 is not a chip —
        it is the carried context the thread opens on."""
        return tuple(s for s in self.steps if s.step != "S0")


# ---------------------------------------------------------------------------
# What only code can say: which column means which thing.
# ---------------------------------------------------------------------------
#
# `product` is the book's own code, so an episode lands in a real product's
# population rather than in a parallel one. `dimension_columns` are what the
# Early Warning drilldown and the Cockpit filter both offer — the specification
# is explicit that a pocket must be filterable in BOTH, and a pocket that is
# only a phrase in an answer cannot be.

_DIMENSIONS: dict[str, dict[str, Any]] = {
    "C01": {
        "product": "CREDIT_CARD",
        "dimension_columns": ("product_subsegment", "origination_score_band"),
        "evidence_columns": ("utilisation_ratio", "payment_to_statement_ratio",
                             "dpd", "dpd_bucket"),
        "diagnosis_model": "behaviour",
        "grain": "facility",
        "headline_metric": mc.AFFECTED_POPULATION.metric_id,
        "step_evidence": {"S1": EV_VERIFIED, "S2": EV_VERIFIED,
                          "S3": EV_CORROBORATED, "S4": EV_CORROBORATED,
                          "S5": EV_CORROBORATED},
    },
    "C02": {
        "product": "PERSONAL_LOAN",
        "dimension_columns": ("origination_channel", "origination_exception_code",
                              "origination_employment_tenure_months"),
        "evidence_columns": ("months_on_book", "first_default_mob",
                             "origination_dbr_ratio",
                             "origination_employment_tenure_months"),
        # The vintage story. Its whole point is that the ORIGINAL decision was
        # weak, so decomposing the behavioural score would answer a question
        # nobody asked.
        "diagnosis_model": "application",
        "grain": "facility",
        "headline_metric": mc.ODR.metric_id,
        "step_evidence": {"S1": EV_VERIFIED, "S2": EV_VERIFIED,
                          "S3": EV_CORROBORATED, "S4": EV_CORROBORATED,
                          "S5": EV_CORROBORATED},
    },
    "C03": {
        "product": "PERSONAL_LOAN",
        "dimension_columns": ("employer_id", "employer_sector", "region"),
        "evidence_columns": ("payroll_credit_sar", "payroll_missing_cycles",
                             "balance_buffer_months",
                             "payroll_evidence_state"),
        "diagnosis_model": "behaviour",
        "grain": "customer",
        "headline_metric": mc.AFFECTED_POPULATION.metric_id,
        "step_evidence": {"S1": EV_VERIFIED, "S2": EV_VERIFIED,
                          "S3": EV_CORROBORATED, "S4": EV_CORROBORATED,
                          "S5": EV_CORROBORATED},
    },
    "C04": {
        "product": "PERSONAL_LOAN",
        "dimension_columns": ("months_since_last_topup", "topup_sequence"),
        "evidence_columns": ("monthly_external_credit_obligations_sar",
                             "verified_obligations_to_income",
                             "disposable_income_sar",
                             "bnpl_obligations_sar"),
        "diagnosis_model": "behaviour",
        "grain": "customer",
        "headline_metric": mc.AFFECTED_POPULATION.metric_id,
        "step_evidence": {"S1": EV_VERIFIED, "S2": EV_VERIFIED,
                          "S3": EV_CORROBORATED, "S4": EV_CORROBORATED,
                          "S5": EV_CORROBORATED},
    },
    "C05": {
        "product": "AUTO_LOAN",
        "dimension_columns": ("balloon_band", "months_to_balloon"),
        "evidence_columns": ("balloon_payment_sar",
                             "balloon_funding_coverage_ratio",
                             "balloon_funding_evidence_state"),
        "diagnosis_model": "behaviour",
        "grain": "facility",
        "headline_metric": mc.AFFECTED_POPULATION.metric_id,
        "step_evidence": {"S1": EV_VERIFIED, "S2": EV_VERIFIED,
                          "S3": EV_CORROBORATED, "S4": EV_CORROBORATED,
                          "S5": EV_CORROBORATED},
    },
    "C06": {
        "product": "AUTO_LOAN",
        "dimension_columns": ("vehicle_age_months", "vehicle_mileage_km",
                              "recovery_channel"),
        "evidence_columns": ("expected_net_proceeds_sar",
                             "recovery_delay_months", "lgd_base",
                             "collateral_valuation_date"),
        # The negative control. The borrower's score and PD barely move; the
        # loss is in severity. A behavioural decomposition here would have to
        # manufacture a deterioration that is not in the data.
        "diagnosis_model": "recovery",
        "grain": "facility",
        "headline_metric": mc.ECL.metric_id,
        "step_evidence": {"S1": EV_VERIFIED, "S2": EV_VERIFIED,
                          "S3": EV_CORROBORATED, "S4": EV_CORROBORATED,
                          "S5": EV_CORROBORATED},
    },
    "C07": {
        "product": "HOME_LOAN",
        "dimension_columns": ("housing_project_id", "construction_stage"),
        "evidence_columns": ("milestone_delay_days",
                             "rent_finance_overlap_flag",
                             "housing_outgoings_ratio",
                             "undrawn_commitment_sar"),
        "diagnosis_model": "behaviour",
        "grain": "customer",
        "headline_metric": mc.AFFECTED_POPULATION.metric_id,
        "step_evidence": {"S1": EV_VERIFIED, "S2": EV_VERIFIED,
                          "S3": EV_CORROBORATED, "S4": EV_CORROBORATED,
                          "S5": EV_CORROBORATED},
    },
    "C08": {
        "product": "HOME_LOAN",
        "dimension_columns": ("housing_support_type",
                              "support_reconciliation_code"),
        "evidence_columns": ("support_expected_sar", "support_received_sar",
                             "support_gap_cycles", "balance_buffer_months"),
        "diagnosis_model": "behaviour",
        "grain": "customer",
        "headline_metric": mc.AFFECTED_POPULATION.metric_id,
        "step_evidence": {"S1": EV_VERIFIED, "S2": EV_VERIFIED,
                          "S3": EV_CORROBORATED, "S4": EV_CORROBORATED,
                          "S5": EV_CORROBORATED},
    },
    "C09": {
        "product": "PERSONAL_LOAN",
        "dimension_columns": ("pension_transition_state",
                              "payment_stepdown_flag"),
        "evidence_columns": ("documented_pension_income_sar",
                             "verified_total_monthly_income_sar",
                             "scheduled_payment_sar",
                             "pension_transition_date"),
        "diagnosis_model": "behaviour",
        "grain": "customer",
        "headline_metric": mc.AFFECTED_POPULATION.metric_id,
        "step_evidence": {"S1": EV_VERIFIED, "S2": EV_VERIFIED,
                          "S3": EV_CORROBORATED, "S4": EV_CORROBORATED,
                          "S5": EV_CORROBORATED},
    },
    "C10": {
        "product": "PERSONAL_LOAN",
        "dimension_columns": ("restructure_strategy", "cure_evidence_state"),
        "evidence_columns": ("restructure_date", "restructure_payments_met",
                             "restructure_payments_due", "redefault_flag",
                             "disposable_income_sar"),
        "diagnosis_model": "behaviour",
        "grain": "facility",
        "headline_metric": mc.ODR.metric_id,
        "step_evidence": {"S1": EV_VERIFIED, "S2": EV_VERIFIED,
                          "S3": EV_CORROBORATED, "S4": EV_CORROBORATED,
                          "S5": EV_CORROBORATED},
    },
}


# ---------------------------------------------------------------------------
# Loading
# ---------------------------------------------------------------------------


@functools.lru_cache(maxsize=1)
def _config() -> dict[str, Any]:
    if not CONFIG.exists():
        raise FileNotFoundError(
            f"{CONFIG} is missing. Run "
            f"`python scripts/build_episode_config.py` to regenerate it from "
            f"the specification and the worked workbook.")
    return json.loads(CONFIG.read_text(encoding="utf-8"))


@functools.lru_cache(maxsize=1)
def all_episodes() -> tuple[Episode, ...]:
    config = _config()
    out: list[Episode] = []
    for raw in config["episodes"]:
        case_id = raw["case_id"]
        dims = _DIMENSIONS.get(case_id)
        if dims is None:
            raise KeyError(
                f"{case_id} is in the config but has no dimension mapping. An "
                f"episode with no columns is card text, and card text is the "
                f"thing this module exists to make impossible.")
        steps = tuple(
            Step(step=s["step"], chip_label=s["chip_label"], prompt=s["prompt"],
                 scope_label=s["scope_label"], chart=s["chart"],
                 metric_ids=tuple(s["metric_ids"]),
                 fixture_customer_n=int(s["fixture_customer_n"]),
                 fixture_expectation=s["fixture_expectation"])
            for s in raw["steps"])
        out.append(Episode(
            case_id=case_id,
            title=raw["title"],
            card_measure=raw["card_measure"],
            severity=raw["severity"],
            product_family=raw["product_family"],
            pocket_label=raw["pocket_label"],
            policy_id=raw["policy_id"],
            policy_version=raw["policy_version"],
            policy_clauses=tuple(raw["policy_clauses"]),
            research=tuple(raw["research"]),
            countercheck=raw["countercheck"],
            steps=steps,
            policy_actions=tuple(raw["policy_actions"]),
            fixture=raw["fixture"],
            product=dims["product"],
            dimension_columns=tuple(dims["dimension_columns"]),
            evidence_columns=tuple(dims["evidence_columns"]),
            diagnosis_model=dims["diagnosis_model"],
            grain=dims["grain"],
            headline_metric=dims["headline_metric"],
            step_evidence=dict(dims["step_evidence"]),
        ))
    return tuple(out)


def by_id(case_id: str) -> Episode | None:
    return next((e for e in all_episodes() if e.case_id == case_id), None)


def case_ids() -> tuple[str, ...]:
    return tuple(e.case_id for e in all_episodes())


def pocket_dimensions() -> dict[str, tuple[str, ...]]:
    """Every pocket dimension, for the Early Warning drilldown and the Cockpit
    filter to offer the same list."""
    return {e.case_id: e.dimension_columns for e in all_episodes()}


def dimension_columns() -> tuple[str, ...]:
    """The union, deduplicated and ordered — what a governed view must carry
    for all ten pockets to be filterable in it."""
    seen: dict[str, None] = {}
    for episode in all_episodes():
        for column in episode.dimension_columns:
            seen[column] = None
    return tuple(seen)


def evidence_columns() -> tuple[str, ...]:
    seen: dict[str, None] = {}
    for episode in all_episodes():
        for column in episode.evidence_columns:
            seen[column] = None
    return tuple(seen)


def disclosure() -> str:
    return _config()["disclosure"]


def config_version() -> str:
    return _config()["config_version"]


def reset_cache() -> None:
    _config.cache_clear()
    all_episodes.cache_clear()


# ---------------------------------------------------------------------------
# The case predicates
# ---------------------------------------------------------------------------
#
# What decides whether a facility is in a case's issue population, evaluated
# over the PUBLISHED columns at the declared date. The generator decides who
# the mechanism is applied to; these decide who the case is about, and the two
# are deliberately not the same function. A facility the mechanism pressed but
# that recovered is not a case, and a facility the mechanism never touched but
# that meets the rule is.
#
# Every threshold is named and carried into the cohort snapshot's predicate
# tree, so a reader can see in the drawer, in the breadcrumb and in the
# exported workbook exactly what was counted.

#: Two consecutive cycles, because one missing salary credit is an account
#: switch or a holiday shift about as often as it is an interruption.
PAYROLL_MISSING_CYCLES = 2
#: Verified monthly commitments at or above half of verified income.
OBLIGATIONS_TO_INCOME = 0.50
#: Liquid coverage of a contractual final payment.
BALLOON_COVERAGE = 0.25
#: Expected net proceeds as a share of the valuation they were set from.
NET_PROCEEDS_RATIO = 0.80
#: A construction delay past the policy-defined tolerance, with a household
#: that has less than a month of buffer behind it.
MILESTONE_DELAY_DAYS = 90
LOW_BUFFER_MONTHS = 1.0
#: Two unresolved posting cycles, not one.
SUPPORT_GAP_CYCLES = 2
#: Total monthly credit obligations as a share of documented recurring
#: income. Total rather than this facility's instalment: a customer with three
#: commitments does not become affordable because each one is small, and the
#: affordability rules the story cites are written against total debt service.
PENSION_PAYMENT_TO_INCOME = 0.40
#: And how much of the customer's verified income the documented pension
#: actually replaces. Both clauses are needed: a high obligation ratio that was
#: already there before the transition is not a transition story, and a low
#: replacement with small commitments is affordable.
PENSION_REPLACEMENT = 0.80
#: The matured outcome window for the acquisition-quality vintage.
MOB_WINDOW = 6

_PREDICATES: dict[str, dict[str, Any]] = {
    "C01": {"describes": "Alpha Card accounts 1-29 days past due",
            "clauses": [("product_subsegment", "==", "ALPHA",
                         "Alpha Card"),
                        ("dpd_bucket", "==", "1-29",
                         "1-29 days past due")]},
    "C02": {"describes": (
                "personal finance facilities in the matured month-on-book six "
                "vintage whose first default fell inside that window"),
            "clauses": [("vintage_cohort", "==", "CURRENT_MATURE_MOB6",
                         "matured MOB6 vintage"),
                        ("first_default_mob", "<=", MOB_WINDOW,
                         f"first default by month-on-book {MOB_WINDOW}")]},
    "C03": {"describes": "financed employees with a verified multi-cycle "
                         "payroll interruption",
            "clauses": [("episode_code", "==", "C03", "financed employees"),
                        ("payroll_missing_cycles", ">=",
                         PAYROLL_MISSING_CYCLES,
                         f"{PAYROLL_MISSING_CYCLES} or more missing payroll "
                         f"cycles")]},
    "C04": {"describes": "top-up borrowers whose verified commitments reach "
                         "half of verified income",
            "clauses": [("episode_code", "==", "C04", "top-up borrowers"),
                        ("verified_obligations_to_income", ">=",
                         OBLIGATIONS_TO_INCOME,
                         f"verified obligations at or above "
                         f"{OBLIGATIONS_TO_INCOME:.0%} of income")]},
    "C05": {"describes": "auto contracts whose final payment falls due inside "
                         "the window with liquid coverage below a quarter",
            "clauses": [("episode_code", "==", "C05",
                         "balloon due within the window"),
                        ("balloon_funding_coverage_ratio", "<",
                         BALLOON_COVERAGE,
                         f"verified coverage below {BALLOON_COVERAGE:.0%}")]},
    "C06": {"describes": "used-vehicle contracts whose expected net proceeds "
                         "have been revised down materially",
            "clauses": [("episode_code", "==", "C06", "used-vehicle book"),
                        ("net_proceeds_ratio", "<=", NET_PROCEEDS_RATIO,
                         f"expected net proceeds at or below "
                         f"{NET_PROCEEDS_RATIO:.0%} of the valuation they "
                         f"were set from")]},
    "C07": {"describes": "self-construction households past the delay "
                         "tolerance with less than a month of buffer",
            "clauses": [("episode_code", "==", "C07",
                         "self-construction book"),
                        ("milestone_delay_days", ">", MILESTONE_DELAY_DAYS,
                         f"milestone delay beyond {MILESTONE_DELAY_DAYS} "
                         f"days"),
                        ("balance_buffer_months", "<", LOW_BUFFER_MONTHS,
                         f"under {LOW_BUFFER_MONTHS:g} month of buffer")]},
    "C08": {"describes": "supported mortgages whose expected support has not "
                         "posted for two cycles",
            "clauses": [("episode_code", "==", "C08", "supported mortgages"),
                        ("support_gap_cycles", ">=", SUPPORT_GAP_CYCLES,
                         f"{SUPPORT_GAP_CYCLES} or more unresolved cycles")]},
    "C09": {"describes": "documented pension transitions whose scheduled "
                         "payment takes two fifths of recurring income",
            "clauses": [("pension_transition_state", "==",
                         "DOCUMENTED_TRANSITION", "documented transition"),
                        ("pension_income_replacement", "<=",
                         PENSION_REPLACEMENT,
                         f"documented pension replacing "
                         f"{PENSION_REPLACEMENT:.0%} or less of verified "
                         f"income"),
                        ("pension_obligations_to_income", ">=",
                         PENSION_PAYMENT_TO_INCOME,
                         f"total obligations at or above "
                         f"{PENSION_PAYMENT_TO_INCOME:.0%} of documented "
                         f"income")]},
    "C10": {"describes": "matured arrangements that defaulted again inside "
                         "the six-month observation window",
            "clauses": [("episode_code", "==", "C10",
                         "matured arrangements"),
                        ("redefault_flag", "==", True,
                         "redefaulted within six months")]},
}


def predicate(case_id: str) -> dict[str, Any]:
    """The issue rule, in the stored form a cohort snapshot carries.

    Each clause says whether it is SCOPE or OUTCOME, and the distinction is
    load-bearing rather than tidy. A scope clause names the population — this
    product, this pocket, this vintage. An outcome clause is the thing that
    happened to them.

    Two of the ten are measured against a matched earlier cohort, and that
    cohort fails the scope clause by definition: it is a DIFFERENT vintage.
    Evaluating the whole rule over it therefore returns nobody, and a
    comparator of zero makes every rate ratio infinite. So the comparator
    evaluates the outcome clauses over the cohort it was handed, and the
    breadcrumb still shows the reader all of them.
    """
    raw = _PREDICATES.get(case_id)
    if raw is None:
        raise KeyError(f"{case_id} has no issue predicate")
    clauses = []
    for index, (field, op, value, label) in enumerate(raw["clauses"]):
        clauses.append({"field": field, "op": op, "value": value,
                        "label": label,
                        "role": "scope" if index == 0 else "outcome"})
    return {"combine": "and", "describes": raw["describes"],
            "clauses": clauses}


def outcome_clauses(case_id: str) -> list[dict[str, Any]]:
    """The clauses that decide whether something HAPPENED, scope aside."""
    return [c for c in predicate(case_id)["clauses"]
            if c["role"] == "outcome"]


def predicate_thresholds() -> dict[str, float | int]:
    """Every named threshold, for the drawer's definitions panel."""
    return {
        "payroll_missing_cycles": PAYROLL_MISSING_CYCLES,
        "obligations_to_income": OBLIGATIONS_TO_INCOME,
        "balloon_coverage": BALLOON_COVERAGE,
        "net_proceeds_ratio": NET_PROCEEDS_RATIO,
        "milestone_delay_days": MILESTONE_DELAY_DAYS,
        "low_buffer_months": LOW_BUFFER_MONTHS,
        "support_gap_cycles": SUPPORT_GAP_CYCLES,
        "pension_obligations_to_income": PENSION_PAYMENT_TO_INCOME,
        "pension_replacement": PENSION_REPLACEMENT,
        "mob_window": MOB_WINDOW,
    }
