"""What the demonstration workspace contains, declared rather than written.

The distinction this file rests on
------------------------------------
§18 is explicit: "Do not seed live statistical answers as hand-entered
paragraphs. Seed governed analysis definitions and compute their initial
stored result through the actual engine."

So nothing here holds a number. Every entry is a QUESTION and the governed
measure that answers it, and the seeder runs the measure. A seeded figure
typed into a paragraph is a figure that disagrees with the screen beside it
the first time the book is rebuilt — and the presenter finds out in front of
a client, because the screen is right and the paragraph is the one everybody
reads.

The counts §17 to §19 ask for
-------------------------------
Twelve projects, each with five or more investigations and eight or more
analyses; sixty distinct investigations, twelve of them showcase threads;
one hundred saved analyses; twenty-four documents. Those are floors, and the
contract says out loud that a count does not excuse filler — so every entry
here asks a different question of a different population, and where two look
similar it is because a bank genuinely asks both (account share and exposure
share of the same delinquency are not the same finding).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

SEED_VERSION = "retail-seed-1.0.0"

CARD = "CREDIT_CARD"
PERSONAL = "PERSONAL_LOAN"
AUTO = "AUTO_LOAN"
HOME = "HOME_LOAN"
RETAIL = ""

OWNERS = {
    "retail_risk": "Head of Retail Credit Risk",
    "model_risk": "Retail Model Risk",
    "collections": "Head of Collections",
    "portfolio": "Retail Portfolio Analytics",
    "ifrs9": "IFRS 9 Reporting",
}


@dataclass(frozen=True)
class Project:
    key: str
    title: str
    product: str
    owner: str
    objective: str
    status: str = "active"


PROJECTS: tuple[Project, ...] = (
    Project("cc-delinquency",
            "Credit Card Delinquency and ECL Deterioration Investigation",
            CARD, OWNERS["retail_risk"],
            "Thirty-plus delinquency on the card book has risen for five "
            "consecutive months. Establish where it is concentrated, "
            "separate the observed default-rate movement from the ECL "
            "movement, and recommend an action."),
    Project("cc-salaried",
            "Credit Card Salaried versus Non-Salaried Review",
            CARD, OWNERS["portfolio"],
            "Salary transfer is the strongest affordability control in the "
            "book. Quantify the gap it produces in delinquency, coverage "
            "and utilisation, and test whether the non-salaried pocket is "
            "priced for it."),
    Project("cc-scorecard",
            "Credit Card Behavioural Scorecard Validation and "
            "Recalibration Review",
            CARD, OWNERS["model_risk"],
            "The behavioural scorecard under-predicts default across every "
            "band. Establish whether that is a level problem or a ranking "
            "problem, and whether it began at development or since."),
    Project("traits-ecl",
            "Retail Customer Traits and ECL Attribution",
            RETAIL, OWNERS["portfolio"],
            "Which customer characteristics have deteriorated, how much of "
            "the movement is the same customers behaving differently rather "
            "than the book changing shape, and what each contributes to "
            "expected credit loss."),
    Project("pf-affordability",
            "Personal Finance Affordability and Income Review",
            PERSONAL, OWNERS["retail_risk"],
            "Verified income and debt-burden across the personal finance "
            "book, and whether the affordability policy still separates the "
            "accounts that go on to default."),
    Project("pf-scorecard",
            "Personal Finance Scorecard Monitoring",
            PERSONAL, OWNERS["model_risk"],
            "Ongoing monitoring of the personal finance application and "
            "behavioural scorecards: discrimination, calibration, stability "
            "and the local rank inversion in the upper bands."),
    Project("auto-collections",
            "Auto Finance Delinquency, Collections and Balloon Exposure "
            "Review",
            AUTO, OWNERS["collections"],
            "Auto delinquency is low and the balloon book is concentrated. "
            "Quantify the exposure falling due within twelve months and the "
            "collections capacity it would need."),
    Project("auto-ews",
            "Auto Finance Early Warning and Collateral Review",
            AUTO, OWNERS["retail_risk"],
            "Forward-risk customers in the auto book who are still current, "
            "and whether collateral cover would absorb a default if the "
            "warning proved right."),
    Project("home-stage2",
            "Home Finance Stage 2 and SICR Migration Review",
            HOME, OWNERS["ifrs9"],
            "Stage 2 migration in the mortgage book, the loan-to-value "
            "distribution behind it, and whether the SICR trigger is firing "
            "on the right population."),
    Project("ifrs9-close",
            "Retail IFRS 9 — Latest Monthly Close",
            RETAIL, OWNERS["ifrs9"],
            "The month's expected credit loss, the bridge from the prior "
            "month, and the staging and coverage movements behind it."),
    Project("ews-monitoring",
            "Retail EWS Forward-Risk Monitoring",
            RETAIL, OWNERS["retail_risk"],
            "Customers whose leading indicators are deteriorating while "
            "they are still current, by product and by layer, with the "
            "clean-cohort separation the review committee asked for."),
    Project("portfolio-quarter",
            "Retail Portfolio Review — Latest Complete Quarter",
            RETAIL, OWNERS["retail_risk"],
            "The quarter's portfolio position across all four products, "
            "with a separately labelled quarter-to-date update for the "
            "months that have closed since."),
)


@dataclass(frozen=True)
class Analysis:
    """A governed analysis definition. The seeder computes its result."""

    key: str
    title: str
    question: str
    product: str
    #: "table", "trend" or "value"
    shape: str
    measures: tuple[str, ...]
    cut: str = ""
    where: dict[str, Any] = field(default_factory=dict)
    months: int = 0            # for a trend: how many recent months
    projects: tuple[str, ...] = ()
    tags: tuple[str, ...] = ()


def _p(product: str) -> str:
    return {CARD: "Credit Card", PERSONAL: "Personal Finance",
            AUTO: "Auto Finance", HOME: "Home Finance",
            RETAIL: "Retail"}[product]


def _mix(key: str, product: str, cut: str, cut_label: str,
         projects: tuple[str, ...], tags: tuple[str, ...] = ()) -> Analysis:
    """The standard exposure-and-risk breakdown of a population by one cut."""
    return Analysis(
        key=key,
        title=f"{_p(product)} exposure and risk by {cut_label.lower()}",
        question=(f"How is the {_p(product).lower()} book distributed across "
                  f"{cut_label.lower()}, and where does the delinquency and "
                  "the coverage sit?"),
        product=product, shape="table", cut=cut,
        measures=("facilities", "customers", "exposure", "ecl", "coverage",
                  "stage2_share", "dpd30_share"),
        projects=projects, tags=("mix", *tags))


def _trend(key: str, product: str, title: str, question: str,
           measures: tuple[str, ...], projects: tuple[str, ...],
           months: int = 13, where: dict[str, Any] | None = None,
           tags: tuple[str, ...] = ()) -> Analysis:
    return Analysis(key=key, title=title, question=question, product=product,
                    shape="trend", measures=measures, months=months,
                    where=dict(where or {}), projects=projects,
                    tags=("trend", *tags))


#: One hundred analyses. Grouped by the question they answer rather than by
#: product, so a reader scanning the file can see that the coverage is real:
#: delinquency, affordability, staging, collateral, scores, mix and trend.
ANALYSES: tuple[Analysis, ...] = (
    # ---------------------------------------- delinquency, by every cut
    _trend("cc-dpd30-trend", CARD,
           "Credit Card 30+ DPD, thirteen months",
           "How far has thirty-plus delinquency on the card book moved, and "
           "over how long?",
           ("dpd30_share", "dpd30_exposure_share", "dpd1_29_share",
            "dpd90_share"),
           ("cc-delinquency", "portfolio-quarter"), tags=("delinquency",)),
    _trend("cc-dpd-weighted", CARD,
           "Credit Card delinquency: accounts against exposure",
           "Is the card delinquency in the large accounts or the small ones?",
           ("dpd30_share", "dpd30_exposure_share"),
           ("cc-delinquency",), tags=("delinquency",)),
    Analysis("cc-dpd-by-salary", "Credit Card 30+ DPD by salary transfer",
             "Does salary transfer still separate the card accounts that "
             "fall into arrears?",
             CARD, "table", ("facilities", "exposure", "dpd30_share",
                             "dpd90_share", "coverage"),
             cut="salary_transfer",
             projects=("cc-delinquency", "cc-salaried"),
             tags=("delinquency", "affordability")),
    Analysis("cc-dpd-by-subproduct", "Credit Card 30+ DPD by sub-product",
             "Which card sub-product is carrying the rise?",
             CARD, "table", ("facilities", "exposure", "dpd30_share",
                             "stage2_share", "coverage"),
             cut="sub_product", projects=("cc-delinquency",),
             tags=("delinquency",)),
    Analysis("cc-dpd-by-segment", "Credit Card 30+ DPD by customer segment",
             "Is the deterioration concentrated in a customer segment?",
             CARD, "table", ("facilities", "exposure", "dpd30_share",
                             "mean_utilisation"),
             cut="segment", projects=("cc-delinquency",),
             tags=("delinquency",)),
    Analysis("cc-dpd-by-vintage", "Credit Card 30+ DPD by origination vintage",
             "Is this a cohort the bank wrote badly, or the whole book "
             "moving together?",
             CARD, "table", ("facilities", "exposure", "dpd30_share",
                             "mean_behaviour_score"),
             cut="vintage", projects=("cc-delinquency", "cc-scorecard"),
             tags=("delinquency", "vintage")),
    Analysis("cc-dpd-by-channel", "Credit Card 30+ DPD by origination channel",
             "Does the channel an account was written through still predict "
             "its arrears?",
             CARD, "table", ("facilities", "exposure", "dpd30_share",
                             "mean_dbr"),
             cut="channel", projects=("cc-delinquency",),
             tags=("delinquency", "origination")),
    Analysis("cc-dpd-by-income", "Credit Card 30+ DPD by income band",
             "Where in the income distribution is the card delinquency?",
             CARD, "table", ("facilities", "exposure", "dpd30_share",
                             "mean_dbr", "coverage"),
             cut="income_band", projects=("cc-delinquency", "traits-ecl"),
             tags=("delinquency", "affordability")),
    Analysis("cc-dpd-by-indebtedness",
             "Credit Card 30+ DPD by indebtedness band",
             "Does recorded indebtedness separate the card accounts in "
             "arrears?",
             CARD, "table", ("facilities", "exposure", "dpd30_share",
                             "stage2_share"),
             cut="indebtedness_band",
             projects=("cc-delinquency", "traits-ecl"),
             tags=("delinquency", "affordability")),
    Analysis("cc-dpd-by-region", "Credit Card 30+ DPD by region",
             "Is the card deterioration geographic?",
             CARD, "table", ("facilities", "exposure", "dpd30_share"),
             cut="region", projects=("cc-delinquency",),
             tags=("delinquency",)),
    Analysis("cc-bucket-mix", "Credit Card delinquency bucket mix",
             "How is the card book distributed across the delinquency "
             "buckets, by accounts and by money?",
             CARD, "table", ("facilities", "exposure", "ecl", "coverage",
                             "mean_behaviour_score"),
             cut="dpd_bucket", projects=("cc-delinquency", "ifrs9-close"),
             tags=("delinquency", "staging")),
    _trend("retail-dpd30-trend", RETAIL,
           "Retail 30+ DPD across all four products",
           "Is the delinquency rise a card problem or a book problem?",
           ("dpd30_share", "dpd30_exposure_share", "dpd90_share"),
           ("portfolio-quarter", "ifrs9-close"), tags=("delinquency",)),
    Analysis("retail-dpd-by-product", "Retail 30+ DPD by product",
             "Which products carry the delinquency, and how much money is "
             "behind each?",
             RETAIL, "table", ("facilities", "customers", "exposure",
                               "dpd30_share", "dpd30_exposure_share",
                               "coverage"),
             cut="product", projects=("portfolio-quarter", "ifrs9-close"),
             tags=("delinquency", "portfolio")),
    _trend("pf-dpd-trend", PERSONAL,
           "Personal Finance 30+ DPD, thirteen months",
           "Has the personal finance book moved with the card book?",
           ("dpd30_share", "dpd90_share", "stage2_share"),
           ("pf-affordability",), tags=("delinquency",)),
    _trend("auto-dpd-trend", AUTO,
           "Auto Finance 30+ DPD, thirteen months",
           "Has auto delinquency moved at all?",
           ("dpd30_share", "dpd90_share", "coverage"),
           ("auto-collections",), tags=("delinquency",)),
    _trend("home-dpd-trend", HOME,
           "Home Finance 30+ DPD, thirteen months",
           "Has mortgage delinquency moved?",
           ("dpd30_share", "stage2_share", "coverage"),
           ("home-stage2",), tags=("delinquency",)),

    # ---------------------------------------------------- staging and ECL
    _trend("retail-ecl-trend", RETAIL,
           "Retail expected credit loss, thirteen months",
           "How has the retail ECL moved, and is coverage moving with it?",
           ("ecl", "exposure", "coverage"),
           ("ifrs9-close", "portfolio-quarter"), tags=("ecl",)),
    _trend("cc-ecl-trend", CARD,
           "Credit Card ECL and coverage, thirteen months",
           "How much of the card ECL rise is exposure growth and how much "
           "is coverage?",
           ("ecl", "exposure", "coverage", "stage2_share"),
           ("cc-delinquency", "ifrs9-close"), tags=("ecl",)),
    Analysis("retail-stage-mix", "Retail staging by product",
             "How is the book distributed across IFRS 9 stages, and what "
             "does each stage cost?",
             RETAIL, "table", ("facilities", "exposure", "ecl", "coverage"),
             cut="stage", projects=("ifrs9-close",), tags=("staging",)),
    Analysis("cc-stage-mix", "Credit Card staging and coverage",
             "Where does the card ECL sit by stage?",
             CARD, "table", ("facilities", "exposure", "ecl", "coverage",
                             "mean_pd"),
             cut="stage", projects=("cc-delinquency", "ifrs9-close"),
             tags=("staging",)),
    Analysis("home-stage-mix", "Home Finance staging and coverage",
             "How much mortgage exposure sits in stage 2, and what is the "
             "coverage on it?",
             HOME, "table", ("facilities", "exposure", "ecl", "coverage",
                             "mean_ltv"),
             cut="stage", projects=("home-stage2",), tags=("staging",)),
    _trend("home-stage2-trend", HOME,
           "Home Finance stage 2 migration, thirteen months",
           "Is the mortgage book migrating into stage 2, by accounts or by "
           "exposure?",
           ("stage2_share", "stage2_exposure_share", "coverage"),
           ("home-stage2", "ifrs9-close"), tags=("staging",)),
    Analysis("home-stage2-by-ltv", "Home Finance stage 2 by loan-to-value",
             "Is the stage 2 migration in the thin-equity mortgages?",
             HOME, "table", ("facilities", "exposure", "stage2_share",
                             "mean_ltv", "coverage"),
             cut="ltv_band", projects=("home-stage2",),
             tags=("staging", "collateral")),
    Analysis("retail-stage2-by-product", "Retail stage 2 by product",
             "Which product is driving the stage 2 balance?",
             RETAIL, "table", ("facilities", "exposure",
                               "stage2_share", "stage2_exposure_share",
                               "coverage"),
             cut="product", projects=("ifrs9-close", "portfolio-quarter"),
             tags=("staging",)),
    Analysis("cc-stage2-by-salary", "Credit Card stage 2 by salary transfer",
             "Does the stage 2 population divide on salary transfer the way "
             "the delinquency does?",
             CARD, "table", ("facilities", "exposure", "stage2_share",
                             "coverage"),
             cut="salary_transfer", projects=("cc-salaried", "ifrs9-close"),
             tags=("staging", "affordability")),
    _trend("retail-coverage-trend", RETAIL,
           "Retail ECL coverage, thirteen months",
           "Has coverage moved because risk moved, or because the mix did?",
           ("coverage", "stage2_share", "dpd30_share"),
           ("ifrs9-close",), tags=("ecl",)),
    Analysis("retail-ecl-by-segment", "Retail ECL by customer segment",
             "Which customer segments carry the expected loss?",
             RETAIL, "table", ("facilities", "exposure", "ecl", "coverage"),
             cut="segment", projects=("ifrs9-close", "portfolio-quarter"),
             tags=("ecl",)),

    # ------------------------------------------------ salaried / affordability
    Analysis("cc-salary-gap", "Credit Card: the salary transfer gap",
             "What does salary transfer change about the card book — "
             "delinquency, coverage, utilisation and score?",
             CARD, "table", ("facilities", "customers", "exposure", "ecl",
                             "coverage", "dpd30_share", "mean_utilisation",
                             "mean_behaviour_score"),
             cut="salary_transfer", projects=("cc-salaried",),
             tags=("affordability",)),
    _trend("cc-salaried-trend", CARD,
           "Credit Card salaried population, thirteen months",
           "Has the salaried share of the card book changed while its "
           "delinquency did?",
           ("salary_transfer_share", "dpd30_share", "coverage"),
           ("cc-salaried",), tags=("affordability", "mix")),
    Analysis("cc-nonsalaried-income",
             "Credit Card non-salaried customers by income band",
             "Where in the income distribution do the non-salaried card "
             "customers sit?",
             CARD, "table", ("facilities", "exposure", "dpd30_share",
                             "mean_dbr", "coverage"),
             cut="income_band", where={"salary_transfer_flag": "False"},
             projects=("cc-salaried",), tags=("affordability",)),
    Analysis("pf-income-bands", "Personal Finance by income band",
             "How is the personal finance book distributed by verified "
             "income, and does the risk follow it?",
             PERSONAL, "table", ("facilities", "exposure", "mean_income",
                                 "mean_disposable", "mean_dbr",
                                 "dpd30_share"),
             cut="income_band", projects=("pf-affordability",),
             tags=("affordability",)),
    Analysis("pf-dbr-bands", "Personal Finance by indebtedness band",
             "Does the debt-burden policy separate the accounts that go on "
             "to arrears?",
             PERSONAL, "table", ("facilities", "exposure", "mean_dbr",
                                 "dpd30_share", "stage2_share", "coverage"),
             cut="indebtedness_band", projects=("pf-affordability",),
             tags=("affordability",)),
    Analysis("pf-employment", "Personal Finance by employment status",
             "Which employment groups hold the personal finance book, and "
             "how do they perform?",
             PERSONAL, "table", ("facilities", "exposure", "mean_income",
                                 "dpd30_share", "coverage"),
             cut="employment", projects=("pf-affordability",),
             tags=("affordability",)),
    _trend("pf-income-trend", PERSONAL,
           "Personal Finance verified income, thirteen months",
           "Has verified income moved across the personal finance book?",
           ("mean_income", "mean_disposable", "mean_dbr"),
           ("pf-affordability", "traits-ecl"), tags=("affordability",)),
    _trend("retail-dbr-trend", RETAIL,
           "Retail debt-burden ratio, thirteen months",
           "Is recorded indebtedness rising across the retail book?",
           ("mean_dbr", "mean_income", "mean_disposable"),
           ("traits-ecl", "portfolio-quarter"), tags=("affordability",)),
    Analysis("retail-income-by-product", "Retail income profile by product",
             "What does each product's customer earn, and what do they owe?",
             RETAIL, "table", ("facilities", "mean_income",
                               "mean_disposable", "mean_dbr",
                               "salary_transfer_share"),
             cut="product", projects=("traits-ecl", "portfolio-quarter"),
             tags=("affordability",)),
    Analysis("cc-dbr-by-utilisation",
             "Credit Card indebtedness by utilisation band",
             "Are the heavily drawn cards held by the heavily indebted "
             "customers?",
             CARD, "table", ("facilities", "exposure", "mean_dbr",
                             "dpd30_share", "mean_utilisation"),
             cut="utilisation_band", projects=("cc-salaried", "traits-ecl"),
             tags=("affordability", "utilisation")),

    # ----------------------------------------------------------- utilisation
    _trend("cc-utilisation-trend", CARD,
           "Credit Card utilisation, thirteen months",
           "Is the card book being drawn harder?",
           ("mean_utilisation", "overlimit_share", "dpd30_share"),
           ("cc-delinquency", "traits-ecl"), tags=("utilisation",)),
    Analysis("cc-utilisation-mix", "Credit Card utilisation band mix",
             "How is the card book distributed by utilisation, and where "
             "is the risk?",
             CARD, "table", ("facilities", "exposure", "ecl", "coverage",
                             "dpd30_share", "mean_behaviour_score"),
             cut="utilisation_band", projects=("cc-delinquency",),
             tags=("utilisation",)),
    Analysis("cc-overlimit-by-segment",
             "Credit Card over-limit accounts by segment",
             "Which customers are drawing beyond their approved limit?",
             CARD, "table", ("facilities", "exposure", "overlimit_share",
                             "dpd30_share"),
             cut="segment", projects=("cc-delinquency", "ews-monitoring"),
             tags=("utilisation",)),
    Analysis("cc-utilisation-by-salary",
             "Credit Card utilisation by salary transfer",
             "Do non-salaried customers draw their cards harder?",
             CARD, "table", ("facilities", "mean_utilisation",
                             "overlimit_share", "dpd30_share"),
             cut="salary_transfer", projects=("cc-salaried",),
             tags=("utilisation", "affordability")),

    # ------------------------------------------------------ auto and balloon
    Analysis("auto-balloon-bands", "Auto Finance balloon exposure by band",
             "How much balloon exposure is outstanding, and when does it "
             "fall due?",
             AUTO, "table", ("facilities", "exposure", "balloon_exposure",
                             "balloon_within_year_share", "dpd30_share"),
             cut="balloon_band", projects=("auto-collections",),
             tags=("balloon",)),
    _trend("auto-balloon-trend", AUTO,
           "Auto Finance balloon exposure, thirteen months",
           "Is the balloon book growing, and is the twelve-month window "
           "filling up?",
           ("balloon_exposure", "balloon_within_year_share", "exposure"),
           ("auto-collections",), tags=("balloon",)),
    Analysis("auto-collateral-cover", "Auto Finance collateral cover by band",
             "Would the collateral absorb a default at each level of "
             "loan-to-value?",
             AUTO, "table", ("facilities", "exposure", "collateral_cover",
                             "mean_ltv", "high_ltv_share", "dpd30_share"),
             cut="ltv_band", projects=("auto-ews", "auto-collections"),
             tags=("collateral",)),
    Analysis("auto-collateral-type",
             "Auto Finance exposure by collateral type",
             "What is securing the auto book?",
             AUTO, "table", ("facilities", "exposure", "collateral_cover",
                             "mean_ltv", "coverage"),
             cut="collateral_type", projects=("auto-ews",),
             tags=("collateral",)),
    _trend("auto-ltv-trend", AUTO,
           "Auto Finance loan-to-value, thirteen months",
           "Is collateral cover eroding as the book amortises against "
           "depreciating security?",
           ("mean_ltv", "high_ltv_share", "collateral_cover"),
           ("auto-ews",), tags=("collateral",)),
    Analysis("auto-by-vintage", "Auto Finance risk by origination vintage",
             "Which auto vintages are performing, and which are not?",
             AUTO, "table", ("facilities", "exposure", "dpd30_share",
                             "mean_ltv", "coverage"),
             cut="vintage", projects=("auto-collections",),
             tags=("vintage",)),
    Analysis("auto-by-channel", "Auto Finance by origination channel",
             "Does the channel predict auto performance?",
             AUTO, "table", ("facilities", "exposure", "dpd30_share",
                             "mean_dbr", "coverage"),
             cut="channel", projects=("auto-collections",),
             tags=("origination",)),

    # ----------------------------------------------------------- mortgage
    Analysis("home-ltv-mix", "Home Finance loan-to-value distribution",
             "How much mortgage exposure sits above eighty per cent "
             "loan-to-value?",
             HOME, "table", ("facilities", "exposure", "mean_ltv",
                             "high_ltv_share", "stage2_share", "coverage"),
             cut="ltv_band", projects=("home-stage2",),
             tags=("collateral",)),
    _trend("home-ltv-trend", HOME,
           "Home Finance loan-to-value, thirteen months",
           "Is mortgage equity building or eroding?",
           ("mean_ltv", "high_ltv_share", "collateral_cover"),
           ("home-stage2",), tags=("collateral",)),
    Analysis("home-by-region", "Home Finance exposure by region",
             "Where is the mortgage book, and does the risk vary by region?",
             HOME, "table", ("facilities", "exposure", "mean_ltv",
                             "stage2_share", "coverage"),
             cut="region", projects=("home-stage2",),
             tags=("portfolio",)),
    Analysis("home-by-income", "Home Finance by income band",
             "Who holds the mortgage book?",
             HOME, "table", ("facilities", "exposure", "mean_income",
                             "mean_dbr", "stage2_share"),
             cut="income_band", projects=("home-stage2",),
             tags=("affordability",)),
    Analysis("home-collateral-cover", "Home Finance collateral cover",
             "What is the cover across the mortgage book by collateral "
             "type?",
             HOME, "table", ("facilities", "exposure", "collateral_cover",
                             "mean_ltv", "coverage"),
             cut="collateral_type", projects=("home-stage2",),
             tags=("collateral",)),

    # ------------------------------------------------------------- scores
    _trend("cc-score-trend", CARD,
           "Credit Card behavioural score, thirteen months",
           "Has the behavioural score drifted while the delinquency rose?",
           ("mean_behaviour_score", "mean_pd", "dpd30_share"),
           ("cc-scorecard", "cc-delinquency"), tags=("score",)),
    Analysis("cc-score-by-band",
             "Credit Card risk by application score band",
             "Does the application score band a customer was written at "
             "still order their behaviour?",
             CARD, "table", ("facilities", "exposure", "dpd30_share",
                             "mean_behaviour_score", "mean_pd", "coverage"),
             cut="application_band", projects=("cc-scorecard",),
             tags=("score",)),
    Analysis("cc-pd-by-stage", "Credit Card predicted PD by stage",
             "Does the predicted PD rise with the stage it is used to set?",
             CARD, "table", ("facilities", "mean_pd", "mean_behaviour_score",
                             "dpd30_share", "coverage"),
             cut="stage", projects=("cc-scorecard", "ifrs9-close"),
             tags=("score", "staging")),
    _trend("retail-pd-trend", RETAIL,
           "Retail predicted PD, thirteen months",
           "Has the modelled probability of default moved with the observed "
           "arrears?",
           ("mean_pd", "dpd30_share", "coverage"),
           ("cc-scorecard", "traits-ecl"), tags=("score",)),
    Analysis("pf-score-by-band",
             "Personal Finance risk by application score band",
             "Is the personal finance application score still ordering "
             "risk?",
             PERSONAL, "table", ("facilities", "exposure", "dpd30_share",
                                 "mean_behaviour_score", "mean_pd"),
             cut="application_band", projects=("pf-scorecard",),
             tags=("score",)),
    _trend("pf-score-trend", PERSONAL,
           "Personal Finance behavioural score, thirteen months",
           "Has the personal finance behavioural score drifted?",
           ("mean_behaviour_score", "mean_pd", "dpd30_share"),
           ("pf-scorecard",), tags=("score",)),
    Analysis("auto-score-by-band", "Auto Finance risk by score band",
             "Does the auto application score band still separate?",
             AUTO, "table", ("facilities", "exposure", "dpd30_share",
                             "mean_behaviour_score", "mean_ltv"),
             cut="application_band", projects=("auto-collections",),
             tags=("score",)),
    Analysis("home-score-by-band", "Home Finance risk by score band",
             "Does the mortgage application score band still separate?",
             HOME, "table", ("facilities", "exposure", "stage2_share",
                             "mean_behaviour_score", "mean_ltv"),
             cut="application_band", projects=("home-stage2",),
             tags=("score",)),
    Analysis("retail-score-by-product", "Retail behavioural score by product",
             "How do the four products compare on behavioural score and "
             "modelled PD?",
             RETAIL, "table", ("facilities", "mean_behaviour_score",
                               "mean_pd", "dpd30_share", "coverage"),
             cut="product", projects=("cc-scorecard", "pf-scorecard"),
             tags=("score",)),
    Analysis("cc-score-by-vintage",
             "Credit Card behavioural score by vintage",
             "Are newer card cohorts scoring differently from older ones?",
             CARD, "table", ("facilities", "mean_behaviour_score", "mean_pd",
                             "dpd30_share"),
             cut="vintage", projects=("cc-scorecard",),
             tags=("score", "vintage")),
    Analysis("cc-lgd-by-stage", "Credit Card loss severity by stage",
             "Is the loss-given-default assumption varying by stage the way "
             "the policy says?",
             CARD, "table", ("facilities", "mean_lgd", "coverage", "ecl"),
             cut="stage", projects=("cc-scorecard", "ifrs9-close"),
             tags=("ecl",)),

    # --------------------------------------------------------- portfolio mix
    _mix("retail-mix-product", RETAIL, "product", "Product",
         ("portfolio-quarter", "ifrs9-close"), ("portfolio",)),
    _mix("retail-mix-segment", RETAIL, "segment", "Customer segment",
         ("portfolio-quarter",), ("portfolio",)),
    _mix("retail-mix-region", RETAIL, "region", "Region",
         ("portfolio-quarter",), ("portfolio",)),
    _mix("retail-mix-channel", RETAIL, "channel", "Origination channel",
         ("portfolio-quarter",), ("origination",)),
    _mix("retail-mix-employment", RETAIL, "employment", "Employment status",
         ("portfolio-quarter", "traits-ecl"), ("portfolio",)),
    _mix("retail-mix-income", RETAIL, "income_band", "Income band",
         ("portfolio-quarter", "traits-ecl"), ("affordability",)),
    _mix("retail-mix-indebtedness", RETAIL, "indebtedness_band",
         "Indebtedness band", ("traits-ecl",), ("affordability",)),
    _mix("retail-mix-vintage", RETAIL, "vintage", "Origination vintage",
         ("portfolio-quarter",), ("vintage",)),
    _mix("cc-mix-segment", CARD, "segment", "Customer segment",
         ("cc-delinquency", "cc-salaried"), ("portfolio",)),
    _mix("cc-mix-region", CARD, "region", "Region",
         ("cc-delinquency",), ("portfolio",)),
    _mix("cc-mix-subproduct", CARD, "sub_product", "Sub-product",
         ("cc-delinquency", "cc-salaried"), ("portfolio",)),
    _mix("pf-mix-segment", PERSONAL, "segment", "Customer segment",
         ("pf-affordability",), ("portfolio",)),
    _mix("pf-mix-region", PERSONAL, "region", "Region",
         ("pf-affordability",), ("portfolio",)),
    _mix("pf-mix-vintage", PERSONAL, "vintage", "Origination vintage",
         ("pf-scorecard",), ("vintage",)),
    _mix("auto-mix-segment", AUTO, "segment", "Customer segment",
         ("auto-collections",), ("portfolio",)),
    _mix("auto-mix-region", AUTO, "region", "Region",
         ("auto-ews",), ("portfolio",)),
    _mix("home-mix-segment", HOME, "segment", "Customer segment",
         ("home-stage2",), ("portfolio",)),
    _mix("home-mix-channel", HOME, "channel", "Origination channel",
         ("home-stage2",), ("origination",)),

    # ----------------------------------------------------- growth and trend
    _trend("retail-exposure-trend", RETAIL,
           "Retail exposure and customers, thirteen months",
           "Is the book growing, and is the growth changing its shape?",
           ("exposure", "facilities", "customers"),
           ("portfolio-quarter",), tags=("portfolio",)),
    _trend("cc-exposure-trend", CARD,
           "Credit Card exposure and customers, thirteen months",
           "Is the card book growing into the delinquency, or despite it?",
           ("exposure", "facilities", "customers", "dpd30_share"),
           ("cc-delinquency", "portfolio-quarter"), tags=("portfolio",)),
    _trend("pf-exposure-trend", PERSONAL,
           "Personal Finance exposure, thirteen months",
           "How fast is personal finance growing?",
           ("exposure", "facilities", "coverage"),
           ("pf-affordability",), tags=("portfolio",)),
    _trend("auto-exposure-trend", AUTO,
           "Auto Finance exposure, thirteen months",
           "How fast is the auto book growing?",
           ("exposure", "facilities", "coverage"),
           ("auto-collections",), tags=("portfolio",)),
    _trend("home-exposure-trend", HOME,
           "Home Finance exposure, thirteen months",
           "How fast is the mortgage book growing?",
           ("exposure", "facilities", "coverage"),
           ("home-stage2",), tags=("portfolio",)),
    _trend("retail-salaried-trend", RETAIL,
           "Retail salary-transferred share, thirteen months",
           "Is the book becoming more or less salary-controlled?",
           ("salary_transfer_share", "dpd30_share", "coverage"),
           ("traits-ecl", "portfolio-quarter"), tags=("mix",)),
    _trend("retail-stage3-trend", RETAIL,
           "Retail stage 3 population, thirteen months",
           "Is the credit-impaired population growing?",
           ("stage3_share", "coverage", "ecl"),
           ("ifrs9-close",), tags=("staging",)),
    _trend("cc-stage3-trend", CARD,
           "Credit Card stage 3 population, thirteen months",
           "Is the card book's impaired population growing?",
           ("stage3_share", "dpd90_share", "coverage"),
           ("cc-delinquency", "ifrs9-close"), tags=("staging",)),
    _trend("cc-meandpd-trend", CARD,
           "Credit Card mean days past due, thirteen months",
           "Is the arrears population getting larger, deeper, or both?",
           ("mean_dpd", "dpd1_29_share", "dpd30_share", "dpd90_share"),
           ("cc-delinquency",), tags=("delinquency",)),

    # ------------------------------------------------- early warning cohorts
    Analysis("ews-cc-current-risk",
             "Credit Card customers still current, by segment",
             "Among the card customers with no arrears at all, how is the "
             "exposure distributed and what does it cost?",
             CARD, "table", ("facilities", "customers", "exposure", "ecl",
                             "coverage", "mean_behaviour_score"),
             cut="segment", where={"dpd_bucket": "0"},
             projects=("ews-monitoring",), tags=("forward-risk",)),
    Analysis("ews-cc-current-utilisation",
             "Credit Card current accounts by utilisation",
             "Which still-current card accounts are being drawn hardest?",
             CARD, "table", ("facilities", "exposure", "mean_utilisation",
                             "overlimit_share", "mean_behaviour_score"),
             cut="utilisation_band", where={"dpd_bucket": "0"},
             projects=("ews-monitoring", "cc-delinquency"),
             tags=("forward-risk", "utilisation")),
    Analysis("ews-retail-current-product",
             "Retail customers still current, by product",
             "How large is the clean population in each product — the one a "
             "forward-risk review is actually about?",
             RETAIL, "table", ("facilities", "customers", "exposure",
                               "mean_behaviour_score", "mean_pd"),
             cut="product", where={"dpd_bucket": "0"},
             projects=("ews-monitoring",), tags=("forward-risk",)),
    Analysis("ews-auto-current-ltv",
             "Auto Finance current accounts by loan-to-value",
             "Among still-current auto customers, where is the thin "
             "collateral cover?",
             AUTO, "table", ("facilities", "exposure", "mean_ltv",
                             "high_ltv_share", "collateral_cover"),
             cut="ltv_band", where={"dpd_bucket": "0"},
             projects=("auto-ews", "ews-monitoring"),
             tags=("forward-risk", "collateral")),
    Analysis("ews-home-current-stage",
             "Home Finance current accounts by stage",
             "How much mortgage exposure is in stage 2 while still fully "
             "up to date?",
             HOME, "table", ("facilities", "exposure", "stage2_share",
                             "mean_ltv", "coverage"),
             cut="stage", where={"dpd_bucket": "0"},
             projects=("home-stage2", "ews-monitoring"),
             tags=("forward-risk", "staging")),
    Analysis("ews-pf-current-income",
             "Personal Finance current accounts by income band",
             "Among still-current personal finance customers, where is the "
             "affordability pressure?",
             PERSONAL, "table", ("facilities", "exposure", "mean_income",
                                 "mean_dbr", "mean_behaviour_score"),
             cut="income_band", where={"dpd_bucket": "0"},
             projects=("ews-monitoring", "pf-affordability"),
             tags=("forward-risk", "affordability")),
    Analysis("ews-cc-stage2-current",
             "Credit Card stage 2 accounts with no arrears",
             "Which card accounts has the SICR trigger moved to stage 2 "
             "while they are still paying on time?",
             CARD, "table", ("facilities", "exposure", "ecl", "coverage",
                             "mean_behaviour_score", "mean_utilisation"),
             cut="segment", where={"dpd_bucket": "0", "ifrs9_stage": "2"},
             projects=("ews-monitoring", "cc-scorecard"),
             tags=("forward-risk", "staging")),

    # ------------------------------------------------ concentration and size
    Analysis("cc-top-vintages", "Credit Card: the five largest vintages",
             "Which origination cohorts hold most of the card book?",
             CARD, "table", ("facilities", "exposure", "ecl", "dpd30_share"),
             cut="vintage", projects=("cc-delinquency",),
             tags=("concentration",)),
    Analysis("retail-top-regions", "Retail: the largest regions by exposure",
             "Where is the retail book concentrated?",
             RETAIL, "table", ("facilities", "customers", "exposure", "ecl",
                               "coverage"),
             cut="region", projects=("portfolio-quarter",),
             tags=("concentration",)),
    Analysis("home-top-regions", "Home Finance concentration by region",
             "How concentrated is the mortgage book geographically?",
             HOME, "table", ("facilities", "exposure", "mean_ltv",
                             "coverage"),
             cut="region", projects=("home-stage2",),
             tags=("concentration",)),
    Analysis("retail-employment-risk",
             "Retail delinquency by employment status",
             "Does employment status separate the retail book's arrears?",
             RETAIL, "table", ("facilities", "exposure", "dpd30_share",
                               "mean_income", "coverage"),
             cut="employment", projects=("traits-ecl",),
             tags=("affordability",)),
    Analysis("retail-channel-risk",
             "Retail delinquency by origination channel",
             "Which channels are writing the arrears?",
             RETAIL, "table", ("facilities", "exposure", "dpd30_share",
                               "mean_dbr", "coverage"),
             cut="channel", projects=("portfolio-quarter", "traits-ecl"),
             tags=("origination",)),
    Analysis("retail-vintage-risk", "Retail delinquency by vintage",
             "Which origination years are performing worst across the "
             "retail book?",
             RETAIL, "table", ("facilities", "exposure", "dpd30_share",
                               "stage2_share", "coverage"),
             cut="vintage", projects=("portfolio-quarter",),
             tags=("vintage",)),
    Analysis("cc-subproduct-coverage", "Credit Card coverage by sub-product",
             "What does each card sub-product cost in expected loss?",
             CARD, "table", ("facilities", "exposure", "ecl", "coverage",
                             "mean_utilisation"),
             cut="sub_product", projects=("cc-delinquency", "ifrs9-close"),
             tags=("ecl",)),
    Analysis("pf-subproduct-mix", "Personal Finance by sub-product",
             "How is the personal finance book split, and how does each "
             "part perform?",
             PERSONAL, "table", ("facilities", "exposure", "ecl",
                                 "dpd30_share", "coverage"),
             cut="sub_product", projects=("pf-affordability",),
             tags=("portfolio",)),
    Analysis("auto-subproduct-mix", "Auto Finance by sub-product",
             "How is the auto book split, and where is the balloon risk?",
             AUTO, "table", ("facilities", "exposure", "balloon_exposure",
                             "dpd30_share", "mean_ltv"),
             cut="sub_product", projects=("auto-collections",),
             tags=("portfolio", "balloon")),
    Analysis("home-subproduct-mix", "Home Finance by sub-product",
             "How is the mortgage book split?",
             HOME, "table", ("facilities", "exposure", "mean_ltv",
                             "stage2_share", "coverage"),
             cut="sub_product", projects=("home-stage2",),
             tags=("portfolio",)),
    Analysis("cc-region-utilisation",
             "Credit Card utilisation by region",
             "Is the hard drawing regional?",
             CARD, "table", ("facilities", "mean_utilisation",
                             "overlimit_share", "dpd30_share"),
             cut="region", projects=("cc-delinquency",),
             tags=("utilisation",)),
    Analysis("retail-segment-affordability",
             "Retail affordability by customer segment",
             "What does each segment earn, owe and cost?",
             RETAIL, "table", ("facilities", "mean_income",
                               "mean_disposable", "mean_dbr",
                               "salary_transfer_share", "coverage"),
             cut="segment", projects=("traits-ecl",),
             tags=("affordability",)),
    _trend("cc-stage2-trend", CARD,
           "Credit Card stage 2 migration, thirteen months",
           "Is the card book migrating into stage 2 ahead of its arrears?",
           ("stage2_share", "stage2_exposure_share", "dpd30_share"),
           ("cc-delinquency", "ifrs9-close"), tags=("staging",)),
    _trend("pf-stage2-trend", PERSONAL,
           "Personal Finance stage 2 migration, thirteen months",
           "Is personal finance migrating into stage 2?",
           ("stage2_share", "stage2_exposure_share", "coverage"),
           ("pf-affordability", "ifrs9-close"), tags=("staging",)),
    _trend("auto-stage2-trend", AUTO,
           "Auto Finance stage 2 migration, thirteen months",
           "Is the auto book migrating into stage 2?",
           ("stage2_share", "coverage", "dpd30_share"),
           ("auto-collections",), tags=("staging",)),
    _trend("retail-customers-trend", RETAIL,
           "Retail customers and facilities per customer",
           "Is the bank adding customers or adding facilities to the "
           "customers it has?",
           ("customers", "facilities", "exposure"),
           ("portfolio-quarter",), tags=("portfolio",)),
    _trend("cc-overlimit-trend", CARD,
           "Credit Card over-limit population, thirteen months",
           "Is the over-limit population growing ahead of the arrears?",
           ("overlimit_share", "mean_utilisation", "dpd30_share"),
           ("cc-delinquency", "ews-monitoring"), tags=("utilisation",)),
    _trend("home-coverage-trend", HOME,
           "Home Finance coverage, thirteen months",
           "Has mortgage coverage moved?",
           ("coverage", "ecl", "stage2_share"),
           ("home-stage2", "ifrs9-close"), tags=("ecl",)),
    _trend("auto-coverage-trend", AUTO,
           "Auto Finance coverage, thirteen months",
           "Has auto coverage moved?",
           ("coverage", "ecl", "collateral_cover"),
           ("auto-collections", "ifrs9-close"), tags=("ecl",)),
    _trend("pf-coverage-trend", PERSONAL,
           "Personal Finance coverage, thirteen months",
           "Has personal finance coverage moved?",
           ("coverage", "ecl", "stage2_share"),
           ("pf-affordability", "ifrs9-close"), tags=("ecl",)),
    Analysis("retail-lgd-by-product", "Retail loss severity by product",
             "What loss severity is each product carrying?",
             RETAIL, "table", ("facilities", "mean_lgd", "coverage", "ecl"),
             cut="product", projects=("ifrs9-close",), tags=("ecl",)),
    Analysis("cc-income-utilisation",
             "Credit Card utilisation by income band",
             "Are the lower-income card customers the ones drawing hardest?",
             CARD, "table", ("facilities", "mean_utilisation",
                             "overlimit_share", "mean_dbr", "dpd30_share"),
             cut="income_band", projects=("cc-salaried", "traits-ecl"),
             tags=("utilisation", "affordability")),
    Analysis("pf-region-risk", "Personal Finance delinquency by region",
             "Is the personal finance arrears geographic?",
             PERSONAL, "table", ("facilities", "exposure", "dpd30_share",
                                 "mean_dbr"),
             cut="region", projects=("pf-affordability",),
             tags=("delinquency",)),
    Analysis("auto-region-risk", "Auto Finance delinquency by region",
             "Is the auto arrears geographic?",
             AUTO, "table", ("facilities", "exposure", "dpd30_share",
                             "mean_ltv"),
             cut="region", projects=("auto-collections",),
             tags=("delinquency",)),
    Analysis("home-employment", "Home Finance by employment status",
             "Who holds the mortgages, and how do they perform?",
             HOME, "table", ("facilities", "exposure", "mean_income",
                             "stage2_share", "mean_ltv"),
             cut="employment", projects=("home-stage2",),
             tags=("affordability",)),
    Analysis("cc-employment-risk",
             "Credit Card delinquency by employment status",
             "Which employment groups hold the card arrears?",
             CARD, "table", ("facilities", "exposure", "dpd30_share",
                             "mean_income", "coverage"),
             cut="employment", projects=("cc-delinquency", "cc-salaried"),
             tags=("delinquency", "affordability")),
    Analysis("retail-bucket-exposure",
             "Retail delinquency bucket mix by exposure",
             "How much money sits in each delinquency bucket across the "
             "retail book?",
             RETAIL, "table", ("facilities", "exposure", "ecl", "coverage"),
             cut="dpd_bucket", projects=("ifrs9-close", "portfolio-quarter"),
             tags=("delinquency",)),
    Analysis("pf-bucket-mix", "Personal Finance delinquency bucket mix",
             "How is personal finance distributed across the arrears "
             "buckets?",
             PERSONAL, "table", ("facilities", "exposure", "ecl",
                                 "coverage", "mean_behaviour_score"),
             cut="dpd_bucket", projects=("pf-affordability",),
             tags=("delinquency",)),
    Analysis("auto-bucket-mix", "Auto Finance delinquency bucket mix",
             "How is the auto book distributed across the arrears buckets?",
             AUTO, "table", ("facilities", "exposure", "ecl", "coverage",
                             "mean_ltv"),
             cut="dpd_bucket", projects=("auto-collections",),
             tags=("delinquency",)),
    Analysis("home-bucket-mix", "Home Finance delinquency bucket mix",
             "How is the mortgage book distributed across the arrears "
             "buckets?",
             HOME, "table", ("facilities", "exposure", "ecl", "coverage",
                             "mean_ltv"),
             cut="dpd_bucket", projects=("home-stage2",),
             tags=("delinquency",)),
    _trend("retail-mean-dpd-trend", RETAIL,
           "Retail mean days past due, thirteen months",
           "Is the whole retail book slipping, or one product?",
           ("mean_dpd", "dpd1_29_share", "dpd30_share"),
           ("portfolio-quarter",), tags=("delinquency",)),
    _trend("cc-income-trend", CARD,
           "Credit Card verified income, thirteen months",
           "Has the income of the card book's customers moved?",
           ("mean_income", "mean_disposable", "mean_dbr"),
           ("traits-ecl", "cc-salaried"), tags=("affordability",)),
    _trend("retail-score-trend", RETAIL,
           "Retail behavioural score, thirteen months",
           "Has the retail behavioural score drifted?",
           ("mean_behaviour_score", "mean_pd", "dpd30_share"),
           ("traits-ecl", "cc-scorecard"), tags=("score",)),
    Analysis("cc-clean-forward-by-vintage",
             "Credit Card still-current accounts by vintage",
             "Which card vintages hold the clean population a forward-risk "
             "review is about?",
             CARD, "table", ("facilities", "exposure",
                             "mean_behaviour_score", "mean_pd",
                             "mean_utilisation"),
             cut="vintage", where={"dpd_bucket": "0"},
             projects=("ews-monitoring", "cc-scorecard"),
             tags=("forward-risk", "vintage")),
    Analysis("retail-stage2-current",
             "Retail stage 2 accounts with no arrears, by product",
             "How much of the stage 2 balance is fully up to date — the "
             "population SICR caught before the arrears did?",
             RETAIL, "table", ("facilities", "exposure", "ecl", "coverage",
                               "mean_pd"),
             cut="product", where={"dpd_bucket": "0", "ifrs9_stage": "2"},
             projects=("ews-monitoring", "ifrs9-close"),
             tags=("forward-risk", "staging")),

    # ----------------- scorecard monitoring and forward-risk, to the floor
    #
    # §17 asks for at least eight analyses on every demo project. These
    # bring `pf-scorecard` and `auto-ews` to it, and each is a question
    # those two reviews genuinely ask rather than a copy of a neighbour's
    # with the product swapped.
    Analysis("pf-score-by-segment",
             "Personal Finance behavioural score by customer segment",
             "Does the personal finance behavioural score sit where the "
             "segment would predict?",
             PERSONAL, "table", ("facilities", "mean_behaviour_score",
                                 "mean_pd", "dpd30_share", "coverage"),
             cut="segment", projects=("pf-scorecard",), tags=("score",)),
    Analysis("pf-score-by-dbr",
             "Personal Finance score against indebtedness",
             "Is the behavioural score already carrying the indebtedness "
             "the affordability policy screens on?",
             PERSONAL, "table", ("facilities", "mean_behaviour_score",
                                 "mean_pd", "mean_dbr", "dpd30_share"),
             cut="indebtedness_band", projects=("pf-scorecard",),
             tags=("score", "affordability")),
    Analysis("pf-score-by-stage",
             "Personal Finance predicted PD by stage",
             "Does the modelled PD rise with the stage it helps to set?",
             PERSONAL, "table", ("facilities", "mean_pd",
                                 "mean_behaviour_score", "coverage", "ecl"),
             cut="stage", projects=("pf-scorecard", "ifrs9-close"),
             tags=("score", "staging")),
    Analysis("pf-score-by-channel",
             "Personal Finance score by origination channel",
             "Are some channels writing accounts the score reads as safer "
             "than they behave?",
             PERSONAL, "table", ("facilities", "mean_behaviour_score",
                                 "mean_pd", "dpd30_share"),
             cut="channel", projects=("pf-scorecard",),
             tags=("score", "origination")),
    _trend("pf-lgd-trend", PERSONAL,
           "Personal Finance loss severity, thirteen months",
           "Has the loss-given-default assumption moved on the personal "
           "finance book?",
           ("mean_lgd", "coverage", "ecl"),
           ("pf-scorecard", "ifrs9-close"), tags=("ecl",)),
    Analysis("pf-score-by-employment",
             "Personal Finance score by employment status",
             "Does the score separate the employment groups the way the "
             "arrears do?",
             PERSONAL, "table", ("facilities", "mean_behaviour_score",
                                 "mean_pd", "dpd30_share", "mean_income"),
             cut="employment", projects=("pf-scorecard",),
             tags=("score", "affordability")),
    Analysis("auto-ews-by-segment",
             "Auto Finance still-current accounts by segment",
             "Which auto customers are current today and worth watching?",
             AUTO, "table", ("facilities", "customers", "exposure",
                             "mean_behaviour_score", "mean_pd",
                             "collateral_cover"),
             cut="segment", where={"dpd_bucket": "0"},
             projects=("auto-ews",), tags=("forward-risk",)),
    Analysis("auto-ews-balloon-current",
             "Auto Finance balloon exposure on current accounts",
             "How much balloon falls due on accounts that are fully up to "
             "date — the refinancing risk nobody is chasing yet?",
             AUTO, "table", ("facilities", "exposure", "balloon_exposure",
                             "balloon_within_year_share",
                             "mean_behaviour_score"),
             cut="balloon_band", where={"dpd_bucket": "0"},
             projects=("auto-ews", "auto-collections"),
             tags=("forward-risk", "balloon")),
    Analysis("auto-ews-by-vintage",
             "Auto Finance still-current accounts by vintage",
             "Which auto cohorts hold the clean population?",
             AUTO, "table", ("facilities", "exposure", "mean_ltv",
                             "collateral_cover", "mean_pd"),
             cut="vintage", where={"dpd_bucket": "0"},
             projects=("auto-ews",), tags=("forward-risk", "vintage")),
    _trend("auto-ews-cover-trend", AUTO,
           "Auto Finance collateral cover on current accounts",
           "Is cover eroding on the accounts that are still performing?",
           ("collateral_cover", "mean_ltv", "high_ltv_share"),
           ("auto-ews",), months=13, where={"dpd_bucket": "0"},
           tags=("forward-risk", "collateral")),
)


__all__ = ["ANALYSES", "Analysis", "OWNERS", "PROJECTS", "Project",
           "SEED_VERSION", "CARD", "PERSONAL", "AUTO", "HOME", "RETAIL"]
