#!/usr/bin/env python3
"""Write COCKPIT_DATA_CONTRACT.md from the map and the snapshot it reads.

Generated rather than written, so the document and the projection cannot
drift: every row below is the mapping the adapter actually applies.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))


def main() -> int:
    from backend.retail_cockpit_adapter import semantic_map as sm
    from backend.retail_cockpit_adapter.projection import relation_fields
    from backend.retail_cockpit_adapter.source import open_snapshot

    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--analytics-dir", type=Path,
                    default=ROOT / "data" / "retail" / "analytics")
    ap.add_argument("--metadata-dir", type=Path,
                    default=ROOT / "metadata" / "retail")
    ap.add_argument("--out", type=Path,
                    default=ROOT / "docs" / "retail_cockpit"
                    / "COCKPIT_DATA_CONTRACT.md")
    args = ap.parse_args()

    snapshot = open_snapshot(args.analytics_dir, args.metadata_dir)
    features = sm.feature_mappings(snapshot.columns)
    originations = sm.origination_mappings(snapshot.columns)

    def mappings_for(relation: str):
        if relation == sm.BEHAVIOUR:
            return sm.MAPS[relation] + features
        if relation == sm.ORIGINATION:
            return sm.MAPS[relation] + originations
        return sm.MAPS[relation]

    out: list[str] = []
    w = out.append
    w("# Cockpit Data — the contract the Cockpit reads it under")
    w("")
    w("Generated by `scripts/retail_cockpit/write_contract_doc.py`. Every row "
      "is the mapping the adapter applies; the document cannot drift from the "
      "projection because it is written from it.")
    w("")
    w("## The source")
    w("")
    w(f"- Domain: **Cockpit Data** (`{snapshot.manifest.get('dataset_name')}`"
      f", domain id `retail_cockpit`)")
    w(f"- Dataset version: `{snapshot.dataset_version}`")
    w(f"- Manifest hash: `{snapshot.manifest_hash}`")
    w(f"- Generator: `{snapshot.generator_version}`, seed "
      f"`{snapshot.manifest.get('seed')}`")
    w(f"- Grain: {snapshot.contract.get('grain')}")
    w(f"- Primary key: `{', '.join(snapshot.contract.get('primary_key', ()))}`")
    w(f"- Periods: {len(snapshot.periods)} months, "
      f"{snapshot.periods[0]} → {snapshot.latest_period}")
    w(f"- Rows: {int(snapshot.manifest.get('total_rows') or 0):,}; "
      f"customers {int(snapshot.manifest.get('distinct_customers_all_months') or 0):,}; "
      f"facilities {int(snapshot.manifest.get('distinct_facilities_all_months') or 0):,}")
    w(f"- Denomination: {snapshot.currency} units. "
      f"{snapshot.contract.get('rate_convention')} "
      f"{snapshot.contract.get('dpd_convention')}")
    w("")
    w("## What the projection publishes")
    w("")
    w("Amounts are converted to " + f"{sm.CURRENCY} {sm.AMOUNT_SCALE}"
      + " — each monetary column is its source column divided by 1,000,000, "
        "recorded field by field below. Nothing is relabelled.")
    w("")
    for relation in sorted(sm.MAPS):
        spec = sm.RELATION_SPEC[relation]
        mappings = mappings_for(relation)
        fields = relation_fields(relation, snapshot, mappings)
        by_name = {f["name"]: f for f in fields}
        w(f"### `{relation}`")
        w("")
        w(f"{spec['description']}")
        w("")
        w(f"- Grain: {spec['grain']}")
        w(f"- Key: `{', '.join(spec['key_columns'])}`")
        w(f"- Columns: {len(fields)}")
        w("")
        w("| column | unit | from | lineage |")
        w("|---|---|---|---|")
        for mapping in mappings:
            field = by_name[mapping.column]
            source = f"`{mapping.source}`" if mapping.source else "computed"
            unit = field["unit"] or "—"
            w(f"| `{mapping.column}` | {unit} | {source} | "
              f"{mapping.lineage} |")
        w("")
    w("## Concepts this book does not publish")
    w("")
    w("Absent from the release rather than present and null. The engine drops "
      "a canonical term whose field a release does not hold, which is how it "
      "says so instead of answering from nothing.")
    w("")
    for field, reason in sm.GAPS:
        w(f"- **`{field}`** — {reason}")
    w("")
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"wrote {args.out} ({len(out)} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
