"""
§14, §15 and the phase's case-governance honesty requirement.

    "Do not call a case human reviewed unless a real human approval record
     exists. Cases generated by rules, blueprints, migration or Claude must be
     identified honestly."

That is a reporting requirement, and reporting requirements are met or missed
in one place: the function that produces the number somebody quotes. So the
governance report is tested harder than the generator that feeds it.
"""

from __future__ import annotations

import pytest

from backend.teaching import schema as sc
from backend.teaching import status as st
from intelligence_factory.teaching import canonical as cn
from intelligence_factory.teaching import migrate as mg
from intelligence_factory.teaching import variants as vr
from tests.conftest import database_available

db = pytest.mark.skipif(not database_available(),
                        reason="needs the platform database")

if database_available():
    from sqlalchemy import text  # noqa: E402

    from backend.db.engine import SessionLocal  # noqa: E402
    from backend.services import teaching_library as tl  # noqa: E402


@pytest.fixture(scope="module")
def canonical() -> list[sc.TeachingCase]:
    return cn.cases()[:80]


@pytest.fixture(scope="module")
def batch(canonical) -> vr.Batch:
    return vr.generate(canonical)


# ================================================== §14 variant generation


def test_every_transform_section_14_names_is_implemented():
    ids = {t.id for t in vr.TRANSFORMS}
    assert {"formal", "casual", "abbreviated", "jargon", "omitted_subject",
            "reordered", "typo"} <= ids


def test_a_variant_is_a_different_sentence_asking_the_same_thing(batch,
                                                                 canonical):
    by_id = {c.case_id: c for c in canonical}
    assert batch.made
    for variant in batch.made[:40]:
        parent = by_id[variant.case_id.rsplit("-v", 1)[0]]
        assert variant.question != parent.question
        assert variant.concepts == parent.concepts
        assert [o.text for o in variant.objectives] == \
            [o.text for o in parent.objectives]


def test_a_transform_that_changes_nothing_makes_no_variant(canonical):
    """A transform that found nothing to change has produced a duplicate, and
    §15 exists to keep those out."""
    made = vr.variant(canonical[0], vr.Transform("noop", "No-op", lambda q: q))
    assert made is None


def test_a_variant_is_never_labelled_human_written(batch):
    for variant in batch.made:
        assert variant.authoring_method == st.VARIANT
        assert not variant.reviewer
        assert variant.review_status != st.APPROVED


def test_an_inheriting_variant_is_validated_but_still_not_approved(batch):
    """§14: a variant meeting all four conditions inherits the reviewed
    target, so its validators have passed on a target a person already read.
    That is AUTO_VALIDATED — approval still needs a person."""
    inheriting = batch.inheriting()
    assert inheriting
    assert {c.review_status for c in inheriting} == {st.AUTO_VALIDATED}


def test_a_variant_that_changes_the_meaning_goes_to_review(canonical):
    """§14: "Otherwise mark SME_REVIEW_REQUIRED." Not rejected — a variant a
    validator cannot vouch for is frequently the most interesting one, because
    it found a phrasing where the structure genuinely changes."""
    parent = canonical[0]
    changed = sc.TeachingCase.from_dict(parent.to_dict())
    changed.question = "Show me exposure."
    changed.concepts = ["something else"]
    verdict = vr.may_inherit(parent, changed,
                             transform=vr.BY_ID["casual"])
    assert not verdict
    assert verdict.reasons


def test_a_variant_that_introduces_an_ambiguity_cannot_inherit(canonical):
    parent = next(c for c in canonical
                  if "exposure at default" in c.question.lower())
    ambiguous = sc.TeachingCase.from_dict(parent.to_dict())
    ambiguous.question = parent.question.replace("exposure at default",
                                                 "exposure")
    verdict = vr.may_inherit(parent, ambiguous,
                             transform=vr.BY_ID["casual"])
    assert not verdict
    assert any("ambiguity" in r for r in verdict.reasons)


def test_a_variant_that_changes_the_period_cannot_inherit(canonical):
    parent = next(c for c in canonical if c.period_contract)
    moved = sc.TeachingCase.from_dict(parent.to_dict())
    moved.period_contract = {"phrase": "some other window"}
    verdict = vr.may_inherit(parent, moved, transform=vr.BY_ID["formal"])
    assert not verdict
    assert any("period" in r for r in verdict.reasons)


def test_a_generated_sentence_starts_with_a_capital(batch):
    """A corpus of questions beginning with a small letter teaches the model
    that the corpus was generated."""
    for variant in batch.made:
        assert variant.question[:1] == variant.question[:1].upper()


# ============================================== §15 clusters and duplicates


def test_a_variant_stays_inside_its_parents_cluster(batch, canonical):
    """Two questions that word-cluster apart but ARE the same question must
    not both be retrievable."""
    by_id = {c.case_id: c for c in canonical}
    for variant in batch.made:
        parent = by_id[variant.case_id.rsplit("-v", 1)[0]]
        assert variant.cluster_id == parent.cluster_id


def test_no_case_may_flood_the_library_with_variants(canonical):
    """Retrieval admits one case per cluster, so a cluster of forty is
    thirty-nine cases that can never be retrieved."""
    made = vr.generate(canonical, per_case=2)
    per_parent: dict[str, int] = {}
    for variant in made.made:
        parent = variant.case_id.rsplit("-v", 1)[0]
        per_parent[parent] = per_parent.get(parent, 0) + 1
    assert max(per_parent.values()) <= 2


def test_two_identical_variants_are_never_both_made(batch):
    prints = [c.fingerprint for c in batch.made]
    assert len(prints) == len(set(prints))


def test_the_cluster_view_separates_paraphrases_from_duplicates(canonical,
                                                                 batch):
    """Two different questions. A cluster holds paraphrases of one question
    and is expected to have several members; a duplicate group holds cases
    that teach exactly the same thing and should have one."""
    found = vr.clusters([*canonical, *batch.made])
    assert found.duplicates == {}
    assert found.total == len(canonical) + len(batch.made)
    assert len(found.by_cluster) <= found.total


def test_an_evaluation_split_cuts_on_clusters_rather_than_cases(canonical):
    """§15: a random split puts "What is total EAD by sector?" in development
    and "By sector, total EAD?" in evaluation, and the score then measures
    paraphrase matching."""
    development, evaluation = vr.split(canonical)
    assert development and evaluation
    left = {c.cluster_id for c in development}
    right = {c.cluster_id for c in evaluation}
    assert not (left & right)


def test_the_split_is_the_same_on_every_run(canonical):
    first = vr.split(canonical)
    second = vr.split(canonical)
    assert [c.case_id for c in first[0]] == [c.case_id for c in second[0]]


# ====================================== the case-governance honesty report


@db
def test_the_report_breaks_the_count_down_by_every_axis_the_phase_asks_for():
    session = SessionLocal()
    try:
        found = tl.governance(session)
    finally:
        session.close()

    assert set(found) >= {
        "cases", "by_status", "by_authoring_method", "by_provenance",
        "by_family", "by_difficulty", "by_scope", "by_language",
        "human_reviewed", "retrievable_now", "sentence"}
    assert set(found["by_status"]) == set(st.STATUSES)


@db
def test_a_case_is_only_human_reviewed_when_a_person_signed_it():
    """The way a case gets wrongly labelled human reviewed is not a deliberate
    lie — it is a status being read as an approval."""
    session = SessionLocal()
    try:
        session.execute(text("DELETE FROM teaching_case_events"))
        session.execute(text("DELETE FROM teaching_cases"))
        session.commit()

        case = cn.cases()[0]
        tl.save(session, case)
        assert tl.governance(session)["human_reviewed"] == 0

        tl.approve(session, case.case_id, reviewer="Amal",
                   note="read the plan against the ontology")
        found = tl.governance(session)
        assert found["human_reviewed"] == 1
        assert found["approved_without_a_reviewer"] == 0
        assert found["retrievable_now"] == 1
    finally:
        session.rollback()
        session.execute(text("DELETE FROM teaching_case_events"))
        session.execute(text("DELETE FROM teaching_cases"))
        session.commit()
        session.close()


def test_a_blueprint_case_is_not_described_as_hand_written():
    """Calling a generated instance hand-written is the exact dishonesty the
    phase forbids. The specification was reviewed; the phrasing was not
    typed."""
    assert st.BLUEPRINT in st.AUTHORING_METHODS
    assert st.BLUEPRINT in st.GENERATED
    assert {c.authoring_method for c in cn.cases()} == {st.BLUEPRINT}


def test_a_migrated_case_says_it_was_migrated():
    assert {c.authoring_method for c in mg.from_curriculum()} == {st.MIGRATED}
    assert {c.authoring_method for c in mg.from_complex()} == {st.MIGRATED}
    assert {c.authoring_method
            for c in mg.from_certified_methods()} == {st.DERIVED}


def test_nothing_in_the_corpus_claims_to_be_hand_written():
    """1,828 cases and not one of them was typed by a person. Whatever the
    report says, it must not say that."""
    everything = [*mg.cases(), *cn.cases()]
    assert not [c for c in everything if c.authoring_method == st.HUMAN]
    assert all(c.authoring_method in st.GENERATED for c in everything)
