"""How the retail app's signed-in user becomes the engine's principal.

The engine derives identity server-side and refuses to read it from a request
body (`routes.principal`). That rule is kept here: the principal crosses the
process boundary in a header the PROXY writes from the session it already
authenticated, authenticated itself with a per-launch shared secret, and the
engine trusts it only when that secret matches.

The secret is generated by the launcher and passed to both processes through
the environment. It is never logged, never returned in a response, and never
read from anything a browser can set.
"""

from __future__ import annotations

import hmac
import json
import os
from typing import Any

#: The header the proxy writes the principal into, and the one that
#: authenticates it. Named for what they are; neither is a cookie, so a
#: browser cannot forge one by navigating.
PRINCIPAL_HEADER = "x-cockpit-principal"
AUTH_HEADER = "x-cockpit-auth"

#: Where both processes read the per-launch secret from.
SECRET_VAR = "RETAIL_COCKPIT_HOST_SECRET"

#: The tenant every retail principal maps to. The retail application has no
#: tenant concept -- a principal is a user id and a role -- while the engine
#: tenant-scopes every store read and every materialised table. So the host
#: maps every authenticated principal to ONE configured tenant, server-side,
#: and it must be the tenant the published release actually carries.
TENANT_VAR = "RETAIL_COCKPIT_TENANT"
DEFAULT_TENANT = "demo-tenant"


class SecretMissing(RuntimeError):
    """Neither process may start without one. Said, rather than defaulted."""


def secret() -> str:
    value = str(os.environ.get(SECRET_VAR, "") or "").strip()
    if not value:
        raise SecretMissing(
            f"{SECRET_VAR} is not set. The retail proxy and the Cockpit "
            f"engine authenticate to each other with a per-launch secret, "
            f"and a default would be the same on every machine. The "
            f"candidate launcher generates one.")
    return value


def tenant() -> str:
    return str(os.environ.get(TENANT_VAR, "") or DEFAULT_TENANT).strip()


def encode(principal: dict[str, Any]) -> str:
    return json.dumps(principal, separators=(",", ":"), sort_keys=True)


def decode(raw: str) -> dict[str, Any] | None:
    try:
        value = json.loads(raw)
    except Exception:  # noqa: BLE001 - a malformed header is not a principal
        return None
    if not isinstance(value, dict) or not str(value.get("id") or ""):
        return None
    return value


def authentic(presented: str) -> bool:
    """Constant-time. A timing signal on the boundary secret is a real one."""
    try:
        return hmac.compare_digest(str(presented or ""), secret())
    except SecretMissing:
        return False


def forwarded_resolver() -> Any:
    """The engine's principal resolver, reading what the proxy forwarded."""

    def resolve(request: Any) -> dict[str, Any] | None:
        headers = request.headers
        if not authentic(headers.get(AUTH_HEADER, "")):
            return None
        return decode(headers.get(PRINCIPAL_HEADER, ""))

    return resolve


def principal_for(account: Any, role: Any) -> dict[str, Any]:
    """One retail account, as the engine's principal dict.

    `name` is carried because the engine's own resolver carries it; it is
    dropped by `context.build` and never reaches the model.
    """
    return {
        "id": str(getattr(account, "id", "") or getattr(account, "email", "")
                  or getattr(account, "username", "")),
        "tenant": tenant(),
        "name": str(getattr(account, "greeting_name", "")
                    or getattr(account, "username", "") or ""),
        "role": str(getattr(role, "value", "") or role or ""),
    }


__all__ = ["AUTH_HEADER", "DEFAULT_TENANT", "PRINCIPAL_HEADER", "SECRET_VAR",
           "SecretMissing", "TENANT_VAR", "authentic", "decode", "encode",
           "forwarded_resolver", "principal_for", "secret", "tenant"]
