"""
Where a V4 domain release lives. V4's own namespace, V4's own manifest.

Why not the V3 store
--------------------
V3's store writes `domain_id: "corporate_cockpit"` into every manifest it
produces, refuses to write at all unless `COCKPIT_AGENTIC_V3` is set, and
lives in the V3 lake. Publishing a Saudi retail book through it would tag
retail rows as corporate, make V4's data plane depend on a V3 feature flag,
and put two products' data in one namespace. None of those is a thing to
work around with a flag of our own.

So V4 publishes its own releases, into its own directory, with a manifest
that says which domain it is. Nothing here reads or writes anything of V3's.

Immutability and the fingerprint
--------------------------------
A published release is final. `publish` refuses an existing directory rather
than overwriting it, because an analysis saved last week names a release id
and expects the numbers it saw. New data means a new version.

The fingerprint is a digest over the bytes actually published -- every
parquet file and the manifest -- not over the id. A release id is a NAME, and
two builds can share a name and hold different numbers; the fingerprint is
what they cannot share. Everything downstream keys on both.
"""

from __future__ import annotations

import hashlib
import json
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from backend.cockpit_v4 import domains as dom
from backend.cockpit_v4 import schema as schema_mod

MANIFEST = "manifest.json"

#: Said on every release, so a reader months later cannot mistake it.
NOT_CLIENT_DATA = (
    "Synthetic demonstration data, generated by CreditProbe for Cockpit V4. "
    "It describes no real borrower, customer, account or institution, and "
    "every name in it is fictional.")

ORIGIN = "SYNTHETIC_DEMO"
DATA_VERSION = "4.0.0"
DEFAULT_TENANT = "demo-tenant"
COUNTRY = "SA"
COUNTRY_NAME = "Saudi Arabia"
CURRENCY = "SAR"
AMOUNT_SCALE = "million"
#: The reporting frequency of the DEFAULT book, kept for the readers that
#: still ask the lake for "the" frequency. Each domain's own frequency is
#: `schema.frequency(domain_id)` and that is what a published manifest
#: records: the Corporate book reports quarterly and the Retail book monthly,
#: and one constant for both is how a quarterly book came to be described as
#: monthly on every screen that read this.
FREQUENCY = "quarterly"


class ReleaseNotFound(LookupError):
    """The release is not published here. Said, never substituted."""


class ReleaseExists(RuntimeError):
    """A published release is immutable. Publish a new version instead."""


def root() -> Path:
    """The V4 lake. Beside the V3 one, never inside it."""
    from backend.config import settings

    return Path(settings.analytics_dir).parent / "cockpit_v4_lake"


def release_dir(release_id: str) -> Path:
    name = str(release_id or "").strip()
    if not name or "/" in name or "\\" in name or name.startswith("."):
        raise ValueError(f"{release_id!r} is not a usable release id.")
    return root() / name


def relation_path(release_id: str, relation: str) -> Path:
    path = release_dir(release_id) / f"{relation}.parquet"
    if not path.exists():
        raise ReleaseNotFound(
            f"{relation!r} is not published in release {release_id!r}.")
    return path


def exists(release_id: str) -> bool:
    return (release_dir(release_id) / MANIFEST).exists()


def read_manifest(release_id: str) -> dict[str, Any]:
    path = release_dir(release_id) / MANIFEST
    if not path.exists():
        raise ReleaseNotFound(
            f"Release {release_id!r} is not published in this runtime. "
            f"Nothing was substituted for it.")
    return json.loads(path.read_text(encoding="utf-8"))


def releases() -> list[str]:
    base = root()
    if not base.exists():
        return []
    return sorted(p.name for p in base.iterdir()
                  if (p / MANIFEST).exists())


def _digest(paths: list[Path]) -> str:
    """SHA-256 over the published bytes, in a fixed order."""
    digest = hashlib.sha256()
    for path in sorted(paths, key=lambda p: p.name):
        digest.update(path.name.encode("utf-8"))
        digest.update(path.read_bytes())
    return digest.hexdigest()


def fingerprint(release_id: str) -> str:
    """The digest recorded when this release was published."""
    return str(read_manifest(release_id).get("release_fingerprint") or "")


def _built_with() -> dict[str, str]:
    """What produced this release, recorded on it.

    A release is supposed to be one book. `v4-saudi-retail-20m-v4` was two:
    the generator's customer-level mean went through the builtin `sum`,
    whose float behaviour CPython changed in 3.12, so a 3.11 machine and a
    3.13 machine published different numbers under one id and both
    manifests looked right -- same rows, same entities, same fields. It
    took a day to find because nothing on the release said what had made
    it.

    So each release now says. The generators are exact arithmetic again and
    this block should never be the answer to anything; it is here so that
    the NEXT divergence of that kind is a lookup rather than an
    investigation. Nothing reads it to make a decision -- substituting a
    release because its versions look close enough is the failure this
    whole area exists to prevent.
    """
    import sys

    out = {"python": ".".join(str(n) for n in sys.version_info[:3])}
    for name in ("pandas", "numpy", "pyarrow"):
        try:  # noqa: SIM105 - an absent optional library is not an error here
            out[name] = str(__import__(name).__version__)
        except Exception:  # noqa: BLE001 - not installed, and it need not be
            pass
    return out


@dataclass(frozen=True)
class Build:
    """A domain release, in memory, on its way to being published."""

    domain_id: str
    release_id: str
    periods: tuple[str, ...]
    frames: dict[str, Any]
    counts: dict[str, int]
    notes: dict[str, Any]


def publish(build: Build, *, overwrite: bool = False,
            tenant_id: str = DEFAULT_TENANT) -> dict[str, Any]:
    """Write the release and its manifest. Refuses to overwrite by default."""
    import pandas as pd  # noqa: F401  (frames are already DataFrames)

    domain_id = dom.parse(build.domain_id)
    target = release_dir(build.release_id)
    if (target / MANIFEST).exists() and not overwrite:
        raise ReleaseExists(
            f"Release {build.release_id!r} is already published and a "
            f"published release is immutable. Publish a new version rather "
            f"than rewriting this one.")
    if target.exists() and overwrite:
        shutil.rmtree(target)
    target.mkdir(parents=True, exist_ok=True)

    expected = set(schema_mod.relation_names(domain_id))
    missing = expected - set(build.frames)
    if missing:
        raise ValueError(
            f"{build.release_id}: the {domain_id} domain defines "
            f"{sorted(missing)} and the build did not produce them.")

    written: list[Path] = []
    for name in sorted(build.frames):
        frame = build.frames[name]
        spec = schema_mod.relation(domain_id, name)
        # Column ORDER is the schema's, not the generator's, so two builds of
        # the same data fingerprint the same.
        frame = frame[list(spec.columns)]
        path = target / f"{name}.parquet"
        frame.to_parquet(path, index=False)
        written.append(path)

    manifest: dict[str, Any] = {
        "release_id": build.release_id,
        "domain_id": domain_id,
        "domain_label": dom.LABELS[domain_id],
        "origin": ORIGIN,
        "data_version": DATA_VERSION,
        "not_client_data": NOT_CLIENT_DATA,
        "tenants": [tenant_id],
        "geography": COUNTRY,
        "geography_name": COUNTRY_NAME,
        "reporting_currency": CURRENCY,
        "amount_scale": AMOUNT_SCALE,
        "reporting_frequency": schema_mod.frequency(domain_id),
        "reporting_periods": list(build.periods),
        "latest_period": build.periods[-1] if build.periods else "",
        "relations": [spec.to_dict()
                      for spec in schema_mod.relations(domain_id)],
        "row_counts": {name: int(len(build.frames[name]))
                       for name in sorted(build.frames)},
        "entity_counts": dict(build.counts),
        "notes": dict(build.notes),
        "built_with": _built_with(),
    }
    # The digest covers the parquet bytes. The manifest then records it, so
    # reading the fingerprint back is a lookup rather than a re-hash of a
    # file that now contains its own hash.
    manifest["release_fingerprint"] = _digest(written)
    (target / MANIFEST).write_text(
        json.dumps(manifest, indent=2, sort_keys=True, default=str),
        encoding="utf-8")
    return manifest


def verify(release_id: str) -> bool:
    """Do the published bytes still match the fingerprint recorded for them?"""
    manifest = read_manifest(release_id)
    target = release_dir(release_id)
    paths = [p for p in target.glob("*.parquet")]
    return _digest(paths) == str(manifest.get("release_fingerprint") or "")


def forget(release_id: str = "") -> None:
    """Delete a release. For tests and for a build that failed its gates."""
    if release_id:
        target = release_dir(release_id)
        if target.exists():
            shutil.rmtree(target)
        return
    base = root()
    if base.exists():
        shutil.rmtree(base)


__all__ = ["AMOUNT_SCALE", "Build", "COUNTRY", "COUNTRY_NAME", "CURRENCY",
           "DEFAULT_TENANT", "FREQUENCY", "MANIFEST", "NOT_CLIENT_DATA",
           "ReleaseExists", "ReleaseNotFound", "exists", "fingerprint",
           "forget", "publish", "read_manifest", "relation_path",
           "release_dir", "releases", "root", "verify"]
