"""
The CBUAE MMS/MMG-aligned validation report, as content. §51-§56, §82, §89.

What this module is careful about
-----------------------------------
**It computes nothing.** Every figure comes from a dashboard that was
already built by the deterministic engine and from rows the registry
already holds. §51 says the model is not asked to recalculate numbers, and
the way that survives is that there is nothing here to recalculate with:
this file has no arithmetic beyond formatting, and no provider call.

**It never claims a certification.** §0: CreditProbe does not provide
regulatory certification or legal compliance. The structure is *aligned
with* CBUAE MMS/MMG — that is a claim about the section list, not about a
regulator having approved anything — and `DISCLAIMER` travels into the
stored report record so a copy downloaded in March still carries the words
it was issued with.

**Absence is written down.** A section that could not be computed says why.
A month whose performance window has not closed produces a discrimination
and stability report with an outcome section that states when the window
closes, not one with zeros in it (§7). A metric with no approved limit
reads NO APPROVED LIMIT, which §50 says is not a pass.

The coverage map is the interesting part
------------------------------------------
§89 lists seventeen things the report must address. `COVERAGE` maps each to
the section that addresses it, and `coverage()` checks that section exists
and has content. That makes §89 a structural test rather than a search for
keywords: a report can contain the word "calibration" and say nothing about
it, and a section list with a hole in it cannot.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass, field
from datetime import UTC, datetime
from typing import Any

from backend.scorecard import build as build_mod
from backend.scorecard import dashboard as dash
from backend.scorecard import equation as equation_mod
from backend.scorecard import policy as policy_mod
from backend.scorecard import synthetic as synth
from backend.scorecard import variables as vars_mod

REPORT_STRUCTURE_VERSION = "cbuae-mms-mmg-aligned-1.0.0"

#: §0. Stored with every report record, not rendered from a template at
#: download time: a disclaimer that lives only in a template is one refactor
#: away from not existing.
DISCLAIMER = (
    "This report is produced by CreditProbe from the data and models "
    "described in it. Its structure is aligned with the CBUAE Model "
    "Management Standards and Guidance section list. CreditProbe does not "
    "provide regulatory certification or a legal compliance opinion, and "
    "nothing in this report constitutes one. The validation opinion is "
    "derived by the governed policy set out in section 12 from the findings "
    "and limits recorded here, and remains subject to the institution's own "
    "review and approval.")

#: §2. Every report over the demonstration universe says what it is over.
SYNTHETIC_NOTICE = (
    "Every figure in this report is computed over synthetic demonstration "
    "data generated by CreditProbe and marked SYNTHETIC_DEMO. It describes "
    "no real customer, no real applicant and no real bank's book, and it is "
    "not client data.")


class ReportError(Exception):
    """A report that cannot be built as asked."""


# --------------------------------------------------------------- formatting


def stat(value: Any, places: int = 4) -> str:
    """A validation statistic on the unit interval.

    Four decimals, matching the screens. An AUC that moved from 0.7179 to
    0.7104 is the finding, and at two decimals both read 0.72.
    """
    if value is None or value == "":
        return "—"
    try:
        return f"{float(value):.{places}f}"
    except (TypeError, ValueError):
        return str(value)


def percent(value: Any) -> str:
    """A rate, under the two-decimal display contract."""
    if value is None or value == "":
        return "—"
    try:
        return f"{float(value) * 100:.2f}%"
    except (TypeError, ValueError):
        return str(value)


def count(value: Any) -> str:
    if value is None or value == "":
        return "—"
    try:
        return f"{int(value):,}"
    except (TypeError, ValueError):
        return str(value)


def text(value: Any) -> str:
    return "—" if value in (None, "") else str(value)


# ------------------------------------------------------------------ content


@dataclass
class Table:
    """One table, with the caption §53 asks every table to carry."""

    caption: str
    columns: list[str]
    rows: list[list[str]]
    note: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {"caption": self.caption, "columns": list(self.columns),
                "rows": [list(r) for r in self.rows], "note": self.note}


@dataclass
class Section:
    """One numbered section. `number` carries its depth: "8.2" is level 2."""

    number: str
    title: str
    narrative: str = ""
    tables: list[Table] = field(default_factory=list)
    #: Set when the section could not be computed. Rendered instead of
    #: figures, never alongside a zero.
    unavailable: str = ""

    @property
    def level(self) -> int:
        return self.number.count(".") + 1

    @property
    def has_content(self) -> bool:
        return bool(self.narrative or self.tables or self.unavailable)

    def to_dict(self) -> dict[str, Any]:
        return {"number": self.number, "title": self.title,
                "level": self.level, "narrative": self.narrative,
                "tables": [t.to_dict() for t in self.tables],
                "unavailable": self.unavailable}


@dataclass
class Evidence:
    """§55. One figure, and everything needed to find it again."""

    section: str
    label: str
    metric: str
    value_text: str
    method: str
    period: str
    model_version: str
    validation_state: str
    analysis_run_id: str = ""
    data_version: str = ""
    value: float | None = None
    workbook_sheet: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "section": self.section, "label": self.label,
            "metric": self.metric, "value": self.value,
            "value_text": self.value_text, "method": self.method,
            "period": self.period, "model_version": self.model_version,
            "validation_state": self.validation_state,
            "analysis_run_id": self.analysis_run_id,
            "data_version": self.data_version,
            "workbook_sheet": self.workbook_sheet,
        }


@dataclass
class Report:
    """The whole document, as content. No format decisions live here."""

    report_id: str
    model_id: str
    model_version: str
    model_name: str
    scorecard_type: str
    model_kind: str
    period: str
    title: str
    structure_version: str
    generated_at: str
    generated_by: str
    opinion: str
    document_control: list[tuple[str, str]] = field(default_factory=list)
    sections: list[Section] = field(default_factory=list)
    evidence: list[Evidence] = field(default_factory=list)
    disclaimer: str = DISCLAIMER
    origin: str = synth.ORIGIN

    def section(self, number: str) -> Section | None:
        for entry in self.sections:
            if entry.number == number:
                return entry
        return None

    @property
    def content_hash(self) -> str:
        """§56. A hash of the analysis, not of the act of generating it.

        Section 1 is excluded, and that exclusion is the whole design. The
        document-control table holds who generated the report and on what
        date, so hashing it would make every regeneration a different hash
        and the number would only ever answer "was this run twice?".

        Everything a validator argues about — the figures, the findings, the
        limits, the opinion, every refusal — is in sections 2 to 13 and is
        hashed. So across §82's regenerations the question the hash answers
        is the useful one: has anything about the model's assessment
        changed, or is this the same report with a new cover?
        """
        body = json.dumps(
            {"model": [self.model_id, self.model_version],
             "period": self.period, "opinion": self.opinion,
             "structure": self.structure_version,
             "sections": [s.to_dict() for s in self.sections
                          if not s.number.startswith("1.")
                          and s.number != "1"]},
            sort_keys=True, default=str)
        return hashlib.sha256(body.encode("utf-8")).hexdigest()

    def to_dict(self) -> dict[str, Any]:
        return {
            "report_id": self.report_id, "model_id": self.model_id,
            "model_version": self.model_version,
            "model_name": self.model_name,
            "scorecard_type": self.scorecard_type,
            "model_kind": self.model_kind, "period": self.period,
            "title": self.title,
            "structure_version": self.structure_version,
            "generated_at": self.generated_at,
            "generated_by": self.generated_by, "opinion": self.opinion,
            "document_control": [list(p) for p in self.document_control],
            "sections": [s.to_dict() for s in self.sections],
            "evidence": [e.to_dict() for e in self.evidence],
            "evidence_count": len(self.evidence),
            "content_hash": self.content_hash,
            "disclaimer": self.disclaimer,
            "origin": self.origin,
            "not_client_data": SYNTHETIC_NOTICE,
        }


# ------------------------------------------------------------ §89 coverage


#: §89's seventeen topics, each mapped to the section that addresses it.
COVERAGE: dict[str, str] = {
    "model identification": "1",
    "materiality and classification": "1",
    "scope, purpose and usage": "3",
    "governance": "4",
    "data": "5",
    "default definition": "5",
    "model design": "6",
    "variables and transformations": "6",
    "validation data": "5",
    "implementation": "7",
    "discrimination": "8.2",
    "calibration": "8.3",
    "stability": "8.4",
    "sensitivity": "8.5",
    "findings and severity": "10",
    "remediation": "12",
    "model risk rating": "11",
    "overall conclusion": "12",
}


def coverage(report: Report) -> dict[str, Any]:
    """§89. Which of the required topics this report actually addresses.

    A topic counts as addressed only if its section exists and has content.
    An empty section with the right heading is the failure mode this check
    exists for.
    """
    addressed: dict[str, str] = {}
    missing: list[str] = []
    for topic, number in COVERAGE.items():
        found = report.section(number)
        if found is not None and found.has_content:
            addressed[topic] = f"{found.number} {found.title}"
        else:
            missing.append(topic)
    return {"addressed": addressed, "missing": missing,
            "complete": not missing, "topics": len(COVERAGE)}


# ------------------------------------------------------------- the builder


def _control_rows(context: dash.Context, registered: Any,
                  *, report_id: str, generated_at: str, generated_by: str,
                  report_version: str) -> list[tuple[str, str]]:
    """§52.1's document-control table."""
    return [
        ("Model ID", text(getattr(registered, "model_id", ""))),
        ("Model name", text(getattr(registered, "model_name", ""))),
        ("Model version", text(getattr(registered, "model_version", ""))),
        ("Scorecard type", context.scorecard_type),
        ("Model owner", text(getattr(registered, "owner", ""))),
        ("Developer", text(getattr(registered, "developer", ""))),
        ("Validator", text(getattr(registered, "validator", ""))),
        ("Materiality", text(getattr(registered, "materiality", ""))),
        ("Model risk rating",
         text(getattr(registered, "model_risk_rating", ""))),
        ("Classification", "Internal — model validation"),
        ("Validation period", context.month),
        ("Validation date", generated_at[:10]),
        ("Report ID", report_id),
        ("Report version", report_version),
        ("Generated by", generated_by),
        ("Approval status",
         text(getattr(registered, "status", "")) + " (model status)"),
        ("Data origin", synth.ORIGIN),
    ]


def _limits_table(limits: list[dict[str, Any]]) -> Table:
    """§81's five columns. `Source` is the one that cannot be dropped."""
    rows = []
    for entry in limits:
        limit = entry.get("limit") or {}
        rows.append([
            text(entry.get("label") or entry.get("metric")),
            stat(entry.get("observed")),
            (stat(limit.get("breach_at")) if limit.get("breach_at") is not None
             else "—"),
            text(entry.get("status")),
            text(limit.get("provenance") or "—"),
        ])
    return Table(
        caption="Monitoring limits and observed values",
        columns=["Metric", "Observed", "Limit", "Status", "Source"],
        rows=rows,
        note=("Limits marked DEMO POLICY are demonstration defaults seeded "
              "for this workspace. They are not regulatory requirements, and "
              "a metric with no approved limit is reported as NO APPROVED "
              "LIMIT rather than as a pass."))


def _refusal(section: dict[str, Any]) -> str:
    """The dashboard's own reason a section could not be computed.

    Quoted rather than restated. The engine already decided this section was
    unavailable and said why; a report that writes its own version of the
    reason is a second place for that sentence to drift, and the two
    disagreeing is worse than either being slightly worse worded.
    """
    if section.get("available") is False:
        return text(section.get("why"))
    return ""


def _not_matured(context: dash.Context) -> str:
    closes = synth.window_closes(context.month,
                                 horizon=context.horizon_months)
    return (
        f"{context.month} has not completed its "
        f"{context.horizon_months}-month performance window, so no outcome "
        "exists to compare predictions against and this section is not "
        f"reported for this month. The window closes in {closes}. The "
        "latest month whose window has closed is "
        f"{context.latest_matured_month or 'none in this data'}.")


def build(scorecard_type: str, *, month: str = "",
          model_kind: str = "INCUMBENT", report_id: str = "",
          report_version: str = "1", generated_by: str = "",
          generated_at: str = "", registered: Any = None,
          findings: list[dict[str, Any]] | None = None) -> Report:
    """Assemble §52's thirteen sections for one model and one month.

    `registered` is the registry row when there is one. The report is built
    without it — an installation that scored a lake but registered nothing
    can still produce a validation report — and says so in section 1 rather
    than inventing an owner and a materiality.
    """
    board = dash.build_dashboard(scorecard_type, model_kind=model_kind,
                                 month=month, curves=False)
    payload = board.to_dict()
    context = board.context
    generated_at = generated_at or _iso_now()
    report_id = report_id or _report_id(scorecard_type, model_kind,
                                        context.month, report_version)

    equation = build_mod.load_equation(scorecard_type, model_kind)
    spec = build_mod.load_spec(scorecard_type)
    version = text(getattr(registered, "model_version", "unregistered"))
    state = payload["context"]["outcome_maturity_status"]
    data_version = f"{scorecard_type.lower()}-lake:{context.month}"

    sections: list[Section] = []
    evidence: list[Evidence] = []

    def add_evidence(section: str, label: str, metric: str, value: Any,
                     value_text: str, method: str, sheet: str) -> None:
        evidence.append(Evidence(
            section=section, label=label, metric=metric,
            value=(float(value) if isinstance(value, int | float) else None),
            value_text=value_text, method=method, period=context.month,
            model_version=version, validation_state=state,
            analysis_run_id=payload["context"].get("reference_population", ""),
            data_version=data_version, workbook_sheet=sheet))

    sections += _cover(context, registered, payload, report_id=report_id,
                       generated_at=generated_at, generated_by=generated_by,
                       report_version=report_version)
    sections += _executive_summary(payload, context, add_evidence)
    sections += _purpose(context, registered, payload)
    sections += _governance(registered)
    sections += _data(payload, context, registered)
    sections += _design(equation, spec, payload, context)
    sections += _implementation(payload, context, add_evidence)
    sections += _quantitative(payload, context, add_evidence)
    sections += _monitoring(payload, context)
    sections += _findings(payload, findings)
    sections += _model_risk(payload, registered, context)
    sections += _conclusion(payload)
    sections += _appendices(equation, spec, payload, context, evidence)

    opinion = ((payload.get("validation_opinion") or {}).get("opinion")
               or "NOT DETERMINED")

    return Report(
        report_id=report_id,
        model_id=text(getattr(registered, "model_id", "")),
        model_version=version,
        model_name=equation.model_name,
        scorecard_type=scorecard_type, model_kind=model_kind,
        period=context.month,
        title=(f"{scorecard_type.title()} Scorecard Validation Report — "
               f"{context.month}"),
        structure_version=REPORT_STRUCTURE_VERSION,
        generated_at=generated_at, generated_by=generated_by,
        opinion=opinion, document_control=_control_rows(
            context, registered, report_id=report_id,
            generated_at=generated_at, generated_by=generated_by,
            report_version=report_version),
        sections=sections, evidence=evidence)


def _iso_now() -> str:
    return datetime.now(UTC).replace(microsecond=0).isoformat()


def _report_id(scorecard_type: str, model_kind: str, month: str,
               version: str) -> str:
    return (f"SCV-{scorecard_type[:3].upper()}-{model_kind[:3].upper()}-"
            f"{month.replace('-', '')}-v{version}")


def filename_for(report: Report, extension: str) -> str:
    """§51's filename, with anything awkward removed."""
    def safe(value: str) -> str:
        return "".join(c if c.isalnum() or c in "-_" else "-"
                       for c in str(value)).strip("-") or "unknown"

    return (f"CreditProbe_{safe(report.scorecard_type)}_"
            f"{safe(report.model_kind)}_{safe(report.period)}_"
            f"Validation_Report.{extension}")


# --------------------------------------------------------------- §52.1-52.4


def _cover(context: dash.Context, registered: Any, payload: dict[str, Any], *,
           report_id: str, generated_at: str, generated_by: str,
           report_version: str) -> list[Section]:
    rows = [[label, value] for label, value in _control_rows(
        context, registered, report_id=report_id, generated_at=generated_at,
        generated_by=generated_by, report_version=report_version)]
    narrative = SYNTHETIC_NOTICE
    if registered is None:
        narrative += (
            " This model is not recorded in the scorecard model registry, so "
            "the owner, developer, validator, materiality and model risk "
            "rating are shown as unavailable rather than assumed. Register "
            "the model to complete this section.")
    return [Section("1", "Cover and document control", narrative,
                    [Table("Document control", ["Field", "Value"], rows)])]


def _executive_summary(payload: dict[str, Any], context: dash.Context,
                       add_evidence) -> list[Section]:
    opinion = payload.get("validation_opinion") or {}
    discrimination = payload.get("discrimination") or {}
    calibration = payload.get("calibration") or {}
    stability = payload.get("stability") or {}
    # The engine returns a whole PSI object — bins, contributions, the note
    # about the conventional cut-offs. The index is the figure; passing the
    # object would put a serialised dict where a number belongs.
    score_psi = (stability.get("score_psi") or {}).get("index")
    counts = (payload.get("findings") or {}).get("counts") or {}

    kpis = [
        ["Validation opinion", text(opinion.get("opinion"))],
        ["Gini", stat(discrimination.get("gini"))],
        ["AUC", stat(discrimination.get("auc"))],
        ["KS", stat(discrimination.get("ks"))],
        ["Observed default rate",
         percent(calibration.get("observed_default_rate"))],
        ["Average predicted PD",
         percent(calibration.get("average_predicted_pd"))],
        ["Score PSI", stat(score_psi)],
        ["Population", count((payload.get("summary") or {}).get("population"))],
    ]
    for label, metric, value in (
            ("Gini", "gini", discrimination.get("gini")),
            ("AUC", "auc", discrimination.get("auc")),
            ("KS", "ks", discrimination.get("ks")),
            ("Score PSI", "score_psi", score_psi)):
        add_evidence("2", label, metric, value, stat(value),
                     "Deterministic scorecard engine", "METRICS")

    severity = [[level, str(counts.get(level, 0))]
                for level in policy_mod.SEVERITIES]
    narrative = (
        f"This report validates the {context.scorecard_type.lower()} "
        f"scorecard on {context.month}. "
        + text(payload["context"].get("what_this_means")) + " "
        + text(opinion.get("because")))
    return [Section(
        "2", "Executive summary", narrative,
        [Table("Key performance indicators", ["Indicator", "Value"], kpis),
         Table("Findings by severity", ["Severity", "Count"], severity)])]


def _purpose(context: dash.Context, registered: Any,
             payload: dict[str, Any]) -> list[Section]:
    summary = payload.get("summary") or {}
    rows = [
        ["Business use",
         text(getattr(registered, "product_scope", "")
              or f"{context.scorecard_type.title()} retail lending")],
        ["Target population",
         text(getattr(registered, "population", "")
              or summary.get("population"))],
        ["Decision supported",
         "Origination decisioning and limit setting"
         if context.scorecard_type == "APPLICATION"
         else "Account management, limit review and early collections"],
        ["Performance horizon", f"{context.horizon_months} months"],
        ["Latest data month", context.latest_data_month],
        ["Latest matured performance month",
         text(context.latest_matured_month)],
        ["Scale (this month)", count(summary.get("population"))],
        ["Overrides", "Not recorded in this workspace"],
    ]
    return [Section(
        "3", "Model purpose, scope and usage",
        "The population, the decision the score supports and the horizon "
        "over which its predictions are assessed.",
        [Table("Purpose and scope", ["Field", "Value"], rows)])]


def _governance(registered: Any) -> list[Section]:
    rows = [
        ["Model owner", text(getattr(registered, "owner", ""))],
        ["Developer", text(getattr(registered, "developer", ""))],
        ["Independent validator",
         text(getattr(registered, "validator", ""))],
        ["Registry status", text(getattr(registered, "status", ""))],
        ["Implementation date",
         text(getattr(registered, "implementation_date", ""))],
        ["Last validation date",
         text(getattr(registered, "last_validation_date", ""))],
    ]
    narrative = (
        "Development and independent validation are separate roles in the "
        "registry, and the permission that proposes a change to a model is "
        "wider than the permission that approves one: proposing and "
        "accepting are recorded as different acts by different people. "
        "Limitations of this workspace are stated in section 11.")
    return [Section("4", "Governance and independence", narrative,
                    [Table("Roles and lifecycle", ["Role", "Held by"], rows)])]


def _data(payload: dict[str, Any], context: dash.Context,
          registered: Any) -> list[Section]:
    quality = payload.get("data_quality") or {}
    definition = dict(getattr(registered, "default_definition", None)
                      or build_mod.DEFAULT_DEFINITION)
    data_rows = [
        ["Development population",
         text(getattr(registered, "development_period", "")
              or f"{synth.DEVELOPMENT_MONTHS[0]} to "
                 f"{synth.DEVELOPMENT_MONTHS[-1]}")],
        ["Validation month", context.month],
        ["Rows", count(quality.get("rows"))],
        ["Unique keys", count(quality.get("unique_keys"))],
        ["Duplicate keys", count(quality.get("duplicate_keys"))],
        ["Defaults", count(quality.get("defaults"))],
        ["Outcome missing", count(quality.get("outcome_missing"))],
        ["Performance window closed",
         "Yes" if quality.get("matured") else "No"],
        ["Data origin", synth.ORIGIN],
    ]
    definition_rows = [[key.replace("_", " ").title(), text(value)]
                       for key, value in definition.items()]
    narrative = (
        "The development population is out of time with respect to the "
        "validation months, so no validation month contributed to fitting "
        "the model or to the Weight of Evidence bins. "
        + _not_matured(context) if not context.outcomes_available else
        "The development population is out of time with respect to the "
        "validation months, so no validation month contributed to fitting "
        "the model or to the Weight of Evidence bins.")
    return [Section(
        "5", "Development and validation data", narrative,
        [Table("Data summary", ["Field", "Value"], data_rows),
         Table("Default definition", ["Element", "Value"], definition_rows,
               note=("The definition is reproduced in full because it is "
                     "what every outcome figure in this report counts."))])]


def _design(equation: Any, spec: Any, payload: dict[str, Any],
            context: dash.Context) -> list[Section]:
    spec_payload = spec.to_dict().get("variables") or {}
    terms = [[t["variable"], stat(t["coefficient"], 6), t["transformation"],
              text(spec_payload.get(t["variable"], {}).get("iv_strength")),
              stat(spec_payload.get(t["variable"], {})
                   .get("information_value"))]
             for t in equation.to_dict()["terms"]]
    mapping = equation.to_dict().get("score_mapping") or {}
    mapping_rows = [
        ["Link", equation.link],
        ["Intercept", stat(equation.intercept, 6)],
        ["Base score", text(mapping.get("base_score"))],
        ["Points to double the odds", text(mapping.get("pdo"))],
        ["Base odds", text(mapping.get("base_odds"))],
        ["Score direction", text(mapping.get("score_direction"))],
        ["Factor", stat(mapping.get("factor"), 6)],
        ["Offset", stat(mapping.get("offset"), 6)],
        ["Formula", text(mapping.get("formula"))],
    ]
    # §52.6's economic rationale. The expected direction comes from the
    # variable dictionary and the verdict from the equation validator's
    # own sign check — not from re-deriving it here, which would let this
    # section agree with the model by construction.
    validation = equation_mod.validate(equation, spec=spec)
    flagged = {
        problem.get("variable"): problem.get("detail")
        for problem in (validation.to_dict()["warnings"]
                        + validation.to_dict()["blocking"])
        if problem.get("check") == "coefficient_sign_matches_credit_sense"}
    sense = []
    for term in equation.to_dict()["terms"]:
        name = term["variable"]
        variable = vars_mod.get(context.scorecard_type, name)
        sense.append([name, text(variable.risk_direction),
                      stat(term["coefficient"], 6),
                      "Flagged: " + text(flagged[name]) if name in flagged
                      else "Consistent"])
    narrative = (
        "The model is a logistic scorecard over Weight of Evidence "
        "transformed variables. The bins were fitted on the development "
        "population and frozen; §10's rule that Weight of Evidence is not "
        "recalculated from the validation month is why the specification "
        f"version ({spec.spec_version}) is reported alongside every figure. "
        "Demographic fields are held in the dictionary for fairness "
        "monitoring and are not scoreable: an equation referencing one is "
        "refused rather than fitted around.")
    tables = [
        Table("Model equation terms",
              ["Variable", "Coefficient", "Transformation", "IV strength",
               "Information value"], terms,
              note=("IV strength labels are a modelling convention, not a "
                    "regulatory classification.")),
        Table("Score mapping", ["Element", "Value"], mapping_rows),
    ]
    if sense:
        tables.append(Table(
            "Economic logic of each term",
            ["Variable", "Expected risk direction", "Coefficient",
             "Sign matches credit sense"], sense))
    return [Section("6", "Model design and conceptual soundness", narrative,
                    tables)]


def _implementation(payload: dict[str, Any], context: dash.Context,
                    add_evidence) -> list[Section]:
    check = payload.get("implementation") or {}
    rows = [
        ["Rows checked", count(check.get("rows_checked"))],
        ["Max absolute logit difference",
         stat(check.get("max_absolute_logit_difference"), 8)],
        ["Max absolute PD difference",
         stat(check.get("max_absolute_pd_difference"), 8)],
        ["Max absolute score difference",
         stat(check.get("max_absolute_score_difference"), 6)],
        ["Bin assignment mismatches",
         count(check.get("bin_assignment_mismatches"))],
        ["Mismatched rows", count(check.get("mismatch_count"))],
        ["Rounding tolerance", text(check.get("rounding_tolerance"))],
        ["Status", text(check.get("status"))],
    ]
    add_evidence("7", "Implementation replication", "mismatch_rate",
                 check.get("mismatch_rate"), stat(check.get("mismatch_rate")),
                 "Independent re-scoring from the stored equation",
                 "IMPLEMENTATION")
    return [Section(
        "7", "Implementation verification",
        "Every scored row is recomputed from the stored binning "
        "specification and the stored equation, and the two are compared at "
        "each stage — bin, Weight of Evidence, logit, PD and score. "
        + text(check.get("why")),
        [Table("Score replication", ["Check", "Result"], rows)])]


# ----------------------------------------------------------------- §52.8


def _quantitative(payload: dict[str, Any], context: dash.Context,
                  add_evidence) -> list[Section]:
    sections = [Section(
        "8", "Quantitative validation",
        "Discrimination and stability are reported for every month. "
        "Outcome-dependent sections are reported only where the performance "
        "window has closed.")]

    quality = payload.get("data_quality") or {}
    sufficiency = quality.get("sample_sufficiency") or []
    rows = [
        ["Observations", count(quality.get("rows")), ""],
        ["Defaults", count(quality.get("defaults")), ""],
        ["Duplicate keys", count(quality.get("duplicate_keys")), ""],
        ["PD within [0, 1]",
         "Yes" if quality.get("pd_within_zero_and_one") else "No", ""],
    ]
    # Each sufficiency check is a governed assessment, so it carries the
    # limit's provenance. Dropping that column would present a seeded
    # minimum as though somebody's regulator had set it.
    for entry in sufficiency:
        rows.append([text(entry.get("label") or entry.get("metric")),
                     f"{stat(entry.get('observed'))} "
                     f"({text(entry.get('status'))})",
                     text(entry.get("source") or "—")])
    sections.append(Section(
        "8.1", "Data and sample diagnostics", "",
        [Table("Sample sufficiency", ["Check", "Value", "Limit source"],
               rows)]))

    discrimination = payload.get("discrimination") or {}
    refused = _refusal(discrimination)
    if refused:
        sections.append(Section("8.2", "Discriminatory power",
                                unavailable=refused))
    else:
        sections.append(Section(
            "8.2", "Discriminatory power",
            text(discrimination.get("label")),
            [Table("Discrimination", ["Metric", "Value"], [
                ["AUC", stat(discrimination.get("auc"))],
                ["AUC 95% interval",
                 f"{stat(discrimination.get('auc_ci_low'))} to "
                 f"{stat(discrimination.get('auc_ci_high'))}"],
                ["Gini / Accuracy Ratio", stat(discrimination.get("gini"))],
                ["KS", stat(discrimination.get("ks"))],
                ["KS at score", text(discrimination.get("ks_at_score"))],
                ["Observations", count(discrimination.get("observations"))],
                ["Events", count(discrimination.get("events"))],
                ["Score direction",
                 text(discrimination.get("score_direction"))],
            ])]))

    calibration = payload.get("calibration") or {}
    refused = _refusal(calibration) or (
        _not_matured(context) if not context.outcomes_available else "")
    if refused:
        sections.append(Section("8.3", "Calibration and accuracy",
                                unavailable=refused))
    else:
        for label, metric, value in (
                ("Brier score", "brier_score",
                 calibration.get("brier_score")),
                ("Log loss", "log_loss", calibration.get("log_loss"))):
            add_evidence("8.3", label, metric, value, stat(value),
                         "Deterministic scorecard engine", "METRICS")
        sections.append(Section(
            "8.3", "Calibration and accuracy",
            text(calibration.get("label")),
            [Table("Calibration", ["Metric", "Value"], [
                ["Observed default rate",
                 percent(calibration.get("observed_default_rate"))],
                ["Average predicted PD",
                 percent(calibration.get("average_predicted_pd"))],
                ["Observed defaults",
                 count(calibration.get("observed_defaults"))],
                ["Expected defaults",
                 count(calibration.get("expected_defaults"))],
                ["Calibration in the large",
                 stat(calibration.get("calibration_in_the_large"))],
                ["Calibration slope",
                 stat(calibration.get("calibration_slope"))],
                ["Brier score", stat(calibration.get("brier_score"))],
                ["Log loss", stat(calibration.get("log_loss"))],
                ["Bucket RMSE", stat(calibration.get("bucket_rmse"))],
                ["MAPE", text(calibration.get("mape_status"))
                 if calibration.get("mape") is None
                 else percent(calibration.get("mape"))],
            ], note=("MAPE is guarded: it is not reported for buckets whose "
                     "observed rate is at or near zero, where the ratio is "
                     "unbounded and the number would be arithmetic rather "
                     "than a measurement."))]))

    stability = payload.get("stability") or {}
    psi = stability.get("score_psi") or {}
    csi_rows = [[text(entry.get("variable")), stat(entry.get("index")),
                 count(entry.get("current_rows"))]
                for entry in (stability.get("variable_csi") or [])]
    special = stability.get("special_bin_rates") or {}
    special_rows = [[name, percent(rates.get("MISSING")),
                     percent(rates.get("UNSEEN"))]
                    for name, rates in sorted(special.items())]
    tables = [Table("Population stability", ["Metric", "Value"], [
        ["Score PSI", stat(psi.get("index"))],
        ["Reference rows", count(psi.get("reference_rows"))],
        ["Current rows", count(psi.get("current_rows"))],
        ["Baseline", text(stability.get("baseline"))],
    ], note=("The 0.10 and 0.25 PSI cut-offs used on the dashboard are a "
             "scorecard convention, not a regulatory threshold."))]
    if csi_rows:
        tables.append(Table("Characteristic stability by variable",
                            ["Variable", "CSI", "Observations"], csi_rows))
    if special_rows:
        tables.append(Table(
            "Missing and unseen bin rates",
            ["Variable", "Missing", "Unseen"], special_rows,
            note=("A variable whose missing rate moved is a data-supply "
                  "change before it is a population change.")))
    sections.append(Section(
        "8.4", "Stability and robustness",
        "Stability is measured against the development population and needs "
        "no outcome, so it is reported for every month including those whose "
        "performance window has not closed.",
        tables))

    variables = (payload.get("variables") or {}).get("variables") or []
    rows = [[text(v.get("variable")), stat(v.get("information_value")),
             stat(v.get("gini")), stat(v.get("ks")),
             text(v.get("evidence")),
             "Yes" if v.get("in_active_model") else "No"]
            for v in variables]
    sections.append(Section(
        "8.5", "Sensitivity and variable diagnostics",
        "Each variable's standalone power, and whether it is in the model. "
        "Leave-one-out contribution is reported by the diagnostics screens "
        "when an ablation is run; a contribution not measured that way is "
        "reported as an association rather than as a cause.",
        [Table("Variable diagnostics",
               ["Variable", "Information value", "Gini", "KS",
                "Evidence", "In model"], rows)]))

    segments = payload.get("segments")
    sections.append(Section(
        "8.6", "Segment performance",
        "" if segments else "",
        [Table("Segments", ["Segment", "Observations", "Gini"],
               [[text(r.get("segment")), count(r.get("observations")),
                 stat(r.get("gini"))]
                for r in (segments or {}).get("segments", [])])]
        if segments else [],
        unavailable=("" if segments else
                     "No segmentation was requested for this report. Segment "
                     "performance is available on the dashboard by choosing a "
                     "segmentation field.")))

    sections.append(Section(
        "8.7", "Cut-off and decision performance",
        unavailable=(
            "No approved cut-off is recorded for this model in this "
            "workspace, so decision performance is not reported. A cut-off "
            "invented for a report would make every acceptance rate in it "
            "fictional.")))
    sections.append(Section(
        "8.8", "Overrides and usage",
        unavailable=(
            "Override and usage data is not captured in this workspace, so "
            "no override rate is reported.")))

    comparison = payload.get("comparison") or {}
    models = comparison.get("models") or []
    sections.append(Section(
        "8.9", "Challenger comparison",
        ("All models are compared on the identical population and period."
         if comparison.get("identical_population") else ""),
        [Table("Model comparison",
               ["Model", "Gini", "AUC", "KS", "Brier"],
               [[text(m.get("model")), stat(m.get("gini")),
                 stat(m.get("auc")), stat(m.get("ks")),
                 stat(m.get("brier_score"))] for m in models],
               note=("Overlapping confidence intervals mean the difference "
                     "is not established by this sample."
                     if comparison.get("overlapping_intervals") else ""))]))
    return sections


# ---------------------------------------------------------------- §52.9-13


def _monitoring(payload: dict[str, Any],
                context: dash.Context) -> list[Section]:
    limits = payload.get("performance_limits") or []
    breached = [entry for entry in limits
                if entry.get("status") == policy_mod.BREACH]
    narrative = (
        f"{len(breached)} of {len(limits)} monitored metrics are in breach "
        f"of their limit on {context.month}."
        if limits else "No limits are recorded for this model.")
    return [Section("9", "Monitoring review", narrative,
                    [_limits_table(limits)])]


def _findings(payload: dict[str, Any],
              extra: list[dict[str, Any]] | None) -> list[Section]:
    found = list((payload.get("findings") or {}).get("findings") or [])
    found += list(extra or [])
    rows = [[text(f.get("severity")), text(f.get("title")),
             text(f.get("metric")), stat(f.get("observed")),
             text(f.get("limit_source")), text(f.get("recommendation")),
             text(f.get("owner")), text(f.get("status"))]
            for f in found]
    narrative = ("No findings were raised for this month."
                 if not rows else
                 "Every finding carries the metric, the observed value and "
                 "the source of the limit it breached. A breach of a "
                 "demonstration default and a breach of a regulatory "
                 "requirement are not the same fact.")
    return [Section(
        "10", "Findings and severity", narrative,
        [Table("Findings",
               ["Severity", "Finding", "Metric", "Observed", "Limit source",
                "Recommendation", "Owner", "Status"], rows)] if rows else [])]


def _model_risk(payload: dict[str, Any], registered: Any,
                context: dash.Context) -> list[Section]:
    opinion = payload.get("validation_opinion") or {}
    rows = [
        ["Materiality", text(getattr(registered, "materiality", ""))],
        ["Model risk rating",
         text(getattr(registered, "model_risk_rating", ""))],
        ["Metrics with no approved limit",
         ", ".join(opinion.get("metrics_with_no_approved_limit") or []) or "—"],
        ["Metrics not measured",
         ", ".join(opinion.get("metrics_not_measured") or []) or "—"],
    ]
    limitations = [
        "The figures are computed over synthetic demonstration data marked "
        f"{synth.ORIGIN}. They characterise the model's behaviour on that "
        "data and nothing else.",
        "Limits shown as DEMO POLICY are demonstration defaults. Conventional "
        "PSI and CSI cut-offs are a modelling convention and are not "
        "presented here as regulatory requirements.",
        "Override and usage data is not captured in this workspace, so "
        "usage-driven model risk is not assessed.",
    ]
    if not context.outcomes_available:
        limitations.insert(0, _not_matured(context))
    return [Section(
        "11", "Model risk assessment",
        "Uncertainty in this assessment comes from the sample, from the "
        "limits available to compare against, and from what this workspace "
        "does not hold.",
        [Table("Model risk", ["Element", "Value"], rows),
         Table("Limitations", ["#", "Limitation"],
               [[str(i), line] for i, line in enumerate(limitations, 1)])])]


def _conclusion(payload: dict[str, Any]) -> list[Section]:
    opinion = payload.get("validation_opinion") or {}
    rows = [
        ["Validation opinion", text(opinion.get("opinion"))],
        ["Because", text(opinion.get("because"))],
        ["How this was decided", text(opinion.get("how_this_was_decided"))],
        ["Findings considered", count(len(opinion.get("findings") or []))],
        ["Breached metrics",
         ", ".join(opinion.get("breached_metrics") or []) or "—"],
    ]
    return [Section(
        "12", "Overall validation conclusion",
        text(opinion.get("not_a_certification")) + " " + DISCLAIMER,
        [Table("Conclusion and remediation", ["Element", "Value"], rows,
               note=("The opinion is derived by the governed policy from the "
                     "findings and limits above. It is not selected by a "
                     "language model: an opinion a model could choose is an "
                     "opinion that moves when the prompt does."))])]


def _appendices(equation: Any, spec: Any, payload: dict[str, Any],
                context: dash.Context,
                evidence: list[Evidence]) -> list[Section]:
    sections = [Section(
        "13", "Appendices",
        "Full equation, bin tables, metric definitions and the evidence "
        "index that links every figure above to the calculation that "
        "produced it.")]

    sections.append(Section(
        "13.1", "Equation and coefficients", "",
        [Table("Coefficients", ["Variable", "Coefficient", "Applied to"],
               [[t["variable"], stat(t["coefficient"], 6), t["column"]]
                for t in equation.to_dict()["terms"]],
               note=(f"Intercept {stat(equation.intercept, 6)}. "
                     f"Binning specification {spec.spec_version}."))]))

    bins: list[list[str]] = []
    for name, entry in sorted((spec.to_dict().get("variables") or {}).items()):
        for row in entry.get("bins") or []:
            bins.append([name, text(row.get("label")),
                         count(row.get("count")), count(row.get("events")),
                         stat(row.get("woe")), stat(row.get("event_rate"))])
    sections.append(Section(
        "13.2", "Weight of Evidence bin tables", "",
        [Table("Bins", ["Variable", "Bin", "Count", "Events", "WoE",
                        "Event rate"], bins)]))

    definitions = (payload.get("discrimination") or {}).get("definitions") or {}
    sections.append(Section(
        "13.3", "Metric definitions", "",
        [Table("Definitions", ["Metric", "Definition"],
               [[k.replace("_", " ").title(), text(v)]
                for k, v in sorted(definitions.items())])]))

    sections.append(Section(
        "13.4", "Data dictionary", "",
        [Table("Variables in this scorecard",
               ["Variable", "Definition", "Risk direction", "Scoreable"],
               [[v.name, v.definition, v.risk_direction,
                 "Yes" if v.scoreable else "No — fairness monitoring only"]
                for v in vars_mod.catalogue(context.scorecard_type)])]))

    sections.append(Section(
        "13.5", "Validation evidence index",
        "Every figure named above, with the period, model version, method "
        "and validation state it was computed under, and the workbook sheet "
        "it can be checked in.",
        [Table("Evidence index",
               ["Section", "Figure", "Value", "Method", "Period",
                "Model version", "Validation state", "Workbook sheet"],
               [[e.section, e.label, e.value_text, e.method, e.period,
                 e.model_version, e.validation_state, e.workbook_sheet]
                for e in evidence])]))
    return sections
